Imports System.Data
Partial Class CGS_rCostos_ArtProd

    Inherits vis2formularios.frmReporte

    Dim loObjetoReporte As CrystalDecisions.CrystalReports.Engine.ReportDocument

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load

        Dim lcParametro0Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(0), goServicios.enuOpcionesRedondeo.KN_FechaInicioDelDia)
        Dim lcParametro0Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(0), goServicios.enuOpcionesRedondeo.KN_FechaFinDelDia)
        Dim lcParametro1Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(1))
        Dim lcParametro1Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(1))
        
        Dim lcOrdenamiento As String = cusAplicacion.goReportes.pcOrden

        Dim lcComandoSeleccionar As New StringBuilder()

        Try

            lcComandoSeleccionar.AppendLine("DECLARE @lcArticuloIni AS VARCHAR(8) = " & lcParametro0Desde)
            lcComandoSeleccionar.AppendLine("DECLARE @lcArticuloFin AS VARCHAR(8) = " & lcParametro0Hasta)
            lcComandoSeleccionar.AppendLine("DECLARE @lcLoteIni		AS VARCHAR(15)= " & lcParametro1Desde)
            lcComandoSeleccionar.AppendLine("DECLARE @lcLoteFin		AS VARCHAR(15)= " & lcParametro1Hasta)
            lcComandoSeleccionar.AppendLine("")
            'lcComandoSeleccionar.AppendLine("DECLARE @lcArticulo    AS VARCHAR(8);")
            'lcComandoSeleccionar.AppendLine("DECLARE @lcLote    	AS VARCHAR(15);")
            'lcComandoSeleccionar.AppendLine("")
            'lcComandoSeleccionar.AppendLine("--RAIZ LOTE BASE LOTE BASE PRODUCCION")
            'lcComandoSeleccionar.AppendLine("SELECT	'CASO UNO'				AS Tabla,")
            'lcComandoSeleccionar.AppendLine("		Raiz.Cod_Art					AS Art_Raiz,")
            'lcComandoSeleccionar.AppendLine("		Proyecto_Raiz.Nom_Pro			AS NomArt_Raiz,")
            'lcComandoSeleccionar.AppendLine("		Lotes_Raiz.Cod_Lot				AS Lote_Raiz,")
            'lcComandoSeleccionar.AppendLine("		Orden_Trabajo_Raiz.Documento	AS OTrabajo_Raiz,")
            'lcComandoSeleccionar.AppendLine("		Proyecto_Raiz.Cod_Pro			AS OProduccion_Raiz,")
            'lcComandoSeleccionar.AppendLine("		Consumo_Raiz.Documento			AS ConsumoP_Raiz,")
            'lcComandoSeleccionar.AppendLine("		Base.Cod_Art					AS Art_Base,")
            'lcComandoSeleccionar.AppendLine("		OP_Base.Nom_Pro					AS NomArt_Base,")
            'lcComandoSeleccionar.AppendLine("		Lotes_Usados.Cod_Lot			AS Lote_Base,")
            'lcComandoSeleccionar.AppendLine("		Orden_Trabajo_Base.Documento	AS OTrabajo_Base,")
            'lcComandoSeleccionar.AppendLine("		OP_Base.Cod_Pro					AS OProduccion_Base,")
            'lcComandoSeleccionar.AppendLine("		Consumo_Base.Documento			AS ConsumoP_Base,")
            'lcComandoSeleccionar.AppendLine("		Formulas.Cos_Otr1				AS CostoActual_ProductoPS,")
            'lcComandoSeleccionar.AppendLine("		Formulas.Cos_Otr2				AS CostoEstandar_ProductoPS,")
            'lcComandoSeleccionar.AppendLine("		Detalle_OTrabajo_Raiz.Can_Art	AS Cantidad_ProductoPS,")
            'lcComandoSeleccionar.AppendLine("		Lotes_Usados.Cantidad			AS CantidadActual_ProductoMP,")
            'lcComandoSeleccionar.AppendLine("		Renglones_Formulas.Can_Art2		AS CantidadEstandar_ProductoMP,")
            'lcComandoSeleccionar.AppendLine("		COALESCE(Formula_MP.Cos_Otr1,Consumo_Detalle.Cos_Ult1)	AS CostoActual_ProductoMP,")
            'lcComandoSeleccionar.AppendLine("		COALESCE(Formula_MP.Cos_Otr2,Consumo_Detalle.Cos_Ult1)	AS CostoEstandar_ProductoMP")
            'lcComandoSeleccionar.AppendLine("INTO #tmpCasoUno")
            'lcComandoSeleccionar.AppendLine("FROM Encabezados AS Orden_Trabajo_Raiz")
            'lcComandoSeleccionar.AppendLine("	JOIN Renglones AS Detalle_OTrabajo_Raiz ON Orden_Trabajo_Raiz.Documento = Detalle_OTrabajo_Raiz.Documento")
            'lcComandoSeleccionar.AppendLine("		AND Detalle_OTrabajo_Raiz.Origen = 'Ordenes de Trabajo'")
            'lcComandoSeleccionar.AppendLine("	JOIN Ajustes ON Orden_Trabajo_Raiz.Documento = Ajustes.Doc_Ori")
            'lcComandoSeleccionar.AppendLine("		AND Orden_Trabajo_Raiz.Origen = 'Ordenes de Trabajo'")
            'lcComandoSeleccionar.AppendLine("		AND Ajustes.Status = 'Confirmado'")
            'lcComandoSeleccionar.AppendLine("	JOIN Renglones_Ajustes AS Raiz  ON Ajustes.Documento = Raiz.Documento	")
            'lcComandoSeleccionar.AppendLine("	JOIN Operaciones_Lotes AS Lotes_Raiz ON Orden_Trabajo_Raiz.Documento = Lotes_Raiz.Num_Doc")
            'lcComandoSeleccionar.AppendLine("		AND Lotes_Raiz.Tip_Ope = 'Entrada'")
            'lcComandoSeleccionar.AppendLine("	JOIN Proyectos AS Proyecto_Raiz ON Proyecto_Raiz.Cod_Pro = Orden_Trabajo_Raiz.Proyecto")
            'lcComandoSeleccionar.AppendLine("	JOIN Encabezados AS Consumo_Raiz ON Consumo_Raiz.Proyecto = Proyecto_Raiz.Cod_Pro")
            'lcComandoSeleccionar.AppendLine("		AND Consumo_Raiz.Origen = 'Consumos Produccion'")
            'lcComandoSeleccionar.AppendLine("	JOIN Renglones_Ajustes AS Base ON Base.Doc_Ori = Consumo_Raiz.Documento")
            'lcComandoSeleccionar.AppendLine("		AND Base.Tipo = 'Salida'")
            'lcComandoSeleccionar.AppendLine("	JOIN Renglones AS Consumo_Detalle ON Consumo_Raiz.Documento = Consumo_Detalle.Documento")
            'lcComandoSeleccionar.AppendLine("		AND Consumo_Detalle.Origen = 'Consumos Produccion'")
            'lcComandoSeleccionar.AppendLine("		AND Consumo_Detalle.Cod_Art = Base.Cod_Art")
            'lcComandoSeleccionar.AppendLine("	JOIN Operaciones_Lotes AS Lotes_Usados ON Lotes_Usados.Num_Doc = Consumo_Raiz.Documento")
            'lcComandoSeleccionar.AppendLine("		AND Lotes_Usados.Tip_Ope = 'Salida'")
            'lcComandoSeleccionar.AppendLine("		AND Lotes_Usados.Cod_Art = Base.Cod_Art")
            'lcComandoSeleccionar.AppendLine("	JOIN Operaciones_Lotes AS Lotes_Base ON Lotes_Usados.Cod_Lot = Lotes_Base.Cod_Lot")
            'lcComandoSeleccionar.AppendLine("		AND Lotes_Base.Cod_Art = Lotes_Base.Cod_Art")
            'lcComandoSeleccionar.AppendLine("		AND Lotes_Base.Tip_Ope = 'Entrada'")
            'lcComandoSeleccionar.AppendLine("		AND Lotes_Base.Adicional = 'Ordenes de Trabajo'")
            'lcComandoSeleccionar.AppendLine("	JOIN Encabezados AS Orden_Trabajo_Base ON Lotes_Base.Num_Doc = Orden_Trabajo_Base.Documento")
            'lcComandoSeleccionar.AppendLine("		AND Orden_Trabajo_Base.Origen = 'Ordenes de Trabajo'")
            'lcComandoSeleccionar.AppendLine("	JOIN Proyectos AS OP_Base ON OP_Base.Cod_Pro = Orden_Trabajo_Base.Proyecto")
            'lcComandoSeleccionar.AppendLine("	JOIN Encabezados AS Consumo_Base ON Orden_Trabajo_Base.Proyecto = Consumo_Base.Proyecto")
            'lcComandoSeleccionar.AppendLine("		AND Consumo_Base.Origen = 'Consumos Produccion'")
            'lcComandoSeleccionar.AppendLine("	JOIN Renglones_OCompras ON Proyecto_Raiz.Cod_Pro = Renglones_OCompras.Caracter2")
            'lcComandoSeleccionar.AppendLine("	JOIN Formulas ON Formulas.Referencia = Proyecto_Raiz.Cod_Pro")
            'lcComandoSeleccionar.AppendLine("	JOIN Renglones_Formulas ON Formulas.Documento = Renglones_Formulas.Documento")
            'lcComandoSeleccionar.AppendLine("		AND Base.Cod_Art =  Renglones_Formulas.Cod_Art")
            'lcComandoSeleccionar.AppendLine("       AND Lotes_Usados.Cod_Lot = Renglones_Formulas.Caracter1")
            'lcComandoSeleccionar.AppendLine("	LEFT JOIN Formulas AS Formula_MP ON Formula_MP.Referencia = OP_Base.Cod_Pro")
            'lcComandoSeleccionar.AppendLine("")
            'lcComandoSeleccionar.AppendLine("--RAIZ LOTE BASE NO LOTE BASE PRODUCCION")
            'lcComandoSeleccionar.AppendLine("SELECT DISTINCT")
            'lcComandoSeleccionar.AppendLine("		'CASO DOS'			AS Tabla,")
            'lcComandoSeleccionar.AppendLine("		Raiz.Cod_Art					AS Art_Raiz,")
            'lcComandoSeleccionar.AppendLine("		Proyecto_Raiz.Nom_Pro			AS NomArt_Raiz,")
            'lcComandoSeleccionar.AppendLine("		Lotes_Raiz.Cod_Lot				AS Lote_Raiz,")
            'lcComandoSeleccionar.AppendLine("		Orden_Trabajo_Raiz.Documento	AS OTrabajo_Raiz,")
            'lcComandoSeleccionar.AppendLine("		Proyecto_Raiz.Cod_Pro			AS OProduccion_Raiz,")
            'lcComandoSeleccionar.AppendLine("		Consumo_Raiz.Documento			AS ConsumoP_Raiz,")
            'lcComandoSeleccionar.AppendLine("		Base.Cod_Art					AS Art_Base,")
            'lcComandoSeleccionar.AppendLine("		OP_Base.Nom_Pro					AS NomArt_Base,")
            'lcComandoSeleccionar.AppendLine("		''								AS Lote_Base,")
            'lcComandoSeleccionar.AppendLine("		Orden_Trabajo_Base.Documento	AS OTrabajo_Base,")
            'lcComandoSeleccionar.AppendLine("		OP_Base.Cod_Pro					AS OProduccion_Base,")
            'lcComandoSeleccionar.AppendLine("		Consumo_Base.Documento			AS ConsumoP_Base,")
            'lcComandoSeleccionar.AppendLine("		Formulas.Cos_Otr1				AS CostoActual_ProductoPS,")
            'lcComandoSeleccionar.AppendLine("		Formulas.Cos_Otr2				AS CostoEstandar_ProductoPS,")
            'lcComandoSeleccionar.AppendLine("		Detalle_OTrabajo_Raiz.Can_Art	AS Cantidad_ProductoPS,")
            'lcComandoSeleccionar.AppendLine("		Consumo_Detalle.Can_Art			AS CantidadActual_ProductoMP,")
            'lcComandoSeleccionar.AppendLine("		Renglones_Formulas.Can_Art2		AS CantidadEstandar_ProductoMP,")
            'lcComandoSeleccionar.AppendLine("		COALESCE(Formula_MP.Cos_Otr1,Consumo_Detalle.Cos_Ult1)	AS CostoActual_ProductoMP,")
            'lcComandoSeleccionar.AppendLine("		COALESCE(Formula_MP.Cos_Otr2,Consumo_Detalle.Cos_Ult1)	AS CostoEstandar_ProductoMP")
            'lcComandoSeleccionar.AppendLine("INTO #tmpCasoDos")
            'lcComandoSeleccionar.AppendLine("FROM Encabezados AS Orden_Trabajo_Raiz")
            'lcComandoSeleccionar.AppendLine("	JOIN Renglones AS Detalle_OTrabajo_Raiz ON Orden_Trabajo_Raiz.Documento = Detalle_OTrabajo_Raiz.Documento")
            'lcComandoSeleccionar.AppendLine("		AND Detalle_OTrabajo_Raiz.Origen = 'Ordenes de Trabajo'")
            'lcComandoSeleccionar.AppendLine("	JOIN Ajustes ON Orden_Trabajo_Raiz.Documento = Ajustes.Doc_Ori")
            'lcComandoSeleccionar.AppendLine("		AND Orden_Trabajo_Raiz.Origen = 'Ordenes de Trabajo'")
            'lcComandoSeleccionar.AppendLine("		AND Ajustes.Status = 'Confirmado'")
            'lcComandoSeleccionar.AppendLine("	JOIN Renglones_Ajustes AS Raiz  ON Ajustes.Documento = Raiz.Documento	")
            'lcComandoSeleccionar.AppendLine("	JOIN Operaciones_Lotes AS Lotes_Raiz ON Orden_Trabajo_Raiz.Documento = Lotes_Raiz.Num_Doc")
            'lcComandoSeleccionar.AppendLine("		AND Lotes_Raiz.Tip_Ope = 'Entrada'")
            'lcComandoSeleccionar.AppendLine("	JOIN Proyectos AS Proyecto_Raiz ON Proyecto_Raiz.Cod_Pro = Orden_Trabajo_Raiz.Proyecto")
            'lcComandoSeleccionar.AppendLine("	JOIN Encabezados AS Consumo_Raiz ON Consumo_Raiz.Proyecto = Proyecto_Raiz.Cod_Pro")
            'lcComandoSeleccionar.AppendLine("		AND Consumo_Raiz.Origen = 'Consumos Produccion'")
            'lcComandoSeleccionar.AppendLine("	JOIN Renglones_Ajustes AS Base ON Base.Doc_Ori = Consumo_Raiz.Documento")
            'lcComandoSeleccionar.AppendLine("		AND Base.Tipo = 'Salida'")
            'lcComandoSeleccionar.AppendLine("	JOIN Renglones AS Consumo_Detalle ON Consumo_Raiz.Documento = Consumo_Detalle.Documento")
            'lcComandoSeleccionar.AppendLine("		AND Consumo_Detalle.Origen = 'Consumos Produccion'")
            'lcComandoSeleccionar.AppendLine("		AND Consumo_Detalle.Cod_Art = Base.Cod_Art")
            'lcComandoSeleccionar.AppendLine("	JOIN Renglones_Ajustes AS Info_Base ON Base.Cod_Art = Info_Base.Cod_Art")
            'lcComandoSeleccionar.AppendLine("		AND Info_Base.Tipo = 'Entrada'")
            'lcComandoSeleccionar.AppendLine("	JOIN Encabezados AS Orden_Trabajo_Base On Info_Base.Doc_Ori = Orden_Trabajo_Base.Documento")
            'lcComandoSeleccionar.AppendLine("		AND Orden_Trabajo_Base.Origen = 'Ordenes de Trabajo'")
            'lcComandoSeleccionar.AppendLine("	JOIN Proyectos AS OP_Base ON OP_Base.Cod_Pro = Orden_Trabajo_Base.Proyecto")
            'lcComandoSeleccionar.AppendLine("	JOIN Encabezados AS Consumo_Base ON OP_Base.Cod_Pro = Consumo_Base.Proyecto")
            'lcComandoSeleccionar.AppendLine("		AND Consumo_Base.Origen = 'Consumos Produccion'")
            'lcComandoSeleccionar.AppendLine("	JOIN Renglones_OCompras ON Proyecto_Raiz.Cod_Pro = Renglones_OCompras.Caracter2")
            'lcComandoSeleccionar.AppendLine("	JOIN Formulas ON Formulas.Referencia = Proyecto_Raiz.Cod_Pro")
            'lcComandoSeleccionar.AppendLine("	JOIN Renglones_Formulas ON Formulas.Documento = Renglones_Formulas.Documento")
            'lcComandoSeleccionar.AppendLine("		AND Base.Cod_Art =  Renglones_Formulas.Cod_Art")
            'lcComandoSeleccionar.AppendLine("	LEFT JOIN Formulas AS Formula_MP ON Formula_MP.Referencia = OP_Base.Cod_Pro")
            'lcComandoSeleccionar.AppendLine("WHERE Base.Cod_Art NOT IN (SELECT #tmpCasoUno.Art_Base FROM #tmpCasoUno)")
            'lcComandoSeleccionar.AppendLine("")
            'lcComandoSeleccionar.AppendLine("SELECT * INTO #tmpCasoUnoDos FROM #tmpCasoUno")
            'lcComandoSeleccionar.AppendLine("UNION ALL")
            'lcComandoSeleccionar.AppendLine("SELECT * FROM #tmpCasoDos")
            'lcComandoSeleccionar.AppendLine("")
            'lcComandoSeleccionar.AppendLine("DROP TABLE #tmpCasoUno")
            'lcComandoSeleccionar.AppendLine("DROP TABLE #tmpCasoDos")
            'lcComandoSeleccionar.AppendLine("")
            'lcComandoSeleccionar.AppendLine("--RAIZ LOTE BASE LOTE BASE NO PRODUCCION")
            'lcComandoSeleccionar.AppendLine("SELECT DISTINCT")
            'lcComandoSeleccionar.AppendLine("		'CASO TRES'	AS Tabla,")
            'lcComandoSeleccionar.AppendLine("		Raiz.Cod_Art					AS Art_Raiz,")
            'lcComandoSeleccionar.AppendLine("		Proyecto_Raiz.Nom_Pro			AS NomArt_Raiz,")
            'lcComandoSeleccionar.AppendLine("		Lotes_Raiz.Cod_Lot				AS Lote_Raiz,")
            'lcComandoSeleccionar.AppendLine("		Orden_Trabajo_Raiz.Documento	AS OTrabajo_Raiz,")
            'lcComandoSeleccionar.AppendLine("		Proyecto_Raiz.Cod_Pro			AS OProduccion_Raiz,")
            'lcComandoSeleccionar.AppendLine("		Consumo_Raiz.Documento			AS ConsumoP_Raiz,")
            'lcComandoSeleccionar.AppendLine("		Base.Cod_Art					AS Art_Base,")
            'lcComandoSeleccionar.AppendLine("		Articulos.Nom_Art				AS NomArt_Base,")
            'lcComandoSeleccionar.AppendLine("		Lotes_Usados.Cod_Lot			AS Lote_Base,")
            'lcComandoSeleccionar.AppendLine("		''								AS OTrabajo_Base,")
            'lcComandoSeleccionar.AppendLine("		''								AS OProduccion_Base,")
            'lcComandoSeleccionar.AppendLine("		''								AS ConsumoP_Base,")
            'lcComandoSeleccionar.AppendLine("		Formulas.Cos_Otr1				AS CostoActual_ProductoPS,")
            'lcComandoSeleccionar.AppendLine("		Formulas.Cos_Otr2				AS CostoEstandar_ProductoPS,")
            'lcComandoSeleccionar.AppendLine("		Detalle_OTrabajo_Raiz.Can_Art	AS Cantidad_ProductoPS,")
            'lcComandoSeleccionar.AppendLine("		Consumo_Detalle.Can_Art			AS CantidadActual_ProductoMP,")
            'lcComandoSeleccionar.AppendLine("		Renglones_Formulas.Can_Art2		AS CantidadEstandar_ProductoMP,")
            'lcComandoSeleccionar.AppendLine("		Consumo_Detalle.Cos_Ult1		AS CostoActual_ProductoMP,")
            'lcComandoSeleccionar.AppendLine("		Consumo_Detalle.Cos_Ult1		AS CostoEstandar_ProductoMP")
            'lcComandoSeleccionar.AppendLine("INTO #tmpCasoTres")
            'lcComandoSeleccionar.AppendLine("FROM Encabezados AS Orden_Trabajo_Raiz")
            'lcComandoSeleccionar.AppendLine("	JOIN Renglones AS Detalle_OTrabajo_Raiz ON Orden_Trabajo_Raiz.Documento = Detalle_OTrabajo_Raiz.Documento")
            'lcComandoSeleccionar.AppendLine("		AND Detalle_OTrabajo_Raiz.Origen = 'Ordenes de Trabajo'")
            'lcComandoSeleccionar.AppendLine("	JOIN Ajustes ON Orden_Trabajo_Raiz.Documento = Ajustes.Doc_Ori")
            'lcComandoSeleccionar.AppendLine("		AND Orden_Trabajo_Raiz.Origen = 'Ordenes de Trabajo'")
            'lcComandoSeleccionar.AppendLine("		AND Ajustes.Status = 'Confirmado'")
            'lcComandoSeleccionar.AppendLine("	JOIN Renglones_Ajustes AS Raiz  ON Ajustes.Documento = Raiz.Documento	")
            'lcComandoSeleccionar.AppendLine("	JOIN Operaciones_Lotes AS Lotes_Raiz ON Orden_Trabajo_Raiz.Documento = Lotes_Raiz.Num_Doc")
            'lcComandoSeleccionar.AppendLine("		AND Lotes_Raiz.Tip_Ope = 'Entrada'")
            'lcComandoSeleccionar.AppendLine("	JOIN Proyectos AS Proyecto_Raiz ON Proyecto_Raiz.Cod_Pro = Orden_Trabajo_Raiz.Proyecto")
            'lcComandoSeleccionar.AppendLine("	JOIN Encabezados AS Consumo_Raiz ON Consumo_Raiz.Proyecto = Proyecto_Raiz.Cod_Pro")
            'lcComandoSeleccionar.AppendLine("		AND Consumo_Raiz.Origen = 'Consumos Produccion'	")
            'lcComandoSeleccionar.AppendLine("	JOIN Renglones_Ajustes AS Base ON Base.Doc_Ori = Consumo_Raiz.Documento")
            'lcComandoSeleccionar.AppendLine("		AND Base.Tipo = 'Salida'")
            'lcComandoSeleccionar.AppendLine("	JOIN Articulos ON Base.Cod_Art = Articulos.Cod_Art")
            'lcComandoSeleccionar.AppendLine("	JOIN Renglones AS Consumo_Detalle ON Consumo_Raiz.Documento = Consumo_Detalle.Documento")
            'lcComandoSeleccionar.AppendLine("		AND Consumo_Detalle.Origen = 'Consumos Produccion'")
            'lcComandoSeleccionar.AppendLine("		AND Consumo_Detalle.Cod_Art = Base.Cod_Art")
            'lcComandoSeleccionar.AppendLine("	JOIN Operaciones_Lotes AS Lotes_Usados ON Lotes_Usados.Num_Doc = Consumo_Raiz.Documento")
            'lcComandoSeleccionar.AppendLine("		AND Lotes_Usados.Tip_Ope = 'Salida'")
            'lcComandoSeleccionar.AppendLine("		AND Lotes_Usados.Cod_Art = Base.Cod_Art")
            'lcComandoSeleccionar.AppendLine("	JOIN Renglones_OCompras ON Proyecto_Raiz.Cod_Pro = Renglones_OCompras.Caracter2")
            'lcComandoSeleccionar.AppendLine("	JOIN Formulas ON Formulas.Referencia = Proyecto_Raiz.Cod_Pro")
            'lcComandoSeleccionar.AppendLine("	JOIN Renglones_Formulas ON Formulas.Documento = Renglones_Formulas.Documento")
            'lcComandoSeleccionar.AppendLine("		AND Base.Cod_Art =  Renglones_Formulas.Cod_Art")
            'lcComandoSeleccionar.AppendLine("WHERE Base.Cod_Art NOT IN (SELECT #tmpCasoUnoDos.Art_Base FROM #tmpCasoUnoDos)")
            'lcComandoSeleccionar.AppendLine("")
            'lcComandoSeleccionar.AppendLine("SELECT * INTO #tmpCasoUnoDosTres FROM #tmpCasoUnoDos")
            'lcComandoSeleccionar.AppendLine("UNION ALL")
            'lcComandoSeleccionar.AppendLine("SELECT * FROM #tmpCasoTres")
            'lcComandoSeleccionar.AppendLine("")
            'lcComandoSeleccionar.AppendLine("DROP TABLE #tmpCasoUnoDos")
            'lcComandoSeleccionar.AppendLine("DROP TABLE #tmpCasoTres")
            'lcComandoSeleccionar.AppendLine("")
            'lcComandoSeleccionar.AppendLine("--RAIZ LOTE BASE NO LOTE BASE NO PRODUCCION")
            'lcComandoSeleccionar.AppendLine("SELECT DISTINCT")
            'lcComandoSeleccionar.AppendLine("		'CASO CUATRO'	AS Tabla,")
            'lcComandoSeleccionar.AppendLine("		Raiz.Cod_Art					AS Art_Raiz,")
            'lcComandoSeleccionar.AppendLine("		Proyecto_Raiz.Nom_Pro			AS NomArt_Raiz,")
            'lcComandoSeleccionar.AppendLine("		Lotes_Raiz.Cod_Lot				AS Lote_Raiz,")
            'lcComandoSeleccionar.AppendLine("		Orden_Trabajo_Raiz.Documento	AS OTrabajo_Raiz,")
            'lcComandoSeleccionar.AppendLine("		Proyecto_Raiz.Cod_Pro			AS OProduccion_Raiz,")
            'lcComandoSeleccionar.AppendLine("		Consumo_Raiz.Documento			AS ConsumoP_Raiz,")
            'lcComandoSeleccionar.AppendLine("		Base.Cod_Art					AS Art_Base,")
            'lcComandoSeleccionar.AppendLine("		Articulos.Nom_Art				AS NomArt_Base,")
            'lcComandoSeleccionar.AppendLine("		''								AS Lote_Base,")
            'lcComandoSeleccionar.AppendLine("		''								AS OTrabajo_Base,")
            'lcComandoSeleccionar.AppendLine("		''								AS OProduccion_Base,")
            'lcComandoSeleccionar.AppendLine("		''								AS ConsumoP_Base,")
            'lcComandoSeleccionar.AppendLine("		Formulas.Cos_Otr1				AS CostoActual_ProductoPS,")
            'lcComandoSeleccionar.AppendLine("		Formulas.Cos_Otr2				AS CostoEstandar_ProductoPS,")
            'lcComandoSeleccionar.AppendLine("		Detalle_OTrabajo_Raiz.Can_Art	AS Cantidad_ProductoPS,")
            'lcComandoSeleccionar.AppendLine("		Consumo_Detalle.Can_Art			AS CantidadActual_ProductoMP,")
            'lcComandoSeleccionar.AppendLine("		Renglones_Formulas.Can_Art2		AS CantidadEstandar_ProductoMP,")
            'lcComandoSeleccionar.AppendLine("		Consumo_Detalle.Cos_Ult1		AS CostoActual_ProductoMP,")
            'lcComandoSeleccionar.AppendLine("		Consumo_Detalle.Cos_Ult1		AS CostoEstandar_ProductoMP")
            'lcComandoSeleccionar.AppendLine("INTO #tmpCasoCuatro")
            'lcComandoSeleccionar.AppendLine("FROM Encabezados AS Orden_Trabajo_Raiz")
            'lcComandoSeleccionar.AppendLine("	JOIN Renglones AS Detalle_OTrabajo_Raiz ON Orden_Trabajo_Raiz.Documento = Detalle_OTrabajo_Raiz.Documento")
            'lcComandoSeleccionar.AppendLine("		AND Detalle_OTrabajo_Raiz.Origen = 'Ordenes de Trabajo'")
            'lcComandoSeleccionar.AppendLine("	JOIN Ajustes ON Orden_Trabajo_Raiz.Documento = Ajustes.Doc_Ori")
            'lcComandoSeleccionar.AppendLine("		AND Orden_Trabajo_Raiz.Origen = 'Ordenes de Trabajo'")
            'lcComandoSeleccionar.AppendLine("		AND Ajustes.Status = 'Confirmado'")
            'lcComandoSeleccionar.AppendLine("	JOIN Renglones_Ajustes AS Raiz  ON Ajustes.Documento = Raiz.Documento	")
            'lcComandoSeleccionar.AppendLine("	JOIN Operaciones_Lotes AS Lotes_Raiz ON Orden_Trabajo_Raiz.Documento = Lotes_Raiz.Num_Doc")
            'lcComandoSeleccionar.AppendLine("		AND Lotes_Raiz.Tip_Ope = 'Entrada'")
            'lcComandoSeleccionar.AppendLine("	JOIN Proyectos AS Proyecto_Raiz ON Orden_Trabajo_Raiz.Proyecto = Proyecto_Raiz.Cod_Pro")
            'lcComandoSeleccionar.AppendLine("	JOIN Encabezados AS Consumo_Raiz ON Proyecto_Raiz.Cod_Pro = Consumo_Raiz.Proyecto")
            'lcComandoSeleccionar.AppendLine("		AND Consumo_Raiz.Origen = 'Consumos Produccion'")
            'lcComandoSeleccionar.AppendLine("	JOIN Renglones AS Consumo_Detalle ON Consumo_Raiz.Documento = Consumo_Detalle.Documento")
            'lcComandoSeleccionar.AppendLine("		AND Consumo_Detalle.Origen = 'Consumos Produccion'")
            'lcComandoSeleccionar.AppendLine("	JOIN Renglones_Ajustes AS Base ON Consumo_Raiz.Documento = Base.Doc_Ori")
            'lcComandoSeleccionar.AppendLine("		AND Base.Tipo = 'Salida'")
            'lcComandoSeleccionar.AppendLine("	JOIN Articulos ON Base.Cod_Art = Articulos.Cod_Art")
            'lcComandoSeleccionar.AppendLine("	JOIN Renglones_OCompras ON Proyecto_Raiz.Cod_Pro = Renglones_OCompras.Caracter2")
            'lcComandoSeleccionar.AppendLine("	JOIN Formulas ON Formulas.Referencia = Proyecto_Raiz.Cod_Pro")
            'lcComandoSeleccionar.AppendLine("	JOIN Renglones_Formulas ON Formulas.Documento = Renglones_Formulas.Documento")
            'lcComandoSeleccionar.AppendLine("		AND Base.Cod_Art =  Renglones_Formulas.Cod_Art")
            'lcComandoSeleccionar.AppendLine("WHERE Base.Cod_Art NOT IN (SELECT #tmpCasoUnoDosTres.Art_Base FROM #tmpCasoUnoDosTres)")
            'lcComandoSeleccionar.AppendLine("")
            'lcComandoSeleccionar.AppendLine("SELECT * INTO #tmpCasoUnoDosTresCuatro FROM #tmpCasoUnoDosTres")
            'lcComandoSeleccionar.AppendLine("UNION ALL ")
            'lcComandoSeleccionar.AppendLine("SELECT * FROM #tmpCasoCuatro")
            'lcComandoSeleccionar.AppendLine("")
            'lcComandoSeleccionar.AppendLine("DROP TABLE #tmpCasoCuatro")
            'lcComandoSeleccionar.AppendLine("DROP TABLE #tmpCasoUnoDosTres")
            'lcComandoSeleccionar.AppendLine("")
            'lcComandoSeleccionar.AppendLine("--RAIZ NO LOTE BASE NO LOTE BASE NO PRODUCCION")
            'lcComandoSeleccionar.AppendLine("SELECT DISTINCT")
            'lcComandoSeleccionar.AppendLine("		'CASO CINCO'	AS Tabla,")
            'lcComandoSeleccionar.AppendLine("		Raiz.Cod_Art					AS Art_Raiz,")
            'lcComandoSeleccionar.AppendLine("		Proyecto_Raiz.Nom_Pro			AS NomArt_Raiz,")
            'lcComandoSeleccionar.AppendLine("		''								AS Lote_Raiz,")
            'lcComandoSeleccionar.AppendLine("		Orden_Trabajo_Raiz.Documento	AS OTrabajo_Raiz,")
            'lcComandoSeleccionar.AppendLine("		Proyecto_Raiz.Cod_Pro			AS OProduccion_Raiz,")
            'lcComandoSeleccionar.AppendLine("		Consumo_Raiz.Documento			AS ConsumoP_Raiz,")
            'lcComandoSeleccionar.AppendLine("		Base.Cod_Art					AS Art_Base,")
            'lcComandoSeleccionar.AppendLine("		Articulos.Nom_Art				AS NomArt_Base,")
            'lcComandoSeleccionar.AppendLine("		''								AS Lote_Base,")
            'lcComandoSeleccionar.AppendLine("		''								AS OTrabajo_Base,")
            'lcComandoSeleccionar.AppendLine("		''								AS OProduccion_Base,")
            'lcComandoSeleccionar.AppendLine("		''								AS ConsumoP_Base,")
            'lcComandoSeleccionar.AppendLine("		Formulas.Cos_Otr1				AS CostoActual_ProductoPS,")
            'lcComandoSeleccionar.AppendLine("		Formulas.Cos_Otr2				AS CostoEstandar_ProductoPS,")
            'lcComandoSeleccionar.AppendLine("		OTrabajo_Raiz.Can_Art	        AS Cantidad_ProductoPS,")
            'lcComandoSeleccionar.AppendLine("		Consumo_Detalle.Can_Art			AS CantidadActual_ProductoMP,")
            'lcComandoSeleccionar.AppendLine("		Renglones_Formulas.Can_Art2		AS CantidadEstandar_ProductoMP,")
            'lcComandoSeleccionar.AppendLine("		Consumo_Detalle.Cos_Ult1		AS CostoActual_ProductoMP,")
            'lcComandoSeleccionar.AppendLine("		Consumo_Detalle.Cos_Ult1		AS CostoEstandar_ProductoMP")
            'lcComandoSeleccionar.AppendLine("INTO #tmpCasoCinco")
            'lcComandoSeleccionar.AppendLine("FROM Encabezados AS Orden_Trabajo_Raiz")
            'lcComandoSeleccionar.AppendLine("	JOIN Renglones AS OTrabajo_Raiz ON Orden_Trabajo_Raiz.Documento = OTrabajo_Raiz.Documento")
            'lcComandoSeleccionar.AppendLine("		AND OTrabajo_Raiz.Origen = 'Ordenes de Trabajo'")
            'lcComandoSeleccionar.AppendLine("	JOIN Proyectos AS Proyecto_Raiz ON Orden_Trabajo_Raiz.Proyecto = Proyecto_Raiz.Cod_Pro")
            'lcComandoSeleccionar.AppendLine("	JOIN Ajustes ON Orden_Trabajo_Raiz.Documento = Ajustes.Doc_Ori")
            'lcComandoSeleccionar.AppendLine("		AND Orden_Trabajo_Raiz.Origen = 'Ordenes de Trabajo'")
            'lcComandoSeleccionar.AppendLine("		AND Ajustes.Status = 'Confirmado'")
            'lcComandoSeleccionar.AppendLine("	JOIN Renglones_Ajustes AS Raiz  ON Ajustes.Documento = Raiz.Documento")
            'lcComandoSeleccionar.AppendLine("		AND Raiz.Tipo = 'Entrada'")
            'lcComandoSeleccionar.AppendLine("	JOIN Encabezados AS Consumo_Raiz ON Proyecto_Raiz.Cod_Pro = Consumo_Raiz.Proyecto")
            'lcComandoSeleccionar.AppendLine("		AND Consumo_Raiz.Origen = 'Consumos Produccion'")
            'lcComandoSeleccionar.AppendLine("	JOIN Renglones AS Consumo_Detalle ON Consumo_Raiz.Documento = Consumo_Detalle.Documento")
            'lcComandoSeleccionar.AppendLine("		AND Consumo_Detalle.Origen = 'Consumos Produccion'")
            'lcComandoSeleccionar.AppendLine("	JOIN Renglones_Ajustes AS Base ON Consumo_Raiz.Documento = Base.Doc_Ori")
            'lcComandoSeleccionar.AppendLine("		AND Base.Tipo = 'Salida'")
            'lcComandoSeleccionar.AppendLine("	JOIN Articulos ON Base.Cod_Art = Articulos.Cod_Art")
            'lcComandoSeleccionar.AppendLine("	JOIN Renglones_OCompras ON Proyecto_Raiz.Cod_Pro = Renglones_OCompras.Caracter2")
            'lcComandoSeleccionar.AppendLine("	JOIN Formulas ON Formulas.Referencia = Proyecto_Raiz.Cod_Pro")
            'lcComandoSeleccionar.AppendLine("	JOIN Renglones_Formulas ON Formulas.Documento = Renglones_Formulas.Documento")
            'lcComandoSeleccionar.AppendLine("		AND Base.Cod_Art =  Renglones_Formulas.Cod_Art")
            'lcComandoSeleccionar.AppendLine("WHERE Base.Cod_Art NOT IN (SELECT #tmpCasoUnoDosTresCuatro.Art_Base FROM #tmpCasoUnoDosTresCuatro)")
            'lcComandoSeleccionar.AppendLine("")
            'lcComandoSeleccionar.AppendLine("SELECT * INTO #tmpDatos FROM #tmpCasoUnoDosTresCuatro")
            'lcComandoSeleccionar.AppendLine("UNION ALL ")
            'lcComandoSeleccionar.AppendLine("SELECT * FROM #tmpCasoCinco")
            'lcComandoSeleccionar.AppendLine("")
            'lcComandoSeleccionar.AppendLine("DROP TABLE #tmpCasoCinco")
            'lcComandoSeleccionar.AppendLine("DROP TABLE #tmpCasoUnoDosTresCuatro;")
            'lcComandoSeleccionar.AppendLine("")
            'lcComandoSeleccionar.AppendLine("WITH BillOfMaterials AS")
            'lcComandoSeleccionar.AppendLine("(	SELECT Tabla, Art_Raiz, NomArt_Raiz, Lote_Raiz, OTrabajo_Raiz, OProduccion_Raiz, ConsumoP_Raiz, Art_Base, NomArt_Base, Lote_Base, OTrabajo_Base, OProduccion_Base, ConsumoP_Base, CostoActual_ProductoPS, CostoEstandar_ProductoPS, Cantidad_ProductoPS, CantidadActual_ProductoMP, CantidadEstandar_ProductoMP, CostoActual_ProductoMP, CostoEstandar_ProductoMP")
            'lcComandoSeleccionar.AppendLine("	FROM #tmpDatos  ")
            'lcComandoSeleccionar.AppendLine("	WHERE Art_Raiz BETWEEN @lcArticuloIni AND @lcArticuloFin")
            'lcComandoSeleccionar.AppendLine("		AND Lote_Raiz BETWEEN @lcLoteIni AND @lcLoteFin")
            'lcComandoSeleccionar.AppendLine("	UNION ALL")
            'lcComandoSeleccionar.AppendLine("	SELECT A.Tabla, A.Art_Raiz, A.NomArt_Raiz, A.Lote_Raiz, A.OTrabajo_Raiz, A.OProduccion_Raiz, A.ConsumoP_Raiz, A.Art_Base, A.NomArt_Base, A.Lote_Base, A.OTrabajo_Base, A.OProduccion_Base, A.ConsumoP_Base, A.CostoActual_ProductoPS, A.CostoEstandar_ProductoPS, A.Cantidad_ProductoPS, A.CantidadActual_ProductoMP, A.CantidadEstandar_ProductoMP, A.CostoActual_ProductoMP, A.CostoEstandar_ProductoMP")
            'lcComandoSeleccionar.AppendLine("	FROM #tmpDatos AS A")
            'lcComandoSeleccionar.AppendLine("		INNER JOIN BillOfMaterials AS B ON B.Art_Base = A.Art_Raiz")
            'lcComandoSeleccionar.AppendLine("			AND B.Lote_Base = A.Lote_Raiz")
            'lcComandoSeleccionar.AppendLine("			AND B.OTrabajo_Base = A.OTrabajo_Raiz")
            'lcComandoSeleccionar.AppendLine("			AND B.OProduccion_Base = A.OProduccion_Raiz")
            'lcComandoSeleccionar.AppendLine("			AND B.ConsumoP_Base = A.ConsumoP_Raiz	")
            'lcComandoSeleccionar.AppendLine(")")
            'lcComandoSeleccionar.AppendLine("")
            'lcComandoSeleccionar.AppendLine("--SELECT DISTINCT * FROM BillOfMaterials")
            'lcComandoSeleccionar.AppendLine("")
            'lcComandoSeleccionar.AppendLine("SELECT ROW_NUMBER() OVER (ORDER BY BoM.Art_Raiz, BoM.Lote_Raiz) AS Num, *")
            'lcComandoSeleccionar.AppendLine("FROM(SELECT DISTINCT Art_Raiz, NomArt_Raiz, Lote_Raiz, OProduccion_Raiz, Cantidad_ProductoPS, CostoActual_ProductoPS, CostoEstandar_ProductoPS, Art_Base, NomArt_Base, Lote_Base, CantidadActual_ProductoMP, CantidadEstandar_ProductoMP, CostoActual_ProductoMP, CostoEstandar_ProductoMP")
            'lcComandoSeleccionar.AppendLine("	FROM BillOfMaterials ")
            'lcComandoSeleccionar.AppendLine("	WHERE Art_Raiz BETWEEN @lcArticuloIni AND @lcArticuloFin")
            'lcComandoSeleccionar.AppendLine("		AND Lote_Raiz BETWEEN @lcLoteIni AND @lcLoteFin)BoM")
            'lcComandoSeleccionar.AppendLine("")
            'lcComandoSeleccionar.AppendLine("DROP TABLE #tmpDatos")

            lcComandoSeleccionar.AppendLine("SELECT	Formulas.Cod_Art				AS Art_Raiz,")
            lcComandoSeleccionar.AppendLine("		Formulas.Nom_Art				AS NomArt_Raiz,")
            lcComandoSeleccionar.AppendLine("		Formulas.Caracter1				AS Lote_Raiz,")
            lcComandoSeleccionar.AppendLine("		Renglones_Formulas.Cod_Art		AS Art_Base,")
            lcComandoSeleccionar.AppendLine("		Renglones_Formulas.Notas		AS NomArt_Base,")
            lcComandoSeleccionar.AppendLine("		Renglones_Formulas.caracter1	AS Lote_Base,")
            lcComandoSeleccionar.AppendLine("		Formulas.Cos_Otr1				AS CostoActual_ProductoPS,")
            lcComandoSeleccionar.AppendLine("		Formulas.Cos_Otr2				AS CostoEstandar_ProductoPS,")
            lcComandoSeleccionar.AppendLine("		Formulas.Can_Ren				AS Cantidad_ProductoPS,")
            lcComandoSeleccionar.AppendLine("		Renglones_Formulas.Can_Art1		AS CantidadActual_ProductoMP,")
            lcComandoSeleccionar.AppendLine("		Renglones_Formulas.Can_Art2		AS CantidadEstandar_ProductoMP,")
            lcComandoSeleccionar.AppendLine("		Renglones_Formulas.Cos_Ult1		AS CostoActual_ProductoMP,")
            lcComandoSeleccionar.AppendLine("		Renglones_Formulas.Cos_Ult2		AS CostoEstandar_ProductoMP")
            lcComandoSeleccionar.AppendLine("FROM Formulas")
            lcComandoSeleccionar.AppendLine("	JOIN Renglones_Formulas ON Formulas.Documento = Renglones_Formulas.Documento")
            lcComandoSeleccionar.AppendLine("WHERE Formulas.Origen = ''")
            lcComandoSeleccionar.AppendLine("	AND Formulas.Cod_Art BETWEEN @lcArticuloIni AND @lcArticuloFin")
            lcComandoSeleccionar.AppendLine("	AND Formulas.Caracter1 BETWEEN @lcLoteIni AND @lcLoteFin")

            'Me.mEscribirConsulta(lcComandoSeleccionar.ToString())

            Dim loServicios As New cusDatos.goDatos

            Dim laDatosReporte As DataSet = loServicios.mObtenerTodosSinEsquema(lcComandoSeleccionar.ToString, "curReportes")

            Me.mCargarLogoEmpresa(laDatosReporte.Tables(0), "LogoEmpresa")

            loObjetoReporte = cusAplicacion.goReportes.mCargarReporte("CGS_rCostos_ArtProd", laDatosReporte)

            Me.mTraducirReporte(loObjetoReporte)

            Me.mFormatearCamposReporte(loObjetoReporte)

            Me.crvCGS_rCostos_ArtProd.ReportSource = loObjetoReporte

        Catch loExcepcion As Exception

            Me.WbcAdministradorMensajeModal.mMostrarMensajeModal("Error", _
                          "No se pudo Completar el Proceso: " & loExcepcion.Message, _
                           vis3Controles.wbcAdministradorMensajeModal.enumTipoMensaje.KN_Error, _
                           "auto", _
                           "auto")

        End Try

    End Sub

    Protected Sub Page_Unload(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Unload
        Try

            loObjetoReporte.Close()

        Catch loExcepcion As Exception

        End Try

    End Sub

End Class
'-------------------------------------------------------------------------------------------'
' JJD: 06/12/08: Programacion inicial
'-------------------------------------------------------------------------------------------'
' YJP: 14/05/09: Agregar filtro revisión
'-------------------------------------------------------------------------------------------'
' CMS: 22/06/09: Metodo de ordenamiento
'-------------------------------------------------------------------------------------------'
' AAP:  01/07/09: Filtro "Sucursal:"
'-------------------------------------------------------------------------------------------'
