'-------------------------------------------------------------------------------------------'
' Inicio del codigo
'-------------------------------------------------------------------------------------------'
' Importando librerias 
'-------------------------------------------------------------------------------------------'
Imports System.Data

'-------------------------------------------------------------------------------------------'
' Inicio de clase "CGS_rStock_LoteAlmacen"
'-------------------------------------------------------------------------------------------'
Partial Class CGS_rStock_LoteAlmacen
    Inherits vis2formularios.frmReporte

    Dim loObjetoReporte As CrystalDecisions.CrystalReports.Engine.ReportDocument

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load

        Try

            Dim lcParametro0Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(0))
            Dim lcParametro0Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(0))
            Dim lcParametro1Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(1))
            Dim lcParametro1Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(1))
            Dim lcParametro2Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(2))
            Dim lcParametro2Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(2))
            Dim lcParametro3Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(3))
            Dim lcParametro3Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(3))
            Dim lcParametro4Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(4))
            Dim lcParametro4Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(4))

            Dim lcOrdenamiento As String = cusAplicacion.goReportes.pcOrden

            Dim loComandoSeleccionar As New StringBuilder()

            loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("DECLARE @lcCodAlm_Desde AS VARCHAR(10) = " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("Declare @lcCodAlm_Hasta As VARCHAR(10) = " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("DECLARE @lcCodArt_Desde AS VARCHAR(8)  = " & lcParametro1Desde)
            loComandoSeleccionar.AppendLine("Declare @lcCodArt_Hasta As VARCHAR(8)  = " & lcParametro1Hasta)
            loComandoSeleccionar.AppendLine("DECLARE @lcCodDep_Desde AS VARCHAR(2)  = " & lcParametro2Desde)
            loComandoSeleccionar.AppendLine("Declare @lcCodDep_Hasta As VARCHAR(2)  = " & lcParametro2Hasta)
            loComandoSeleccionar.AppendLine("DECLARE @lcCodSec_Desde AS VARCHAR(2)  = " & lcParametro3Desde)
            loComandoSeleccionar.AppendLine("Declare @lcCodSec_Hasta As VARCHAR(2)  = " & lcParametro3Hasta)
            loComandoSeleccionar.AppendLine("DECLARE @lcCodLot_Desde AS VARCHAR(30) = " & lcParametro4Desde)
            loComandoSeleccionar.AppendLine("Declare @lcCodLot_Hasta As VARCHAR(30) = " & lcParametro4Hasta)
            loComandoSeleccionar.AppendLine("DECLARE @lnCero AS DECIMAL(28,10) = 0")
            loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("DECLARE @tmpArticulos AS TABLE(Cod_Art CHAR(30), Saldo DECIMAL(28,10), Usa_Lot BIT) ;")
            loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("INSERT INTO @tmpArticulos ")
            loComandoSeleccionar.AppendLine("SELECT	Cod_Art, 0,Usa_Lot")
            loComandoSeleccionar.AppendLine("FROM Articulos")
            loComandoSeleccionar.AppendLine("WHERE Cod_Art BETWEEN @lcCodArt_Desde AND @lcCodArt_Hasta")
            loComandoSeleccionar.AppendLine("   AND Cod_Dep BETWEEN @lcCodDep_Desde AND @lcCodDep_Hasta")
            loComandoSeleccionar.AppendLine("	AND	Cod_Sec BETWEEN @lcCodSec_Desde AND @lcCodSec_Hasta")
            loComandoSeleccionar.AppendLine("		")
            loComandoSeleccionar.AppendLine("SELECT	'Ajustes'								AS	Operacion, 	")
            loComandoSeleccionar.AppendLine("		CASE WHEN Renglones_Ajustes.Tipo = 'Entrada'")
            loComandoSeleccionar.AppendLine("		     THEN 1 ELSE 2 END					AS	Orden,")
            loComandoSeleccionar.AppendLine("		Ajustes.Documento						AS	Documento,")
            loComandoSeleccionar.AppendLine("		Renglones_Ajustes.Cod_Art				AS	Cod_Art,")
            loComandoSeleccionar.AppendLine("       CASE WHEN Articulos.Usa_Lot = 1")
            loComandoSeleccionar.AppendLine("            THEN COALESCE(Operaciones_Lotes.Cod_Lot,'')")
            loComandoSeleccionar.AppendLine("            ELSE '' END                        AS Lote,")
            loComandoSeleccionar.AppendLine("		(CASE WHEN Renglones_Ajustes.Tipo = 'Entrada'  THEN COALESCE(Piezas.Res_Num, @lnCero) ELSE @lnCero END)	AS	Piezas_Ent,")
            loComandoSeleccionar.AppendLine("		(CASE WHEN Renglones_Ajustes.Tipo = 'Salida' THEN COALESCE(Piezas.Res_Num, @lnCero) ELSE @lnCero END)	AS	Piezas_Sal,")
            loComandoSeleccionar.AppendLine("		COALESCE(Longitud.Res_Num, 0)           AS  Longitud,")
            loComandoSeleccionar.AppendLine("		Ajustes.Fec_Ini							AS	Fec_Ini, 	")
            loComandoSeleccionar.AppendLine("		Renglones_Ajustes.Cod_Alm				AS	Cod_Alm, 	")
            loComandoSeleccionar.AppendLine("		Almacenes.Nom_Alm				        AS  Nom_Alm, 	")
            loComandoSeleccionar.AppendLine("		CASE WHEN Renglones_Ajustes.Tipo = 'Salida' ")
            loComandoSeleccionar.AppendLine("			  THEN (CASE WHEN Articulos.Usa_Lot = 1 THEN Operaciones_Lotes.Cantidad ELSE @lnCero END)")
            loComandoSeleccionar.AppendLine("			  ELSE @lnCero END					AS	CanLte_Sal, ")
            loComandoSeleccionar.AppendLine("		CASE WHEN Renglones_Ajustes.Tipo = 'Entrada'  ")
            loComandoSeleccionar.AppendLine("			THEN (CASE WHEN Articulos.Usa_Lot = 1 THEN Operaciones_Lotes.Cantidad ELSE @lnCero END) ")
            loComandoSeleccionar.AppendLine("			ELSE @lnCero END					AS	CanLte_Ent, ")
            loComandoSeleccionar.AppendLine("		@lnCero									AS	Saldo_Piezas,")
            loComandoSeleccionar.AppendLine(" 		Articulos.Saldo				            AS	Saldo		")
            loComandoSeleccionar.AppendLine("INTO #curTemporal ")
            loComandoSeleccionar.AppendLine("FROM Ajustes")
            loComandoSeleccionar.AppendLine("	JOIN Renglones_Ajustes ON Renglones_Ajustes.Documento = Ajustes.Documento")
            loComandoSeleccionar.AppendLine(" 	JOIN Almacenes ON Renglones_Ajustes.Cod_Alm = Almacenes.Cod_Alm")
            loComandoSeleccionar.AppendLine("	JOIN @tmpArticulos AS Articulos ON Articulos.Cod_Art = Renglones_Ajustes.Cod_Art ")
            loComandoSeleccionar.AppendLine("	LEFT JOIN Operaciones_Lotes ON Operaciones_Lotes.Num_Doc = Ajustes.Documento")
            loComandoSeleccionar.AppendLine("		AND Operaciones_Lotes.Tip_Doc = 'Ajustes_Inventarios'")
            loComandoSeleccionar.AppendLine("		AND Operaciones_Lotes.Tip_Ope = Renglones_Ajustes.Tipo")
            loComandoSeleccionar.AppendLine("		AND Operaciones_Lotes.Ren_Ori = Renglones_Ajustes.Renglon")
            loComandoSeleccionar.AppendLine("		AND Operaciones_Lotes.Cod_Art = Renglones_Ajustes.Cod_Art")
            loComandoSeleccionar.AppendLine("	LEFT JOIN Mediciones ON Mediciones.Cod_Reg = Ajustes.Documento")
            loComandoSeleccionar.AppendLine("		AND Mediciones.Origen = 'Ajustes_Inventarios'")
            loComandoSeleccionar.AppendLine("		AND Mediciones.Cod_Art = Articulos.Cod_Art")
            loComandoSeleccionar.AppendLine("	    AND Mediciones.Cod_Alm = Almacenes.Cod_Alm")
            loComandoSeleccionar.AppendLine("		AND Mediciones.Adicional LIKE ('%'+RTRIM(Operaciones_Lotes.Cod_Lot)+'%')")
            loComandoSeleccionar.AppendLine("		AND Renglones_Ajustes.Renglon = SUBSTRING(Mediciones.Adicional, LEN(Mediciones.Adicional), 1)")
            loComandoSeleccionar.AppendLine("	LEFT JOIN Renglones_Mediciones AS Piezas ON Mediciones.Documento = Piezas.Documento")
            loComandoSeleccionar.AppendLine("		AND Piezas.Cod_Var = 'AINV-NPIEZ'")
            loComandoSeleccionar.AppendLine("	LEFT JOIN Renglones_Mediciones AS Longitud ON Mediciones.Documento = Longitud.Documento")
            loComandoSeleccionar.AppendLine("		AND Longitud.Cod_Var = 'AINV-LARG'")
            loComandoSeleccionar.AppendLine("WHERE Ajustes.Status = 'Confirmado' ")
            loComandoSeleccionar.AppendLine("	AND	Renglones_Ajustes.Tipo IN ('Entrada', 'Salida') ")
            loComandoSeleccionar.AppendLine(" 	AND	Renglones_Ajustes.Cod_Alm BETWEEN @lcCodAlm_Desde AND @lcCodAlm_Hasta")
            loComandoSeleccionar.AppendLine("	AND Operaciones_Lotes.Cod_Lot BETWEEN @lcCodLot_Desde AND @lcCodLot_Hasta")
            loComandoSeleccionar.AppendLine(" 	")
            loComandoSeleccionar.AppendLine("UNION ALL ")
            loComandoSeleccionar.AppendLine("	")
            loComandoSeleccionar.AppendLine("SELECT 'Traslados'								AS	Operacion,	")
            loComandoSeleccionar.AppendLine("		2									    AS	Orden,")
            loComandoSeleccionar.AppendLine(" 		Traslados.Documento						AS	Documento,	")
            loComandoSeleccionar.AppendLine(" 		Renglones_Traslados.Cod_Art				AS	Cod_Art,")
            loComandoSeleccionar.AppendLine("       CASE WHEN Articulos.Usa_Lot = 1")
            loComandoSeleccionar.AppendLine("            THEN COALESCE(Operaciones_Lotes.Cod_Lot,'')")
            loComandoSeleccionar.AppendLine("            ELSE '' END                        AS Lote,")
            loComandoSeleccionar.AppendLine("		@lnCero									AS	Piezas_Ent,")
            loComandoSeleccionar.AppendLine("		COALESCE(Piezas.Res_Num, @lnCero)		AS	Piezas_Sal,")
            loComandoSeleccionar.AppendLine("		COALESCE(Longitud.Res_Num, @lnCero)     AS  Longitud,")
            loComandoSeleccionar.AppendLine(" 		Traslados.Fec_Ini						AS	Fec_Ini, ")
            loComandoSeleccionar.AppendLine(" 		Traslados.Alm_Ori						AS	Cod_Alm, ")
            loComandoSeleccionar.AppendLine("		Almacenes.Nom_Alm				        AS  Nom_Alm, ")
            loComandoSeleccionar.AppendLine("		CASE WHEN Articulos.Usa_Lot = 1")
            loComandoSeleccionar.AppendLine("            THEN Operaciones_Lotes.Cantidad")
            loComandoSeleccionar.AppendLine("            ELSE @lnCero END					AS	CanLte_Sal, ")
            loComandoSeleccionar.AppendLine(" 		@lnCero									AS	CanLte_Ent, ")
            loComandoSeleccionar.AppendLine("		@lnCero									AS	Saldo_Piezas,")
            loComandoSeleccionar.AppendLine(" 		Articulos.Saldo				            AS	Saldo		")
            loComandoSeleccionar.AppendLine("FROM Traslados")
            loComandoSeleccionar.AppendLine("	JOIN Renglones_Traslados ON Renglones_Traslados.Documento = Traslados.Documento")
            loComandoSeleccionar.AppendLine(" 	JOIN Almacenes ON Traslados.Alm_Ori = Almacenes.Cod_Alm")
            loComandoSeleccionar.AppendLine("	JOIN @tmpArticulos AS Articulos ON Articulos.Cod_Art = Renglones_Traslados.Cod_Art")
            loComandoSeleccionar.AppendLine("	LEFT JOIN Operaciones_Lotes ON Operaciones_Lotes.Num_Doc = Traslados.Documento")
            loComandoSeleccionar.AppendLine("		AND Operaciones_Lotes.Tip_Doc = 'Traslados'")
            loComandoSeleccionar.AppendLine("		AND Operaciones_Lotes.Tip_Ope = 'Salida'")
            loComandoSeleccionar.AppendLine("		AND Operaciones_Lotes.Ren_Ori = Renglones_Traslados.Renglon")
            loComandoSeleccionar.AppendLine("		AND Operaciones_Lotes.Cod_Art = Renglones_Traslados.Cod_Art ")
            loComandoSeleccionar.AppendLine("	LEFT JOIN Mediciones ON Mediciones.Cod_Reg = Traslados.Documento")
            loComandoSeleccionar.AppendLine("		AND Mediciones.Origen = 'Traslados'")
            loComandoSeleccionar.AppendLine("		AND Mediciones.Cod_Art = Articulos.Cod_Art")
            loComandoSeleccionar.AppendLine("	    AND Mediciones.Cod_Alm = Almacenes.Cod_Alm")
            loComandoSeleccionar.AppendLine("		AND Mediciones.Adicional LIKE ('%'+RTRIM(Operaciones_Lotes.Cod_Lot)+'%')")
            loComandoSeleccionar.AppendLine("		AND Renglones_Traslados.Renglon = SUBSTRING(Mediciones.Adicional, LEN(Mediciones.Adicional), 1)")
            loComandoSeleccionar.AppendLine("	LEFT JOIN Renglones_Mediciones AS Piezas ON Mediciones.Documento = Piezas.Documento")
            loComandoSeleccionar.AppendLine("		AND Piezas.Cod_Var IN ('TA-NPIEZ', 'TALM-NPIEZ')")
            loComandoSeleccionar.AppendLine("	LEFT JOIN Renglones_Mediciones AS Longitud ON Mediciones.Documento = Longitud.Documento")
            loComandoSeleccionar.AppendLine("		AND Longitud.Cod_Var = 'TA-LARG'")
            loComandoSeleccionar.AppendLine("WHERE Traslados.Status IN ('Confirmado', 'Procesado')	")
            loComandoSeleccionar.AppendLine("	AND Traslados.Alm_Ori BETWEEN @lcCodAlm_Desde AND @lcCodAlm_Hasta")
            loComandoSeleccionar.AppendLine("	AND Operaciones_Lotes.Cod_Lot BETWEEN @lcCodLot_Desde AND @lcCodLot_Hasta")
            loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("UNION ALL ")
            loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("SELECT 'Traslados'								AS	Operacion,	")
            loComandoSeleccionar.AppendLine("		1									    AS	Orden,")
            loComandoSeleccionar.AppendLine(" 		Traslados.Documento						AS	Documento,")
            loComandoSeleccionar.AppendLine(" 		Renglones_Traslados.Cod_Art				AS	Cod_Art,")
            loComandoSeleccionar.AppendLine("       CASE WHEN Articulos.Usa_Lot = 1")
            loComandoSeleccionar.AppendLine("            THEN COALESCE(Operaciones_Lotes.Cod_Lot,'')")
            loComandoSeleccionar.AppendLine("            ELSE '' END                        AS Lote,")
            loComandoSeleccionar.AppendLine("		COALESCE(Piezas.Res_Num, @lnCero)		AS	Piezas_Ent,")
            loComandoSeleccionar.AppendLine("		@lnCero									AS	Piezas_Sal,")
            loComandoSeleccionar.AppendLine("		COALESCE(Longitud.Res_Num, @lnCero)     AS  Longitud,")
            loComandoSeleccionar.AppendLine(" 		Traslados.Fec_Ini						AS	Fec_Ini, 	")
            loComandoSeleccionar.AppendLine(" 		CASE Traslados.Status					")
            loComandoSeleccionar.AppendLine(" 		    WHEN 'Confirmado'	THEN 'TRANSITO'")
            loComandoSeleccionar.AppendLine(" 		    WHEN 'Procesado'	THEN Traslados.Alm_Des")
            loComandoSeleccionar.AppendLine(" 		END										AS	Cod_Alm, 	")
            loComandoSeleccionar.AppendLine("		Almacenes.Nom_Alm				        AS  Nom_Alm, 	")
            loComandoSeleccionar.AppendLine("		@lnCero									AS	CanLte_Sal, 	")
            loComandoSeleccionar.AppendLine("		CASE WHEN Articulos.Usa_Lot = 1")
            loComandoSeleccionar.AppendLine("            THEN Operaciones_Lotes.Cantidad")
            loComandoSeleccionar.AppendLine("            ELSE @lnCero END					AS	CanLte_Ent, 	")
            loComandoSeleccionar.AppendLine("		@lnCero									AS	Saldo_Piezas,")
            loComandoSeleccionar.AppendLine(" 		Articulos.Saldo				            AS	Saldo		")
            loComandoSeleccionar.AppendLine("FROM Traslados")
            loComandoSeleccionar.AppendLine("	JOIN Renglones_Traslados ON Renglones_Traslados.Documento = Traslados.Documento")
            loComandoSeleccionar.AppendLine(" 	JOIN Almacenes ON Traslados.Alm_Des = Almacenes.Cod_Alm")
            loComandoSeleccionar.AppendLine("	JOIN @tmpArticulos AS Articulos ON Articulos.Cod_Art = Renglones_Traslados.Cod_Art ")
            loComandoSeleccionar.AppendLine("	LEFT JOIN Operaciones_Lotes ON Operaciones_Lotes.Num_Doc = Traslados.Documento")
            loComandoSeleccionar.AppendLine("		AND Operaciones_Lotes.Tip_Doc = 'Traslados'")
            loComandoSeleccionar.AppendLine("		AND Operaciones_Lotes.Tip_Ope = 'Entrada'")
            loComandoSeleccionar.AppendLine("		AND Operaciones_Lotes.Ren_Ori = Renglones_Traslados.Renglon")
            loComandoSeleccionar.AppendLine("		AND Operaciones_Lotes.Cod_Art = Renglones_Traslados.Cod_Art")
            loComandoSeleccionar.AppendLine("	LEFT JOIN Mediciones ON Mediciones.Cod_Reg = Traslados.Documento")
            loComandoSeleccionar.AppendLine("		AND Mediciones.Origen = 'Traslados'")
            loComandoSeleccionar.AppendLine("		AND Mediciones.Cod_Art = Articulos.Cod_Art")
            loComandoSeleccionar.AppendLine("	    AND Mediciones.Cod_Alm = Almacenes.Cod_Alm")
            loComandoSeleccionar.AppendLine("		AND Mediciones.Adicional LIKE ('%'+RTRIM(Operaciones_Lotes.Cod_Lot)+'%')")
            loComandoSeleccionar.AppendLine("		AND Renglones_Traslados.Renglon = SUBSTRING(Mediciones.Adicional, LEN(Mediciones.Adicional), 1)")
            loComandoSeleccionar.AppendLine("	LEFT JOIN Renglones_Mediciones AS Piezas ON Mediciones.Documento = Piezas.Documento")
            loComandoSeleccionar.AppendLine("		AND Piezas.Cod_Var IN ('TA-NPIEZ', 'TALM-NPIEZ')")
            loComandoSeleccionar.AppendLine("	LEFT JOIN Renglones_Mediciones AS Longitud ON Mediciones.Documento = Longitud.Documento")
            loComandoSeleccionar.AppendLine("		AND Longitud.Cod_Var = 'TA-LARG'")
            loComandoSeleccionar.AppendLine("WHERE Traslados.Status IN ('Confirmado', 'Procesado')	")
            loComandoSeleccionar.AppendLine(" 	AND (CASE Traslados.Status					")
            loComandoSeleccionar.AppendLine(" 		    WHEN 'Confirmado' THEN 'TRANSITO'")
            loComandoSeleccionar.AppendLine(" 		    WHEN 'Procesado' THEN Traslados.Alm_Des")
            loComandoSeleccionar.AppendLine(" 		END) BETWEEN @lcCodAlm_Desde AND @lcCodAlm_Hasta")
            loComandoSeleccionar.AppendLine("   AND Operaciones_Lotes.Cod_Lot BETWEEN @lcCodLot_Desde AND @lcCodLot_Hasta")
            loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("UNION ALL ")
            loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("SELECT	'Recepciones'						    AS	Operacion,	")
            loComandoSeleccionar.AppendLine("		1									    AS	Orden,")
            loComandoSeleccionar.AppendLine(" 		Recepciones.Documento				    AS	Documento,")
            loComandoSeleccionar.AppendLine(" 		Renglones_Recepciones.Cod_Art		    AS	Cod_Art,")
            loComandoSeleccionar.AppendLine("       CASE WHEN Articulos.Usa_Lot = 1")
            loComandoSeleccionar.AppendLine("            THEN COALESCE(Operaciones_Lotes.Cod_Lot,'')")
            loComandoSeleccionar.AppendLine("            ELSE '' END                        AS Lote,")
            loComandoSeleccionar.AppendLine("       COALESCE(Piezas.Res_Num, @lnCero) 		AS	Piezas_Ent,")
            loComandoSeleccionar.AppendLine("       @lnCero									AS	Piezas_Sal,")
            loComandoSeleccionar.AppendLine("		@lnCero                                 AS  Longitud,")
            loComandoSeleccionar.AppendLine(" 		Recepciones.Fec_Ini					    AS	Fec_Ini, 	")
            loComandoSeleccionar.AppendLine(" 		Renglones_Recepciones.Cod_Alm		    AS	Cod_Alm, 	")
            loComandoSeleccionar.AppendLine("		Almacenes.Nom_Alm				        AS  Nom_Alm, 	")
            loComandoSeleccionar.AppendLine("		@lnCero									AS	CanLte_Sal, ")
            loComandoSeleccionar.AppendLine("		CASE WHEN Articulos.Usa_Lot = 1")
            loComandoSeleccionar.AppendLine("            THEN Operaciones_Lotes.Cantidad")
            loComandoSeleccionar.AppendLine("            ELSE @lnCero END					AS	CanLte_Ent,	")
            loComandoSeleccionar.AppendLine("       @lnCero									AS	Saldo_Piezas,")
            loComandoSeleccionar.AppendLine(" 		Articulos.Saldo				            AS	Saldo ")
            loComandoSeleccionar.AppendLine("FROM Recepciones")
            loComandoSeleccionar.AppendLine("	JOIN Renglones_Recepciones ON Renglones_Recepciones.Documento = Recepciones.Documento")
            loComandoSeleccionar.AppendLine(" 	JOIN Almacenes ON Renglones_Recepciones.Cod_Alm = Almacenes.Cod_Alm")
            loComandoSeleccionar.AppendLine("	JOIN @tmpArticulos AS Articulos ON Articulos.Cod_Art = Renglones_Recepciones.Cod_Art ")
            loComandoSeleccionar.AppendLine("	LEFT JOIN Operaciones_Lotes ON Operaciones_Lotes.Num_Doc = Recepciones.Documento")
            loComandoSeleccionar.AppendLine("		AND Operaciones_Lotes.Tip_Doc = 'Recepciones'")
            loComandoSeleccionar.AppendLine("		AND Operaciones_Lotes.Tip_Ope = 'Entrada'")
            loComandoSeleccionar.AppendLine("		AND Operaciones_Lotes.Ren_Ori = Renglones_Recepciones.Renglon")
            loComandoSeleccionar.AppendLine("		AND Operaciones_Lotes.Cod_Art = Renglones_Recepciones.Cod_Art")
            loComandoSeleccionar.AppendLine("	LEFT JOIN Mediciones ON Mediciones.Cod_Reg = Recepciones.Documento")
            loComandoSeleccionar.AppendLine("		AND Mediciones.Origen = 'Recepciones'")
            loComandoSeleccionar.AppendLine("		AND Mediciones.Cod_Art = Articulos.Cod_Art")
            loComandoSeleccionar.AppendLine("	    AND Mediciones.Cod_Alm = Almacenes.Cod_Alm")
            loComandoSeleccionar.AppendLine("		AND Mediciones.Adicional LIKE ('%'+RTRIM(Operaciones_Lotes.Cod_Lot)+'%')")
            loComandoSeleccionar.AppendLine("		AND Renglones_Recepciones.Renglon = SUBSTRING(Mediciones.Adicional, LEN(Mediciones.Adicional), 1)")
            loComandoSeleccionar.AppendLine("	LEFT JOIN Renglones_Mediciones AS Piezas ON Mediciones.Documento = Piezas.Documento")
            loComandoSeleccionar.AppendLine("		AND Piezas.Cod_Var = 'NREC-NPIEZ'")
            loComandoSeleccionar.AppendLine("WHERE Recepciones.Status IN ('Confirmado', 'Afectado', 'Procesado')")
            loComandoSeleccionar.AppendLine("	AND Renglones_Recepciones.Cod_Alm BETWEEN @lcCodAlm_Desde AND @lcCodAlm_Hasta")
            loComandoSeleccionar.AppendLine("	AND Operaciones_Lotes.Cod_Lot BETWEEN @lcCodLot_Desde AND @lcCodLot_Hasta")
            loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("UNION ALL ")
            loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("SELECT	'Ordenes_Trabajo'						AS	Operacion,	")
            loComandoSeleccionar.AppendLine("		1										AS	Orden,")
            loComandoSeleccionar.AppendLine(" 		Encabezados.Documento					AS	Documento,	")
            loComandoSeleccionar.AppendLine(" 		Formulas.Cod_Art						AS	Cod_Art,")
            loComandoSeleccionar.AppendLine("       CASE WHEN Articulos.Usa_Lot = 1")
            loComandoSeleccionar.AppendLine("            THEN COALESCE(Operaciones_Lotes.Cod_Lot,'')")
            loComandoSeleccionar.AppendLine("            ELSE '' END                        AS Lote,")
            loComandoSeleccionar.AppendLine("       COALESCE(Piezas.Res_Num, @lnCero)		AS	Piezas_Ent,")
            loComandoSeleccionar.AppendLine("       @lnCero								    AS	Piezas_Sal,")
            loComandoSeleccionar.AppendLine("		COALESCE(Longitud.Res_Num, @lnCero)     AS  Longitud,")
            loComandoSeleccionar.AppendLine(" 		Encabezados.Fec_Ini						AS	Fec_Ini, 	")
            loComandoSeleccionar.AppendLine(" 		Encabezados.Cod_Alm						AS	Cod_Alm, ")
            loComandoSeleccionar.AppendLine("		Almacenes.Nom_Alm						AS 	Nom_Alm,	")
            loComandoSeleccionar.AppendLine("		@lnCero									AS	CanLte_Sal, 	")
            loComandoSeleccionar.AppendLine("		CASE WHEN Articulos.Usa_Lot = 1")
            loComandoSeleccionar.AppendLine("            THEN Operaciones_Lotes.Cantidad")
            loComandoSeleccionar.AppendLine("            ELSE @lnCero END					AS	CanLte_Ent,	")
            loComandoSeleccionar.AppendLine("       @lnCero								    AS	Saldo_Piezas,")
            loComandoSeleccionar.AppendLine("		Articulos.Saldo							AS	Saldo ")
            loComandoSeleccionar.AppendLine("FROM Encabezados")
            loComandoSeleccionar.AppendLine("	JOIN Renglones ON Encabezados.Documento = Renglones.Documento ")
            loComandoSeleccionar.AppendLine("		AND Renglones.Origen = 'Ordenes de Trabajo'")
            loComandoSeleccionar.AppendLine("	JOIN Almacenes ON Encabezados.Cod_Alm = Almacenes.Cod_Alm	")
            loComandoSeleccionar.AppendLine("	JOIN Formulas ON Renglones.Cod_Reg = Formulas.Documento")
            loComandoSeleccionar.AppendLine("	JOIN @tmpArticulos AS Articulos ON Articulos.Cod_Art = Formulas.Cod_Art ")
            loComandoSeleccionar.AppendLine("	LEFT JOIN Operaciones_Lotes ON Operaciones_Lotes.Num_Doc = Encabezados.Documento")
            loComandoSeleccionar.AppendLine("		AND Operaciones_Lotes.Tip_Doc = 'Encabezados'")
            loComandoSeleccionar.AppendLine("		AND Operaciones_Lotes.Adicional = 'Ordenes de Trabajo'")
            loComandoSeleccionar.AppendLine("		AND Operaciones_Lotes.Tip_Ope = 'Entrada'")
            loComandoSeleccionar.AppendLine("		AND Operaciones_Lotes.Ren_Ori = Renglones.Renglon")
            loComandoSeleccionar.AppendLine("		AND Operaciones_Lotes.Cod_Art = Articulos.Cod_Art")
            loComandoSeleccionar.AppendLine("	LEFT JOIN Mediciones ON Mediciones.Cod_Reg = Encabezados.Documento")
            loComandoSeleccionar.AppendLine("		AND Mediciones.Origen = 'Encabezados'")
            loComandoSeleccionar.AppendLine("		AND Mediciones.Cod_Art = Articulos.Cod_Art")
            loComandoSeleccionar.AppendLine("	    AND Mediciones.Cod_Alm = Almacenes.Cod_Alm")
            loComandoSeleccionar.AppendLine("		AND Mediciones.Adicional LIKE ('%'+RTRIM(Operaciones_Lotes.Cod_Lot)+'%')")
            loComandoSeleccionar.AppendLine("		AND Renglones.Renglon = SUBSTRING(Mediciones.Adicional, LEN(Mediciones.Adicional), 1)")
            loComandoSeleccionar.AppendLine("	LEFT JOIN Renglones_Mediciones AS Piezas ON Mediciones.Documento = Piezas.Documento")
            loComandoSeleccionar.AppendLine("		AND Piezas.Cod_Var = 'OTRA-NPIEZ'")
            loComandoSeleccionar.AppendLine("	LEFT JOIN Renglones_Mediciones AS Longitud ON Mediciones.Documento = Longitud.Documento")
            loComandoSeleccionar.AppendLine("		AND Longitud.Cod_Var = 'OTRA-LARG'")
            loComandoSeleccionar.AppendLine("WHERE Encabezados.Status IN ('Confirmado', 'Procesado') ")
            loComandoSeleccionar.AppendLine("	AND Encabezados.Origen = 'Ordenes de Trabajo'")
            loComandoSeleccionar.AppendLine("		AND Encabezados.Cod_Alm BETWEEN @lcCodAlm_Desde AND @lcCodAlm_Hasta")
            loComandoSeleccionar.AppendLine("		AND Operaciones_Lotes.Cod_Lot BETWEEN @lcCodLot_Desde AND @lcCodLot_Hasta")
            loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("UNION ALL ")
            loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("SELECT	'Consumos_Produccion'					AS	Operacion,	")
            loComandoSeleccionar.AppendLine("		2										AS	Orden,")
            loComandoSeleccionar.AppendLine(" 		Encabezados.Documento					AS	Documento,	")
            loComandoSeleccionar.AppendLine(" 		Renglones.Cod_Art						AS	Cod_Art,")
            loComandoSeleccionar.AppendLine("       CASE WHEN Articulos.Usa_Lot = 1")
            loComandoSeleccionar.AppendLine("            THEN COALESCE(Operaciones_Lotes.Cod_Lot,'')")
            loComandoSeleccionar.AppendLine("            ELSE '' END                        AS Lote,")
            loComandoSeleccionar.AppendLine("       @lnCero								    AS	Piezas_Ent,")
            loComandoSeleccionar.AppendLine("		COALESCE(Piezas.Res_Num, @lnCero)		AS	Piezas_Sal,")
            loComandoSeleccionar.AppendLine("		COALESCE(Longitud.Res_Num, @lnCero)     AS  Longitud,")
            loComandoSeleccionar.AppendLine(" 		Encabezados.Fec_Ini						AS	Fec_Ini, 	")
            loComandoSeleccionar.AppendLine(" 		Encabezados.Cod_Alm						AS	Cod_Alm, ")
            loComandoSeleccionar.AppendLine("		Almacenes.Nom_Alm						AS 	Nom_Alm,	")
            loComandoSeleccionar.AppendLine("		CASE WHEN Articulos.Usa_Lot = 1")
            loComandoSeleccionar.AppendLine("            THEN Operaciones_Lotes.Cantidad")
            loComandoSeleccionar.AppendLine("            ELSE @lnCero END					AS	CanLte_Sal,")
            loComandoSeleccionar.AppendLine(" 		@lnCero				                    AS	CanLte_Ent,	")
            loComandoSeleccionar.AppendLine("       @lnCero								    AS	Saldo_Piezas,")
            loComandoSeleccionar.AppendLine("		Articulos.Saldo							AS	Saldo ")
            loComandoSeleccionar.AppendLine("FROM Encabezados")
            loComandoSeleccionar.AppendLine("	JOIN Renglones ON Encabezados.Documento = Renglones.Documento ")
            loComandoSeleccionar.AppendLine("		AND Renglones.Origen = 'Consumos Produccion'")
            loComandoSeleccionar.AppendLine("	JOIN Almacenes ON Encabezados.Cod_Alm = Almacenes.Cod_Alm	")
            loComandoSeleccionar.AppendLine("	JOIN @tmpArticulos AS Articulos ON Articulos.Cod_Art = Renglones.Cod_Art ")
            loComandoSeleccionar.AppendLine("	LEFT JOIN Operaciones_Lotes ON Operaciones_Lotes.Num_Doc = Encabezados.Documento")
            loComandoSeleccionar.AppendLine("		AND Operaciones_Lotes.Tip_Doc = 'Encabezados'")
            loComandoSeleccionar.AppendLine("		AND Operaciones_Lotes.Adicional = 'Consumos Produccion'")
            loComandoSeleccionar.AppendLine("		AND Operaciones_Lotes.Tip_Ope = 'Salida'")
            loComandoSeleccionar.AppendLine("		AND Operaciones_Lotes.Ren_Ori = Renglones.Renglon")
            loComandoSeleccionar.AppendLine("		AND Operaciones_Lotes.Cod_Art = Articulos.Cod_Art")
            loComandoSeleccionar.AppendLine("	LEFT JOIN Mediciones ON Mediciones.Cod_Reg = Encabezados.Documento")
            loComandoSeleccionar.AppendLine("		AND Mediciones.Origen = 'Encabezados'")
            loComandoSeleccionar.AppendLine("		AND Mediciones.Cod_Art = Articulos.Cod_Art")
            loComandoSeleccionar.AppendLine("	    AND Mediciones.Cod_Alm = Almacenes.Cod_Alm")
            loComandoSeleccionar.AppendLine("		AND Mediciones.Adicional LIKE ('%'+RTRIM(Operaciones_Lotes.Cod_Lot)+'%')")
            loComandoSeleccionar.AppendLine("		AND Renglones.Renglon = SUBSTRING(Mediciones.Adicional, LEN(Mediciones.Adicional), 1)")
            loComandoSeleccionar.AppendLine("	LEFT JOIN Renglones_Mediciones AS Piezas ON Mediciones.Documento = Piezas.Documento")
            loComandoSeleccionar.AppendLine("		AND Piezas.Cod_Var = 'CPRO-NPIEZ'")
            loComandoSeleccionar.AppendLine("	LEFT JOIN Renglones_Mediciones AS Longitud ON Mediciones.Documento = Longitud.Documento")
            loComandoSeleccionar.AppendLine("		AND Longitud.Cod_Var = 'CPRO-LARG'")
            loComandoSeleccionar.AppendLine("WHERE Encabezados.Status IN ('Confirmado', 'Procesado') ")
            loComandoSeleccionar.AppendLine("	AND Encabezados.Origen = 'Consumos Produccion'")
            loComandoSeleccionar.AppendLine("		AND Encabezados.Cod_Alm BETWEEN @lcCodAlm_Desde AND @lcCodAlm_Hasta")
            loComandoSeleccionar.AppendLine("		AND Operaciones_Lotes.Cod_Lot BETWEEN @lcCodLot_Desde AND @lcCodLot_Hasta")
            loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("CREATE CLUSTERED INDEX PK_Fecha ON #curTemporal(Fec_Ini)")
            loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("UPDATE #curTemporal")
            loComandoSeleccionar.AppendLine("SET	Saldo = S.Saldo,")
            loComandoSeleccionar.AppendLine("	Saldo_Piezas = S.Saldo_Piezas")
            loComandoSeleccionar.AppendLine("FROM (SELECT Cod_Art, Cod_Alm, Lote,")
            loComandoSeleccionar.AppendLine("			 SUM(CanLte_Ent - CanLte_Sal) As Saldo,")
            loComandoSeleccionar.AppendLine("			 SUM(Piezas_Ent - Piezas_Sal) As Saldo_Piezas		")
            loComandoSeleccionar.AppendLine("	  FROM #curTemporal")
            loComandoSeleccionar.AppendLine("	  GROUP BY Cod_Art, Cod_Alm, Lote)	AS S")
            loComandoSeleccionar.AppendLine("WHERE #curTemporal.Cod_Art = S.Cod_Art  ")
            loComandoSeleccionar.AppendLine("	AND	#curTemporal.Cod_Alm = S.Cod_Alm")
            loComandoSeleccionar.AppendLine("	AND	#curTemporal.Lote = S.Lote ")
            loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("SELECT	DISTINCT")
            loComandoSeleccionar.AppendLine("		#curTemporal.Cod_Alm				                            AS Cod_Alm,")
            loComandoSeleccionar.AppendLine("		#curTemporal.Nom_Alm				                            AS Nom_Alm,")
            loComandoSeleccionar.AppendLine("		#curTemporal.Cod_Art				                            AS Cod_Art,")
            loComandoSeleccionar.AppendLine("		Articulos.Nom_Art					                            AS Nom_Art,")
            loComandoSeleccionar.AppendLine("		CASE WHEN LEN(Articulos.Nom_Art) > 50")
            loComandoSeleccionar.AppendLine("			 THEN CONCAT(SUBSTRING(Articulos.Nom_Art, 0, 50), '...')")
            loComandoSeleccionar.AppendLine("			 ELSE Articulos.Nom_Art")
            loComandoSeleccionar.AppendLine("		END											                    AS Descripcion,")
            loComandoSeleccionar.AppendLine("		Articulos.Cod_Uni1							                    AS Cod_Uni,")
            loComandoSeleccionar.AppendLine("		Articulos.Usa_Lot							                    AS Usa_Lot,")
            loComandoSeleccionar.AppendLine("		Departamentos.Nom_Dep						                    AS Nom_Dep,")
            loComandoSeleccionar.AppendLine("		Secciones.Nom_Sec							                    AS Nom_Sec,")
            loComandoSeleccionar.AppendLine("       CASE WHEN Articulos.Usa_Lot = 0")
            loComandoSeleccionar.AppendLine("            THEN Renglones_Almacenes.Exi_Act1")
            loComandoSeleccionar.AppendLine("            ELSE COALESCE(Renglones_Lotes.Exi_Act1,Renglones_Almacenes.Exi_Act1)")
            loComandoSeleccionar.AppendLine("       END                                                             AS Existencia,")
            loComandoSeleccionar.AppendLine("       CASE WHEN Articulos.Usa_Lot = 0")
            loComandoSeleccionar.AppendLine("            THEN ''")
            loComandoSeleccionar.AppendLine("            ELSE COALESCE(#curTemporal.Lote,'')")
            loComandoSeleccionar.AppendLine("       END                                                             AS Lote,")
            loComandoSeleccionar.AppendLine("		#curTemporal.Saldo_Piezas			                            AS Piezas,")
            loComandoSeleccionar.AppendLine("		COALESCE((SELECT TOP 1 Desperdicio.Res_Num ")
            loComandoSeleccionar.AppendLine("				 FROM Mediciones ")
            loComandoSeleccionar.AppendLine("					LEFT JOIN Renglones_Mediciones AS Desperdicio ON Mediciones.Documento = Desperdicio.Documento")
            loComandoSeleccionar.AppendLine("						AND Desperdicio.Cod_Var  IN ('AINV-PDESP', 'NREC-PDESP', 'TA-PDESP','OTRA-PDESP','CPRO-PDESP')")
            loComandoSeleccionar.AppendLine("				WHERE Mediciones.Cod_Art = Articulos.Cod_Art")
            'loComandoSeleccionar.AppendLine("                     Mediciones.Cod_Alm = #curTemporal.Nom_Alm")
            loComandoSeleccionar.AppendLine("					AND Mediciones.Origen IN ('Ajustes_Inventarios', 'Recepciones', 'Traslados', 'Encabezados')")
            loComandoSeleccionar.AppendLine("					AND Mediciones.Adicional LIKE ('%'+RTRIM(Renglones_Lotes.Cod_Lot)+'%')")
            loComandoSeleccionar.AppendLine("				ORDER BY Mediciones.Fecha DESC),0)                      AS Porc_Desperdicio,")
            loComandoSeleccionar.AppendLine("		CASE WHEN @lcCodArt_Desde <> ''")
            loComandoSeleccionar.AppendLine("			 THEN (SELECT Nom_Art FROM Articulos WHERE Cod_Art = @lcCodArt_Desde)")
            loComandoSeleccionar.AppendLine("			 ELSE '' END				                                AS Art_Desde,")
            loComandoSeleccionar.AppendLine("		CASE WHEN @lcCodArt_Hasta <> 'zzzzzzz'")
            loComandoSeleccionar.AppendLine("			 THEN (SELECT Nom_Art FROM Articulos WHERE Cod_Art = @lcCodArt_Hasta)")
            loComandoSeleccionar.AppendLine("			 ELSE '' END				                                AS Art_Hasta,")
            loComandoSeleccionar.AppendLine("		CASE WHEN @lcCodDep_Desde <> ''")
            loComandoSeleccionar.AppendLine("			 THEN (SELECT Nom_Dep FROM Departamentos WHERE Cod_Dep = @lcCodDep_Desde)")
            loComandoSeleccionar.AppendLine("			 ELSE '' END				                                AS Dep_Desde,")
            loComandoSeleccionar.AppendLine("		CASE WHEN @lcCodDep_Hasta <> 'zzzzzzz'")
            loComandoSeleccionar.AppendLine("			 THEN (SELECT Nom_Dep FROM Departamentos WHERE Cod_Dep = @lcCodDep_Hasta)")
            loComandoSeleccionar.AppendLine("			 ELSE '' END				                                AS Dep_Hasta,")
            loComandoSeleccionar.AppendLine("		CASE WHEN @lcCodSec_Desde <> ''")
            loComandoSeleccionar.AppendLine("			 THEN (SELECT Nom_Sec FROM Secciones WHERE Cod_Sec = @lcCodSec_Desde AND Cod_Dep = @lcCodDep_Desde)")
            loComandoSeleccionar.AppendLine("			 ELSE '' END				                                AS Sec_Desde,")
            loComandoSeleccionar.AppendLine("		CASE WHEN @lcCodSec_Hasta <> 'zzzzzzz'")
            loComandoSeleccionar.AppendLine("			 THEN (SELECT Nom_Sec FROM Secciones WHERE Cod_Sec = @lcCodSec_Hasta AND Cod_Dep = @lcCodDep_Hasta)")
            loComandoSeleccionar.AppendLine("			 ELSE '' END				                                AS Sec_Hasta,")
            loComandoSeleccionar.AppendLine("		CASE WHEN @lcCodAlm_Desde <> ''")
            loComandoSeleccionar.AppendLine("			 THEN (SELECT Nom_Alm FROM Almacenes  WHERE Cod_Alm = @lcCodAlm_Desde)")
            loComandoSeleccionar.AppendLine("			 ELSE '' END				                                AS Alm_Desde,")
            loComandoSeleccionar.AppendLine("		CASE WHEN @lcCodAlm_Hasta <> 'zzzzzzz'")
            loComandoSeleccionar.AppendLine("			 THEN (SELECT Nom_Alm  FROM Almacenes  WHERE Cod_Alm = @lcCodAlm_Hasta)")
            loComandoSeleccionar.AppendLine("			 ELSE '' END				                                AS Alm_Hasta,")
            loComandoSeleccionar.AppendLine("		CONCAT(@lcCodLot_Desde, ' - ', (CASE WHEN @lcCodLot_Hasta = 'zzzzzzz' THEN '' ELSE @lcCodLot_Hasta END))	AS Lotes")
            loComandoSeleccionar.AppendLine("FROM #curTemporal")
            loComandoSeleccionar.AppendLine("	JOIN Articulos ON Articulos.Cod_Art = #curTemporal.Cod_Art")
            loComandoSeleccionar.AppendLine("	JOIN Departamentos ON Articulos.Cod_Dep = Departamentos.Cod_Dep")
            loComandoSeleccionar.AppendLine("	JOIN Secciones ON Secciones.Cod_Sec = Articulos.Cod_Sec")
            loComandoSeleccionar.AppendLine("	    AND Secciones.Cod_Dep = Departamentos.Cod_Dep")
            loComandoSeleccionar.AppendLine("	JOIN Renglones_Almacenes ON #curTemporal.Cod_Alm = Renglones_Almacenes.Cod_Alm")
            loComandoSeleccionar.AppendLine("		AND Renglones_Almacenes.Cod_Art = Articulos.Cod_Art")
            loComandoSeleccionar.AppendLine("	LEFT JOIN Lotes ON Articulos.Cod_Art = Lotes.Cod_Art")
            loComandoSeleccionar.AppendLine("		AND Lotes.Cod_Lot = #curTemporal.Lote")
            loComandoSeleccionar.AppendLine("	LEFT JOIN Renglones_Lotes ON Renglones_Lotes.Cod_Lot = Lotes.Cod_Lot ")
            loComandoSeleccionar.AppendLine("		AND Lotes.Cod_Art = Renglones_Lotes.Cod_Art")
            loComandoSeleccionar.AppendLine("		AND Renglones_Lotes.Cod_Alm = #curTemporal.Cod_Alm")
            loComandoSeleccionar.AppendLine("WHERE Lotes.Exi_Act1 > 0 OR Renglones_Almacenes.Exi_Act1 > 0")
            loComandoSeleccionar.AppendLine("ORDER BY Cod_Alm ASC, Cod_Art ASC")
            loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("DROP TABLE #curTemporal")
            loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("")


            'Me.mEscribirConsulta(loComandoSeleccionar.ToString())

            Dim loServicios As New cusDatos.goDatos

            Dim laDatosReporte As DataSet = loServicios.mObtenerTodosSinEsquema(loComandoSeleccionar.ToString, "curReportes")

            Me.mCargarLogoEmpresa(laDatosReporte.Tables(0), "LogoEmpresa")

            '-------------------------------------------------------------------------------------------------------
            ' Verificando si el select (tabla nº0) trae registros
            '-------------------------------------------------------------------------------------------------------

            If (laDatosReporte.Tables(0).Rows.Count <= 0) Then
                Me.WbcAdministradorMensajeModal.mMostrarMensajeModal("Información", _
                                          "No se Encontraron Registros para los Parámetros Especificados. ", _
                                           vis3Controles.wbcAdministradorMensajeModal.enumTipoMensaje.KN_Informacion, _
                                           "350px", _
                                           "200px")
            End If

            loObjetoReporte = cusAplicacion.goReportes.mCargarReporte("CGS_rStock_LoteAlmacen", laDatosReporte)

            Me.mTraducirReporte(loObjetoReporte)
            Me.mFormatearCamposReporte(loObjetoReporte)
            Me.crvCGS_rStock_LoteAlmacen.ReportSource = loObjetoReporte

        Catch loExcepcion As Exception

            Me.WbcAdministradorMensajeModal.mMostrarMensajeModal("Error", _
                          "No se pudo Completar el Proceso: " & loExcepcion.Message, _
                           vis3Controles.wbcAdministradorMensajeModal.enumTipoMensaje.KN_Error, _
                           "auto", _
                           "auto")

        End Try

    End Sub

    Protected Sub Page_Unload(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Unload
        Try

            loObjetoReporte.Close()

        Catch loExcepcion As Exception


        End Try
    End Sub

End Class
'---------------------------------------------------------------------------------------------------------------'
' Fin del codigo
'---------------------------------------------------------------------------------------------------------------'
' CMS: 28/08/08: Codigo inicial
'---------------------------------------------------------------------------------------------------------------'
' GS: 02/02/17: Las mediciones solo se realizan desde Ajustes de Inventario, Recepciones y Órdenes de Trabajo
'---------------------------------------------------------------------------------------------------------------'