'-------------------------------------------------------------------------------------------'
' Inicio del codigo
'-------------------------------------------------------------------------------------------'
' Importando librerias 
'-------------------------------------------------------------------------------------------'
Imports System.Data

'-------------------------------------------------------------------------------------------'
' Inicio de clase "fFicha_Expedientes"
'-------------------------------------------------------------------------------------------'
Partial Class fFicha_Expedientes
    Inherits vis2Formularios.frmReporte

    Dim loObjetoReporte As CrystalDecisions.CrystalReports.Engine.ReportDocument

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load

        Try

            Dim loComandoSeleccionar As New StringBuilder()
            
            Dim llIncluyeImpuesto AS Boolean = goOpciones.mObtener("INCIMPORDP","L")
            
            loComandoSeleccionar.AppendLine(" ")	
			loComandoSeleccionar.AppendLine(" SELECT CAST(Seguimientos as XML) AS Seg_XML INTO #xmlData from Expedientes")
            loComandoSeleccionar.AppendLine(" WHERE " & cusAplicacion.goFormatos.pcCondicionPrincipal)
			loComandoSeleccionar.AppendLine(" ")	
            
            loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("SELECT			Expedientes.Documento			AS	Documento	,")
			loComandoSeleccionar.AppendLine("				Expedientes.Status				AS	Status		,")
			loComandoSeleccionar.AppendLine("				Expedientes.Expediente			AS	Expediente	,")
			loComandoSeleccionar.AppendLine("				Expedientes.Importacion			AS	Importacion	,")
			loComandoSeleccionar.AppendLine("				Expedientes.Factura				AS	Factura		,")
			loComandoSeleccionar.AppendLine("				Expedientes.Control				As	Control		,")
			loComandoSeleccionar.AppendLine("				Expedientes.Declaracion			AS	Declaracion	,")
			loComandoSeleccionar.AppendLine("				Expedientes.Pla_Liq				AS	Pla_Liq		,")
			loComandoSeleccionar.AppendLine("				Expedientes.Cod_Log				AS	Cod_Log		,")
 			loComandoSeleccionar.AppendLine("				Operadores.Nom_Pro				AS	Nom_Log		,")
			loComandoSeleccionar.AppendLine("				Expedientes.Cod_Reg				AS	Cod_Reg		,")
 			loComandoSeleccionar.AppendLine("				Proveedores.Nom_Pro				AS	Nom_Reg		,")
			loComandoSeleccionar.AppendLine("				Expedientes.Cod_Cli				AS	Cod_Cli		,")
 			loComandoSeleccionar.AppendLine("				Clientes.Nom_Cli				AS	Nom_Cli		,")
			loComandoSeleccionar.AppendLine("				Expedientes.Tipo				AS	Tipo		,")
			loComandoSeleccionar.AppendLine("				Expedientes.Clase				AS	Clase		,")
			loComandoSeleccionar.AppendLine("				Expedientes.Descripcion			AS	Descripcion	,")
			loComandoSeleccionar.AppendLine("				Expedientes.Comentario			AS	Comentario	,")
			loComandoSeleccionar.AppendLine("				Expedientes.Fec_Ini				AS	Fec_Ini		,")
			loComandoSeleccionar.AppendLine("				Expedientes.Fec_Fin				AS	Fec_Fin		,")
			loComandoSeleccionar.AppendLine("				Expedientes.Fec_Rec				AS	Fec_Rec		,")
			loComandoSeleccionar.AppendLine("				Expedientes.Fec_Lle				AS	Fec_Lle		,")
			loComandoSeleccionar.AppendLine("				Expedientes.Fec_Pag				AS	Fec_Pag		,")
			loComandoSeleccionar.AppendLine("				Expedientes.Fec_Reg				AS	Fec_Reg		,")
			loComandoSeleccionar.AppendLine("				Expedientes.Fec_Adi1			AS	Fec_Adi1	,")
			loComandoSeleccionar.AppendLine("				Expedientes.Fec_Adi2			AS	Fec_Adi2	,")
			loComandoSeleccionar.AppendLine("				Expedientes.Fec_Adi3			AS	Fec_Adi3	,")
			loComandoSeleccionar.AppendLine("				Expedientes.Fec_Adi4			AS	Fec_Adi4	,")
			loComandoSeleccionar.AppendLine("				Expedientes.Fec_Adi5			AS	Fec_Adi5	,")
			loComandoSeleccionar.AppendLine("				Expedientes.Containers			AS	Containers	,")
			loComandoSeleccionar.AppendLine("				Expedientes.Num_Bul				AS	Num_Bul		,")
			loComandoSeleccionar.AppendLine("				Expedientes.Bultos				AS	Bultos		,")
			loComandoSeleccionar.AppendLine("				Expedientes.Cajas				AS	Cajas		,")
			loComandoSeleccionar.AppendLine("				Expedientes.Unidades			AS	Unidades	,")
			loComandoSeleccionar.AppendLine("				Expedientes.Cod_Mon				AS	Cod_Mon	,")
			loComandoSeleccionar.AppendLine("				Monedas.Nom_Mon					AS	Nom_Mon	,")
			loComandoSeleccionar.AppendLine("				Expedientes.Tasa				AS	Tasa	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS 	Doc_Renglon	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS 	Doc_Tip_Ren	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS 	Doc_Tip_Doc	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS 	Doc_Referencia	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS 	Doc_Detalle	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS 	Doc_Status	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS 	Doc_Control	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS 	Doc_Completo,")
			loComandoSeleccionar.AppendLine("				NULL  							AS 	Doc_Fec_Ini	,")
			loComandoSeleccionar.AppendLine("				NULL  							As 	Doc_Fec_Fin	,")
			loComandoSeleccionar.AppendLine("				NULL  							As 	Doc_Comentario,")
			loComandoSeleccionar.AppendLine("				NULL  							AS 	Doc_Prioridad,")
			loComandoSeleccionar.AppendLine("				NULL	 						AS	Art_Renglon,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Doc_Cod_Art,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Doc_Cod_Alm,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Doc_Can_Art1,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Doc_Cod_Uni,")	
			loComandoSeleccionar.AppendLine("				NULL  							AS	Doc_Precio1,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Doc_Precio2,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Doc_Mon_Net,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Doc_Cod_Imp,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Doc_Por_Imp1,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Doc_Mon_Imp1,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Doc_Nom_Art,")
			loComandoSeleccionar.AppendLine("				NULL  							As 	Art_Comentario,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Renglon	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Tip_Tra	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Factura	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Control	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Referencia,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Transporte,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Vehiculo,")
			loComandoSeleccionar.AppendLine("				NULL 							As	Emb_Lug_Emb,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Containers,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Bultos,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Cajas,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Unidades,")
			loComandoSeleccionar.AppendLine("				NULL 							As	Emb_Peso,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Volumen,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Cod_Uni,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Nom_Uni,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Can_Art,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Detalle,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Status,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Fec_Ini,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Fec_Fin,")
			loComandoSeleccionar.AppendLine("				NULL							AS	Emb_Fec_Emb,")
			loComandoSeleccionar.AppendLine("				NULL							AS	Emb_Fec_Lle,")
			loComandoSeleccionar.AppendLine("				NULL							AS	Emb_Comentario,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Con_Renglon,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Con_Cod_Tip,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Con_Nom_Tip,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Con_Numero,")
			loComandoSeleccionar.AppendLine("				NULL  							AS  Con_Control,")
			loComandoSeleccionar.AppendLine("				NULL  							AS  Con_Referencia,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Con_Detalle,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Con_Status,")
			loComandoSeleccionar.AppendLine("				NULL  							As	Con_Peso,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Con_Volumen,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Con_Color,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Con_Fec_Ini,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Con_Fec_Fin,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Con_Comentario,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Gas_Renglon,")
			loComandoSeleccionar.AppendLine("				NULL							AS	Inc_Imp		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Gas_Cod_Con,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Gas_Nom_Con,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Gas_Mon_Deb,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Gas_Mon_Hab,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Gas_Cod_Imp,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Gas_Por_imp1,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Gas_Mon_Imp1, ")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Gas_Mon_Net,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Gas_Comentario,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Cod_Ven		,")
 			loComandoSeleccionar.AppendLine("				NULL  							AS	Nom_Ven		,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Cod_Usu		,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Cod_Gru		,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Por_Eje		,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Etapa		,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Prioridad	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Importancia	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Nivel		,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Ord_Com		,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Ord_Tra		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Defecto		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Logico1		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Logico2		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Logico3		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Logico4		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Logico5		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fecha1		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fecha2		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fecha3		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fecha4		,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Fecha5		,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Caracter1	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Caracter2	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Caracter3	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Caracter4	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Caracter5	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Numerico1	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Numerico2	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Numerico3	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Numerico4	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Numerico5	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Seguimientos,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fec_Aut_Leg,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fec_Pre_Leg,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Not_Pre_Leg,")	   
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fec_Rec_Leg,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fec_Act_Ret,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fec_Env_Act,")
			loComandoSeleccionar.AppendLine(" 				NULL 							AS	Seg_Renglon,")	
			loComandoSeleccionar.AppendLine(" 				NULL 							AS	Seg_Fecha,")	
			loComandoSeleccionar.AppendLine(" 				NULL 							AS	Seg_Seguimientos,")	
			loComandoSeleccionar.AppendLine(" 				NULL 							AS	Seg_Status,")	
			loComandoSeleccionar.AppendLine("				1								AS 	Origen  ")	
			loComandoSeleccionar.AppendLine("FROM Expedientes")
			loComandoSeleccionar.AppendLine("JOIN Clientes ON Clientes.Cod_Cli = Expedientes.Cod_Cli")
			loComandoSeleccionar.AppendLine("LEFT JOIN Proveedores AS Operadores ON (Operadores.Cod_Pro = Expedientes.Cod_Log)")
			loComandoSeleccionar.AppendLine("LEFT JOIN Proveedores ON (Proveedores.Cod_Pro = Expedientes.Cod_Reg)")
			loComandoSeleccionar.AppendLine("LEFT JOIN Monedas On (Monedas.Cod_Mon = Expedientes.Cod_Mon)")
			loComandoSeleccionar.AppendLine("WHERE " & cusAplicacion.goFormatos.pcCondicionPrincipal)
			loComandoSeleccionar.AppendLine("")
			
			
			loComandoSeleccionar.AppendLine("UNION ALL")
			
			
			loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("SELECT		Renglones_Expedientes.Documento		AS	Documento	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Status		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Expediente	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Importacion	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Factura		,")
			loComandoSeleccionar.AppendLine("			NULL 								As	Control		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Declaracion	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Pla_Liq		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Cod_Log		,")
 			loComandoSeleccionar.AppendLine("			NULL 								AS	Nom_Log		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Cod_Reg		,")
 			loComandoSeleccionar.AppendLine("			NULL 								AS	Nom_Reg		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Cod_Cli		,")
 			loComandoSeleccionar.AppendLine("			NULL 								AS	Nom_Cli		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Tipo		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Clase		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Descripcion	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Comentario	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Ini		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Fin		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Rec		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Lle		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Pag		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Reg		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Adi1	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Adi2	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Adi3	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Adi4	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Adi5	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Containers	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Num_Bul		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Bultos		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Cajas		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Unidades	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Cod_Mon	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Nom_Mon	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Tasa	,")
			loComandoSeleccionar.AppendLine("			Renglones_Expedientes.Renglon	 	AS	Doc_Renglon,")
			loComandoSeleccionar.AppendLine("			Renglones_Expedientes.Tip_Ren	 	AS	Doc_Tip_Ren,")
			loComandoSeleccionar.AppendLine("			Renglones_Expedientes.Tip_Doc	 	AS 	Doc_Tip_Doc,")
			loComandoSeleccionar.AppendLine("			Renglones_Expedientes.Referencia 	AS 	Doc_Referencia,")
			loComandoSeleccionar.AppendLine("			Renglones_Expedientes.Detalle	 	AS 	Doc_Detalle,")
			loComandoSeleccionar.AppendLine("			Renglones_Expedientes.Status	 	AS 	Doc_Status,")
			loComandoSeleccionar.AppendLine("			Renglones_Expedientes.Control	 	AS 	Doc_Control,")
			loComandoSeleccionar.AppendLine("			Renglones_Expedientes.Completo	 	AS 	Doc_Completo,")
			loComandoSeleccionar.AppendLine("			Renglones_Expedientes.Fec_Ini	 	AS 	Doc_Fec_Ini,")
			loComandoSeleccionar.AppendLine("			Renglones_Expedientes.Fec_Fin	 	As 	Doc_Fec_Fin,")
			loComandoSeleccionar.AppendLine("			Renglones_Expedientes.Comentario 	As 	Doc_Comentario,")
			loComandoSeleccionar.AppendLine("			Renglones_Expedientes.Prioridad	 	AS 	Doc_Prioridad,")
			loComandoSeleccionar.AppendLine("			NULL		 						AS	Art_Renglon,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Doc_Cod_Art,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Doc_Cod_Alm,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Doc_Can_Art1,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Doc_Cod_Uni,")	
			loComandoSeleccionar.AppendLine("			NULL  								AS	Doc_Precio1,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Doc_Precio2,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Doc_Mon_Net,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Doc_Cod_Imp,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Doc_Por_Imp1,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Doc_Mon_Imp1,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Doc_Nom_Art,")
			loComandoSeleccionar.AppendLine("			NULL	  							As 	Art_Comentario,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Renglon	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Tip_Tra	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Factura	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Control	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Referencia,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Transporte,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Vehiculo,")
			loComandoSeleccionar.AppendLine("			NULL 								As	Emb_Lug_Emb,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Containers,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Bultos,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Cajas,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Unidades,")
			loComandoSeleccionar.AppendLine("			NULL 								As	Emb_Peso,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Volumen,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Cod_Uni,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Nom_Uni,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Can_Art,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Detalle,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Status,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Fec_Ini,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Fec_Fin,")
			loComandoSeleccionar.AppendLine("			NULL								AS	Emb_Fec_Emb,")
			loComandoSeleccionar.AppendLine("			NULL								AS	Emb_Fec_Lle,")
			loComandoSeleccionar.AppendLine("			NULL								AS	Emb_Comentario,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Con_Renglon,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Con_Cod_Tip,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Con_Nom_Tip,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Con_Numero,")
			loComandoSeleccionar.AppendLine("			NULL  								AS  Con_Control,")
			loComandoSeleccionar.AppendLine("			NULL  								AS  Con_Referencia,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Con_Detalle,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Con_Status,")
			loComandoSeleccionar.AppendLine("			NULL  								As	Con_Peso,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Con_Volumen,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Con_Color,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Con_Fec_Ini,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Con_Fec_Fin,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Con_Comentario,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Gas_Renglon,")
			loComandoSeleccionar.AppendLine("			NULL								AS	Inc_Imp		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Gas_Cod_Con,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Gas_Nom_Con,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Gas_Mon_Deb,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Gas_Mon_Hab,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Gas_Cod_Imp,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Gas_Por_imp1,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Gas_Mon_Imp1, ")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Gas_Mon_Net,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Gas_Comentario,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Cod_Ven		,")
 			loComandoSeleccionar.AppendLine("			NULL  								AS	Nom_Ven		,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Cod_Usu		,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Cod_Gru		,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Por_Eje		,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Etapa		,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Prioridad	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Importancia	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Nivel		,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Ord_Com		,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Ord_Tra		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Defecto		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Logico1		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Logico2		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Logico3		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Logico4		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Logico5		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fecha1		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fecha2		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fecha3		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fecha4		,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Fecha5		,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Caracter1	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Caracter2	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Caracter3	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Caracter4	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Caracter5	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Numerico1	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Numerico2	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Numerico3	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Numerico4	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Numerico5	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Seguimientos,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Aut_Leg,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Pre_Leg,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Not_Pre_Leg,")	   
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Rec_Leg,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Act_Ret,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Env_Act,")
			loComandoSeleccionar.AppendLine(" 			NULL 								AS	Seg_Renglon,")	
			loComandoSeleccionar.AppendLine(" 			NULL 								AS	Seg_Fecha,")	
			loComandoSeleccionar.AppendLine(" 			NULL 								AS	Seg_Seguimientos,")	
			loComandoSeleccionar.AppendLine(" 			NULL 								AS	Seg_Status,")
			loComandoSeleccionar.AppendLine("			2									AS Origen")	
			loComandoSeleccionar.AppendLine("FROM Renglones_Expedientes")
			loComandoSeleccionar.AppendLine("JOIN Expedientes ON Expedientes.Documento = Renglones_Expedientes.Documento")
			loComandoSeleccionar.AppendLine("WHERE Renglones_Expedientes.Tip_Ren = 'Documento' AND" & cusAplicacion.goFormatos.pcCondicionPrincipal)
			loComandoSeleccionar.AppendLine("")
			
			loComandoSeleccionar.AppendLine("UNION ALL")
			
			loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("SELECT		Detalles_Expedientes.Documento		AS	Documento,")
            loComandoSeleccionar.AppendLine("			NULL 								AS	Status		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Expediente	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Importacion	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Factura		,")
			loComandoSeleccionar.AppendLine("			NULL 								As	Control		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Declaracion	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Pla_Liq		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Cod_Log		,")
 			loComandoSeleccionar.AppendLine("			NULL 								AS	Nom_Log		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Cod_Reg		,")
 			loComandoSeleccionar.AppendLine("			NULL 								AS	Nom_Reg		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Cod_Cli		,")
 			loComandoSeleccionar.AppendLine("			NULL 								AS	Nom_Cli		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Tipo		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Clase		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Descripcion	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Comentario	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Ini		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Fin		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Rec		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Lle		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Pag		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Reg		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Adi1	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Adi2	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Adi3	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Adi4	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Adi5	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Containers	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Num_Bul		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Bultos		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Cajas		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Unidades	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Cod_Mon	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Nom_Mon	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Tasa	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS 	Doc_Renglon	,")
			loComandoSeleccionar.AppendLine("			NULL								AS 	Doc_Tip_Ren	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS 	Doc_Tip_Doc	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS 	Doc_Referencia	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS 	Doc_Detalle	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS 	Doc_Status	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS 	Doc_Control	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS 	Doc_Completo,")
			loComandoSeleccionar.AppendLine("			NULL  								AS 	Doc_Fec_Ini	,")
			loComandoSeleccionar.AppendLine("			NULL  								As 	Doc_Fec_Fin	,")
			loComandoSeleccionar.AppendLine("			NULL  								As 	Doc_Comentario,")
			loComandoSeleccionar.AppendLine("			NULL  								AS 	Doc_Prioridad,")
			loComandoSeleccionar.AppendLine("			NULL		 						AS	Art_Renglon,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Doc_Cod_Art,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Doc_Cod_Alm,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Doc_Can_Art1,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Doc_Cod_Uni,")	
			loComandoSeleccionar.AppendLine("			NULL  								AS	Doc_Precio1,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Doc_Precio2,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Doc_Mon_Net,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Doc_Cod_Imp,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Doc_Por_Imp1,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Doc_Mon_Imp1,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Doc_Nom_Art,")
			loComandoSeleccionar.AppendLine("			NULL	  							As 	Art_Comentario,")
			loComandoSeleccionar.AppendLine("			Detalles_Expedientes.Renglon		AS	Emb_Renglon,")
			loComandoSeleccionar.AppendLine("			Detalles_Expedientes.Tip_Tra		AS  Emb_Tip_Tra,")
			loComandoSeleccionar.AppendLine("			Detalles_Expedientes.Factura		AS  Emb_Factura,")
			loComandoSeleccionar.AppendLine("			Detalles_Expedientes.Control		AS  Emb_Control,")
			loComandoSeleccionar.AppendLine("			Detalles_Expedientes.Referencia		AS  Emb_Referencia,")
			loComandoSeleccionar.AppendLine("			Detalles_Expedientes.Transporte		AS	Emb_Transporte,")
			loComandoSeleccionar.AppendLine("			Detalles_Expedientes.Vehiculo		AS	Emb_Vehiculo,")
			loComandoSeleccionar.AppendLine("			Detalles_Expedientes.Lug_Emb		As	Emb_Lug_Emb,")
			loComandoSeleccionar.AppendLine("			Detalles_Expedientes.Containers		AS	Emb_Containers,")
			loComandoSeleccionar.AppendLine("			Detalles_Expedientes.Bultos			AS	Emb_Bultos,")
			loComandoSeleccionar.AppendLine("			Detalles_Expedientes.Cajas			AS	Emb_Cajas,")
			loComandoSeleccionar.AppendLine("			Detalles_Expedientes.Unidades		AS	Emb_Unidades,")
			loComandoSeleccionar.AppendLine("			Detalles_Expedientes.Peso			As	Emb_Peso,")
			loComandoSeleccionar.AppendLine("			Detalles_Expedientes.Volumen		AS	Emb_Volumen,")
			loComandoSeleccionar.AppendLine("			Detalles_Expedientes.Cod_Uni		AS	Emb_Cod_Uni,")
			loComandoSeleccionar.AppendLine("			Unidades.Nom_Uni					AS	Emb_Nom_Uni,")
			loComandoSeleccionar.AppendLine("			Detalles_Expedientes.Can_Art		AS	Emb_Can_Art,")
			loComandoSeleccionar.AppendLine("			Detalles_Expedientes.Detalle		AS	Emb_Detalle,")
			loComandoSeleccionar.AppendLine("			Detalles_Expedientes.Status			AS	Emb_Status,")
			loComandoSeleccionar.AppendLine("			Detalles_Expedientes.Fec_Ini		AS	Emb_Fec_Ini,")
			loComandoSeleccionar.AppendLine("			Detalles_Expedientes.Fec_Fin		AS	Emb_Fec_Fin,")
			loComandoSeleccionar.AppendLine("			Detalles_Expedientes.Fec_Emb		AS  Emb_Fec_Emb,")
			loComandoSeleccionar.AppendLine("			Detalles_Expedientes.Fec_Lle		AS	Emb_Fec_Lle,")
			loComandoSeleccionar.AppendLine("			Detalles_Expedientes.Comentario		AS	Emb_Comentario,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Con_Renglon,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Con_Cod_Tip,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Con_Nom_Tip,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Con_Numero,")
			loComandoSeleccionar.AppendLine("				NULL  							AS  Con_Control,")
			loComandoSeleccionar.AppendLine("				NULL  							AS  Con_Referencia,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Con_Detalle,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Con_Status,")
			loComandoSeleccionar.AppendLine("				NULL  							As	Con_Peso,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Con_Volumen,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Con_Color,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Con_Fec_Ini,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Con_Fec_Fin,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Con_Comentario,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Gas_Renglon,")
			loComandoSeleccionar.AppendLine("				NULL							AS	Inc_Imp		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Gas_Cod_Con,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Gas_Nom_Con,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Gas_Mon_Deb,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Gas_Mon_Hab,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Gas_Cod_Imp,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Gas_Por_imp1,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Gas_Mon_Imp1, ")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Gas_Mon_Net,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Gas_Comentario,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Cod_Ven		,")
 			loComandoSeleccionar.AppendLine("				NULL  							AS	Nom_Ven		,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Cod_Usu		,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Cod_Gru		,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Por_Eje		,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Etapa		,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Prioridad	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Importancia	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Nivel		,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Ord_Com		,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Ord_Tra		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Defecto		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Logico1		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Logico2		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Logico3		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Logico4		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Logico5		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fecha1		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fecha2		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fecha3		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fecha4		,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Fecha5		,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Caracter1	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Caracter2	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Caracter3	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Caracter4	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Caracter5	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Numerico1	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Numerico2	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Numerico3	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Numerico4	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Numerico5	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Seguimientos,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fec_Aut_Leg,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fec_Pre_Leg,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Not_Pre_Leg,")	   
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fec_Rec_Leg,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fec_Act_Ret,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fec_Env_Act,")
			loComandoSeleccionar.AppendLine(" 				NULL 							AS Seg_Renglon,")	
			loComandoSeleccionar.AppendLine(" 				NULL 							AS Seg_Fecha,")	
			loComandoSeleccionar.AppendLine(" 				NULL 							AS Seg_Seguimientos,")	
			loComandoSeleccionar.AppendLine(" 				NULL 							AS Seg_Status,")
			loComandoSeleccionar.AppendLine("				3								AS Origen")		
			loComandoSeleccionar.AppendLine("FROM Detalles_Expedientes")
			loComandoSeleccionar.AppendLine("JOIN Expedientes ON Expedientes.Documento = Detalles_Expedientes.Documento")
			loComandoSeleccionar.AppendLine("JOIN Unidades ON Unidades.Cod_Uni = Detalles_Expedientes.Cod_Uni")
			loComandoSeleccionar.AppendLine("WHERE " & cusAplicacion.goFormatos.pcCondicionPrincipal)
			loComandoSeleccionar.AppendLine("")
				
			loComandoSeleccionar.AppendLine("UNION ALL")
			
			loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("SELECT		Containers_Expedientes.Documento	AS	Documento,")
            loComandoSeleccionar.AppendLine("			NULL 								AS	Status		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Expediente	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Importacion	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Factura		,")
			loComandoSeleccionar.AppendLine("			NULL 								As	Control		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Declaracion	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Pla_Liq		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Cod_Log		,")
 			loComandoSeleccionar.AppendLine("			NULL 								AS	Nom_Log		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Cod_Reg		,")
 			loComandoSeleccionar.AppendLine("			NULL 								AS	Nom_Reg		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Cod_Cli		,")
 			loComandoSeleccionar.AppendLine("			NULL 								AS	Nom_Cli		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Tipo		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Clase		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Descripcion	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Comentario	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Ini		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Fin		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Rec		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Lle		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Pag		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Reg		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Adi1	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Adi2	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Adi3	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Adi4	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Adi5	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Containers	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Num_Bul		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Bultos		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Cajas		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Unidades	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Cod_Mon	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Nom_Mon	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Tasa	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS 	Doc_Renglon	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS 	Doc_Tip_Ren	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS 	Doc_Tip_Doc	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS 	Doc_Referencia	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS 	Doc_Detalle	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS 	Doc_Status	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS 	Doc_Control	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS 	Doc_Completo,")
			loComandoSeleccionar.AppendLine("			NULL  								AS 	Doc_Fec_Ini	,")
			loComandoSeleccionar.AppendLine("			NULL  								As 	Doc_Fec_Fin	,")
			loComandoSeleccionar.AppendLine("			NULL  								As 	Doc_Comentario,")
			loComandoSeleccionar.AppendLine("			NULL  								AS 	Doc_Prioridad,")
			loComandoSeleccionar.AppendLine("			NULL		 						AS	Art_Renglon,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Doc_Cod_Art,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Doc_Cod_Alm,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Doc_Can_Art1,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Doc_Cod_Uni,")	
			loComandoSeleccionar.AppendLine("			NULL  								AS	Doc_Precio1,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Doc_Precio2,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Doc_Mon_Net,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Doc_Cod_Imp,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Doc_Por_Imp1,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Doc_Mon_Imp1,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Doc_Nom_Art,")
			loComandoSeleccionar.AppendLine("			NULL	  							As 	Art_Comentario,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Renglon	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Tip_Tra	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Factura	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Control	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Referencia,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Transporte,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Vehiculo,")
			loComandoSeleccionar.AppendLine("			NULL 								As	Emb_Lug_Emb,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Containers,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Bultos,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Cajas,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Unidades,")
			loComandoSeleccionar.AppendLine("			NULL 								As	Emb_Peso,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Volumen,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Cod_Uni,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Nom_Uni,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Can_Art,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Detalle,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Status,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Fec_Ini,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Fec_Fin,")
			loComandoSeleccionar.AppendLine("			NULL								AS	Emb_Fec_Emb,")
			loComandoSeleccionar.AppendLine("			NULL								AS	Emb_Fec_Lle,")
			loComandoSeleccionar.AppendLine("			NULL								AS	Emb_Comentario,")
			loComandoSeleccionar.AppendLine("			Containers_Expedientes.Renglon		AS	Con_Renglon,")
			loComandoSeleccionar.AppendLine("			Containers_Expedientes.Cod_Tip		AS	Con_Cod_Tip,")
			loComandoSeleccionar.AppendLine("			Containers_Expedientes.Nom_Tip		AS	Con_Nom_Tip,")
			loComandoSeleccionar.AppendLine("			Containers_Expedientes.Numero		AS	Con_Numero,")
			loComandoSeleccionar.AppendLine("			Containers_Expedientes.Control		AS  Con_Control,")
			loComandoSeleccionar.AppendLine("			Containers_Expedientes.Referencia	AS  Con_Referencia,")
			loComandoSeleccionar.AppendLine("			Containers_Expedientes.Detalle		AS	Con_Detalle,")
			loComandoSeleccionar.AppendLine("			Containers_Expedientes.Status		AS	Con_Status,")
			loComandoSeleccionar.AppendLine("			Containers_Expedientes.Peso			As	Con_Peso,")
			loComandoSeleccionar.AppendLine("			Containers_Expedientes.Volumen		AS	Con_Volumen,")
			loComandoSeleccionar.AppendLine("			Containers_Expedientes.Color		AS	Con_Color,")
			loComandoSeleccionar.AppendLine("			Containers_Expedientes.Fec_Ini		AS	Con_Fec_Ini,")
			loComandoSeleccionar.AppendLine("			Containers_Expedientes.Fec_Fin		AS	Con_Fec_Fin,")
			loComandoSeleccionar.AppendLine("			Containers_Expedientes.Comentario	AS	Con_Comentario,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Gas_Renglon,")
			loComandoSeleccionar.AppendLine("			NULL								AS	Inc_Imp		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Gas_Cod_Con,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Gas_Nom_Con,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Gas_Mon_Deb,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Gas_Mon_Hab,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Gas_Cod_Imp,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Gas_Por_imp1,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Gas_Mon_Imp1, ")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Gas_Mon_Net,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Gas_Comentario,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Cod_Ven		,")
 			loComandoSeleccionar.AppendLine("			NULL  								AS	Nom_Ven		,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Cod_Usu		,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Cod_Gru		,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Por_Eje		,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Etapa		,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Prioridad	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Importancia	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Nivel		,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Ord_Com		,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Ord_Tra		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Defecto		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Logico1		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Logico2		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Logico3		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Logico4		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Logico5		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fecha1		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fecha2		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fecha3		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fecha4		,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Fecha5		,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Caracter1	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Caracter2	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Caracter3	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Caracter4	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Caracter5	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Numerico1	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Numerico2	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Numerico3	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Numerico4	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Numerico5	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Seguimientos	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Aut_Leg,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Pre_Leg,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Not_Pre_Leg,")	   
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Rec_Leg,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Act_Ret,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Env_Act,")
			loComandoSeleccionar.AppendLine(" 			NULL 								AS Seg_Renglon,")	
			loComandoSeleccionar.AppendLine(" 			NULL 								AS Seg_Fecha,")	
			loComandoSeleccionar.AppendLine(" 			NULL 								AS Seg_Seguimientos,")	
			loComandoSeleccionar.AppendLine(" 			NULL 								AS Seg_Status,")
			loComandoSeleccionar.AppendLine("			4									AS Origen")		
			loComandoSeleccionar.AppendLine("FROM Containers_Expedientes")
			loComandoSeleccionar.AppendLine("JOIN Expedientes ON Expedientes.Documento = Containers_Expedientes.Documento")
			loComandoSeleccionar.AppendLine("WHERE " & cusAplicacion.goFormatos.pcCondicionPrincipal)
			loComandoSeleccionar.AppendLine("")
				
			loComandoSeleccionar.AppendLine("UNION ALL")
			
			loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("SELECT		Gastos_Expedientes.Documento		AS	Documento,")
            loComandoSeleccionar.AppendLine("			NULL 								AS	Status		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Expediente	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Importacion	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Factura		,")
			loComandoSeleccionar.AppendLine("			NULL 								As	Control		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Declaracion	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Pla_Liq		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Cod_Log		,")
 			loComandoSeleccionar.AppendLine("			NULL 								AS	Nom_Log		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Cod_Reg		,")
 			loComandoSeleccionar.AppendLine("			NULL 								AS	Nom_Reg		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Cod_Cli		,")
 			loComandoSeleccionar.AppendLine("			NULL 								AS	Nom_Cli		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Tipo		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Clase		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Descripcion	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Comentario	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Ini		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Fin		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Rec		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Lle		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Pag		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Reg		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Adi1	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Adi2	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Adi3	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Adi4	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Adi5	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Containers	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Num_Bul		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Bultos		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Cajas		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Unidades	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Cod_Mon	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Nom_Mon	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Tasa	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS 	Doc_Renglon	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS 	Doc_Tip_Ren	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS 	Doc_Tip_Doc	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS 	Doc_Referencia,")
			loComandoSeleccionar.AppendLine("			NULL  								AS 	Doc_Detalle	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS 	Doc_Status	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS 	Doc_Control	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS 	Doc_Completo,")
			loComandoSeleccionar.AppendLine("			NULL  								AS 	Doc_Fec_Ini	,")
			loComandoSeleccionar.AppendLine("			NULL  								As 	Doc_Fec_Fin	,")
			loComandoSeleccionar.AppendLine("			NULL  								As 	Doc_Comentario,")
			loComandoSeleccionar.AppendLine("			NULL  								AS 	Doc_Prioridad,")
			loComandoSeleccionar.AppendLine("			NULL		 						AS	Art_Renglon,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Doc_Cod_Art,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Doc_Cod_Alm,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Doc_Can_Art1,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Doc_Cod_Uni,")	
			loComandoSeleccionar.AppendLine("			NULL  								AS	Doc_Precio1,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Doc_Precio2,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Doc_Mon_Net,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Doc_Cod_Imp,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Doc_Por_Imp1,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Doc_Mon_Imp1,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Doc_Nom_Art,")
			loComandoSeleccionar.AppendLine("			NULL	  							As 	Art_Comentario,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Renglon	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Tip_Tra	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Factura	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Control	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Referencia,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Transporte,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Vehiculo,")
			loComandoSeleccionar.AppendLine("			NULL 								As	Emb_Lug_Emb,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Containers,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Bultos,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Cajas,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Unidades,")
			loComandoSeleccionar.AppendLine("			NULL 								As	Emb_Peso,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Volumen,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Cod_Uni,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Nom_Uni,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Can_Art,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Detalle,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Status,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Fec_Ini,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Fec_Fin,")
			loComandoSeleccionar.AppendLine("			NULL								AS	Emb_Fec_Emb,")
			loComandoSeleccionar.AppendLine("			NULL								AS	Emb_Fec_Lle,")
			loComandoSeleccionar.AppendLine("			NULL								AS	Emb_Comentario,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Con_Renglon,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Con_Cod_Tip,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Con_Nom_Tip,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Con_Numero,")
			loComandoSeleccionar.AppendLine("			NULL  								AS  Con_Control,")
			loComandoSeleccionar.AppendLine("			NULL  								AS  Con_Referencia,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Con_Detalle,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Con_Status,")
			loComandoSeleccionar.AppendLine("			NULL  								As	Con_Peso,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Con_Volumen,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Con_Color,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Con_Fec_Ini,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Con_Fec_Fin,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Con_Comentario,")
			loComandoSeleccionar.AppendLine("			Gastos_Expedientes.Renglon			AS	Gas_Renglon,")
			loComandoSeleccionar.AppendLine("			" & goServicios.mObtenerCampoFormatoSQL(llIncluyeImpuesto) & " AS	Inc_Imp,")
			loComandoSeleccionar.AppendLine("			Gastos_Expedientes.Cod_Con			AS	Gas_Cod_Con,")
			loComandoSeleccionar.AppendLine("			Gastos_Expedientes.Notas			AS	Gas_Nom_Con,")
			loComandoSeleccionar.AppendLine("			Gastos_Expedientes.Mon_Deb			AS	Gas_Mon_Deb,")
			loComandoSeleccionar.AppendLine("			Gastos_Expedientes.Mon_Hab			AS	Gas_Mon_Hab,")
			loComandoSeleccionar.AppendLine("			Gastos_Expedientes.Cod_Imp			AS	Gas_Cod_Imp,")
			loComandoSeleccionar.AppendLine("			Gastos_Expedientes.Por_imp1			AS	Gas_Por_imp1,")
			loComandoSeleccionar.AppendLine("			Gastos_Expedientes.Mon_Imp1			AS	Gas_Mon_Imp1,")
			loComandoSeleccionar.AppendLine("			Gastos_Expedientes.Mon_Net			AS	Gas_Mon_Net,")
			loComandoSeleccionar.AppendLine("			Gastos_Expedientes.Comentario		AS	Gas_Comentario,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Cod_Ven		,")
 			loComandoSeleccionar.AppendLine("			NULL  								AS	Nom_Ven		,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Cod_Usu		,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Cod_Gru		,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Por_Eje		,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Etapa		,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Prioridad	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Importancia	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Nivel		,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Ord_Com		,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Ord_Tra		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Defecto		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Logico1		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Logico2		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Logico3		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Logico4		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Logico5		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fecha1		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fecha2		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fecha3		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fecha4		,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Fecha5		,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Caracter1	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Caracter2	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Caracter3	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Caracter4	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Caracter5	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Numerico1	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Numerico2	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Numerico3	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Numerico4	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Numerico5	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Seguimientos,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Aut_Leg,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Pre_Leg,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Not_Pre_Leg,")	   
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Rec_Leg,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Act_Ret,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Env_Act,")
			loComandoSeleccionar.AppendLine(" 			NULL 								AS Seg_Renglon,")	
			loComandoSeleccionar.AppendLine(" 			NULL 								AS Seg_Fecha,")	
			loComandoSeleccionar.AppendLine(" 			NULL 								AS Seg_Seguimientos,")	
			loComandoSeleccionar.AppendLine(" 			NULL 								AS Seg_Status,")
			loComandoSeleccionar.AppendLine("			5									AS Origen")		
			loComandoSeleccionar.AppendLine("FROM Gastos_Expedientes")
			loComandoSeleccionar.AppendLine("JOIN Expedientes ON Expedientes.Documento = Gastos_Expedientes.Documento")
			loCOmandoSeleccionar.AppendLine("JOIN Conceptos ON Conceptos.Cod_Con = Gastos_Expedientes.Cod_Con")
			loComandoSeleccionar.AppendLine("WHERE " & cusAplicacion.goFormatos.pcCondicionPrincipal)
			
			loComandoSeleccionar.AppendLine("UNION ALL")
			
			loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("SELECT			Expedientes.Documento			AS	Documento	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Status		,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Expediente	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Importacion	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Factura		,")
			loComandoSeleccionar.AppendLine("				NULL  							As	Control		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Declaracion	,")
			loComandoSeleccionar.AppendLine("				NULL							AS	Pla_Liq		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Cod_Log		,")
 			loComandoSeleccionar.AppendLine("				NULL 							AS	Nom_Log		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Cod_Reg		,")
 			loComandoSeleccionar.AppendLine("				NULL 							AS	Nom_Reg		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Cod_Cli		,")
 			loComandoSeleccionar.AppendLine("				NULL 							AS	Nom_Cli		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Tipo		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Clase		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Descripcion	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Comentario	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fec_Ini		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fec_Fin		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fec_Rec		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fec_Lle		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fec_Pag		,")
			loComandoSeleccionar.AppendLine("				NULL							AS	Fec_Reg		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fec_Adi1	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fec_Adi2	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fec_Adi3	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fec_Adi4	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fec_Adi5	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Containers	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Num_Bul		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Bultos		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Cajas		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Unidades	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Cod_Mon	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Nom_Mon	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Tasa	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS 	Doc_Renglon	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS 	Doc_Tip_Ren	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS 	Doc_Tip_Doc	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS 	Doc_Referencia	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS 	Doc_Detalle	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS 	Doc_Status	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS 	Doc_Control	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS 	Doc_Completo,")
			loComandoSeleccionar.AppendLine("				NULL  							AS 	Doc_Fec_Ini	,")
			loComandoSeleccionar.AppendLine("				NULL  							As 	Doc_Fec_Fin	,")
			loComandoSeleccionar.AppendLine("				NULL  							As 	Doc_Comentario,")
			loComandoSeleccionar.AppendLine("				NULL  							AS 	Doc_Prioridad,")
			loComandoSeleccionar.AppendLine("				NULL	 						AS	Art_Renglon,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Doc_Cod_Art,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Doc_Cod_Alm,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Doc_Can_Art1,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Doc_Cod_Uni,")	
			loComandoSeleccionar.AppendLine("				NULL  							AS	Doc_Precio1,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Doc_Precio2,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Doc_Mon_Net,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Doc_Cod_Imp,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Doc_Por_Imp1,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Doc_Mon_Imp1,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Doc_Nom_Art,")
			loComandoSeleccionar.AppendLine("				NULL  							As 	Art_Comentario,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Renglon	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Tip_Tra	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Factura	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Control	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Referencia,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Transporte,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Vehiculo,")
			loComandoSeleccionar.AppendLine("				NULL 							As	Emb_Lug_Emb,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Containers,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Bultos,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Cajas,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Unidades,")
			loComandoSeleccionar.AppendLine("				NULL 							As	Emb_Peso,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Volumen,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Cod_Uni,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Nom_Uni,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Can_Art,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Detalle,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Status,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Fec_Ini,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Fec_Fin,")
			loComandoSeleccionar.AppendLine("				NULL							AS	Emb_Fec_Emb,")
			loComandoSeleccionar.AppendLine("				NULL							AS	Emb_Fec_Lle,")
			loComandoSeleccionar.AppendLine("				NULL							AS	Emb_Comentario,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Con_Renglon,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Con_Cod_Tip,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Con_Nom_Tip,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Con_Numero,")
			loComandoSeleccionar.AppendLine("				NULL  							AS  Con_Control,")
			loComandoSeleccionar.AppendLine("				NULL  							AS  Con_Referencia,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Con_Detalle,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Con_Status,")
			loComandoSeleccionar.AppendLine("				NULL  							As	Con_Peso,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Con_Volumen,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Con_Color,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Con_Fec_Ini,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Con_Fec_Fin,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Con_Comentario,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Gas_Renglon,")
			loComandoSeleccionar.AppendLine("				NULL							AS	Inc_Imp		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Gas_Cod_Con,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Gas_Nom_Con,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Gas_Mon_Deb,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Gas_Mon_Hab,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Gas_Cod_Imp,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Gas_Por_imp1,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Gas_Mon_Imp1, ")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Gas_Mon_Net,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Gas_Comentario,")
			loComandoSeleccionar.AppendLine("				Expedientes.Cod_Ven				AS	Cod_Ven		,")
 			loComandoSeleccionar.AppendLine("				Vendedores.Nom_Ven				AS	Nom_Ven		,")
			loComandoSeleccionar.AppendLine("				Expedientes.Cod_Usu				AS	Cod_Usu		,")
			loComandoSeleccionar.AppendLine("				Expedientes.Cod_Gru				AS	Cod_Gru		,")
			loComandoSeleccionar.AppendLine("				Expedientes.Por_Eje				AS	Por_Eje		,")
			loComandoSeleccionar.AppendLine("				Expedientes.Etapa				AS	Etapa		,")
			loComandoSeleccionar.AppendLine("				Expedientes.Prioridad			AS	Prioridad	,")
			loComandoSeleccionar.AppendLine("				Expedientes.Importancia			AS	Importancia	,")
			loComandoSeleccionar.AppendLine("				Expedientes.Nivel				AS	Nivel		,")
			loComandoSeleccionar.AppendLine("				Expedientes.Ord_Com				AS	Ord_Com		,")
			loComandoSeleccionar.AppendLine("				Expedientes.Ord_Tra				AS	Ord_Tra		,")
			loComandoSeleccionar.AppendLine("				Expedientes.Defecto				AS	Defecto		,")
			loComandoSeleccionar.AppendLine("				Expedientes.Logico1				AS	Logico1		,")
			loComandoSeleccionar.AppendLine("				Expedientes.Logico2				AS	Logico2		,")
			loComandoSeleccionar.AppendLine("				Expedientes.Logico3				AS	Logico3		,")
			loComandoSeleccionar.AppendLine("				Expedientes.Logico4				AS	Logico4		,")
			loComandoSeleccionar.AppendLine("				Expedientes.Logico5				AS	Logico5		,")
			loComandoSeleccionar.AppendLine("				Expedientes.Fecha1				AS	Fecha1		,")
			loComandoSeleccionar.AppendLine("				Expedientes.Fecha2				AS	Fecha2		,")
			loComandoSeleccionar.AppendLine("				Expedientes.Fecha3				AS	Fecha3		,")
			loComandoSeleccionar.AppendLine("				Expedientes.Fecha4				AS	Fecha4		,")
			loComandoSeleccionar.AppendLine("				Expedientes.Fecha5				AS	Fecha5		,")
			loComandoSeleccionar.AppendLine("				Expedientes.Caracter1			AS	Caracter1	,")
			loComandoSeleccionar.AppendLine("				Expedientes.Caracter2			AS	Caracter2	,")
			loComandoSeleccionar.AppendLine("				Expedientes.Caracter3			AS	Caracter3	,")
			loComandoSeleccionar.AppendLine("				Expedientes.Caracter4			AS	Caracter4	,")
			loComandoSeleccionar.AppendLine("				Expedientes.Caracter5			AS	Caracter5	,")
			loComandoSeleccionar.AppendLine("				Expedientes.Numerico1			AS	Numerico1	,")
			loComandoSeleccionar.AppendLine("				Expedientes.Numerico2			AS	Numerico2	,")
			loComandoSeleccionar.AppendLine("				Expedientes.Numerico3			AS	Numerico3	,")
			loComandoSeleccionar.AppendLine("				Expedientes.Numerico4			AS	Numerico4	,")
			loComandoSeleccionar.AppendLine("				Expedientes.Numerico5			AS	Numerico5	,")
			loComandoSeleccionar.AppendLine("				Expedientes.Seguimientos		AS	Seguimientos,")
			loComandoSeleccionar.AppendLine("				Expedientes.Fec_Aut_Leg			AS	Fec_Aut_Leg,")
			loComandoSeleccionar.AppendLine("				Expedientes.Fec_Pre_Leg			AS	Fec_Pre_Leg,")
			loComandoSeleccionar.AppendLine("				Expedientes.Not_Pre_Leg			AS	Not_Pre_Leg,")	   
			loComandoSeleccionar.AppendLine("				Expedientes.Fec_Rec_Leg			AS	Fec_Rec_Leg,")
			loComandoSeleccionar.AppendLine("				Expedientes.Fec_Act_Ret			AS	Fec_Act_Ret,")
			loComandoSeleccionar.AppendLine("				Expedientes.Fec_Env_Act			AS	Fec_Env_Act,")
			loComandoSeleccionar.AppendLine(" 				NULL 							AS Seg_Renglon,")	
			loComandoSeleccionar.AppendLine(" 				NULL 							AS Seg_Fecha,")	
			loComandoSeleccionar.AppendLine(" 				NULL 							AS Seg_Seguimientos,")	
			loComandoSeleccionar.AppendLine(" 				NULL 							AS Seg_Status,")
			loComandoSeleccionar.AppendLine("				8								AS Origen")		
			loComandoSeleccionar.AppendLine("FROM Expedientes")
			loComandoSeleccionar.AppendLine("JOIN Vendedores ON Vendedores.Cod_Ven = Expedientes.Cod_Ven")
			loComandoSeleccionar.AppendLine("WHERE " & cusAplicacion.goFormatos.pcCondicionPrincipal)
			loComandoSeleccionar.AppendLine("")
			
			loComandoSeleccionar.AppendLine("UNION ALL")
			
			loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("SELECT		Renglones_Expedientes.Documento		AS	Documento	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Status		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Expediente	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Importacion	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Factura		,")
			loComandoSeleccionar.AppendLine("			NULL 								As	Control		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Declaracion	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Pla_Liq		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Cod_Log		,")
 			loComandoSeleccionar.AppendLine("			NULL 								AS	Nom_Log		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Cod_Reg		,")
 			loComandoSeleccionar.AppendLine("			NULL 								AS	Nom_Reg		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Cod_Cli		,")
 			loComandoSeleccionar.AppendLine("			NULL 								AS	Nom_Cli		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Tipo		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Clase		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Descripcion	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Comentario	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Ini		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Fin		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Rec		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Lle		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Pag		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Reg		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Adi1	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Adi2	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Adi3	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Adi4	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Adi5	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Containers	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Num_Bul		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Bultos		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Cajas		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Unidades	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Cod_Mon	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Nom_Mon	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Tasa	,")
			loComandoSeleccionar.AppendLine("			NULL							 	AS	Doc_Renglon,")
			loComandoSeleccionar.AppendLine("			Renglones_Expedientes.Tip_Ren	 	AS	Doc_Tip_Ren,")
			loComandoSeleccionar.AppendLine("			NULL  								AS 	Doc_Tip_Doc	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS 	Doc_Referencia	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS 	Doc_Detalle	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS 	Doc_Status	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS 	Doc_Control	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS 	Doc_Completo,")
			loComandoSeleccionar.AppendLine("			NULL  								AS 	Doc_Fec_Ini	,")
			loComandoSeleccionar.AppendLine("			NULL  								As 	Doc_Fec_Fin	,")
			loComandoSeleccionar.AppendLine("			NULL								As 	Doc_Comentario,")
			loComandoSeleccionar.AppendLine("			NULL  								AS 	Doc_Prioridad,")
			loComandoSeleccionar.AppendLine("			Renglones_Expedientes.Renglon	 	AS	Art_Renglon,")
			loComandoSeleccionar.AppendLine("			Renglones_Expedientes.Cod_Art	 	AS	Doc_Cod_Art,")
			loComandoSeleccionar.AppendLine("			Renglones_Expedientes.Cod_Alm	 	AS	Doc_Cod_Alm,")
			loComandoSeleccionar.AppendLine("			Renglones_Expedientes.Can_Art1	 	AS	Doc_Can_Art1,")
			loComandoSeleccionar.AppendLine("			Renglones_Expedientes.Cod_Uni	 	AS	Doc_Cod_Uni,")	
			loComandoSeleccionar.AppendLine("			Renglones_Expedientes.Precio1	 	AS	Doc_Precio1,")
			loComandoSeleccionar.AppendLine("			Renglones_Expedientes.Precio2	 	AS	Doc_Precio2,")
			loComandoSeleccionar.AppendLine("			Renglones_Expedientes.Mon_Net	 	AS	Doc_Mon_Net,")
			loComandoSeleccionar.AppendLine("			Renglones_Expedientes.Cod_Imp	 	AS	Doc_Cod_Imp,")
			loComandoSeleccionar.AppendLine("			Renglones_Expedientes.Por_Imp1	 	AS	Doc_Por_Imp1,")
			loComandoSeleccionar.AppendLine("			Renglones_Expedientes.Mon_Imp1	 	AS	Doc_Mon_Imp1,")
			loComandoSeleccionar.AppendLine("			Renglones_Expedientes.Nom_Art	 	AS	Doc_Nom_Art,")
			loComandoSeleccionar.AppendLine("			Renglones_Expedientes.Comentario	As 	Art_Comentario,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Renglon	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Tip_Tra	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Factura	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Control	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Referencia,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Transporte,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Vehiculo,")
			loComandoSeleccionar.AppendLine("			NULL 								As	Emb_Lug_Emb,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Containers,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Bultos,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Cajas,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Unidades,")
			loComandoSeleccionar.AppendLine("			NULL 								As	Emb_Peso,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Volumen,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Cod_Uni,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Nom_Uni,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Can_Art,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Detalle,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Status,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Fec_Ini,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Emb_Fec_Fin,")
			loComandoSeleccionar.AppendLine("			NULL								AS	Emb_Fec_Emb,")
			loComandoSeleccionar.AppendLine("			NULL								AS	Emb_Fec_Lle,")
			loComandoSeleccionar.AppendLine("			NULL								AS	Emb_Comentario,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Con_Renglon,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Con_Cod_Tip,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Con_Nom_Tip,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Con_Numero,")
			loComandoSeleccionar.AppendLine("			NULL  								AS  Con_Control,")
			loComandoSeleccionar.AppendLine("			NULL  								AS  Con_Referencia,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Con_Detalle,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Con_Status,")
			loComandoSeleccionar.AppendLine("			NULL  								As	Con_Peso,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Con_Volumen,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Con_Color,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Con_Fec_Ini,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Con_Fec_Fin,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Con_Comentario,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Gas_Renglon,")
			loComandoSeleccionar.AppendLine("			NULL								AS	Inc_Imp		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Gas_Cod_Con,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Gas_Nom_Con,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Gas_Mon_Deb,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Gas_Mon_Hab,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Gas_Cod_Imp,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Gas_Por_imp1,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Gas_Mon_Imp1, ")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Gas_Mon_Net,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Gas_Comentario,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Cod_Ven		,")
 			loComandoSeleccionar.AppendLine("			NULL  								AS	Nom_Ven		,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Cod_Usu		,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Cod_Gru		,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Por_Eje		,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Etapa		,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Prioridad	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Importancia	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Nivel		,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Ord_Com		,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Ord_Tra		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Defecto		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Logico1		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Logico2		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Logico3		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Logico4		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Logico5		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fecha1		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fecha2		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fecha3		,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fecha4		,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Fecha5		,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Caracter1	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Caracter2	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Caracter3	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Caracter4	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Caracter5	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Numerico1	,")
			loComandoSeleccionar.AppendLine("			NULL  								AS	Numerico2	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Numerico3	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Numerico4	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Numerico5	,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Seguimientos,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Aut_Leg,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Pre_Leg,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Not_Pre_Leg,")	   
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Rec_Leg,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Act_Ret,")
			loComandoSeleccionar.AppendLine("			NULL 								AS	Fec_Env_Act,")
			loComandoSeleccionar.AppendLine(" 			NULL 								AS Seg_Renglon,")	
			loComandoSeleccionar.AppendLine(" 			NULL 								AS Seg_Fecha,")	
			loComandoSeleccionar.AppendLine(" 			NULL 								AS Seg_Seguimientos,")	
			loComandoSeleccionar.AppendLine(" 			NULL 								AS Seg_Status,")
			loComandoSeleccionar.AppendLine("			7									AS Origen")		
			loComandoSeleccionar.AppendLine("FROM Renglones_Expedientes")
			loComandoSeleccionar.AppendLine("JOIN Expedientes ON Expedientes.Documento = Renglones_Expedientes.Documento")
			loComandoSeleccionar.AppendLine("WHERE Renglones_Expedientes.Tip_Ren = 'Articulo' AND" & cusAplicacion.goFormatos.pcCondicionPrincipal)
			loComandoSeleccionar.AppendLine("")
			
			loComandoSeleccionar.AppendLine("UNION ALL")
		
			loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("SELECT			Expedientes.Documento			AS	Documento	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Status		,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Expediente	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Importacion	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Factura		,")
			loComandoSeleccionar.AppendLine("				NULL  							As	Control		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Declaracion	,")
			loComandoSeleccionar.AppendLine("				NULL							AS	Pla_Liq		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Cod_Log		,")
 			loComandoSeleccionar.AppendLine("				NULL 							AS	Nom_Log		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Cod_Reg		,")
 			loComandoSeleccionar.AppendLine("				NULL 							AS	Nom_Reg		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Cod_Cli		,")
 			loComandoSeleccionar.AppendLine("				NULL 							AS	Nom_Cli		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Tipo		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Clase		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Descripcion	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Comentario	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fec_Ini		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fec_Fin		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fec_Rec		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fec_Lle		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fec_Pag		,")
			loComandoSeleccionar.AppendLine("				NULL							AS	Fec_Reg		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fec_Adi1	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fec_Adi2	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fec_Adi3	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fec_Adi4	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fec_Adi5	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Containers	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Num_Bul		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Bultos		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Cajas		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Unidades	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Cod_Mon	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Nom_Mon	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Tasa	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS 	Doc_Renglon	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS 	Doc_Tip_Ren	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS 	Doc_Tip_Doc	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS 	Doc_Referencia	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS 	Doc_Detalle	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS 	Doc_Status	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS 	Doc_Control	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS 	Doc_Completo,")
			loComandoSeleccionar.AppendLine("				NULL  							AS 	Doc_Fec_Ini	,")
			loComandoSeleccionar.AppendLine("				NULL  							As 	Doc_Fec_Fin	,")
			loComandoSeleccionar.AppendLine("				NULL  							As 	Doc_Comentario,")
			loComandoSeleccionar.AppendLine("				NULL  							AS 	Doc_Prioridad,")
			loComandoSeleccionar.AppendLine("				NULL	 						AS	Art_Renglon,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Doc_Cod_Art,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Doc_Cod_Alm,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Doc_Can_Art1,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Doc_Cod_Uni,")	
			loComandoSeleccionar.AppendLine("				NULL  							AS	Doc_Precio1,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Doc_Precio2,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Doc_Mon_Net,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Doc_Cod_Imp,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Doc_Por_Imp1,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Doc_Mon_Imp1,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Doc_Nom_Art,")
			loComandoSeleccionar.AppendLine("				NULL  							As 	Art_Comentario,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Renglon	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Tip_Tra	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Factura	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Control	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Referencia,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Transporte,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Vehiculo,")
			loComandoSeleccionar.AppendLine("				NULL 							As	Emb_Lug_Emb,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Containers,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Bultos,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Cajas,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Unidades,")
			loComandoSeleccionar.AppendLine("				NULL 							As	Emb_Peso,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Volumen,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Cod_Uni,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Nom_Uni,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Can_Art,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Detalle,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Status,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Fec_Ini,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Emb_Fec_Fin,")
			loComandoSeleccionar.AppendLine("				NULL							AS	Emb_Fec_Emb,")
			loComandoSeleccionar.AppendLine("				NULL							AS	Emb_Fec_Lle,")
			loComandoSeleccionar.AppendLine("				NULL							AS	Emb_Comentario,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Con_Renglon,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Con_Cod_Tip,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Con_Nom_Tip,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Con_Numero,")
			loComandoSeleccionar.AppendLine("				NULL  							AS  Con_Control,")
			loComandoSeleccionar.AppendLine("				NULL  							AS  Con_Referencia,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Con_Detalle,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Con_Status,")
			loComandoSeleccionar.AppendLine("				NULL  							As	Con_Peso,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Con_Volumen,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Con_Color,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Con_Fec_Ini,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Con_Fec_Fin,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Con_Comentario,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Gas_Renglon,")
			loComandoSeleccionar.AppendLine("				NULL							AS	Inc_Imp		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Gas_Cod_Con,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Gas_Nom_Con,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Gas_Mon_Deb,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Gas_Mon_Hab,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Gas_Cod_Imp,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Gas_Por_imp1,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Gas_Mon_Imp1, ")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Gas_Mon_Net,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Gas_Comentario,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Cod_Ven		,")
 			loComandoSeleccionar.AppendLine("				NULL  							AS	Nom_Ven		,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Cod_Usu		,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Cod_Gru		,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Por_Eje		,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Etapa		,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Prioridad	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Importancia	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Nivel		,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Ord_Com		,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Ord_Tra		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Defecto		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Logico1		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Logico2		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Logico3		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Logico4		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Logico5		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fecha1		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fecha2		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fecha3		,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fecha4		,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Fecha5		,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Caracter1	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Caracter2	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Caracter3	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Caracter4	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Caracter5	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Numerico1	,")
			loComandoSeleccionar.AppendLine("				NULL  							AS	Numerico2	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Numerico3	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Numerico4	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Numerico5	,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Seguimientos,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fec_Aut_Leg,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fec_Pre_Leg,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Not_Pre_Leg,")	   
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fec_Rec_Leg,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fec_Act_Ret,")
			loComandoSeleccionar.AppendLine("				NULL 							AS	Fec_Env_Act,")
			loComandoSeleccionar.AppendLine("				ROW_NUMBER() OVER (ORDER BY D.C.value('@fecha', 'datetime'),D.C.value('@seguimiento', 'Varchar(5000)'), D.C.value('@status', 'Varchar(15)') DESC) AS Seg_renglon,")	
			loComandoSeleccionar.AppendLine(" 				D.C.value('@fecha', 'datetime') AS Seg_Fecha,")
			loComandoSeleccionar.AppendLine(" 				D.C.value('@seguimiento', 'Varchar(5000)') AS Seg_Seguimientos,")
			loComandoSeleccionar.AppendLine(" 				D.C.value('@status', 'Varchar(15)') AS Seg_Status,")
			loComandoSeleccionar.AppendLine(" 				6 as Origen")
			loComandoSeleccionar.AppendLine(" ")	
			loComandoSeleccionar.AppendLine(" FROM #xmlData")
			loComandoSeleccionar.AppendLine("JOIN Expedientes ON " & cusAplicacion.goFormatos.pcCondicionPrincipal)	
			loComandoSeleccionar.AppendLine(" CROSS APPLY Seg_XML.nodes('elementos/elemento') D(c)")	
			loComandoSeleccionar.AppendLine(" ORDER BY Expedientes.Documento DESC ,Origen, Doc_Renglon, Emb_Renglon, Con_Renglon, Gas_Renglon,Seg_Renglon,Art_Renglon")
			

            Dim loServicios As New cusDatos.goDatos
            Dim laDatosReporte As DataSet = loServicios.mObtenerTodosSinEsquema(loComandoSeleccionar.ToString, "curReportes")
			
			'--------------------------------------------------'
			' Carga la imagen del logo en cusReportes          '
			'--------------------------------------------------'
			Me.mCargarLogoEmpresa(laDatosReporte.Tables(0), "LogoEmpresa")
			

			'-------------------------------------------------------------------------------------------------------
            ' Verificando si el select (tabla nº0) trae registros
            '-------------------------------------------------------------------------------------------------------

            If (laDatosReporte.Tables(0).Rows.Count <= 0) Then
                Me.WbcAdministradorMensajeModal.mMostrarMensajeModal("Información", _
                                          "No se Encontraron Registros para los Parámetros Especificados. ", _
						vis3Controles.wbcAdministradorMensajeModal.enumTipoMensaje.KN_Informacion, _
                                           "350px", _
                                           "200px")
            End If


            loObjetoReporte = cusAplicacion.goFormatos.mCargarInforme("fFicha_Expedientes", laDatosReporte)
            
            Me.mTraducirReporte(loObjetoReporte)
            Me.mFormatearCamposReporte(loObjetoReporte)
            Me.crvfFicha_Expedientes.ReportSource = loObjetoReporte

        Catch loExcepcion As Exception

            Me.WbcAdministradorMensajeModal.mMostrarMensajeModal("Error", _
                          "No se pudo Completar el Proceso: " & loExcepcion.Message, _
                           vis3Controles.wbcAdministradorMensajeModal.enumTipoMensaje.KN_Error, _
                           "auto", _
                           "auto")

        End Try

    End Sub

    Protected Sub Page_Unload(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Unload

        Try

            loObjetoReporte.Close()

        Catch loExcepcion As Exception

            Me.WbcAdministradorMensajeModal.mMostrarMensajeModal("Error", _
                          "No se pudo Completar el Proceso: " & loExcepcion.Message, _
                           vis3Controles.wbcAdministradorMensajeModal.enumTipoMensaje.KN_Error, _
                           "auto", _
                           "auto")

        End Try

    End Sub

End Class
'-------------------------------------------------------------------------------------------'
' Fin del codigo
'-------------------------------------------------------------------------------------------'
' MAT: 29/03/11 : Codigo inicial
'-------------------------------------------------------------------------------------------'
' MAT: 07/04/11 : Adición al select del Grupo Artículos
'-------------------------------------------------------------------------------------------'
