'-------------------------------------------------------------------------------------------'
' Inicio del codigo
'-------------------------------------------------------------------------------------------'
' Importando librerias 
'-------------------------------------------------------------------------------------------'
Imports System.Data
Imports System.Data.SqlClient

'-------------------------------------------------------------------------------------------'
' Inicio de clase "grOperaciones_MensualesCompras"
'-------------------------------------------------------------------------------------------'
Partial Class grOperaciones_MensualesCompras
    Inherits vis2formularios.frmReporte

    Dim loObjetoReporte As CrystalDecisions.CrystalReports.Engine.ReportDocument

    Private Property poResultado() As DataSet
        Get
            Return ViewState("poResultado")
        End Get
        Set(ByVal value As DataSet)
            ViewState("poResultado") = value
        End Set
    End Property

    Private Function mObtenerTodosLocal(ByVal lcCadenaConexion As String, ByVal lcComandoSelect As String, _
                                             ByVal lcNombreTabla As String) As DataSet

        Dim loConexionExterna As New SqlConnection(lcCadenaConexion)
        Dim TimeOut As SqlCommand = loConexionExterna.CreateCommand()

        TimeOut.CommandText = lcComandoSelect
        TimeOut.CommandTimeout = 0

        Dim loDataAdapter As New SqlDataAdapter(TimeOut)
        Dim loDataSet As New DataSet

        Try

            loConexionExterna.Open()
            loDataAdapter.Fill(loDataSet, lcNombreTabla)
            loConexionExterna.Close()
        Catch loExcepcion As Exception

            Throw New Exception("Error en mObtenerTodosLocal: " + loExcepcion.Message, loExcepcion.InnerException)

        End Try
        Return loDataSet

    End Function

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load

        Try

            Dim lcParametro0Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(0))
            Dim lcParametro1Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(1))
            Dim lcParametro1Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(1))
            Dim lcParametro2Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(2))
            Dim lcParametro2Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(2))
            Dim lcParametro3Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(3))
            Dim lcParametro3Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(3))
            Dim lcParametro4Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(4))
            Dim lcParametro4Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(4))
            Dim lcParametro5Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(5))
            Dim lcParametro5Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(5))
            Dim lcParametro6Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(6))
            Dim lcParametro6Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(6))
            Dim lcParametro7Desde As String = goServicios.mObtenerListaFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(7))
            Dim lcParametro8Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(8))
            Dim lcParametro8Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(8))
            Dim lcParametro9Desde As String = cusAplicacion.goReportes.paParametrosIniciales(9)
            Dim lcParametro10Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(10))
            Dim lcParametro10Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(10))

            If cusAplicacion.goReportes.paParametrosIniciales(0) = 0 Then
                lcParametro0Desde = "'" & Date.Now().Year() & "'"
            End If

            Dim lcOrdenamiento As String = cusAplicacion.goReportes.pcOrden

            Dim loComandoSeleccionar As New StringBuilder()

            loComandoSeleccionar.AppendLine(" -----Pagos")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine("   SELECT")
            loComandoSeleccionar.AppendLine("   	DATEPART(YEAR, Pagos.Fec_Ini) AS Año, ")
            loComandoSeleccionar.AppendLine("   	DATEPART(MONTH, Pagos.Fec_Ini) AS Mes, ")
            loComandoSeleccionar.AppendLine("   	CASE  ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Pagos.Fec_Ini) = 1 THEN SUM(Renglones_Pagos.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Pagos.Fec_Ini) = 2 THEN SUM(Renglones_Pagos.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Pagos.Fec_Ini) = 3 THEN SUM(Renglones_Pagos.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Pagos.Fec_Ini) = 4 THEN SUM(Renglones_Pagos.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Pagos.Fec_Ini) = 5 THEN SUM(Renglones_Pagos.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Pagos.Fec_Ini) = 6 THEN SUM(Renglones_Pagos.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Pagos.Fec_Ini) = 7 THEN SUM(Renglones_Pagos.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Pagos.Fec_Ini) = 8 THEN SUM(Renglones_Pagos.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Pagos.Fec_Ini) = 9 THEN SUM(Renglones_Pagos.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Pagos.Fec_Ini) = 10 THEN SUM(Renglones_Pagos.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Pagos.Fec_Ini) = 11 THEN SUM(Renglones_Pagos.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Pagos.Fec_Ini) = 12 THEN SUM(Renglones_Pagos.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		ELSE 0 ")
            loComandoSeleccionar.AppendLine("   	END AS MontoCobrados ")
            loComandoSeleccionar.AppendLine("   INTO #TempPagos ")
            loComandoSeleccionar.AppendLine("   FROM Pagos ")
            loComandoSeleccionar.AppendLine("   JOIN Renglones_Pagos ON Pagos.Documento = Renglones_Pagos.Documento ")
            loComandoSeleccionar.AppendLine(" WHERE         ")
            loComandoSeleccionar.AppendLine("      			DATEPART(YEAR, Pagos.Fec_Ini) = " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine(" 				AND Pagos.Cod_Pro between " & lcParametro2Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro2Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Pagos.Cod_Ven between " & lcParametro3Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro3Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Pagos.Status IN (" & lcParametro7Desde & ")")

            If lcParametro9Desde = "Igual" Then
                loComandoSeleccionar.AppendLine(" 				AND Pagos.Cod_Rev between " & lcParametro8Desde)
            Else
                loComandoSeleccionar.AppendLine(" 				AND Pagos.Cod_Rev NOT between " & lcParametro8Desde)
            End If
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro8Hasta)
            loComandoSeleccionar.AppendLine("               AND Pagos.Cod_Suc between " & lcParametro10Desde)
            loComandoSeleccionar.AppendLine("               AND " & lcParametro10Hasta)
            loComandoSeleccionar.AppendLine(" GROUP BY DATEPART(YEAR, Pagos.Fec_Ini), DATEPART(MONTH, Pagos.Fec_Ini) ")
            loComandoSeleccionar.AppendLine(" ORDER BY DATEPART(YEAR, Pagos.Fec_Ini), DATEPART(MONTH, Pagos.Fec_Ini) ")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	1 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCobrados")
            loComandoSeleccionar.AppendLine("   INTO #TempPagos2")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	2 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCobrados")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	3 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCobrados")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	4 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCobrados")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	5 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCobrados")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	6 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCobrados")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	7 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCobrados")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	8 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCobrados")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	9 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCobrados")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	10 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCobrados")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	11 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCobrados")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	12 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCobrados")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	Año,")
            loComandoSeleccionar.AppendLine("   	Mes,")
            loComandoSeleccionar.AppendLine("   	MontoCobrados")
            loComandoSeleccionar.AppendLine("   FROM #TempPagos")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine(" SELECT ")
            loComandoSeleccionar.AppendLine("   	Año,")
            loComandoSeleccionar.AppendLine("   	Mes,")
            loComandoSeleccionar.AppendLine("   	SUM(MontoCobrados) AS MontoCobrados")
            loComandoSeleccionar.AppendLine("  INTO #TempPagos3")
            loComandoSeleccionar.AppendLine("  FROM #TempPagos2")
            loComandoSeleccionar.AppendLine("  GROUP BY Año,Mes")
            loComandoSeleccionar.AppendLine("  order BY 2")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine(" ------  Presupuestos")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine("   SELECT")
            loComandoSeleccionar.AppendLine("   	DATEPART(YEAR, Presupuestos.Fec_Ini) AS Año, ")
            loComandoSeleccionar.AppendLine("   	DATEPART(MONTH, Presupuestos.Fec_Ini) AS Mes, ")
            loComandoSeleccionar.AppendLine("   	CASE  ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Presupuestos.Fec_Ini) = 1 THEN SUM(Renglones_Presupuestos.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Presupuestos.Fec_Ini) = 2 THEN SUM(Renglones_Presupuestos.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Presupuestos.Fec_Ini) = 3 THEN SUM(Renglones_Presupuestos.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Presupuestos.Fec_Ini) = 4 THEN SUM(Renglones_Presupuestos.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Presupuestos.Fec_Ini) = 5 THEN SUM(Renglones_Presupuestos.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Presupuestos.Fec_Ini) = 6 THEN SUM(Renglones_Presupuestos.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Presupuestos.Fec_Ini) = 7 THEN SUM(Renglones_Presupuestos.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Presupuestos.Fec_Ini) = 8 THEN SUM(Renglones_Presupuestos.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Presupuestos.Fec_Ini) = 9 THEN SUM(Renglones_Presupuestos.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Presupuestos.Fec_Ini) = 10 THEN SUM(Renglones_Presupuestos.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Presupuestos.Fec_Ini) = 11 THEN SUM(Renglones_Presupuestos.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Presupuestos.Fec_Ini) = 12 THEN SUM(Renglones_Presupuestos.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		ELSE 0 ")
            loComandoSeleccionar.AppendLine("   	END AS MontoPresupuestos ")
            loComandoSeleccionar.AppendLine("   INTO #TempPresupuestos ")
            loComandoSeleccionar.AppendLine("   FROM Presupuestos ")
            loComandoSeleccionar.AppendLine("   JOIN Renglones_Presupuestos ON Presupuestos.Documento = Renglones_Presupuestos.Documento ")
            loComandoSeleccionar.AppendLine("   JOIN Articulos ON Articulos.Cod_Art = Renglones_Presupuestos.Cod_Art ")
            loComandoSeleccionar.AppendLine(" WHERE         ")
            loComandoSeleccionar.AppendLine("      			DATEPART(YEAR, Presupuestos.Fec_Ini) = " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine(" 				AND Renglones_Presupuestos.Cod_Art between " & lcParametro1Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro1Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Presupuestos.Cod_Pro between " & lcParametro2Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro2Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Presupuestos.Cod_Ven between " & lcParametro3Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro3Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Articulos.Cod_Dep between " & lcParametro4Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro4Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Articulos.Cod_Tip between " & lcParametro5Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro5Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Articulos.Cod_Cla between " & lcParametro6Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro6Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Presupuestos.Status IN (" & lcParametro7Desde & ")")

            If lcParametro9Desde = "Igual" Then
                loComandoSeleccionar.AppendLine(" 				AND Presupuestos.Cod_Rev between " & lcParametro8Desde)
            Else
                loComandoSeleccionar.AppendLine(" 				AND Presupuestos.Cod_Rev NOT between " & lcParametro8Desde)
            End If
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro8Hasta)
            loComandoSeleccionar.AppendLine("               AND Presupuestos.Cod_Suc between " & lcParametro10Desde)
            loComandoSeleccionar.AppendLine("               AND " & lcParametro10Hasta)
            loComandoSeleccionar.AppendLine(" GROUP BY DATEPART(YEAR, Presupuestos.Fec_Ini), DATEPART(MONTH, Presupuestos.Fec_Ini) ")
            loComandoSeleccionar.AppendLine(" ORDER BY DATEPART(YEAR, Presupuestos.Fec_Ini), DATEPART(MONTH, Presupuestos.Fec_Ini) ")


            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	1 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoPresupuestos")
            loComandoSeleccionar.AppendLine("   INTO #TempPresupuestos2")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	2 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoPresupuestos")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	3 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoPresupuestos")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	4 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoPresupuestos")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	5 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoPresupuestos")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	6 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoPresupuestos")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	7 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoPresupuestos")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	8 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoPresupuestos")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	9 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoPresupuestos")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	10 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoPresupuestos")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	11 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoPresupuestos")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	12 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoPresupuestos")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	Año,")
            loComandoSeleccionar.AppendLine("   	Mes,")
            loComandoSeleccionar.AppendLine("   	MontoPresupuestos")
            loComandoSeleccionar.AppendLine("   FROM #TempPresupuestos")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine(" SELECT ")
            loComandoSeleccionar.AppendLine("   	Año,")
            loComandoSeleccionar.AppendLine("   	Mes,")
            loComandoSeleccionar.AppendLine("   	SUM(MontoPresupuestos) AS MontoPresupuestos")
            loComandoSeleccionar.AppendLine("  INTO #TempPresupuestos3")
            loComandoSeleccionar.AppendLine("  FROM #TempPresupuestos2")
            loComandoSeleccionar.AppendLine("  GROUP BY Año,Mes")
            loComandoSeleccionar.AppendLine("  order BY 2")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine(" ---- Devoluciones Proveedores")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine(" SELECT")
            loComandoSeleccionar.AppendLine("   	DATEPART(YEAR, Devoluciones_Proveedores.Fec_Ini) AS Año, ")
            loComandoSeleccionar.AppendLine("   	DATEPART(MONTH, Devoluciones_Proveedores.Fec_Ini) AS Mes, ")
            loComandoSeleccionar.AppendLine("   	CASE  ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Devoluciones_Proveedores.Fec_Ini) = 1 THEN SUM(Renglones_dProveedores.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Devoluciones_Proveedores.Fec_Ini) = 2 THEN SUM(Renglones_dProveedores.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Devoluciones_Proveedores.Fec_Ini) = 3 THEN SUM(Renglones_dProveedores.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Devoluciones_Proveedores.Fec_Ini) = 4 THEN SUM(Renglones_dProveedores.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Devoluciones_Proveedores.Fec_Ini) = 5 THEN SUM(Renglones_dProveedores.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Devoluciones_Proveedores.Fec_Ini) = 6 THEN SUM(Renglones_dProveedores.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Devoluciones_Proveedores.Fec_Ini) = 7 THEN SUM(Renglones_dProveedores.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Devoluciones_Proveedores.Fec_Ini) = 8 THEN SUM(Renglones_dProveedores.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Devoluciones_Proveedores.Fec_Ini) = 9 THEN SUM(Renglones_dProveedores.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Devoluciones_Proveedores.Fec_Ini) = 10 THEN SUM(Renglones_dProveedores.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Devoluciones_Proveedores.Fec_Ini) = 11 THEN SUM(Renglones_dProveedores.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Devoluciones_Proveedores.Fec_Ini) = 12 THEN SUM(Renglones_dProveedores.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		ELSE 0 ")
            loComandoSeleccionar.AppendLine("   	END AS MontoDevoluciones_Proveedores ")
            loComandoSeleccionar.AppendLine("   INTO #TempDevoluciones_Proveedores ")
            loComandoSeleccionar.AppendLine("   FROM Devoluciones_Proveedores ")
            loComandoSeleccionar.AppendLine("   JOIN Renglones_dProveedores ON Devoluciones_Proveedores.Documento = Renglones_dProveedores.Documento ")
            loComandoSeleccionar.AppendLine("   JOIN Articulos ON Articulos.Cod_Art = Renglones_dProveedores.Cod_Art ")
            loComandoSeleccionar.AppendLine(" WHERE         ")
            loComandoSeleccionar.AppendLine("      			DATEPART(YEAR, Devoluciones_Proveedores.Fec_Ini) = " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine(" 				AND Renglones_dProveedores.Cod_Art between " & lcParametro1Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro1Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Devoluciones_Proveedores.Cod_Pro between " & lcParametro2Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro2Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Devoluciones_Proveedores.Cod_Ven between " & lcParametro3Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro3Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Articulos.Cod_Dep between " & lcParametro4Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro4Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Articulos.Cod_Tip between " & lcParametro5Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro5Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Articulos.Cod_Cla between " & lcParametro6Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro6Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Devoluciones_Proveedores.Status IN (" & lcParametro7Desde & ")")

            If lcParametro9Desde = "Igual" Then
                loComandoSeleccionar.AppendLine(" 				AND Devoluciones_Proveedores.Cod_Rev between " & lcParametro8Desde)
            Else
                loComandoSeleccionar.AppendLine(" 				AND Devoluciones_Proveedores.Cod_Rev NOT between " & lcParametro8Desde)
            End If
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro8Hasta)
            loComandoSeleccionar.AppendLine("               AND Devoluciones_Proveedores.Cod_Suc between " & lcParametro10Desde)
            loComandoSeleccionar.AppendLine("               AND " & lcParametro10Hasta)
            loComandoSeleccionar.AppendLine(" GROUP BY DATEPART(YEAR, Devoluciones_Proveedores.Fec_Ini), DATEPART(MONTH, Devoluciones_Proveedores.Fec_Ini) ")
            loComandoSeleccionar.AppendLine(" ORDER BY DATEPART(YEAR, Devoluciones_Proveedores.Fec_Ini), DATEPART(MONTH, Devoluciones_Proveedores.Fec_Ini) ")


            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	1 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoDevoluciones_Proveedores")
            loComandoSeleccionar.AppendLine("   INTO #TempDevoluciones_Proveedores2")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	2 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoDevoluciones_Proveedores")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	3 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoDevoluciones_Proveedores")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	4 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoDevoluciones_Proveedores")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	5 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoDevoluciones_Proveedores")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	6 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoDevoluciones_Proveedores")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	7 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoDevoluciones_Proveedores")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	8 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoDevoluciones_Proveedores")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	9 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoDevoluciones_Proveedores")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	10 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoDevoluciones_Proveedores")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	11 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoDevoluciones_Proveedores")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	12 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoDevoluciones_Proveedores")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	Año,")
            loComandoSeleccionar.AppendLine("   	Mes,")
            loComandoSeleccionar.AppendLine("   	MontoDevoluciones_Proveedores")
            loComandoSeleccionar.AppendLine("   FROM #TempDevoluciones_Proveedores")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine("  SELECT ")
            loComandoSeleccionar.AppendLine("   	Año,")
            loComandoSeleccionar.AppendLine("   	Mes,")
            loComandoSeleccionar.AppendLine("   	SUM(MontoDevoluciones_Proveedores) AS MontoDevoluciones_Proveedores")
            loComandoSeleccionar.AppendLine("  INTO #TempDevoluciones_Proveedores3")
            loComandoSeleccionar.AppendLine("  FROM #TempDevoluciones_Proveedores2")
            loComandoSeleccionar.AppendLine("  GROUP BY Año,Mes")
            loComandoSeleccionar.AppendLine("  order BY 2")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine(" ----Ordenes_Compras")
            loComandoSeleccionar.AppendLine(" SELECT")
            loComandoSeleccionar.AppendLine("   	DATEPART(YEAR, Ordenes_Compras.Fec_Ini) AS Año, ")
            loComandoSeleccionar.AppendLine("   	DATEPART(MONTH, Ordenes_Compras.Fec_Ini) AS Mes, ")
            loComandoSeleccionar.AppendLine("   	CASE  ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Ordenes_Compras.Fec_Ini) = 1 THEN SUM(Renglones_oCompras.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Ordenes_Compras.Fec_Ini) = 2 THEN SUM(Renglones_oCompras.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Ordenes_Compras.Fec_Ini) = 3 THEN SUM(Renglones_oCompras.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Ordenes_Compras.Fec_Ini) = 4 THEN SUM(Renglones_oCompras.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Ordenes_Compras.Fec_Ini) = 5 THEN SUM(Renglones_oCompras.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Ordenes_Compras.Fec_Ini) = 6 THEN SUM(Renglones_oCompras.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Ordenes_Compras.Fec_Ini) = 7 THEN SUM(Renglones_oCompras.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Ordenes_Compras.Fec_Ini) = 8 THEN SUM(Renglones_oCompras.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Ordenes_Compras.Fec_Ini) = 9 THEN SUM(Renglones_oCompras.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Ordenes_Compras.Fec_Ini) = 10 THEN SUM(Renglones_oCompras.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Ordenes_Compras.Fec_Ini) = 11 THEN SUM(Renglones_oCompras.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Ordenes_Compras.Fec_Ini) = 12 THEN SUM(Renglones_oCompras.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		ELSE 0 ")
            loComandoSeleccionar.AppendLine("   	END AS MontoOrdenes_Compras ")
            loComandoSeleccionar.AppendLine("   INTO #TempOrdenes_Compras ")
            loComandoSeleccionar.AppendLine("   FROM Ordenes_Compras ")
            loComandoSeleccionar.AppendLine("   JOIN Renglones_oCompras ON Ordenes_Compras.Documento = Renglones_oCompras.Documento ")
            loComandoSeleccionar.AppendLine("   JOIN Articulos ON Articulos.Cod_Art = Renglones_oCompras.Cod_Art ")
            loComandoSeleccionar.AppendLine(" WHERE         ")
            loComandoSeleccionar.AppendLine("      			DATEPART(YEAR, Ordenes_Compras.Fec_Ini) = " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine(" 				AND Renglones_oCompras.Cod_Art between " & lcParametro1Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro1Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Ordenes_Compras.Cod_Pro between " & lcParametro2Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro2Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Ordenes_Compras.Cod_Ven between " & lcParametro3Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro3Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Articulos.Cod_Dep between " & lcParametro4Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro4Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Articulos.Cod_Tip between " & lcParametro5Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro5Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Articulos.Cod_Cla between " & lcParametro6Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro6Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Ordenes_Compras.Status IN (" & lcParametro7Desde & ")")

            If lcParametro9Desde = "Igual" Then
                loComandoSeleccionar.AppendLine(" 				AND Ordenes_Compras.Cod_Rev between " & lcParametro8Desde)
            Else
                loComandoSeleccionar.AppendLine(" 				AND Ordenes_Compras.Cod_Rev NOT between " & lcParametro8Desde)
            End If
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro8Hasta)
            loComandoSeleccionar.AppendLine("               AND Ordenes_Compras.Cod_Suc between " & lcParametro10Desde)
            loComandoSeleccionar.AppendLine("               AND " & lcParametro10Hasta)
            loComandoSeleccionar.AppendLine(" GROUP BY DATEPART(YEAR, Ordenes_Compras.Fec_Ini), DATEPART(MONTH, Ordenes_Compras.Fec_Ini) ")
            loComandoSeleccionar.AppendLine(" ORDER BY DATEPART(YEAR, Ordenes_Compras.Fec_Ini), DATEPART(MONTH, Ordenes_Compras.Fec_Ini) ")


            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	1 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoOrdenes_Compras")
            loComandoSeleccionar.AppendLine("   INTO #TempOrdenes_Compras2")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	2 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoOrdenes_Compras")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	3 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoOrdenes_Compras")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	4 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoOrdenes_Compras")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	5 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoOrdenes_Compras")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	6 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoOrdenes_Compras")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	7 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoOrdenes_Compras")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	8 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoOrdenes_Compras")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	9 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoOrdenes_Compras")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	10 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoOrdenes_Compras")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	11 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoOrdenes_Compras")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	12 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoOrdenes_Compras")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	Año,")
            loComandoSeleccionar.AppendLine("   	Mes,")
            loComandoSeleccionar.AppendLine("   	MontoOrdenes_Compras")
            loComandoSeleccionar.AppendLine("   FROM #TempOrdenes_Compras")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine("  SELECT ")
            loComandoSeleccionar.AppendLine("   	Año,")
            loComandoSeleccionar.AppendLine("   	Mes,")
            loComandoSeleccionar.AppendLine("   	SUM(MontoOrdenes_Compras) AS MontoOrdenes_Compras")
            loComandoSeleccionar.AppendLine("  INTO #TempOrdenes_Compras3")
            loComandoSeleccionar.AppendLine("  FROM #TempOrdenes_Compras2")
            loComandoSeleccionar.AppendLine("  GROUP BY Año,Mes")
            loComandoSeleccionar.AppendLine("  order BY 2")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine(" ----------Compras")
            loComandoSeleccionar.AppendLine("   SELECT")
            loComandoSeleccionar.AppendLine("   	DATEPART(YEAR, Compras.Fec_Ini) AS Año, ")
            loComandoSeleccionar.AppendLine("   	DATEPART(MONTH, Compras.Fec_Ini) AS Mes, ")
            loComandoSeleccionar.AppendLine("   	CASE  ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Compras.Fec_Ini) = 1 THEN SUM(Renglones_Compras.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Compras.Fec_Ini) = 2 THEN SUM(Renglones_Compras.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Compras.Fec_Ini) = 3 THEN SUM(Renglones_Compras.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Compras.Fec_Ini) = 4 THEN SUM(Renglones_Compras.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Compras.Fec_Ini) = 5 THEN SUM(Renglones_Compras.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Compras.Fec_Ini) = 6 THEN SUM(Renglones_Compras.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Compras.Fec_Ini) = 7 THEN SUM(Renglones_Compras.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Compras.Fec_Ini) = 8 THEN SUM(Renglones_Compras.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Compras.Fec_Ini) = 9 THEN SUM(Renglones_Compras.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Compras.Fec_Ini) = 10 THEN SUM(Renglones_Compras.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Compras.Fec_Ini) = 11 THEN SUM(Renglones_Compras.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Compras.Fec_Ini) = 12 THEN SUM(Renglones_Compras.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		ELSE 0 ")
            loComandoSeleccionar.AppendLine("   	END AS MontoCompras ")
            loComandoSeleccionar.AppendLine("   INTO #TempCompras ")
            loComandoSeleccionar.AppendLine("   FROM Compras ")
            loComandoSeleccionar.AppendLine("   JOIN Renglones_Compras ON Compras.Documento = Renglones_Compras.Documento ")
            loComandoSeleccionar.AppendLine("   JOIN Articulos ON Articulos.Cod_Art = Renglones_Compras.Cod_Art ")
            loComandoSeleccionar.AppendLine(" WHERE         ")
            loComandoSeleccionar.AppendLine("      			DATEPART(YEAR, Compras.Fec_Ini) = " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine(" 				AND Renglones_Compras.Cod_Art between " & lcParametro1Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro1Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Compras.Cod_Pro between " & lcParametro2Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro2Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Compras.Cod_Ven between " & lcParametro3Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro3Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Articulos.Cod_Dep between " & lcParametro4Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro4Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Articulos.Cod_Tip between " & lcParametro5Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro5Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Articulos.Cod_Cla between " & lcParametro6Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro6Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Compras.Status IN (" & lcParametro7Desde & ")")

            If lcParametro9Desde = "Igual" Then
                loComandoSeleccionar.AppendLine(" 				AND Compras.Cod_Rev between " & lcParametro8Desde)
            Else
                loComandoSeleccionar.AppendLine(" 				AND Compras.Cod_Rev NOT between " & lcParametro8Desde)
            End If
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro8Hasta)
            loComandoSeleccionar.AppendLine("               AND Compras.Cod_Suc between " & lcParametro10Desde)
            loComandoSeleccionar.AppendLine("               AND " & lcParametro10Hasta)
            loComandoSeleccionar.AppendLine(" GROUP BY DATEPART(YEAR, Compras.Fec_Ini), DATEPART(MONTH, Compras.Fec_Ini) ")
            loComandoSeleccionar.AppendLine(" ORDER BY DATEPART(YEAR, Compras.Fec_Ini), DATEPART(MONTH, Compras.Fec_Ini) ")


            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	1 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCompras")
            loComandoSeleccionar.AppendLine("   INTO #TempCompras2")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	2 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCompras")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	3 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCompras")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	4 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCompras")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	5 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCompras")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	6 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCompras")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	7 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCompras")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	8 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCompras")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	9 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCompras")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	10 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCompras")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	11 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCompras")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	12 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCompras")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	Año,")
            loComandoSeleccionar.AppendLine("   	Mes,")
            loComandoSeleccionar.AppendLine("   	MontoCompras")
            loComandoSeleccionar.AppendLine("   FROM #TempCompras")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine(" SELECT ")
            loComandoSeleccionar.AppendLine("   	Año,")
            loComandoSeleccionar.AppendLine("   	Mes,")
            loComandoSeleccionar.AppendLine("   	SUM(MontoCompras) AS MontoCompras")
            loComandoSeleccionar.AppendLine("  INTO #TempCompras3")
            loComandoSeleccionar.AppendLine("  FROM #TempCompras2")
            loComandoSeleccionar.AppendLine("  GROUP BY Año,Mes")
            loComandoSeleccionar.AppendLine("  order BY 2")
            loComandoSeleccionar.AppendLine("   ")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine(" -------union de todas las tablas nivel 3")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine(" SELECT ")
            loComandoSeleccionar.AppendLine(" 		#TempCompras3.Año,")
            loComandoSeleccionar.AppendLine(" 		#TempCompras3.Mes,")
            loComandoSeleccionar.AppendLine(" 		#TempCompras3.MontoCompras AS Facturas,")
            loComandoSeleccionar.AppendLine(" 		#TempOrdenes_Compras3.MontoOrdenes_Compras AS Ordenes_Compras,")
            loComandoSeleccionar.AppendLine(" 		#TempPresupuestos3.MontoPresupuestos AS Presupuestos,")
            loComandoSeleccionar.AppendLine(" 		#TempDevoluciones_Proveedores3.MontoDevoluciones_Proveedores AS Devoluciones,")
            loComandoSeleccionar.AppendLine(" 		#TempPagos3.MontoCobrados AS Pagos")
            loComandoSeleccionar.AppendLine(" FROM #TempCompras3")
            loComandoSeleccionar.AppendLine(" JOIN #TempPagos3 ON #TempPagos3.Año = #TempCompras3.Año AND #TempPagos3.Mes = #TempCompras3.Mes")
            loComandoSeleccionar.AppendLine(" JOIN #TempOrdenes_Compras3 ON #TempOrdenes_Compras3.Año = #TempCompras3.Año AND #TempOrdenes_Compras3.Mes = #TempCompras3.Mes")
            loComandoSeleccionar.AppendLine(" JOIN #TempDevoluciones_Proveedores3 ON #TempDevoluciones_Proveedores3.Año = #TempCompras3.Año AND #TempDevoluciones_Proveedores3.Mes = #TempCompras3.Mes")
            loComandoSeleccionar.AppendLine(" JOIN #TempPresupuestos3 ON #TempPresupuestos3.Año = #TempCompras3.Año AND #TempPresupuestos3.Mes = #TempCompras3.Mes")

            'me.mEscribirConsulta(loComandoSeleccionar.ToString)
            Dim lcConexion As String = ""
            Dim laDatosReporte As DataSet

            If Not Me.IsPostBack Then

                lcConexion = goDatos.pcCadenaConexionAdministrativo()

                laDatosReporte = mObtenerTodosLocal(lcConexion.ToString, loComandoSeleccionar.ToString(), "curReportes")
                Me.poResultado = laDatosReporte

            Else

                laDatosReporte = Me.poResultado

            End If

            'Dim loServicios As New cusDatos.goDatos
            'Dim laDatosReporte As DataSet = loServicios.mObtenerTodosSinEsquema(loComandoSeleccionar.ToString, "curReportes")

            loObjetoReporte = cusAplicacion.goReportes.mCargarReporte("grOperaciones_MensualesCompras", laDatosReporte)

            '-------------------------------------------------------------------------------------------------------
            ' Verificando si el select (tabla nº0) trae registros
            '-------------------------------------------------------------------------------------------------------

            If laDatosReporte.Tables(0).Rows.Count <= 0 Then
                Me.WbcAdministradorMensajeModal.mMostrarMensajeModal("Información", _
                                          "No se Encontraron Registros para los Parámetros Especificados. ", _
                                           vis3Controles.wbcAdministradorMensajeModal.enumTipoMensaje.KN_Informacion, _
                                           "350px", _
                                           "200px")
            End If



            Me.mTraducirReporte(loObjetoReporte)
            Me.mFormatearCamposReporte(loObjetoReporte)
            Me.crvgrOperaciones_MensualesCompras.ReportSource = loObjetoReporte

        Catch loExcepcion As Exception

            Me.WbcAdministradorMensajeModal.mMostrarMensajeModal("Error", _
                          "No se pudo Completar el Proceso: " & loExcepcion.Message, _
                           vis3Controles.wbcAdministradorMensajeModal.enumTipoMensaje.KN_Error, _
                           "auto", _
                           "auto")

        End Try

    End Sub

    Protected Sub Page_Unload(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Unload
        Try

            loObjetoReporte.Close()

        Catch loExcepcion As Exception


        End Try
    End Sub

End Class
'-------------------------------------------------------------------------------------------'
' Fin del codigo                                                                            '
'-------------------------------------------------------------------------------------------'
' CMS: 25/06/10: Codigo inicial.                                                            '
'-------------------------------------------------------------------------------------------'
' RJG: 05/12/14: Se ajustó el layout para que quepa en una sola página.                     '
'-------------------------------------------------------------------------------------------'
