'-------------------------------------------------------------------------------------------'
' Inicio del codigo
'-------------------------------------------------------------------------------------------'
' Importando librerias 
'-------------------------------------------------------------------------------------------'
Imports System.Data
Imports System.Data.SqlClient

'-------------------------------------------------------------------------------------------'
' Inicio de clase "grOperaciones_Mensuales"
'-------------------------------------------------------------------------------------------'
Partial Class grOperaciones_Mensuales
    Inherits vis2formularios.frmReporte

    Dim loObjetoReporte As CrystalDecisions.CrystalReports.Engine.ReportDocument

    Private Property poResultado() As DataSet

        Get
            Return ViewState("poResultado")
        End Get

        Set(ByVal value As DataSet)
            ViewState("poResultado") = value
        End Set

    End Property

    Private Function mObtenerTodosLocal(ByVal lcCadenaConexion As String, ByVal lcComandoSelect As String, _
                                             ByVal lcNombreTabla As String) As DataSet

        Dim loConexionExterna As New SqlConnection(lcCadenaConexion)
        Dim TimeOut As SqlCommand = loConexionExterna.CreateCommand()

        TimeOut.CommandText = lcComandoSelect
        TimeOut.CommandTimeout = 0

        Dim loDataAdapter As New SqlDataAdapter(TimeOut)
        Dim loDataSet As New DataSet

        Try

            loConexionExterna.Open()
            loDataAdapter.Fill(loDataSet, lcNombreTabla)
            loConexionExterna.Close()
        Catch loExcepcion As Exception

            Throw New Exception("Error en mObtenerTodosLocal: " + loExcepcion.Message, loExcepcion.InnerException)

        End Try
        Return loDataSet

    End Function


    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load

        Try

            Dim lcParametro0Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(0))
            Dim lcParametro1Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(1))
            Dim lcParametro1Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(1))
            Dim lcParametro2Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(2))
            Dim lcParametro2Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(2))
            Dim lcParametro3Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(3))
            Dim lcParametro3Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(3))
            Dim lcParametro4Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(4))
            Dim lcParametro4Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(4))
            Dim lcParametro5Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(5))
            Dim lcParametro5Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(5))
            Dim lcParametro6Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(6))
            Dim lcParametro6Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(6))
            Dim lcParametro7Desde As String = goServicios.mObtenerListaFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(7))
            Dim lcParametro8Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(8))
            Dim lcParametro8Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(8))
            Dim lcParametro9Desde As String = cusAplicacion.goReportes.paParametrosIniciales(9)
            Dim lcParametro10Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(10))
            Dim lcParametro10Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(10))

            If cusAplicacion.goReportes.paParametrosIniciales(0) = 0 Then
                lcParametro0Desde = "'" & Now.Year & "'"
            End If

            Dim lcOrdenamiento As String = cusAplicacion.goReportes.pcOrden

            Dim loComandoSeleccionar As New StringBuilder()

            loComandoSeleccionar.AppendLine(" -----Cobros")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine("   SELECT")
            loComandoSeleccionar.AppendLine("   	DATEPART(YEAR, Cobros.Fec_Ini) AS Año, ")
            loComandoSeleccionar.AppendLine("   	DATEPART(MONTH, Cobros.Fec_Ini) AS Mes, ")
            loComandoSeleccionar.AppendLine("   	CASE  ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Cobros.Fec_Ini) = 1 THEN SUM(Renglones_Cobros.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Cobros.Fec_Ini) = 2 THEN SUM(Renglones_Cobros.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Cobros.Fec_Ini) = 3 THEN SUM(Renglones_Cobros.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Cobros.Fec_Ini) = 4 THEN SUM(Renglones_Cobros.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Cobros.Fec_Ini) = 5 THEN SUM(Renglones_Cobros.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Cobros.Fec_Ini) = 6 THEN SUM(Renglones_Cobros.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Cobros.Fec_Ini) = 7 THEN SUM(Renglones_Cobros.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Cobros.Fec_Ini) = 8 THEN SUM(Renglones_Cobros.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Cobros.Fec_Ini) = 9 THEN SUM(Renglones_Cobros.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Cobros.Fec_Ini) = 10 THEN SUM(Renglones_Cobros.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Cobros.Fec_Ini) = 11 THEN SUM(Renglones_Cobros.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Cobros.Fec_Ini) = 12 THEN SUM(Renglones_Cobros.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		ELSE 0 ")
            loComandoSeleccionar.AppendLine("   	END AS MontoCobrados ")
            loComandoSeleccionar.AppendLine("   INTO #TempCobros ")
            loComandoSeleccionar.AppendLine("   FROM Cobros ")
            loComandoSeleccionar.AppendLine("   JOIN Renglones_Cobros ON Cobros.Documento = Renglones_Cobros.Documento ")
            loComandoSeleccionar.AppendLine(" WHERE         ")
            loComandoSeleccionar.AppendLine("      			DATEPART(YEAR, Cobros.Fec_Ini) = " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine(" 				AND Cobros.Cod_Cli between " & lcParametro2Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro2Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Cobros.Cod_Ven between " & lcParametro3Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro3Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Cobros.Status IN (" & lcParametro7Desde & ")")

            If lcParametro9Desde = "Igual" Then
                loComandoSeleccionar.AppendLine(" 				AND Cobros.Cod_Rev between " & lcParametro8Desde)
            Else
                loComandoSeleccionar.AppendLine(" 				AND Cobros.Cod_Rev NOT between " & lcParametro8Desde)
            End If
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro8Hasta)
            loComandoSeleccionar.AppendLine("               AND Cobros.Cod_Suc between " & lcParametro10Desde)
            loComandoSeleccionar.AppendLine("               AND " & lcParametro10Hasta)
            loComandoSeleccionar.AppendLine(" GROUP BY DATEPART(YEAR, Cobros.Fec_Ini), DATEPART(MONTH, Cobros.Fec_Ini) ")
            loComandoSeleccionar.AppendLine(" ORDER BY DATEPART(YEAR, Cobros.Fec_Ini), DATEPART(MONTH, Cobros.Fec_Ini) ")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	1 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCobrados")
            loComandoSeleccionar.AppendLine("   INTO #TempCobros2")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	2 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCobrados")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	3 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCobrados")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	4 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCobrados")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	5 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCobrados")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	6 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCobrados")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	7 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCobrados")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	8 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCobrados")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	9 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCobrados")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	10 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCobrados")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	11 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCobrados")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	12 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCobrados")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	Año,")
            loComandoSeleccionar.AppendLine("   	Mes,")
            loComandoSeleccionar.AppendLine("   	MontoCobrados")
            loComandoSeleccionar.AppendLine("   FROM #TempCobros")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine(" SELECT ")
            loComandoSeleccionar.AppendLine("   	Año,")
            loComandoSeleccionar.AppendLine("   	Mes,")
            loComandoSeleccionar.AppendLine("   	SUM(MontoCobrados) AS MontoCobrados")
            loComandoSeleccionar.AppendLine("  INTO #TempCobros3")
            loComandoSeleccionar.AppendLine("  FROM #TempCobros2")
            loComandoSeleccionar.AppendLine("  GROUP BY Año,Mes")
            loComandoSeleccionar.AppendLine("  order BY 2")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine(" ------  Cotizaciones")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine("   SELECT")
            loComandoSeleccionar.AppendLine("   	DATEPART(YEAR, Cotizaciones.Fec_Ini) AS Año, ")
            loComandoSeleccionar.AppendLine("   	DATEPART(MONTH, Cotizaciones.Fec_Ini) AS Mes, ")
            loComandoSeleccionar.AppendLine("   	CASE  ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Cotizaciones.Fec_Ini) = 1 THEN SUM(Renglones_Cotizaciones.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Cotizaciones.Fec_Ini) = 2 THEN SUM(Renglones_Cotizaciones.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Cotizaciones.Fec_Ini) = 3 THEN SUM(Renglones_Cotizaciones.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Cotizaciones.Fec_Ini) = 4 THEN SUM(Renglones_Cotizaciones.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Cotizaciones.Fec_Ini) = 5 THEN SUM(Renglones_Cotizaciones.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Cotizaciones.Fec_Ini) = 6 THEN SUM(Renglones_Cotizaciones.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Cotizaciones.Fec_Ini) = 7 THEN SUM(Renglones_Cotizaciones.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Cotizaciones.Fec_Ini) = 8 THEN SUM(Renglones_Cotizaciones.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Cotizaciones.Fec_Ini) = 9 THEN SUM(Renglones_Cotizaciones.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Cotizaciones.Fec_Ini) = 10 THEN SUM(Renglones_Cotizaciones.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Cotizaciones.Fec_Ini) = 11 THEN SUM(Renglones_Cotizaciones.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Cotizaciones.Fec_Ini) = 12 THEN SUM(Renglones_Cotizaciones.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		ELSE 0 ")
            loComandoSeleccionar.AppendLine("   	END AS MontoCotizaciones ")
            loComandoSeleccionar.AppendLine("   INTO #TempCotizaciones ")
            loComandoSeleccionar.AppendLine("   FROM Cotizaciones ")
            loComandoSeleccionar.AppendLine("   JOIN Renglones_Cotizaciones ON Cotizaciones.Documento = Renglones_Cotizaciones.Documento ")
            loComandoSeleccionar.AppendLine("   JOIN Articulos ON Articulos.Cod_Art = Renglones_Cotizaciones.Cod_Art ")
            loComandoSeleccionar.AppendLine(" WHERE         ")
            loComandoSeleccionar.AppendLine("      			DATEPART(YEAR, Cotizaciones.Fec_Ini) = " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine(" 				AND Renglones_Cotizaciones.Cod_Art between " & lcParametro1Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro1Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Cotizaciones.Cod_Cli between " & lcParametro2Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro2Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Cotizaciones.Cod_Ven between " & lcParametro3Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro3Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Articulos.Cod_Dep between " & lcParametro4Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro4Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Articulos.Cod_Tip between " & lcParametro5Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro5Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Articulos.Cod_Cla between " & lcParametro6Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro6Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Cotizaciones.Status IN (" & lcParametro7Desde & ")")

            If lcParametro9Desde = "Igual" Then
                loComandoSeleccionar.AppendLine(" 				AND Cotizaciones.Cod_Rev between " & lcParametro8Desde)
            Else
                loComandoSeleccionar.AppendLine(" 				AND Cotizaciones.Cod_Rev NOT between " & lcParametro8Desde)
            End If
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro8Hasta)
            loComandoSeleccionar.AppendLine("               AND Cotizaciones.Cod_Suc between " & lcParametro10Desde)
            loComandoSeleccionar.AppendLine("               AND " & lcParametro10Hasta)
            loComandoSeleccionar.AppendLine(" GROUP BY DATEPART(YEAR, Cotizaciones.Fec_Ini), DATEPART(MONTH, Cotizaciones.Fec_Ini) ")
            loComandoSeleccionar.AppendLine(" ORDER BY DATEPART(YEAR, Cotizaciones.Fec_Ini), DATEPART(MONTH, Cotizaciones.Fec_Ini) ")


            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	1 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCotizaciones")
            loComandoSeleccionar.AppendLine("   INTO #TempCotizaciones2")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	2 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCotizaciones")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	3 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCotizaciones")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	4 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCotizaciones")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	5 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCotizaciones")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	6 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCotizaciones")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	7 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCotizaciones")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	8 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCotizaciones")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	9 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCotizaciones")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	10 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCotizaciones")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	11 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCotizaciones")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	12 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoCotizaciones")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	Año,")
            loComandoSeleccionar.AppendLine("   	Mes,")
            loComandoSeleccionar.AppendLine("   	MontoCotizaciones")
            loComandoSeleccionar.AppendLine("   FROM #TempCotizaciones")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine(" SELECT ")
            loComandoSeleccionar.AppendLine("   	Año,")
            loComandoSeleccionar.AppendLine("   	Mes,")
            loComandoSeleccionar.AppendLine("   	SUM(MontoCotizaciones) AS MontoCotizaciones")
            loComandoSeleccionar.AppendLine("  INTO #TempCotizaciones3")
            loComandoSeleccionar.AppendLine("  FROM #TempCotizaciones2")
            loComandoSeleccionar.AppendLine("  GROUP BY Año,Mes")
            loComandoSeleccionar.AppendLine("  order BY 2")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine(" ")
            'loComandoSeleccionar.AppendLine(" ---- Devoluciones Proveedores")
            'loComandoSeleccionar.AppendLine(" ")
            'loComandoSeleccionar.AppendLine(" SELECT")
            'loComandoSeleccionar.AppendLine("   	DATEPART(YEAR, Devoluciones_Proveedores.Fec_Ini) AS Año, ")
            'loComandoSeleccionar.AppendLine("   	DATEPART(MONTH, Devoluciones_Proveedores.Fec_Ini) AS Mes, ")
            'loComandoSeleccionar.AppendLine("   	CASE  ")
            'loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Devoluciones_Proveedores.Fec_Ini) = 1 THEN SUM(Renglones_dProveedores.Mon_Net) ")
            'loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Devoluciones_Proveedores.Fec_Ini) = 2 THEN SUM(Renglones_dProveedores.Mon_Net) ")
            'loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Devoluciones_Proveedores.Fec_Ini) = 3 THEN SUM(Renglones_dProveedores.Mon_Net) ")
            'loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Devoluciones_Proveedores.Fec_Ini) = 4 THEN SUM(Renglones_dProveedores.Mon_Net) ")
            'loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Devoluciones_Proveedores.Fec_Ini) = 5 THEN SUM(Renglones_dProveedores.Mon_Net) ")
            'loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Devoluciones_Proveedores.Fec_Ini) = 6 THEN SUM(Renglones_dProveedores.Mon_Net) ")
            'loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Devoluciones_Proveedores.Fec_Ini) = 7 THEN SUM(Renglones_dProveedores.Mon_Net) ")
            'loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Devoluciones_Proveedores.Fec_Ini) = 8 THEN SUM(Renglones_dProveedores.Mon_Net) ")
            'loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Devoluciones_Proveedores.Fec_Ini) = 9 THEN SUM(Renglones_dProveedores.Mon_Net) ")
            'loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Devoluciones_Proveedores.Fec_Ini) = 10 THEN SUM(Renglones_dProveedores.Mon_Net) ")
            'loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Devoluciones_Proveedores.Fec_Ini) = 11 THEN SUM(Renglones_dProveedores.Mon_Net) ")
            'loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Devoluciones_Proveedores.Fec_Ini) = 12 THEN SUM(Renglones_dProveedores.Mon_Net) ")
            'loComandoSeleccionar.AppendLine("   		ELSE 0 ")
            'loComandoSeleccionar.AppendLine("   	END AS MontoDevoluciones_Proveedores ")
            'loComandoSeleccionar.AppendLine("   INTO #TempDevoluciones_Proveedores ")
            'loComandoSeleccionar.AppendLine("   FROM Devoluciones_Proveedores ")
            'loComandoSeleccionar.AppendLine("   JOIN Renglones_dProveedores ON Devoluciones_Proveedores.Documento = Renglones_dProveedores.Documento ")
            'loComandoSeleccionar.AppendLine("   JOIN Articulos ON Articulos.Cod_Art = Renglones_dProveedores.Cod_Art ")
            'loComandoSeleccionar.AppendLine(" WHERE         ")
            'loComandoSeleccionar.AppendLine("      			DATEPART(YEAR, Devoluciones_Proveedores.Fec_Ini) = " & lcParametro0Desde)
            'loComandoSeleccionar.AppendLine(" 				AND Renglones_dProveedores.Cod_Art between " & lcParametro1Desde)
            'loComandoSeleccionar.AppendLine(" 				AND " & lcParametro1Hasta)
            'loComandoSeleccionar.AppendLine(" 				AND Devoluciones_Proveedores.Cod_Pro between " & lcParametro2Desde)
            'loComandoSeleccionar.AppendLine(" 				AND " & lcParametro2Hasta)
            'loComandoSeleccionar.AppendLine(" 				AND Devoluciones_Proveedores.Cod_Ven between " & lcParametro3Desde)
            'loComandoSeleccionar.AppendLine(" 				AND " & lcParametro3Hasta)
            'loComandoSeleccionar.AppendLine(" 				AND Articulos.Cod_Dep between " & lcParametro4Desde)
            'loComandoSeleccionar.AppendLine(" 				AND " & lcParametro4Hasta)
            'loComandoSeleccionar.AppendLine(" 				AND Articulos.Cod_Tip between " & lcParametro5Desde)
            'loComandoSeleccionar.AppendLine(" 				AND " & lcParametro5Hasta)
            'loComandoSeleccionar.AppendLine(" 				AND Articulos.Cod_Cla between " & lcParametro6Desde)
            'loComandoSeleccionar.AppendLine(" 				AND " & lcParametro6Hasta)
            'loComandoSeleccionar.AppendLine(" 				AND Devoluciones_Proveedores.Status IN (" & lcParametro7Desde & ")")

            'If lcParametro9Desde = "Igual" Then
            '	loComandoSeleccionar.AppendLine(" 				AND Devoluciones_Proveedores.Cod_Rev between " & lcParametro8Desde)
            'Else
            '	loComandoSeleccionar.AppendLine(" 				AND Devoluciones_Proveedores.Cod_Rev NOT between " & lcParametro8Desde)
            'End If
            'loComandoSeleccionar.AppendLine(" 				AND " & lcParametro8Hasta)
            'loComandoSeleccionar.AppendLine("               AND Devoluciones_Proveedores.Cod_Suc between " & lcParametro10Desde)
            'loComandoSeleccionar.AppendLine("               AND " & lcParametro10Hasta)
            'loComandoSeleccionar.AppendLine(" GROUP BY DATEPART(YEAR, Devoluciones_Proveedores.Fec_Ini), DATEPART(MONTH, Devoluciones_Proveedores.Fec_Ini) ")
            'loComandoSeleccionar.AppendLine(" ORDER BY DATEPART(YEAR, Devoluciones_Proveedores.Fec_Ini), DATEPART(MONTH, Devoluciones_Proveedores.Fec_Ini) ")




            'loComandoSeleccionar.AppendLine(" ")
            'loComandoSeleccionar.AppendLine("   SELECT ")
            'loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            'loComandoSeleccionar.AppendLine("   	1 AS Mes,")
            'loComandoSeleccionar.AppendLine("   	0 AS MontoDevoluciones_Proveedores")
            'loComandoSeleccionar.AppendLine("   INTO #TempDevoluciones_Proveedores2")
            'loComandoSeleccionar.AppendLine("   UNION ALL")
            'loComandoSeleccionar.AppendLine("   SELECT ")
            'loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            'loComandoSeleccionar.AppendLine("   	2 AS Mes,")
            'loComandoSeleccionar.AppendLine("   	0 AS MontoDevoluciones_Proveedores")
            'loComandoSeleccionar.AppendLine("   UNION ALL")
            'loComandoSeleccionar.AppendLine("   SELECT ")
            'loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            'loComandoSeleccionar.AppendLine("   	3 AS Mes,")
            'loComandoSeleccionar.AppendLine("   	0 AS MontoDevoluciones_Proveedores")
            'loComandoSeleccionar.AppendLine("   UNION ALL")
            'loComandoSeleccionar.AppendLine("   SELECT ")
            'loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            'loComandoSeleccionar.AppendLine("   	4 AS Mes,")
            'loComandoSeleccionar.AppendLine("   	0 AS MontoDevoluciones_Proveedores")
            'loComandoSeleccionar.AppendLine("   UNION ALL")
            'loComandoSeleccionar.AppendLine("   SELECT ")
            'loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            'loComandoSeleccionar.AppendLine("   	5 AS Mes,")
            'loComandoSeleccionar.AppendLine("   	0 AS MontoDevoluciones_Proveedores")
            'loComandoSeleccionar.AppendLine("   UNION ALL")
            'loComandoSeleccionar.AppendLine("   SELECT ")
            'loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            'loComandoSeleccionar.AppendLine("   	6 AS Mes,")
            'loComandoSeleccionar.AppendLine("   	0 AS MontoDevoluciones_Proveedores")
            'loComandoSeleccionar.AppendLine("   UNION ALL")
            'loComandoSeleccionar.AppendLine("   SELECT ")
            'loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            'loComandoSeleccionar.AppendLine("   	7 AS Mes,")
            'loComandoSeleccionar.AppendLine("   	0 AS MontoDevoluciones_Proveedores")
            'loComandoSeleccionar.AppendLine("   UNION ALL")
            'loComandoSeleccionar.AppendLine("   SELECT ")
            'loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            'loComandoSeleccionar.AppendLine("   	8 AS Mes,")
            'loComandoSeleccionar.AppendLine("   	0 AS MontoDevoluciones_Proveedores")
            'loComandoSeleccionar.AppendLine("   UNION ALL")
            'loComandoSeleccionar.AppendLine("   SELECT ")
            'loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            'loComandoSeleccionar.AppendLine("   	9 AS Mes,")
            'loComandoSeleccionar.AppendLine("   	0 AS MontoDevoluciones_Proveedores")
            'loComandoSeleccionar.AppendLine("   UNION ALL")
            'loComandoSeleccionar.AppendLine("   SELECT ")
            'loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            'loComandoSeleccionar.AppendLine("   	10 AS Mes,")
            'loComandoSeleccionar.AppendLine("   	0 AS MontoDevoluciones_Proveedores")
            'loComandoSeleccionar.AppendLine("   UNION ALL")
            'loComandoSeleccionar.AppendLine("   SELECT ")
            'loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            'loComandoSeleccionar.AppendLine("   	11 AS Mes,")
            'loComandoSeleccionar.AppendLine("   	0 AS MontoDevoluciones_Proveedores")
            'loComandoSeleccionar.AppendLine("   UNION ALL")
            'loComandoSeleccionar.AppendLine("   SELECT ")
            'loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            'loComandoSeleccionar.AppendLine("   	12 AS Mes,")
            'loComandoSeleccionar.AppendLine("   	0 AS MontoDevoluciones_Proveedores")
            'loComandoSeleccionar.AppendLine("   UNION ALL")
            'loComandoSeleccionar.AppendLine("   SELECT ")
            'loComandoSeleccionar.AppendLine("   	Año,")
            'loComandoSeleccionar.AppendLine("   	Mes,")
            'loComandoSeleccionar.AppendLine("   	MontoDevoluciones_Proveedores")
            'loComandoSeleccionar.AppendLine("   FROM #TempDevoluciones_Proveedores")
            'loComandoSeleccionar.AppendLine(" ")
            'loComandoSeleccionar.AppendLine("  SELECT ")
            'loComandoSeleccionar.AppendLine("   	Año,")
            'loComandoSeleccionar.AppendLine("   	Mes,")
            'loComandoSeleccionar.AppendLine("   	SUM(MontoDevoluciones_Proveedores) AS MontoDevoluciones_Proveedores")
            'loComandoSeleccionar.AppendLine("  INTO #TempDevoluciones_Proveedores3")
            'loComandoSeleccionar.AppendLine("  FROM #TempDevoluciones_Proveedores2")
            'loComandoSeleccionar.AppendLine("  GROUP BY Año,Mes")
            'loComandoSeleccionar.AppendLine("  order BY 2")
            'loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine(" ---- Devoluciones Clientes")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine(" SELECT")
            loComandoSeleccionar.AppendLine("   	DATEPART(YEAR, Devoluciones_Clientes.Fec_Ini) AS Año, ")
            loComandoSeleccionar.AppendLine("   	DATEPART(MONTH, Devoluciones_Clientes.Fec_Ini) AS Mes, ")
            loComandoSeleccionar.AppendLine("   	CASE  ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Devoluciones_Clientes.Fec_Ini) = 1 THEN SUM(Renglones_dClientes.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Devoluciones_Clientes.Fec_Ini) = 2 THEN SUM(Renglones_dClientes.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Devoluciones_Clientes.Fec_Ini) = 3 THEN SUM(Renglones_dClientes.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Devoluciones_Clientes.Fec_Ini) = 4 THEN SUM(Renglones_dClientes.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Devoluciones_Clientes.Fec_Ini) = 5 THEN SUM(Renglones_dClientes.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Devoluciones_Clientes.Fec_Ini) = 6 THEN SUM(Renglones_dClientes.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Devoluciones_Clientes.Fec_Ini) = 7 THEN SUM(Renglones_dClientes.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Devoluciones_Clientes.Fec_Ini) = 8 THEN SUM(Renglones_dClientes.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Devoluciones_Clientes.Fec_Ini) = 9 THEN SUM(Renglones_dClientes.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Devoluciones_Clientes.Fec_Ini) = 10 THEN SUM(Renglones_dClientes.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Devoluciones_Clientes.Fec_Ini) = 11 THEN SUM(Renglones_dClientes.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Devoluciones_Clientes.Fec_Ini) = 12 THEN SUM(Renglones_dClientes.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		ELSE 0 ")
            loComandoSeleccionar.AppendLine("   	END AS MontoDevoluciones_Clientes ")
            loComandoSeleccionar.AppendLine("   INTO #TempDevoluciones_Clientes ")
            loComandoSeleccionar.AppendLine("   FROM Devoluciones_Clientes ")
            loComandoSeleccionar.AppendLine("   JOIN Renglones_dClientes ON Devoluciones_Clientes.Documento = Renglones_dClientes.Documento ")
            loComandoSeleccionar.AppendLine("   JOIN Articulos ON Articulos.Cod_Art = Renglones_dClientes.Cod_Art ")
            loComandoSeleccionar.AppendLine(" WHERE         ")
            loComandoSeleccionar.AppendLine("      			DATEPART(YEAR, Devoluciones_Clientes.Fec_Ini) = " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine(" 				AND Renglones_dClientes.Cod_Art between " & lcParametro1Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro1Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Devoluciones_Clientes.Cod_Cli between " & lcParametro2Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro2Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Devoluciones_Clientes.Cod_Ven between " & lcParametro3Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro3Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Articulos.Cod_Dep between " & lcParametro4Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro4Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Articulos.Cod_Tip between " & lcParametro5Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro5Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Articulos.Cod_Cla between " & lcParametro6Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro6Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Devoluciones_Clientes.Status IN (" & lcParametro7Desde & ")")

            If lcParametro9Desde = "Igual" Then
                loComandoSeleccionar.AppendLine(" 				AND Devoluciones_Clientes.Cod_Rev between " & lcParametro8Desde)
            Else
                loComandoSeleccionar.AppendLine(" 				AND Devoluciones_Clientes.Cod_Rev NOT between " & lcParametro8Desde)
            End If
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro8Hasta)
            loComandoSeleccionar.AppendLine("               AND Devoluciones_Clientes.Cod_Suc between " & lcParametro10Desde)
            loComandoSeleccionar.AppendLine("               AND " & lcParametro10Hasta)
            loComandoSeleccionar.AppendLine(" GROUP BY DATEPART(YEAR, Devoluciones_Clientes.Fec_Ini), DATEPART(MONTH, Devoluciones_Clientes.Fec_Ini) ")
            loComandoSeleccionar.AppendLine(" ORDER BY DATEPART(YEAR, Devoluciones_Clientes.Fec_Ini), DATEPART(MONTH, Devoluciones_Clientes.Fec_Ini) ")


            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	1 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoDevoluciones_Clientes")
            loComandoSeleccionar.AppendLine("   INTO #TempDevoluciones_Clientes2")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	2 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoDevoluciones_Clientes")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	3 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoDevoluciones_Clientes")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	4 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoDevoluciones_Clientes")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	5 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoDevoluciones_Clientes")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	6 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoDevoluciones_Clientes")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	7 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoDevoluciones_Clientes")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	8 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoDevoluciones_Clientes")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	9 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoDevoluciones_Clientes")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	10 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoDevoluciones_Clientes")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	11 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoDevoluciones_Clientes")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	12 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoDevoluciones_Clientes")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	Año,")
            loComandoSeleccionar.AppendLine("   	Mes,")
            loComandoSeleccionar.AppendLine("   	MontoDevoluciones_Clientes")
            loComandoSeleccionar.AppendLine("   FROM #TempDevoluciones_Clientes")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine("  SELECT ")
            loComandoSeleccionar.AppendLine("   	Año,")
            loComandoSeleccionar.AppendLine("   	Mes,")
            loComandoSeleccionar.AppendLine("   	SUM(MontoDevoluciones_Clientes) AS MontoDevoluciones_Clientes")
            loComandoSeleccionar.AppendLine("  INTO #TempDevoluciones_Clientes3")
            loComandoSeleccionar.AppendLine("  FROM #TempDevoluciones_Clientes2")
            loComandoSeleccionar.AppendLine("  GROUP BY Año,Mes")
            loComandoSeleccionar.AppendLine("  order BY 2")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine(" ----Pediddos")
            loComandoSeleccionar.AppendLine(" SELECT")
            loComandoSeleccionar.AppendLine("   	DATEPART(YEAR, Pedidos.Fec_Ini) AS Año, ")
            loComandoSeleccionar.AppendLine("   	DATEPART(MONTH, Pedidos.Fec_Ini) AS Mes, ")
            loComandoSeleccionar.AppendLine("   	CASE  ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Pedidos.Fec_Ini) = 1 THEN SUM(Renglones_Pedidos.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Pedidos.Fec_Ini) = 2 THEN SUM(Renglones_Pedidos.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Pedidos.Fec_Ini) = 3 THEN SUM(Renglones_Pedidos.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Pedidos.Fec_Ini) = 4 THEN SUM(Renglones_Pedidos.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Pedidos.Fec_Ini) = 5 THEN SUM(Renglones_Pedidos.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Pedidos.Fec_Ini) = 6 THEN SUM(Renglones_Pedidos.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Pedidos.Fec_Ini) = 7 THEN SUM(Renglones_Pedidos.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Pedidos.Fec_Ini) = 8 THEN SUM(Renglones_Pedidos.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Pedidos.Fec_Ini) = 9 THEN SUM(Renglones_Pedidos.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Pedidos.Fec_Ini) = 10 THEN SUM(Renglones_Pedidos.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Pedidos.Fec_Ini) = 11 THEN SUM(Renglones_Pedidos.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Pedidos.Fec_Ini) = 12 THEN SUM(Renglones_Pedidos.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		ELSE 0 ")
            loComandoSeleccionar.AppendLine("   	END AS MontoPedidos ")
            loComandoSeleccionar.AppendLine("   INTO #TempPedidos ")
            loComandoSeleccionar.AppendLine("   FROM Pedidos ")
            loComandoSeleccionar.AppendLine("   JOIN Renglones_Pedidos ON Pedidos.Documento = Renglones_Pedidos.Documento ")
            loComandoSeleccionar.AppendLine("   JOIN Articulos ON Articulos.Cod_Art = Renglones_Pedidos.Cod_Art ")
            loComandoSeleccionar.AppendLine(" WHERE         ")
            loComandoSeleccionar.AppendLine("      			DATEPART(YEAR, Pedidos.Fec_Ini) = " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine(" 				AND Renglones_Pedidos.Cod_Art between " & lcParametro1Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro1Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Pedidos.Cod_Cli between " & lcParametro2Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro2Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Pedidos.Cod_Ven between " & lcParametro3Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro3Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Articulos.Cod_Dep between " & lcParametro4Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro4Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Articulos.Cod_Tip between " & lcParametro5Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro5Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Articulos.Cod_Cla between " & lcParametro6Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro6Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Pedidos.Status IN (" & lcParametro7Desde & ")")

            If lcParametro9Desde = "Igual" Then
                loComandoSeleccionar.AppendLine(" 				AND Pedidos.Cod_Rev between " & lcParametro8Desde)
            Else
                loComandoSeleccionar.AppendLine(" 				AND Pedidos.Cod_Rev NOT between " & lcParametro8Desde)
            End If
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro8Hasta)
            loComandoSeleccionar.AppendLine("               AND Pedidos.Cod_Suc between " & lcParametro10Desde)
            loComandoSeleccionar.AppendLine("               AND " & lcParametro10Hasta)
            loComandoSeleccionar.AppendLine(" GROUP BY DATEPART(YEAR, Pedidos.Fec_Ini), DATEPART(MONTH, Pedidos.Fec_Ini) ")
            loComandoSeleccionar.AppendLine(" ORDER BY DATEPART(YEAR, Pedidos.Fec_Ini), DATEPART(MONTH, Pedidos.Fec_Ini) ")


            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	1 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoPedidos")
            loComandoSeleccionar.AppendLine("   INTO #TempPedidos2")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	2 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoPedidos")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	3 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoPedidos")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	4 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoPedidos")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	5 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoPedidos")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	6 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoPedidos")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	7 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoPedidos")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	8 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoPedidos")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	9 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoPedidos")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	10 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoPedidos")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	11 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoPedidos")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	12 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoPedidos")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	Año,")
            loComandoSeleccionar.AppendLine("   	Mes,")
            loComandoSeleccionar.AppendLine("   	MontoPedidos")
            loComandoSeleccionar.AppendLine("   FROM #TempPedidos")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine("  SELECT ")
            loComandoSeleccionar.AppendLine("   	Año,")
            loComandoSeleccionar.AppendLine("   	Mes,")
            loComandoSeleccionar.AppendLine("   	SUM(MontoPedidos) AS MontoPedidos")
            loComandoSeleccionar.AppendLine("  INTO #TempPedidos3")
            loComandoSeleccionar.AppendLine("  FROM #TempPedidos2")
            loComandoSeleccionar.AppendLine("  GROUP BY Año,Mes")
            loComandoSeleccionar.AppendLine("  order BY 2")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine(" ----------Facturas")
            loComandoSeleccionar.AppendLine("   SELECT")
            loComandoSeleccionar.AppendLine("   	DATEPART(YEAR, Facturas.Fec_Ini) AS Año, ")
            loComandoSeleccionar.AppendLine("   	DATEPART(MONTH, Facturas.Fec_Ini) AS Mes, ")
            loComandoSeleccionar.AppendLine("   	CASE  ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Facturas.Fec_Ini) = 1 THEN SUM(Renglones_Facturas.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Facturas.Fec_Ini) = 2 THEN SUM(Renglones_Facturas.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Facturas.Fec_Ini) = 3 THEN SUM(Renglones_Facturas.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Facturas.Fec_Ini) = 4 THEN SUM(Renglones_Facturas.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Facturas.Fec_Ini) = 5 THEN SUM(Renglones_Facturas.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Facturas.Fec_Ini) = 6 THEN SUM(Renglones_Facturas.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Facturas.Fec_Ini) = 7 THEN SUM(Renglones_Facturas.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Facturas.Fec_Ini) = 8 THEN SUM(Renglones_Facturas.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Facturas.Fec_Ini) = 9 THEN SUM(Renglones_Facturas.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Facturas.Fec_Ini) = 10 THEN SUM(Renglones_Facturas.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Facturas.Fec_Ini) = 11 THEN SUM(Renglones_Facturas.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		WHEN DATEPART(MONTH, Facturas.Fec_Ini) = 12 THEN SUM(Renglones_Facturas.Mon_Net) ")
            loComandoSeleccionar.AppendLine("   		ELSE 0 ")
            loComandoSeleccionar.AppendLine("   	END AS MontoFacturas ")
            loComandoSeleccionar.AppendLine("   INTO #TempFacturas ")
            loComandoSeleccionar.AppendLine("   FROM Facturas ")
            loComandoSeleccionar.AppendLine("   JOIN Renglones_Facturas ON Facturas.Documento = Renglones_Facturas.Documento ")
            loComandoSeleccionar.AppendLine("   JOIN Articulos ON Articulos.Cod_Art = Renglones_Facturas.Cod_Art ")
            loComandoSeleccionar.AppendLine(" WHERE         ")
            loComandoSeleccionar.AppendLine("      			DATEPART(YEAR, Facturas.Fec_Ini) = " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine(" 				AND Renglones_Facturas.Cod_Art between " & lcParametro1Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro1Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Facturas.Cod_Cli between " & lcParametro2Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro2Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Facturas.Cod_Ven between " & lcParametro3Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro3Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Articulos.Cod_Dep between " & lcParametro4Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro4Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Articulos.Cod_Tip between " & lcParametro5Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro5Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Articulos.Cod_Cla between " & lcParametro6Desde)
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro6Hasta)
            loComandoSeleccionar.AppendLine(" 				AND Facturas.Status IN (" & lcParametro7Desde & ")")

            If lcParametro9Desde = "Igual" Then
                loComandoSeleccionar.AppendLine(" 				AND Facturas.Cod_Rev between " & lcParametro8Desde)
            Else
                loComandoSeleccionar.AppendLine(" 				AND Facturas.Cod_Rev NOT between " & lcParametro8Desde)
            End If
            loComandoSeleccionar.AppendLine(" 				AND " & lcParametro8Hasta)
            loComandoSeleccionar.AppendLine("               AND Facturas.Cod_Suc between " & lcParametro10Desde)
            loComandoSeleccionar.AppendLine("               AND " & lcParametro10Hasta)
            loComandoSeleccionar.AppendLine(" GROUP BY DATEPART(YEAR, Facturas.Fec_Ini), DATEPART(MONTH, Facturas.Fec_Ini) ")
            loComandoSeleccionar.AppendLine(" ORDER BY DATEPART(YEAR, Facturas.Fec_Ini), DATEPART(MONTH, Facturas.Fec_Ini) ")


            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	1 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoFacturas")
            loComandoSeleccionar.AppendLine("   INTO #TempFacturas2")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	2 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoFacturas")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	3 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoFacturas")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	4 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoFacturas")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	5 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoFacturas")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	6 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoFacturas")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	7 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoFacturas")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	8 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoFacturas")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	9 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoFacturas")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	10 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoFacturas")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	11 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoFacturas")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	" & lcParametro0Desde & " AS Año,")
            loComandoSeleccionar.AppendLine("   	12 AS Mes,")
            loComandoSeleccionar.AppendLine("   	0 AS MontoFacturas")
            loComandoSeleccionar.AppendLine("   UNION ALL")
            loComandoSeleccionar.AppendLine("   SELECT ")
            loComandoSeleccionar.AppendLine("   	Año,")
            loComandoSeleccionar.AppendLine("   	Mes,")
            loComandoSeleccionar.AppendLine("   	MontoFacturas")
            loComandoSeleccionar.AppendLine("   FROM #TempFacturas")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine(" SELECT ")
            loComandoSeleccionar.AppendLine("   	Año,")
            loComandoSeleccionar.AppendLine("   	Mes,")
            loComandoSeleccionar.AppendLine("   	SUM(MontoFacturas) AS MontoFacturas")
            loComandoSeleccionar.AppendLine("  INTO #TempFacturas3")
            loComandoSeleccionar.AppendLine("  FROM #TempFacturas2")
            loComandoSeleccionar.AppendLine("  GROUP BY Año,Mes")
            loComandoSeleccionar.AppendLine("  order BY 2")
            loComandoSeleccionar.AppendLine("   ")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine(" -------union de todas las tablas nivel 3")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine(" SELECT ")
            loComandoSeleccionar.AppendLine(" 			#TempFacturas3.Año,")
            loComandoSeleccionar.AppendLine(" 			#TempFacturas3.Mes,")
            loComandoSeleccionar.AppendLine(" 			#TempFacturas3.MontoFacturas AS Facturas,")
            loComandoSeleccionar.AppendLine(" 			#TempPedidos3.MontoPedidos AS Pedidos,")
            loComandoSeleccionar.AppendLine(" 			#TempCotizaciones3.MontoCotizaciones AS Cotizaciones,")
            loComandoSeleccionar.AppendLine(" 			#TempDevoluciones_Clientes3.MontoDevoluciones_Clientes AS Devoluciones,")
            'loComandoSeleccionar.AppendLine(" 			#TempDevoluciones_Proveedores3.MontoDevoluciones_Proveedores,")
            loComandoSeleccionar.AppendLine(" 			#TempCobros3.MontoCobrados AS Cobros")
            loComandoSeleccionar.AppendLine(" FROM #TempFacturas3")
            loComandoSeleccionar.AppendLine(" JOIN #TempCobros3 ON #TempCobros3.Año = #TempFacturas3.Año AND #TempCobros3.Mes = #TempFacturas3.Mes")
            loComandoSeleccionar.AppendLine(" JOIN #TempPedidos3 ON #TempPedidos3.Año = #TempFacturas3.Año AND #TempPedidos3.Mes = #TempFacturas3.Mes")
            loComandoSeleccionar.AppendLine(" JOIN #TempDevoluciones_Clientes3 ON #TempDevoluciones_Clientes3.Año = #TempFacturas3.Año AND #TempDevoluciones_Clientes3.Mes = #TempFacturas3.Mes")
            'loComandoSeleccionar.AppendLine(" JOIN #TempDevoluciones_Proveedores3 ON #TempDevoluciones_Proveedores3.Año = #TempFacturas3.Año AND #TempDevoluciones_Proveedores3.Mes = #TempFacturas3.Mes")
            loComandoSeleccionar.AppendLine(" JOIN #TempCotizaciones3 ON #TempCotizaciones3.Año = #TempFacturas3.Año AND #TempCotizaciones3.Mes = #TempFacturas3.Mes")

            Dim lcConexion As String = ""
            Dim laDatosReporte As DataSet

            If Not Me.IsPostBack Then

                lcConexion = goDatos.pcCadenaConexionAdministrativo()

                laDatosReporte = mObtenerTodosLocal(lcConexion.ToString(), loComandoSeleccionar.ToString(), "curReportes")
                Me.poResultado = laDatosReporte

            Else

                laDatosReporte = Me.poResultado

            End If

            'Dim loServicios As New cusDatos.goDatos
            'Dim laDatosReporte As DataSet = loServicios.mObtenerTodosSinEsquema(loComandoSeleccionar.ToString, "curReportes")

            loObjetoReporte = cusAplicacion.goReportes.mCargarReporte("grOperaciones_Mensuales", laDatosReporte)

            '-------------------------------------------------------------------------------------------------------
            ' Verificando si el select (tabla nº0) trae registros
            '-------------------------------------------------------------------------------------------------------

            If laDatosReporte.Tables(0).Rows.Count <= 0 Then
                Me.WbcAdministradorMensajeModal.mMostrarMensajeModal("Información", _
                                          "No se Encontraron Registros para los Parámetros Especificados. ", _
                                           vis3Controles.wbcAdministradorMensajeModal.enumTipoMensaje.KN_Informacion, _
                                           "350px", _
                                           "200px")
            End If



            Me.mTraducirReporte(loObjetoReporte)
            Me.mFormatearCamposReporte(loObjetoReporte)
            Me.crvgrOperaciones_Mensuales.ReportSource = loObjetoReporte

        Catch loExcepcion As Exception

            Me.WbcAdministradorMensajeModal.mMostrarMensajeModal("Error", _
                          "No se pudo Completar el Proceso: " & loExcepcion.Message, _
                           vis3Controles.wbcAdministradorMensajeModal.enumTipoMensaje.KN_Error, _
                           "auto", _
                           "auto")

        End Try

    End Sub

    Protected Sub Page_Unload(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Unload
        Try

            loObjetoReporte.Close()

        Catch loExcepcion As Exception


        End Try
    End Sub

End Class
'-------------------------------------------------------------------------------------------'
' Fin del codigo
'-------------------------------------------------------------------------------------------'
' CMS: 22/04/10: Codigo inicial
'-------------------------------------------------------------------------------------------'
' RJG: 05/12/14: Se ajustó el layout para que quepa en una sola página.                     '
'-------------------------------------------------------------------------------------------'
