'-------------------------------------------------------------------------------------------'
' Inicio del codigo
'-------------------------------------------------------------------------------------------'
' Importando librerias 
'-------------------------------------------------------------------------------------------'
Imports System.Data

'-------------------------------------------------------------------------------------------'
' Inicio de clase "rAnalisis_tUnidades"
'-------------------------------------------------------------------------------------------'
Partial Class rAnalisis_tUnidades
    Inherits vis2formularios.frmReporte

    Dim loObjetoReporte As CrystalDecisions.CrystalReports.Engine.ReportDocument

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load

        Dim lcParametro0Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(0), goServicios.enuOpcionesRedondeo.KN_FechaInicioDelDia)
        Dim lcParametro0Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(0), goServicios.enuOpcionesRedondeo.KN_FechaFinDelDia)
        Dim lcParametro1Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(1), goServicios.enuOpcionesRedondeo.KN_FechaInicioDelDia)
        'Dim lcParametro1Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(1), goServicios.enuOpcionesRedondeo.KN_FechaFinDelDia)
        Dim lcParametro2Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(2), goServicios.enuOpcionesRedondeo.KN_FechaInicioDelDia)
        Dim lcParametro2Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(2), goServicios.enuOpcionesRedondeo.KN_FechaFinDelDia)
        Dim lcParametro3Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(3), goServicios.enuOpcionesRedondeo.KN_FechaInicioDelDia)
        Dim lcParametro3Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(3), goServicios.enuOpcionesRedondeo.KN_FechaFinDelDia)
        Dim lcParametro4Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(4), goServicios.enuOpcionesRedondeo.KN_FechaInicioDelDia)
        Dim lcParametro4Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(4), goServicios.enuOpcionesRedondeo.KN_FechaFinDelDia)
        Dim lcParametro5Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(5), goServicios.enuOpcionesRedondeo.KN_FechaInicioDelDia)
        Dim lcParametro5Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(5), goServicios.enuOpcionesRedondeo.KN_FechaFinDelDia)
        Dim lcParametro6Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(6), goServicios.enuOpcionesRedondeo.KN_FechaInicioDelDia)
        Dim lcParametro6Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(6), goServicios.enuOpcionesRedondeo.KN_FechaFinDelDia)
        Dim lcParametro7Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(7), goServicios.enuOpcionesRedondeo.KN_FechaInicioDelDia)
        Dim lcParametro7Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(7), goServicios.enuOpcionesRedondeo.KN_FechaFinDelDia)
        Dim lcParametro8Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(8), goServicios.enuOpcionesRedondeo.KN_FechaInicioDelDia)
        Dim lcParametro8Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(8), goServicios.enuOpcionesRedondeo.KN_FechaFinDelDia)
        Dim lcParametro9Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(9), goServicios.enuOpcionesRedondeo.KN_FechaInicioDelDia)
        Dim lcParametro9Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(9), goServicios.enuOpcionesRedondeo.KN_FechaFinDelDia)
        Dim lcParametro10Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(10), goServicios.enuOpcionesRedondeo.KN_FechaInicioDelDia)
        Dim lcParametro10Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(10), goServicios.enuOpcionesRedondeo.KN_FechaFinDelDia)
        Dim lcParametro11Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(11), goServicios.enuOpcionesRedondeo.KN_FechaInicioDelDia)
        Dim lcParametro11Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(11), goServicios.enuOpcionesRedondeo.KN_FechaFinDelDia)


        Dim lcOrdenamiento As String = cusAplicacion.goReportes.pcOrden

        Try

            Dim loComandoSeleccionar As New StringBuilder()
            
            If lcParametro1Desde = "'0'" Then
				lcParametro1Desde = "'2010'"
			End If


			loComandoSeleccionar.AppendLine("  SELECT	 ")
			loComandoSeleccionar.AppendLine("  		SUM(CASE WHEN DATEPART(mm, Ajustes.Fec_Ini) <= 3 THEN  Renglones_Ajustes.Can_Art1 ELSE 0 END ) AS	Can_Sal1, ")
			loComandoSeleccionar.AppendLine("  		SUM(CASE WHEN DATEPART(mm, Ajustes.Fec_Ini) > 3 AND DATEPART(mm, Ajustes.Fec_Ini) <= 6 THEN Renglones_Ajustes.Can_Art1 ELSE 0 END ) AS	Can_Sal2,  ")
			loComandoSeleccionar.AppendLine("  		SUM(CASE WHEN DATEPART(mm, Ajustes.Fec_Ini) > 6 AND DATEPART(mm, Ajustes.Fec_Ini) <= 9 THEN Renglones_Ajustes.Can_Art1 ELSE 0 END ) AS	Can_Sal3,  ")
			loComandoSeleccionar.AppendLine("  		SUM(CASE WHEN DATEPART(mm, Ajustes.Fec_Ini) > 9 THEN Renglones_Ajustes.Can_Art1 ELSE 0 END ) AS	Can_Sal4 , ")
			loComandoSeleccionar.AppendLine("  		Renglones_Ajustes.Cod_Art  ")
			loComandoSeleccionar.AppendLine("  INTO #tempSalidas  ")
			loComandoSeleccionar.AppendLine("  FROM	Ajustes,   ")
			loComandoSeleccionar.AppendLine("  		Renglones_Ajustes,   ")
			loComandoSeleccionar.AppendLine("  		Articulos   ")
			loComandoSeleccionar.AppendLine("  WHERE	Ajustes.Documento = Renglones_Ajustes.Documento   ")
			loComandoSeleccionar.AppendLine("  		And Articulos.Cod_Art =	Renglones_Ajustes.Cod_Art   ")
			loComandoSeleccionar.AppendLine("  		And Ajustes.Status					=	'Confirmado'   ")
			loComandoSeleccionar.AppendLine("  		And Renglones_Ajustes.Tipo			=	'Salida'   ")
			loComandoSeleccionar.AppendLine("			And Articulos.Cod_Art				BETWEEN " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("			And DATEPART(YEAR,Ajustes.Fec_Ini)	= " & lcParametro1Desde )
            loComandoSeleccionar.AppendLine("			And Renglones_Ajustes.Cod_Alm		BETWEEN " & lcParametro2Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro2Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Dep				BETWEEN " & lcParametro3Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro3Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Sec				BETWEEN " & lcParametro4Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro4Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Mar				BETWEEN " & lcParametro5Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro5Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Cla				BETWEEN " & lcParametro6Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro6Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Tip				BETWEEN " & lcParametro7Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro7Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Pro				BETWEEN " & lcParametro8Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro8Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Uni1				BETWEEN " & lcParametro9Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro9Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Suc				BETWEEN " & lcParametro10Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro10Hasta)
            loComandoSeleccionar.AppendLine("           And Articulos.Cod_Ubi    Between " & lcParametro11Desde)
            loComandoSeleccionar.AppendLine("           And " & lcParametro11Hasta)
			loComandoSeleccionar.AppendLine("  GROUP BY Renglones_Ajustes.Cod_Art  ")
			loComandoSeleccionar.AppendLine("  ORDER BY Renglones_Ajustes.Cod_Art  ")
			loComandoSeleccionar.AppendLine("    ")
			
			
			
			loComandoSeleccionar.AppendLine("  SELECT	 ")
			loComandoSeleccionar.AppendLine("  		SUM(CASE WHEN DATEPART(mm, Ajustes.Fec_Ini) <= 3 THEN  Renglones_Ajustes.Can_Art1 ELSE 0 END ) AS	Can_Ent1, ")
			loComandoSeleccionar.AppendLine("  		SUM(CASE WHEN DATEPART(mm, Ajustes.Fec_Ini) > 3 AND DATEPART(mm, Ajustes.Fec_Ini) <= 6 THEN Renglones_Ajustes.Can_Art1 ELSE 0 END ) AS	Can_Ent2,  ")
			loComandoSeleccionar.AppendLine("  		SUM(CASE WHEN DATEPART(mm, Ajustes.Fec_Ini) > 6 AND DATEPART(mm, Ajustes.Fec_Ini) <= 9 THEN Renglones_Ajustes.Can_Art1 ELSE 0 END ) AS	Can_Ent3,  ")
			loComandoSeleccionar.AppendLine("  		SUM(CASE WHEN DATEPART(mm, Ajustes.Fec_Ini) > 9 THEN Renglones_Ajustes.Can_Art1 ELSE 0 END ) AS	Can_Ent4 , ")
			loComandoSeleccionar.AppendLine("  		Renglones_Ajustes.Cod_Art  ")
			loComandoSeleccionar.AppendLine("  INTO #tempEntradas  ")
			loComandoSeleccionar.AppendLine("  FROM	Ajustes,   ")
			loComandoSeleccionar.AppendLine("  		Renglones_Ajustes,   ")
			loComandoSeleccionar.AppendLine("  		Articulos   ")
			loComandoSeleccionar.AppendLine("  WHERE	Ajustes.Documento = Renglones_Ajustes.Documento   ")
			loComandoSeleccionar.AppendLine("  		And Articulos.Cod_Art =	Renglones_Ajustes.Cod_Art   ")
			loComandoSeleccionar.AppendLine("  		And Ajustes.Status = 'Confirmado'   ")
			loComandoSeleccionar.AppendLine("  		And Renglones_Ajustes.Tipo = 'Entrada'   ")
			loComandoSeleccionar.AppendLine("			And Articulos.Cod_Art				BETWEEN " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("			And DATEPART(YEAR,Ajustes.Fec_Ini)	= " & lcParametro1Desde )
            loComandoSeleccionar.AppendLine("			And Renglones_Ajustes.Cod_Alm		BETWEEN " & lcParametro2Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro2Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Dep				BETWEEN " & lcParametro3Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro3Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Sec				BETWEEN " & lcParametro4Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro4Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Mar				BETWEEN " & lcParametro5Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro5Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Cla				BETWEEN " & lcParametro6Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro6Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Tip				BETWEEN " & lcParametro7Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro7Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Pro				BETWEEN " & lcParametro8Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro8Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Uni1				BETWEEN " & lcParametro9Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro9Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Suc				BETWEEN " & lcParametro10Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro10Hasta)
            loComandoSeleccionar.AppendLine("           And Articulos.Cod_Ubi    Between " & lcParametro11Desde)
            loComandoSeleccionar.AppendLine("           And " & lcParametro11Hasta)
			loComandoSeleccionar.AppendLine("  GROUP BY Renglones_Ajustes.Cod_Art  ")
			loComandoSeleccionar.AppendLine("  ORDER BY Renglones_Ajustes.Cod_Art  ")
			loComandoSeleccionar.AppendLine("    ")
			loComandoSeleccionar.AppendLine("  ")
			
			
			
			loComandoSeleccionar.AppendLine(" SELECT	Renglones_Entregas.Cod_Art			AS	Cod_Art,  ")
			loComandoSeleccionar.AppendLine("  		SUM(CASE WHEN DATEPART(mm, Entregas.Fec_Ini) <= 3 THEN  Renglones_Entregas.Can_Art1 ELSE 0 END ) AS	Can_Ven1, ")
			loComandoSeleccionar.AppendLine("  		SUM(CASE WHEN DATEPART(mm, Entregas.Fec_Ini) > 3 AND DATEPART(mm, Entregas.Fec_Ini) <= 6 THEN Renglones_Entregas.Can_Art1 ELSE 0 END ) AS	Can_Ven2,  ")
			loComandoSeleccionar.AppendLine("  		SUM(CASE WHEN DATEPART(mm, Entregas.Fec_Ini) > 6 AND DATEPART(mm, Entregas.Fec_Ini) <= 9 THEN Renglones_Entregas.Can_Art1 ELSE 0 END ) AS	Can_Ven3,  ")
			loComandoSeleccionar.AppendLine("  		SUM(CASE WHEN DATEPART(mm, Entregas.Fec_Ini) > 9 THEN Renglones_Entregas.Can_Art1 ELSE 0 END ) AS	Can_Ven4  ")
			loComandoSeleccionar.AppendLine("  INTO		#tempEntradasEntregas  ")
			loComandoSeleccionar.AppendLine("  FROM		Entregas,  ")
			loComandoSeleccionar.AppendLine(" 			Renglones_Entregas,  ")
			loComandoSeleccionar.AppendLine(" 			Articulos  ")
			loComandoSeleccionar.AppendLine("  WHERE		Entregas.Documento					=	Renglones_Entregas.Documento  ")
			loComandoSeleccionar.AppendLine(" 			And Articulos.Cod_Art				=	Renglones_Entregas.Cod_Art  ")
			loComandoSeleccionar.AppendLine(" 				AND Entregas.Status			IN	('Confirmado', 'Afectado', 'Procesado') ")
			loComandoSeleccionar.AppendLine("			And Articulos.Cod_Art				BETWEEN " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("			And DATEPART(YEAR,Entregas.Fec_Ini)	= " & lcParametro1Desde )
            loComandoSeleccionar.AppendLine("			And Renglones_Entregas.Cod_Alm		BETWEEN " & lcParametro2Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro2Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Dep				BETWEEN " & lcParametro3Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro3Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Sec				BETWEEN " & lcParametro4Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro4Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Mar				BETWEEN " & lcParametro5Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro5Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Cla				BETWEEN " & lcParametro6Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro6Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Tip				BETWEEN " & lcParametro7Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro7Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Pro				BETWEEN " & lcParametro8Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro8Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Uni1				BETWEEN " & lcParametro9Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro9Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Suc				BETWEEN " & lcParametro10Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro10Hasta)
            loComandoSeleccionar.AppendLine("           And Articulos.Cod_Ubi    Between " & lcParametro11Desde)
            loComandoSeleccionar.AppendLine("           And " & lcParametro11Hasta)
			loComandoSeleccionar.AppendLine("  GROUP BY Renglones_Entregas.Cod_Art  ")
			loComandoSeleccionar.AppendLine("  ORDER BY Renglones_Entregas.Cod_Art  ")
			loComandoSeleccionar.AppendLine("   ")
			loComandoSeleccionar.AppendLine("  ")
			
			
			
			loComandoSeleccionar.AppendLine(" SELECT	Renglones_Facturas.Cod_Art			AS	Cod_Art,  ")
			loComandoSeleccionar.AppendLine("  		SUM(CASE WHEN DATEPART(mm, Facturas.Fec_Ini) <= 3 THEN  Renglones_Facturas.Can_Art1 ELSE 0 END ) AS	Can_Ven1, ")
			loComandoSeleccionar.AppendLine("  		SUM(CASE WHEN DATEPART(mm, Facturas.Fec_Ini) > 3 AND DATEPART(mm, Facturas.Fec_Ini) <= 6 THEN Renglones_Facturas.Can_Art1 ELSE 0 END ) AS	Can_Ven2,  ")
			loComandoSeleccionar.AppendLine("  		SUM(CASE WHEN DATEPART(mm, Facturas.Fec_Ini) > 6 AND DATEPART(mm, Facturas.Fec_Ini) <= 9 THEN Renglones_Facturas.Can_Art1 ELSE 0 END ) AS	Can_Ven3,  ")
			loComandoSeleccionar.AppendLine("  		SUM(CASE WHEN DATEPART(mm, Facturas.Fec_Ini) > 9 THEN Renglones_Facturas.Can_Art1 ELSE 0 END ) AS	Can_Ven4  ")
			loComandoSeleccionar.AppendLine("  INTO		#tempEntradasFacturas  ")
			loComandoSeleccionar.AppendLine("  FROM		Facturas,  ")
			loComandoSeleccionar.AppendLine(" 			Renglones_Facturas,  ")
			loComandoSeleccionar.AppendLine(" 			Articulos  ")
			loComandoSeleccionar.AppendLine("  WHERE		Facturas.Documento					=	Renglones_Facturas.Documento  ")
			loComandoSeleccionar.AppendLine(" 			And Articulos.Cod_Art				=	Renglones_Facturas.Cod_Art  ")
			loComandoSeleccionar.AppendLine("			AND Facturas.Status				IN ('Confirmado', 'Afectado', 'Procesado')")
			loComandoSeleccionar.AppendLine(" 			And Renglones_Facturas.Tip_Ori		<>	'Entregas'  ")
			loComandoSeleccionar.AppendLine("			And Articulos.Cod_Art				BETWEEN " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("			And DATEPART(YEAR,Facturas.Fec_Ini)	= " & lcParametro1Desde )
            loComandoSeleccionar.AppendLine("			And Renglones_Facturas.Cod_Alm		BETWEEN " & lcParametro2Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro2Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Dep				BETWEEN " & lcParametro3Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro3Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Sec				BETWEEN " & lcParametro4Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro4Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Mar				BETWEEN " & lcParametro5Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro5Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Cla				BETWEEN " & lcParametro6Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro6Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Tip				BETWEEN " & lcParametro7Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro7Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Pro				BETWEEN " & lcParametro8Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro8Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Uni1				BETWEEN " & lcParametro9Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro9Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Suc				BETWEEN " & lcParametro10Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro10Hasta)
            loComandoSeleccionar.AppendLine("           And Articulos.Cod_Ubi    Between " & lcParametro11Desde)
            loComandoSeleccionar.AppendLine("           And " & lcParametro11Hasta)
			loComandoSeleccionar.AppendLine(" GROUP BY Renglones_Facturas.Cod_Art  ")
			loComandoSeleccionar.AppendLine("  ORDER BY Renglones_Facturas.Cod_Art  ")
			loComandoSeleccionar.AppendLine("  ")
			
			loComandoSeleccionar.AppendLine(" SELECT	Renglones_Traslados.Cod_Art			AS	Cod_Art,  ")
			loComandoSeleccionar.AppendLine("  			SUM(CASE WHEN DATEPART(mm, Traslados.Fec_Ini) <= 3 THEN  Renglones_Traslados.Can_Art1 ELSE 0 END ) AS	Can_Ven1, ")
			loComandoSeleccionar.AppendLine("  			SUM(CASE WHEN DATEPART(mm, Traslados.Fec_Ini) > 3 AND DATEPART(mm, Traslados.Fec_Ini) <= 6 THEN Renglones_Traslados.Can_Art1 ELSE 0 END ) AS	Can_Ven2,  ")
			loComandoSeleccionar.AppendLine("  			SUM(CASE WHEN DATEPART(mm, Traslados.Fec_Ini) > 6 AND DATEPART(mm, Traslados.Fec_Ini) <= 9 THEN Renglones_Traslados.Can_Art1 ELSE 0 END ) AS	Can_Ven3,  ")
			loComandoSeleccionar.AppendLine("  			SUM(CASE WHEN DATEPART(mm, Traslados.Fec_Ini) > 9 THEN Renglones_Traslados.Can_Art1 ELSE 0 END ) AS	Can_Ven4  ")
			loComandoSeleccionar.AppendLine("  INTO		#tempSalidasTraslados  ")
			loComandoSeleccionar.AppendLine(" FROM		Traslados, ")
            loComandoSeleccionar.AppendLine("			Renglones_Traslados, ")
            loComandoSeleccionar.AppendLine("			Articulos ")
			loComandoSeleccionar.AppendLine("  WHERE	Traslados.Documento					=	Renglones_Traslados.Documento  ")
			loComandoSeleccionar.AppendLine(" 			And Articulos.Cod_Art				=	Renglones_Traslados.Cod_Art  ")
			loComandoSeleccionar.AppendLine("			AND Traslados.Status		IN ('Confirmado', 'Procesado') ") 
			loComandoSeleccionar.AppendLine("			And Articulos.Cod_Art				BETWEEN " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("			And DATEPART(YEAR,Traslados.Fec_Ini)	= " & lcParametro1Desde )
            loComandoSeleccionar.AppendLine("			And Traslados.Alm_Des				BETWEEN " & lcParametro2Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro2Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Dep				BETWEEN " & lcParametro3Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro3Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Sec				BETWEEN " & lcParametro4Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro4Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Mar				BETWEEN " & lcParametro5Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro5Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Cla				BETWEEN " & lcParametro6Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro6Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Tip				BETWEEN " & lcParametro7Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro7Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Pro				BETWEEN " & lcParametro8Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro8Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Uni1				BETWEEN " & lcParametro9Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro9Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Suc				BETWEEN " & lcParametro10Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro10Hasta)
            loComandoSeleccionar.AppendLine("           And Articulos.Cod_Ubi    Between " & lcParametro11Desde)
            loComandoSeleccionar.AppendLine("           And " & lcParametro11Hasta)
			loComandoSeleccionar.AppendLine(" GROUP BY Renglones_Traslados.Cod_Art  ")
			loComandoSeleccionar.AppendLine("  ORDER BY Renglones_Traslados.Cod_Art  ")
			
			
			loComandoSeleccionar.AppendLine("  ")


			loComandoSeleccionar.AppendLine(" SELECT	Renglones_dProveedores.Cod_Art			AS	Cod_Art,  ")
			loComandoSeleccionar.AppendLine("   		SUM(CASE WHEN DATEPART(mm, Devoluciones_Proveedores.Fec_Ini) <= 3 THEN  Renglones_dProveedores.Can_Art1 ELSE 0 END ) AS	Can_Ven1, ")
			loComandoSeleccionar.AppendLine("   		SUM(CASE WHEN DATEPART(mm, Devoluciones_Proveedores.Fec_Ini) > 3 AND DATEPART(mm, Devoluciones_Proveedores.Fec_Ini) <= 6 THEN Renglones_dProveedores.Can_Art1 ELSE 0 END ) AS	Can_Ven2,  ")
			loComandoSeleccionar.AppendLine("   		SUM(CASE WHEN DATEPART(mm, Devoluciones_Proveedores.Fec_Ini) > 6 AND DATEPART(mm, Devoluciones_Proveedores.Fec_Ini) <= 9 THEN Renglones_dProveedores.Can_Art1 ELSE 0 END ) AS	Can_Ven3,  ")
			loComandoSeleccionar.AppendLine("   		SUM(CASE WHEN DATEPART(mm, Devoluciones_Proveedores.Fec_Ini) > 9 THEN Renglones_dProveedores.Can_Art1 ELSE 0 END ) AS	Can_Ven4  ")
			loComandoSeleccionar.AppendLine("   INTO		#tempSalidaDevolucionProveedor")
			loComandoSeleccionar.AppendLine("   FROM		Devoluciones_Proveedores,  ")
			loComandoSeleccionar.AppendLine("  			Renglones_dProveedores,  ")
			loComandoSeleccionar.AppendLine("  			Articulos  ")
			loComandoSeleccionar.AppendLine("   WHERE		Devoluciones_Proveedores.Documento					=	Renglones_dProveedores.Documento  ")
			loComandoSeleccionar.AppendLine("  			And Articulos.Cod_Art				=	Renglones_dProveedores.Cod_Art  ")
			loComandoSeleccionar.AppendLine("  			And Devoluciones_Proveedores.Status					IN	('Confirmado', 'Afectado', 'Procesado')  ")
			loComandoSeleccionar.AppendLine("			And Articulos.Cod_Art				BETWEEN " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("			And DATEPART(YEAR,Devoluciones_Proveedores.Fec_Ini)	= " & lcParametro1Desde )
            loComandoSeleccionar.AppendLine("			And Renglones_dProveedores.Cod_Alm		BETWEEN " & lcParametro2Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro2Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Dep				BETWEEN " & lcParametro3Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro3Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Sec				BETWEEN " & lcParametro4Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro4Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Mar				BETWEEN " & lcParametro5Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro5Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Cla				BETWEEN " & lcParametro6Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro6Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Tip				BETWEEN " & lcParametro7Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro7Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Pro				BETWEEN " & lcParametro8Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro8Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Uni1				BETWEEN " & lcParametro9Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro9Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Suc				BETWEEN " & lcParametro10Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro10Hasta)
            loComandoSeleccionar.AppendLine("           And Articulos.Cod_Ubi    Between " & lcParametro11Desde)
            loComandoSeleccionar.AppendLine("           And " & lcParametro11Hasta)
			loComandoSeleccionar.AppendLine(" GROUP BY Renglones_dProveedores.Cod_Art  ")
			loComandoSeleccionar.AppendLine("  ORDER BY Renglones_dProveedores.Cod_Art  ")
			loComandoSeleccionar.AppendLine("  ")
			loComandoSeleccionar.AppendLine("  ")
			loComandoSeleccionar.AppendLine(" SELECT Cod_Art, Can_Ven1, Can_Ven2, Can_Ven3, Can_Ven4  ")
			loComandoSeleccionar.AppendLine(" INTO #tempVentasSalida ")
			loComandoSeleccionar.AppendLine(" FROM #tempEntradasEntregas ")
			loComandoSeleccionar.AppendLine(" UNION ALL ")
			loComandoSeleccionar.AppendLine(" SELECT Cod_Art, Can_Ven1, Can_Ven2, Can_Ven3, Can_Ven4 FROM #tempEntradasFacturas ")
			loComandoSeleccionar.AppendLine(" UNION ALL ")
			loComandoSeleccionar.AppendLine(" SELECT Cod_Art, Can_Ven1, Can_Ven2, Can_Ven3, Can_Ven4 FROM #tempSalidaDevolucionProveedor ")
			loComandoSeleccionar.AppendLine(" UNION ALL ")
			loComandoSeleccionar.AppendLine(" SELECT Cod_Art, Can_Ven1, Can_Ven2, Can_Ven3, Can_Ven4 FROM #tempSalidasTraslados ")
			loComandoSeleccionar.AppendLine("  ")
			loComandoSeleccionar.AppendLine(" SELECT  ")
			loComandoSeleccionar.AppendLine(" Cod_Art,  ")
			loComandoSeleccionar.AppendLine(" SUM(Can_Ven1) As Can_Sal1, ")
			loComandoSeleccionar.AppendLine(" SUM(Can_Ven2) As Can_Sal2, ")
			loComandoSeleccionar.AppendLine(" SUM(Can_Ven3) As Can_Sal3, ")
			loComandoSeleccionar.AppendLine(" SUM(Can_Ven4) As Can_Sal4 ")
			loComandoSeleccionar.AppendLine(" INTO #tempVentasSalida2 ")
			loComandoSeleccionar.AppendLine(" FROM #tempVentasSalida ")
			loComandoSeleccionar.AppendLine(" GROUP BY Cod_Art ")
			loComandoSeleccionar.AppendLine("  ")
			loComandoSeleccionar.AppendLine("  ")
			loComandoSeleccionar.AppendLine("  ")
			loComandoSeleccionar.AppendLine(" SELECT	Renglones_Recepciones.Cod_Art			AS	Cod_Art,  ")
			loComandoSeleccionar.AppendLine("  		SUM(CASE WHEN DATEPART(mm, Recepciones.Fec_Ini) <= 3 THEN  Renglones_Recepciones.Can_Art1 ELSE 0 END ) AS	Can_Com1, ")
			loComandoSeleccionar.AppendLine("  		SUM(CASE WHEN DATEPART(mm, Recepciones.Fec_Ini) > 3 AND DATEPART(mm, Recepciones.Fec_Ini) <= 6 THEN Renglones_Recepciones.Can_Art1 ELSE 0 END ) AS	Can_Com2,  ")
			loComandoSeleccionar.AppendLine("  		SUM(CASE WHEN DATEPART(mm, Recepciones.Fec_Ini) > 6 AND DATEPART(mm, Recepciones.Fec_Ini) <= 9 THEN Renglones_Recepciones.Can_Art1 ELSE 0 END ) AS	Can_Com3,  ")
			loComandoSeleccionar.AppendLine("  		SUM(CASE WHEN DATEPART(mm, Recepciones.Fec_Ini) > 9 THEN Renglones_Recepciones.Can_Art1 ELSE 0 END ) AS	Can_Com4  ")
			loComandoSeleccionar.AppendLine("  INTO		#tempEntradasRecepciones  ")
			loComandoSeleccionar.AppendLine("  FROM		Recepciones,  ")
			loComandoSeleccionar.AppendLine(" 			Renglones_Recepciones,  ")
			loComandoSeleccionar.AppendLine(" 			Articulos  ")
			loComandoSeleccionar.AppendLine("  WHERE		Recepciones.Documento					=	Renglones_Recepciones.Documento  ")
			loComandoSeleccionar.AppendLine(" 			And Articulos.Cod_Art				=	Renglones_Recepciones.Cod_Art  ")
			loComandoSeleccionar.AppendLine("			AND Recepciones.Status			IN	('Confirmado', 'Afectado', 'Procesado') ")
			loComandoSeleccionar.AppendLine("			And Articulos.Cod_Art				BETWEEN " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("			And DATEPART(YEAR,Recepciones.Fec_Ini)	= " & lcParametro1Desde )
            loComandoSeleccionar.AppendLine("			And Renglones_Recepciones.Cod_Alm		BETWEEN " & lcParametro2Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro2Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Dep				BETWEEN " & lcParametro3Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro3Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Sec				BETWEEN " & lcParametro4Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro4Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Mar				BETWEEN " & lcParametro5Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro5Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Cla				BETWEEN " & lcParametro6Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro6Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Tip				BETWEEN " & lcParametro7Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro7Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Pro				BETWEEN " & lcParametro8Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro8Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Uni1				BETWEEN " & lcParametro9Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro9Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Suc				BETWEEN " & lcParametro10Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro10Hasta)
            loComandoSeleccionar.AppendLine("           And Articulos.Cod_Ubi    Between " & lcParametro11Desde)
            loComandoSeleccionar.AppendLine("           And " & lcParametro11Hasta)
			loComandoSeleccionar.AppendLine("  GROUP BY Renglones_Recepciones.Cod_Art  ")
			loComandoSeleccionar.AppendLine("  ORDER BY Renglones_Recepciones.Cod_Art  ")
			loComandoSeleccionar.AppendLine("   ")
			loComandoSeleccionar.AppendLine("  ")
			
			
			loComandoSeleccionar.AppendLine(" SELECT	Renglones_Compras.Cod_Art			AS	Cod_Art,  ")
			loComandoSeleccionar.AppendLine("  		SUM(CASE WHEN DATEPART(mm, Compras.Fec_Ini) <= 3 THEN  Renglones_Compras.Can_Art1 ELSE 0 END ) AS	Can_Com1, ")
			loComandoSeleccionar.AppendLine("  		SUM(CASE WHEN DATEPART(mm, Compras.Fec_Ini) > 3 AND DATEPART(mm, Compras.Fec_Ini) <= 6 THEN Renglones_Compras.Can_Art1 ELSE 0 END ) AS	Can_Com2,  ")
			loComandoSeleccionar.AppendLine("  		SUM(CASE WHEN DATEPART(mm, Compras.Fec_Ini) > 6 AND DATEPART(mm, Compras.Fec_Ini) <= 9 THEN Renglones_Compras.Can_Art1 ELSE 0 END ) AS	Can_Com3,  ")
			loComandoSeleccionar.AppendLine("  		SUM(CASE WHEN DATEPART(mm, Compras.Fec_Ini) > 9 THEN Renglones_Compras.Can_Art1 ELSE 0 END ) AS	Can_Com4  ")
			loComandoSeleccionar.AppendLine("  INTO		#tempEntradasCompras  ")
			loComandoSeleccionar.AppendLine("  FROM		Compras,  ")
			loComandoSeleccionar.AppendLine(" 			Renglones_Compras,  ")
			loComandoSeleccionar.AppendLine(" 			Articulos  ")
			loComandoSeleccionar.AppendLine("  WHERE		Compras.Documento					=	Renglones_Compras.Documento  ")
			loComandoSeleccionar.AppendLine(" 			And Articulos.Cod_Art				=	Renglones_Compras.Cod_Art  ")
			loComandoSeleccionar.AppendLine(" 			And Compras.Status					IN ('Confirmado', 'Afectado', 'Procesado')  ")
			loComandoSeleccionar.AppendLine(" 			And Renglones_Compras.Tip_Ori		<>	'Recepciones'  ")
			loComandoSeleccionar.AppendLine("			And Articulos.Cod_Art				BETWEEN " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("			And DATEPART(YEAR,Compras.Fec_Ini)	= " & lcParametro1Desde )
            loComandoSeleccionar.AppendLine("			And Renglones_Compras.Cod_Alm		BETWEEN " & lcParametro2Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro2Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Dep				BETWEEN " & lcParametro3Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro3Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Sec				BETWEEN " & lcParametro4Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro4Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Mar				BETWEEN " & lcParametro5Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro5Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Cla				BETWEEN " & lcParametro6Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro6Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Tip				BETWEEN " & lcParametro7Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro7Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Pro				BETWEEN " & lcParametro8Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro8Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Uni1				BETWEEN " & lcParametro9Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro9Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Suc				BETWEEN " & lcParametro10Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro10Hasta)
            loComandoSeleccionar.AppendLine("           And Articulos.Cod_Ubi    Between " & lcParametro11Desde)
            loComandoSeleccionar.AppendLine("           And " & lcParametro11Hasta)
			loComandoSeleccionar.AppendLine(" GROUP BY Renglones_Compras.Cod_Art  ")
			loComandoSeleccionar.AppendLine("  ORDER BY Renglones_Compras.Cod_Art  ")
			
			loComandoSeleccionar.AppendLine(" SELECT	Renglones_Traslados.Cod_Art			AS	Cod_Art,  ")
			loComandoSeleccionar.AppendLine("  		SUM(CASE WHEN DATEPART(mm, Traslados.Fec_Ini) <= 3 THEN  Renglones_Traslados.Can_Art1 ELSE 0 END ) AS	Can_Com1, ")
			loComandoSeleccionar.AppendLine("  		SUM(CASE WHEN DATEPART(mm, Traslados.Fec_Ini) > 3 AND DATEPART(mm, Traslados.Fec_Ini) <= 6 THEN Renglones_Traslados.Can_Art1 ELSE 0 END ) AS	Can_Com2,  ")
			loComandoSeleccionar.AppendLine("  		SUM(CASE WHEN DATEPART(mm, Traslados.Fec_Ini) > 6 AND DATEPART(mm, Traslados.Fec_Ini) <= 9 THEN Renglones_Traslados.Can_Art1 ELSE 0 END ) AS	Can_Com3,  ")
			loComandoSeleccionar.AppendLine("  		SUM(CASE WHEN DATEPART(mm, Traslados.Fec_Ini) > 9 THEN Renglones_Traslados.Can_Art1 ELSE 0 END ) AS	Can_Com4  ")
			loComandoSeleccionar.AppendLine("  INTO		#tempEntradasTraslados  ")
			loComandoSeleccionar.AppendLine(" FROM		Traslados, ")
            loComandoSeleccionar.AppendLine("			Renglones_Traslados, ")
            loComandoSeleccionar.AppendLine("			Articulos ")
			loComandoSeleccionar.AppendLine("  WHERE	Traslados.Documento					=	Renglones_Traslados.Documento  ")
			loComandoSeleccionar.AppendLine(" 			And Articulos.Cod_Art				=	Renglones_Traslados.Cod_Art  ")
			loComandoSeleccionar.AppendLine("			AND Traslados.Status		IN ('Confirmado', 'Procesado') ") 
			loComandoSeleccionar.AppendLine("			And Articulos.Cod_Art				BETWEEN " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("			And DATEPART(YEAR,Traslados.Fec_Ini)	= " & lcParametro1Desde )
            loComandoSeleccionar.AppendLine("			And Traslados.Alm_Ori				BETWEEN " & lcParametro2Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro2Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Dep				BETWEEN " & lcParametro3Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro3Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Sec				BETWEEN " & lcParametro4Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro4Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Mar				BETWEEN " & lcParametro5Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro5Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Cla				BETWEEN " & lcParametro6Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro6Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Tip				BETWEEN " & lcParametro7Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro7Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Pro				BETWEEN " & lcParametro8Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro8Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Uni1				BETWEEN " & lcParametro9Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro9Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Suc				BETWEEN " & lcParametro10Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro10Hasta)
            loComandoSeleccionar.AppendLine("           And Articulos.Cod_Ubi    Between " & lcParametro11Desde)
            loComandoSeleccionar.AppendLine("           And " & lcParametro11Hasta)
			loComandoSeleccionar.AppendLine(" GROUP BY Renglones_Traslados.Cod_Art  ")
			loComandoSeleccionar.AppendLine("  ORDER BY Renglones_Traslados.Cod_Art  ")
			
			
			loComandoSeleccionar.AppendLine(" SELECT	Renglones_dClientes.Cod_Art			AS	Cod_Art,   ")
			loComandoSeleccionar.AppendLine("   		SUM(CASE WHEN DATEPART(mm, Devoluciones_Clientes.Fec_Ini) <= 3 THEN  Renglones_dClientes.Can_Art1 ELSE 0 END ) AS	Can_Com1,  ")
			loComandoSeleccionar.AppendLine("  		SUM(CASE WHEN DATEPART(mm, Devoluciones_Clientes.Fec_Ini) > 3 AND DATEPART(mm, Devoluciones_Clientes.Fec_Ini) <= 6 THEN Renglones_dClientes.Can_Art1 ELSE 0 END ) AS	Can_Com2,  	")
			loComandoSeleccionar.AppendLine("  		SUM(CASE WHEN DATEPART(mm, Devoluciones_Clientes.Fec_Ini) > 6 AND DATEPART(mm, Devoluciones_Clientes.Fec_Ini) <= 9 THEN Renglones_dClientes.Can_Art1 ELSE 0 END ) AS	Can_Com3,  	")
			loComandoSeleccionar.AppendLine("  		SUM(CASE WHEN DATEPART(mm, Devoluciones_Clientes.Fec_Ini) > 9 THEN Renglones_dClientes.Can_Art1 ELSE 0 END ) AS	Can_Com4  	")
			loComandoSeleccionar.AppendLine("  INTO		#tempEntradaDevolucionCliente	")
			loComandoSeleccionar.AppendLine("  FROM		Devoluciones_Clientes,  	")
			loComandoSeleccionar.AppendLine(" 			Renglones_dClientes,  	")
			loComandoSeleccionar.AppendLine(" 			Articulos  	")
			loComandoSeleccionar.AppendLine("  WHERE		Devoluciones_Clientes.Documento					=	Renglones_dClientes.Documento  	")
			loComandoSeleccionar.AppendLine(" 			And Articulos.Cod_Art				=	Renglones_dClientes.Cod_Art  	")
			loComandoSeleccionar.AppendLine(" 			And Devoluciones_Clientes.Status					IN	('Confirmado', 'Afectado', 'Procesado')  	")
			loComandoSeleccionar.AppendLine("			And Articulos.Cod_Art				BETWEEN " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("			And DATEPART(YEAR,Devoluciones_Clientes.Fec_Ini)	= " & lcParametro1Desde )
            loComandoSeleccionar.AppendLine("			And Renglones_dClientes.Cod_Alm		BETWEEN " & lcParametro2Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro2Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Dep				BETWEEN " & lcParametro3Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro3Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Sec				BETWEEN " & lcParametro4Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro4Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Mar				BETWEEN " & lcParametro5Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro5Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Cla				BETWEEN " & lcParametro6Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro6Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Tip				BETWEEN " & lcParametro7Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro7Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Pro				BETWEEN " & lcParametro8Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro8Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Uni1				BETWEEN " & lcParametro9Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro9Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Suc				BETWEEN " & lcParametro10Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro10Hasta)
            loComandoSeleccionar.AppendLine("           And Articulos.Cod_Ubi    Between " & lcParametro11Desde)
            loComandoSeleccionar.AppendLine("           And " & lcParametro11Hasta)
			loComandoSeleccionar.AppendLine(" GROUP BY Renglones_dClientes.Cod_Art  ")
			loComandoSeleccionar.AppendLine("  ORDER BY Renglones_dClientes.Cod_Art  ")
			loComandoSeleccionar.AppendLine("  ")
			loComandoSeleccionar.AppendLine("  ")
			loComandoSeleccionar.AppendLine(" SELECT Cod_Art, Can_Com1, Can_Com2, Can_Com3, Can_Com4  ")
			loComandoSeleccionar.AppendLine(" INTO #tempComprasEntradas ")
			loComandoSeleccionar.AppendLine(" FROM #tempEntradasRecepciones ")
			loComandoSeleccionar.AppendLine(" UNION ALL ")
			loComandoSeleccionar.AppendLine(" SELECT Cod_Art, Can_Com1, Can_Com2, Can_Com3, Can_Com4 FROM #tempEntradasCompras ")
			loComandoSeleccionar.AppendLine(" UNION ALL ")
			loComandoSeleccionar.AppendLine(" SELECT Cod_Art, Can_Com1, Can_Com2, Can_Com3, Can_Com4 FROM #tempEntradaDevolucionCliente ")
			loComandoSeleccionar.AppendLine(" UNION ALL ")
			loComandoSeleccionar.AppendLine(" SELECT Cod_Art, Can_Com1, Can_Com2, Can_Com3, Can_Com4 FROM #tempEntradasTraslados ")
			loComandoSeleccionar.AppendLine("  ")
			loComandoSeleccionar.AppendLine(" SELECT  ")
			loComandoSeleccionar.AppendLine(" 		Cod_Art,  ")
			loComandoSeleccionar.AppendLine(" 		SUM(Can_Com1) As Can_Ent1, ")
			loComandoSeleccionar.AppendLine(" 		SUM(Can_Com2) As Can_Ent2, ")
			loComandoSeleccionar.AppendLine(" 		SUM(Can_Com3) As Can_Ent3, ")
			loComandoSeleccionar.AppendLine(" 		SUM(Can_Com4) As Can_Ent4 ")
			loComandoSeleccionar.AppendLine(" INTO #tempComprasEntradas2 ")
			loComandoSeleccionar.AppendLine(" FROM #tempComprasEntradas ")
			loComandoSeleccionar.AppendLine(" GROUP BY Cod_Art ")
			loComandoSeleccionar.AppendLine("  ")
			loComandoSeleccionar.AppendLine("  ")
			loComandoSeleccionar.AppendLine("  ")
			loComandoSeleccionar.AppendLine(" SELECT   ")
			loComandoSeleccionar.AppendLine("  		ISNULL(#tempEntradas.Cod_Art, #tempSalidas.Cod_Art) AS Cod_Art,  ")
			loComandoSeleccionar.AppendLine("  		ISNULL(#tempEntradas.Can_Ent1, 0) As Can_Ent1,  ")
			loComandoSeleccionar.AppendLine("  		ISNULL(#tempSalidas.Can_Sal1, 0) As Can_Sal1,   ")
			loComandoSeleccionar.AppendLine("  		ISNULL(#tempEntradas.Can_Ent2, 0) As Can_Ent2,  ")
			loComandoSeleccionar.AppendLine("  		ISNULL(#tempSalidas.Can_Sal2, 0) As Can_Sal2,   ")
			loComandoSeleccionar.AppendLine("  		ISNULL(#tempEntradas.Can_Ent3, 0) As Can_Ent3,  ")
			loComandoSeleccionar.AppendLine("  		ISNULL(#tempSalidas.Can_Sal3, 0) As Can_Sal3,   ")
			loComandoSeleccionar.AppendLine("  		ISNULL(#tempEntradas.Can_Ent4, 0) As Can_Ent4,  ")
			loComandoSeleccionar.AppendLine("  		ISNULL(#tempSalidas.Can_Sal4, 0) As Can_Sal4   ")
			loComandoSeleccionar.AppendLine("  INTO tempAjustes ")
			loComandoSeleccionar.AppendLine("  FROM #tempSalidas  ")
			loComandoSeleccionar.AppendLine("  Full JOIN #tempEntradas ON #tempEntradas.Cod_Art = #tempSalidas.Cod_Art  ")
			loComandoSeleccionar.AppendLine("  ")
			loComandoSeleccionar.AppendLine(" SELECT  ")
			loComandoSeleccionar.AppendLine(" 		ISNULL(#tempComprasEntradas2.Cod_Art, #tempVentasSalida2.Cod_Art) AS Cod_Art,  ")
			loComandoSeleccionar.AppendLine("  		ISNULL(#tempComprasEntradas2.Can_Ent1, 0) As Can_Ent1,  ")
			loComandoSeleccionar.AppendLine("  		ISNULL(#tempVentasSalida2.Can_Sal1, 0) As Can_Sal1,   ")
			loComandoSeleccionar.AppendLine("  		ISNULL(#tempComprasEntradas2.Can_Ent2, 0) As Can_Ent2,  ")
			loComandoSeleccionar.AppendLine("  		ISNULL(#tempVentasSalida2.Can_Sal2, 0) As Can_Sal2,   ")
			loComandoSeleccionar.AppendLine("  		ISNULL(#tempComprasEntradas2.Can_Ent3, 0) As Can_Ent3,  ")
			loComandoSeleccionar.AppendLine("  		ISNULL(#tempVentasSalida2.Can_Sal3, 0) As Can_Sal3,   ")
			loComandoSeleccionar.AppendLine("  		ISNULL(#tempComprasEntradas2.Can_Ent4, 0) As Can_Ent4,  ")
			loComandoSeleccionar.AppendLine("  		ISNULL(#tempVentasSalida2.Can_Sal4, 0) As Can_Sal4  ")
			loComandoSeleccionar.AppendLine(" INTO #tempVENTASCOMPRAS ")
			loComandoSeleccionar.AppendLine(" FROM #tempComprasEntradas2 ")
			loComandoSeleccionar.AppendLine(" Full JOIN #tempVentasSalida2 ON #tempVentasSalida2.Cod_Art = #tempComprasEntradas2.Cod_Art  ")
			loComandoSeleccionar.AppendLine("  ")
			loComandoSeleccionar.AppendLine(" SELECT *  ")
			loComandoSeleccionar.AppendLine(" INTO #temAJUSTESVENTASCOMPRAS ")
			loComandoSeleccionar.AppendLine(" FROM tempAjustes ")
			loComandoSeleccionar.AppendLine(" UNION ")
			loComandoSeleccionar.AppendLine(" SELECT * FROM #tempVENTASCOMPRAS ")
			loComandoSeleccionar.AppendLine("  ")
			loComandoSeleccionar.AppendLine(" SELECT  ")
			loComandoSeleccionar.AppendLine(" 		#temAJUSTESVENTASCOMPRAS.Cod_Art,  ")
			loComandoSeleccionar.AppendLine(" 		Articulos.Nom_Art, ")
			loComandoSeleccionar.AppendLine(" 		SUM(Can_Ent1) As Can_Ent1, ")
			loComandoSeleccionar.AppendLine(" 		SUM(Can_Ent2) As Can_Ent2, ")
			loComandoSeleccionar.AppendLine(" 		SUM(Can_Ent3) As Can_Ent3, ")
			loComandoSeleccionar.AppendLine(" 		SUM(Can_Ent4) As Can_Ent4, ")
			loComandoSeleccionar.AppendLine(" 		SUM(Can_Sal1) As Can_Sal1, ")
			loComandoSeleccionar.AppendLine(" 		SUM(Can_Sal2) As Can_Sal2, ")
			loComandoSeleccionar.AppendLine(" 		SUM(Can_Sal3) As Can_Sal3, ")
			loComandoSeleccionar.AppendLine(" 		SUM(Can_Sal4) As Can_Sal4		 ")
			loComandoSeleccionar.AppendLine(" FROM #temAJUSTESVENTASCOMPRAS ")
			loComandoSeleccionar.AppendLine(" JOIN Articulos ON Articulos.Cod_Art = #temAJUSTESVENTASCOMPRAS.Cod_Art ")
			loComandoSeleccionar.AppendLine(" GROUP BY      #temAJUSTESVENTASCOMPRAS.Cod_Art, Articulos.Nom_Art  ")
			loComandoSeleccionar.AppendLine("ORDER BY      " & lcOrdenamiento)

'me.mEscribirConsulta(loComandoSeleccionar.ToString)

			loComandoSeleccionar.AppendLine(" DROP TABLE #tempEntradasRecepciones ")
			loComandoSeleccionar.AppendLine(" DROP TABLE #tempEntradasCompras ")
			loComandoSeleccionar.AppendLine(" DROP TABLE #tempComprasEntradas ")
			loComandoSeleccionar.AppendLine(" DROP TABLE #tempComprasEntradas2 ")
			loComandoSeleccionar.AppendLine(" DROP TABLE #tempEntradasEntregas ")
			loComandoSeleccionar.AppendLine(" DROP TABLE #tempEntradasFacturas ")
			loComandoSeleccionar.AppendLine(" DROP TABLE #tempVentasSalida ")
			loComandoSeleccionar.AppendLine(" DROP TABLE #tempVentasSalida2 ")
			loComandoSeleccionar.AppendLine(" DROP TABLE #tempEntradas ")
			loComandoSeleccionar.AppendLine(" DROP TABLE #tempSalidas  ")
			loComandoSeleccionar.AppendLine(" DROP TABLE tempAjustes ")
			loComandoSeleccionar.AppendLine(" DROP TABLE #tempVENTASCOMPRAS ")
			loComandoSeleccionar.AppendLine(" DROP TABLE #temAJUSTESVENTASCOMPRAS ")
			loComandoSeleccionar.AppendLine(" DROP TABLE #tempEntradasTraslados ")
			loComandoSeleccionar.AppendLine(" DROP TABLE #tempSalidasTraslados ")
			 

            Dim loServicios As New cusDatos.goDatos

            Dim laDatosReporte As DataSet = loServicios.mObtenerTodosSinEsquema(loComandoSeleccionar.ToString(), "curReportes")

            '-------------------------------------------------------------------------------------------------------
            ' Verificando si el select (tabla nº0) trae registros
            '-------------------------------------------------------------------------------------------------------

            If (laDatosReporte.Tables(0).Rows.Count <= 0) Then
                Me.WbcAdministradorMensajeModal.mMostrarMensajeModal("Información", _
                                          "No se Encontraron Registros para los Parámetros Especificados. ", _
                                           vis3Controles.wbcAdministradorMensajeModal.enumTipoMensaje.KN_Informacion, _
                                           "350px", _
                                           "200px")
            End If

            loObjetoReporte = cusAplicacion.goReportes.mCargarReporte("rAnalisis_tUnidades", laDatosReporte)

            Me.mTraducirReporte(loObjetoReporte)

            Me.mFormatearCamposReporte(loObjetoReporte)

            Me.crvrAnalisis_tUnidades.ReportSource = loObjetoReporte

        Catch loExcepcion As Exception

            Me.WbcAdministradorMensajeModal.mMostrarMensajeModal("Error", _
                          "No se pudo Completar el Proceso: " & loExcepcion.Message, _
                           vis3Controles.wbcAdministradorMensajeModal.enumTipoMensaje.KN_Error, _
                           "auto", _
                           "auto")

        End Try

    End Sub

    Protected Sub Page_Unload(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Unload

        Try

            loObjetoReporte.Close()

        Catch loExcepcion As Exception

        End Try

    End Sub

End Class
'-------------------------------------------------------------------------------------------'
' Fin del codigo
'-------------------------------------------------------------------------------------------'
' CMS: 20/04/10: Codigo inicial
'-------------------------------------------------------------------------------------------'
' RJG: 09/12/10: Ajustado el estatus de las facturas de venta en el filtro.					' 
'-------------------------------------------------------------------------------------------'
' MAT: 01/04/11: Ajustado la vista de diseño												' 
'-------------------------------------------------------------------------------------------'
