'-------------------------------------------------------------------------------------------'
' Inicio del codigo
'-------------------------------------------------------------------------------------------'
' Importando librerias 
'-------------------------------------------------------------------------------------------'
Imports System.Data
Imports cusAplicacion

'-------------------------------------------------------------------------------------------'
' Inicio de clase "rLVentas_Dacron"
'-------------------------------------------------------------------------------------------'
Partial Class rLVentas_Dacron
    Inherits vis2formularios.frmReporte

    Dim loObjetoReporte As CrystalDecisions.CrystalReports.Engine.ReportDocument

	Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load

        Try

            Dim lcParametro0Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(0), goServicios.enuOpcionesRedondeo.KN_FechaInicioDelDia)
            Dim lcParametro0Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(0), goServicios.enuOpcionesRedondeo.KN_FechaFinDelDia)
            Dim lcParametro1Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(1), goServicios.enuOpcionesRedondeo.KN_FechaInicioDelDia)
            Dim lcParametro1Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(1), goServicios.enuOpcionesRedondeo.KN_FechaFinDelDia)
            
            Dim lcParametro2Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(2))
            Dim lcParametro2Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(2))
            
            Dim lcParametro3Desde As String = cusAplicacion.goReportes.paParametrosIniciales(3) 
            
            Dim lcOrdenamiento As String = cusAplicacion.goReportes.pcOrden

            Dim loConsulta As New StringBuilder()
		
            loConsulta.AppendLine("")
            loConsulta.AppendLine("DECLARE @lnCero AS Decimal(28,10)")
            loConsulta.AppendLine("SET	 @lnCero = 0;")
            loConsulta.AppendLine("")

            loConsulta.AppendLine("")
            loConsulta.AppendLine("--***************************************************************************************")
            loConsulta.AppendLine("-- Obtiene el detalle de los datos a mostrar y aplica los filtros del reporte.          *")
            loConsulta.AppendLine("--***************************************************************************************")
            loConsulta.AppendLine("SELECT   CONVERT(NCHAR(10), Cuentas_Cobrar.Fec_Ini, 103)								AS Fecha1,				")
            loConsulta.AppendLine("       	CONVERT(NCHAR(25), Cuentas_Cobrar.Fec_Ini, 121)								AS Fecha2,				")
            loConsulta.AppendLine("       	DATEPART(WEEKDAY, Cuentas_Cobrar.Fec_Ini)									AS Dia,					")
            loConsulta.AppendLine("       	Cuentas_Cobrar.Fiscal2														AS Documento,			")
            loConsulta.AppendLine("       	Cuentas_Cobrar.Documento													AS Numero_Documento,	")
            loConsulta.AppendLine("       	Cuentas_Cobrar.Doc_Ori														AS Documento_Origen,	")
            loConsulta.AppendLine("       	Cuentas_Cobrar.Tip_Ori														AS Tipo_Origen,			")
            loConsulta.AppendLine("       	Cuentas_Cobrar.Cla_Ori														AS Clase_Origen,		")
            loConsulta.AppendLine("       	N'          '																AS Documento_Afectado,	")
            loConsulta.AppendLine("       	N'          '																AS Comprobante_Retencion,")
            loConsulta.AppendLine("       	@lnCero																		AS Monto_Retenido,		")
            loConsulta.AppendLine("       	@lnCero																		AS Ventas_No_Sujetas,	")
            loConsulta.AppendLine("       	@lnCero																		AS Exportacion,			")
            loConsulta.AppendLine("       	Cuentas_Cobrar.Cod_Tip														AS Cod_Tip,				")
            loConsulta.AppendLine("       	Cuentas_Cobrar.Cod_Suc														AS Cod_Suc,				")
            loConsulta.AppendLine("       	Cuentas_Cobrar.Usu_Cre														AS Usu_Cre,				")
            loConsulta.AppendLine("       	Cuentas_Cobrar.Fiscal1														AS Impresora,			")
            loConsulta.AppendLine("       	ISNULL(Cajas.Cod_Caj, '')													AS Cod_Caj,				")
            loConsulta.AppendLine("       	Clientes.Fiscal																AS Fiscal,				")
            loConsulta.AppendLine("       	Clientes.Rif																AS Rif,					")
            loConsulta.AppendLine("       	Clientes.Nom_Cli															AS Nom_Cli,				")
            loConsulta.AppendLine("       	(CASE WHEN (Cuentas_Cobrar.Cod_Tip IN ('N/CR', 'RETIVA')) THEN -1 ELSE 1 END)	AS Signo,			")
            loConsulta.AppendLine("       	Cuentas_Cobrar.Mon_Bru														AS Bruto,				")
            loConsulta.AppendLine("       	Cuentas_Cobrar.Mon_Exe														AS Exento,				")
            loConsulta.AppendLine("       	Cuentas_Cobrar.Por_Des														AS Por_Des,				")
            loConsulta.AppendLine("       	Cuentas_Cobrar.Mon_Des														AS Mon_Des,				")
            loConsulta.AppendLine("       	Cuentas_Cobrar.Por_Rec														AS Por_Rec,				")
            loConsulta.AppendLine("       	Cuentas_Cobrar.Mon_Rec														AS Mon_Rec,				")
            loConsulta.AppendLine("       	(Cuentas_Cobrar.Mon_Otr1+Cuentas_Cobrar.Mon_Otr2+Cuentas_Cobrar.Mon_Otr3)	AS Mon_Otr,				")
            loConsulta.AppendLine("       	CAST(Cuentas_Cobrar.Dis_Imp AS XML)											AS Dis_Imp				")
            loConsulta.AppendLine("INTO		#tmpRegistros ")
            loConsulta.AppendLine("FROM		Cuentas_Cobrar ")
            loConsulta.AppendLine("	JOIN	Clientes ON Cuentas_Cobrar.Cod_Cli = Clientes.Cod_Cli ")
            loConsulta.AppendLine("	LEFT JOIN Cajas ON Cajas.Caracter1 = Cuentas_Cobrar.Fiscal1")
            loConsulta.AppendLine("					AND Cajas.Caracter1 > ''")
            loConsulta.AppendLine("WHERE		Cuentas_Cobrar.Fec_Ini    BETWEEN " & lcParametro0Desde)    '@ldFechaDesde
            loConsulta.AppendLine("			AND " & lcParametro0Hasta)                                      '@ldFechaHasta
            loConsulta.AppendLine("			AND Cuentas_Cobrar.Cod_Tip IN ('FACT','N/CR','RETIVA')")
            loConsulta.AppendLine("			AND Cuentas_Cobrar.Status <> 'Anulado'")
            loConsulta.AppendLine("       	AND Cuentas_Cobrar.Cod_Suc    BETWEEN " & lcParametro1Desde)    '@lcSucursalDesde
            loConsulta.AppendLine("       	AND " & lcParametro1Hasta)                                      '@lcSucursalHasta
            If lcParametro3Desde = "Igual" Then
                loConsulta.AppendLine(" 		AND Cuentas_Cobrar.Cod_Rev BETWEEN " & lcParametro2Desde)       '@lcRevisionDesde
            Else
                loConsulta.AppendLine(" 		AND Cuentas_Cobrar.Cod_Rev NOT BETWEEN " & lcParametro2Desde)   '@lcRevisionDesde
            End If
            loConsulta.AppendLine(" 			AND " & lcParametro2Hasta)                                  '@lcRevisionHasta
            loConsulta.AppendLine("")

            loConsulta.AppendLine("")
            loConsulta.AppendLine("--***************************************************************************************")
            loConsulta.AppendLine("-- Revisa la distibución de impuestos por documento y los separa del XML.               *")
            loConsulta.AppendLine("--***************************************************************************************")
            loConsulta.AppendLine("")
            loConsulta.AppendLine("SELECT	Documento,	Cod_Tip,														")
            loConsulta.AppendLine("		Fecha1,		Fecha2,		Dia,												")
            loConsulta.AppendLine("		Cod_Suc,	Usu_Cre,														")
            loConsulta.AppendLine("		Signo,		Fiscal,		Cod_Caj,											")
            loConsulta.AppendLine("		Rif, Nom_cli,																")
            loConsulta.AppendLine("		Documento_Origen, Tipo_Origen, Clase_Origen,								")
            loConsulta.AppendLine("		Numero_Documento,	 														")
            loConsulta.AppendLine("		Documento_Afectado, 														")
            loConsulta.AppendLine("		Comprobante_Retencion,														")
            loConsulta.AppendLine("		Monto_Retenido, 															")
            loConsulta.AppendLine("		Ventas_No_Sujetas, 															")
            loConsulta.AppendLine("		Exportacion,																")
            loConsulta.AppendLine("		(CASE WHEN (Impresora='') THEN 'SIF' ELSE Impresora END)	AS Impresora,	")
            loConsulta.AppendLine("		(Por_Des*Signo)												AS Por_Des,		")
            loConsulta.AppendLine("		(Mon_Des*Signo)												AS Mon_Des,		")
            loConsulta.AppendLine("		(Por_Rec*Signo)												AS Por_Rec,		")
            loConsulta.AppendLine("		(Mon_Rec*Signo)												AS Mon_Rec,		")
            loConsulta.AppendLine("		(Mon_Otr*Signo)												AS Mon_Otr,		")
            loConsulta.AppendLine("		(Exento*Signo)												AS Exento,		")
            loConsulta.AppendLine("		REPLACE(REPLACE(REPLACE(T.C.value('(./codigo)[1]', 'NVARCHAR(10)'), CHAR(10),''), CHAR(13),''), CHAR(9),'')									AS Codigo,	")
            loConsulta.AppendLine("		CAST(REPLACE(REPLACE(REPLACE(T.C.value('(./porcentaje)[1]',	'NVARCHAR(20)')	, CHAR(10),''), CHAR(13),''), CHAR(9),'') AS DECIMAL(28,10))	AS Porcentaje,	")
            loConsulta.AppendLine("		CAST(REPLACE(REPLACE(REPLACE(T.C.value('(./base)[1]',	'NVARCHAR(20)')	, CHAR(10),''), CHAR(13),''), CHAR(9),'') AS DECIMAL(28,10))*Signo	AS Base,		")
            loConsulta.AppendLine("		CAST(REPLACE(REPLACE(REPLACE(T.C.value('(./monto)[1]',	'NVARCHAR(20)')	, CHAR(10),''), CHAR(13),''), CHAR(9),'') AS DECIMAL(28,10))*Signo	AS Impuesto")
            loConsulta.AppendLine("INTO	#tmpImpuestoDistribuido")
            loConsulta.AppendLine("FROM	#tmpRegistros")
            loConsulta.AppendLine("	CROSS APPLY #tmpRegistros.Dis_Imp.nodes('/impuestos/impuesto') AS T(C)")
            loConsulta.AppendLine("WHERE	CAST(REPLACE(REPLACE(REPLACE(T.C.value('(./porcentaje)[1]',	'NVARCHAR(20)')	, CHAR(10),''), CHAR(13),''), CHAR(9),'') AS DECIMAL(28,10)) > @lnCero")
            loConsulta.AppendLine("	OR	Bruto = Exento	")
            loConsulta.AppendLine("")
            loConsulta.AppendLine("-- La primera tabla temporal ya no es necesaria")
            loConsulta.AppendLine("DROP TABLE #tmpRegistros;")
            loConsulta.AppendLine("")
            
			loConsulta.AppendLine("")
			loConsulta.AppendLine("--***************************************************************************************")
            loConsulta.AppendLine("-- Busca la información de la factura de origen de las devoluciones y retenciones.      *")
            loConsulta.AppendLine("--**************************************************************************************")
			loConsulta.AppendLine("")
            loConsulta.AppendLine("SELECT   F.Fiscal2						AS Fis_Afectado, 		")
            loConsulta.AppendLine("         F.Documento						AS Doc_Afectado, 		")
			loConsulta.AppendLine("         ISNULL(R.Num_Com, '')			AS Numero_Comprobante, 	")
			loConsulta.AppendLine("         ID.Documento					AS Documento,			")
            loConsulta.AppendLine("         ID.Numero_Documento				AS Numero_Documento,	")
            loConsulta.AppendLine("         ID.Cod_Tip						AS Tipo_Documento,		")
            loConsulta.AppendLine("         ID.Tipo_Origen					AS Tipo_Origen ")
            loConsulta.AppendLine("INTO	    #tmpDevoluciones										")
			loConsulta.AppendLine("FROM	    Cuentas_Cobrar AS Origen								")
			loConsulta.AppendLine("	JOIN    #tmpImpuestoDistribuido AS ID							")
            loConsulta.AppendLine("		ON  ID.Documento_Origen = Origen.Documento				")
            loConsulta.AppendLine("		AND ID.Cod_Tip IN ('RETIVA')							")
			loConsulta.AppendLine("		AND Origen.Cod_Tip = 'FACT'							    ")
            loConsulta.AppendLine("	LEFT JOIN Retenciones_Documentos AS R						")
            loConsulta.AppendLine("		ON  R.Doc_Des = ID.Numero_Documento						")
            loConsulta.AppendLine("		AND R.Cla_Des = 'RETIVA'								")
            loConsulta.AppendLine("		AND R.Tip_Des = 'Cuentas_Cobrar'						")
			loConsulta.AppendLine("	LEFT JOIN Cuentas_Cobrar AS F								")
			loConsulta.AppendLine("		ON  F.Documento = R.Doc_Ori								")
            loConsulta.AppendLine("		AND F.Cod_Tip = 'FACT'")
            loConsulta.AppendLine("		AND R.Tip_Ori = 'Cuentas_Cobrar'")
            loConsulta.AppendLine("		AND R.Cla_Ori = 'FACT'")
            loConsulta.AppendLine("UNION ALL 																")
			loConsulta.AppendLine("SELECT	Origen.Fiscal2					AS Fis_Afectado, 				")
			loConsulta.AppendLine("         Origen.Documento				AS Doc_Afectado, 				")
            loConsulta.AppendLine("         ''                              AS Numero_Comprobante, 			")
            loConsulta.AppendLine("         ID.Documento					AS Documento,					")
            loConsulta.AppendLine("         ID.Numero_Documento				AS Numero_Documento,			")
            loConsulta.AppendLine("         ID.Cod_Tip						AS Tipo_Documento,				")
            loConsulta.AppendLine("         ID.Tipo_Origen					AS Tipo_Origen					")
			loConsulta.AppendLine("FROM	    #tmpImpuestoDistribuido AS ID									")
			loConsulta.AppendLine("	JOIN    Renglones_dClientes AS RC										")
            loConsulta.AppendLine("		ON  RC.Documento = ID.Documento_Origen								")
            loConsulta.AppendLine("		AND ID.Cod_Tip IN ('N/CR')											")
            loConsulta.AppendLine("		AND RC.Renglon = 1													")
            loConsulta.AppendLine("		AND ID.Tipo_Origen = 'Devoluciones_Clientes'						")
			loConsulta.AppendLine("	JOIN    Cuentas_Cobrar AS Origen										")
            loConsulta.AppendLine("		ON  Origen.Cod_Tip = 'FACT' 										")
            loConsulta.AppendLine("		AND Origen.Documento = RC.Doc_Ori									")
            loConsulta.AppendLine("		AND RC.Renglon = 1													")
		    loConsulta.AppendLine("UNION ALL 																")
		    loConsulta.AppendLine("SELECT	Origen.Fiscal2					AS Fis_Afectado, 				")
            loConsulta.AppendLine("		    Origen.Documento				AS Doc_Afectado, 				")
            loConsulta.AppendLine("		    ''					            AS Numero_Comprobante, 			")
            loConsulta.AppendLine("		    ID.Documento					AS Documento,					")
            loConsulta.AppendLine("		    ID.Numero_Documento				AS Numero_Documento,			")
			loConsulta.AppendLine("		    ID.Cod_Tip						AS Tipo_Documento,				")
			loConsulta.AppendLine("		    ID.Tipo_Origen					AS Tipo_Origen					")
			loConsulta.AppendLine("FROM	    #tmpImpuestoDistribuido AS ID									")
            loConsulta.AppendLine("	JOIN Cuentas_Cobrar AS Origen											")
            loConsulta.AppendLine("		ON Origen.Cod_Tip = 'FACT' 											")
            loConsulta.AppendLine("		AND Origen.Documento = ID.Documento_Origen							")
            loConsulta.AppendLine("		AND ID.Tipo_Origen = 'Facturas'										")
			loConsulta.AppendLine("")

			loConsulta.AppendLine("")
			loConsulta.AppendLine("--'**************************************************************************************")
            loConsulta.AppendLine("--' Tabla de soporte: días de la semana.                                        	    *")
            loConsulta.AppendLine("--'**************************************************************************************")
            loConsulta.AppendLine("")
            loConsulta.AppendLine("CREATE TABLE #tmpDias(Dia INT, Dia_Sem NVARCHAR(20))")
			loConsulta.AppendLine("INSERT INTO #tmpDias VALUES (1, 'Domingo')")
			loConsulta.AppendLine("INSERT INTO #tmpDias VALUES (2, 'Lunes')")
            loConsulta.AppendLine("INSERT INTO #tmpDias VALUES (3, 'Martes')")
            loConsulta.AppendLine("INSERT INTO #tmpDias VALUES (4, 'Miércoles')")
            loConsulta.AppendLine("INSERT INTO #tmpDias VALUES (5, 'Jueves')")
            loConsulta.AppendLine("INSERT INTO #tmpDias VALUES (6, 'Viernes')")
            loConsulta.AppendLine("INSERT INTO #tmpDias VALUES (7, 'Sábado')")
			loConsulta.AppendLine("")

			loConsulta.AppendLine("--'**************************************************************************************")
            loConsulta.AppendLine("--' Tabla de resultados (sin agrupar).                                                  *")
			loConsulta.AppendLine("--'**************************************************************************************")
            loConsulta.AppendLine("CREATE TABLE #tmpResultados(    Tipo_Operacion           CHAR(1) COLLATE DATABASE_DEFAULT,")
            loConsulta.AppendLine("                                Fecha1                   CHAR(10) COLLATE DATABASE_DEFAULT,")
            loConsulta.AppendLine("                                Fecha2                   CHAR(10) COLLATE DATABASE_DEFAULT,")
            loConsulta.AppendLine("                                Dia_Sem                  NVARCHAR(20) COLLATE DATABASE_DEFAULT,")
			loConsulta.AppendLine("                                Cod_Suc                  CHAR(10) COLLATE DATABASE_DEFAULT,")
            loConsulta.AppendLine("                                Cod_Caj                  CHAR(10) COLLATE DATABASE_DEFAULT,")
            loConsulta.AppendLine("                                Impresora                VARCHAR(20) COLLATE DATABASE_DEFAULT,")
            loConsulta.AppendLine("                                Doc_Ini                  CHAR(10) COLLATE DATABASE_DEFAULT,")
            loConsulta.AppendLine("                                Doc_Fin                  CHAR(10) COLLATE DATABASE_DEFAULT,")
			loConsulta.AppendLine("                                Doc_Ncr                  CHAR(10) COLLATE DATABASE_DEFAULT,")
            loConsulta.AppendLine("                                Mon_Otr                  DECIMAL(28, 10),")
			loConsulta.AppendLine("                                Numero_Documento         CHAR(30) COLLATE DATABASE_DEFAULT,")
			loConsulta.AppendLine("                                Tipo_Documento           CHAR(10) COLLATE DATABASE_DEFAULT,")
            loConsulta.AppendLine("                                Documento_AfectadoNC     CHAR(10) COLLATE DATABASE_DEFAULT,")
            loConsulta.AppendLine("                                Documento_Afectado       CHAR(10) COLLATE DATABASE_DEFAULT,")
            loConsulta.AppendLine("                                Comprobante_Retencion    CHAR(30) COLLATE DATABASE_DEFAULT,")
            loConsulta.AppendLine("                                Monto_Retenido           DECIMAL(28, 10),")
			loConsulta.AppendLine("                                Ventas_No_Sujetas        DECIMAL(28, 10),")
            loConsulta.AppendLine("                                Exportacion              DECIMAL(28, 10),")
			loConsulta.AppendLine("                                Rif                      CHAR(20) COLLATE DATABASE_DEFAULT,")
			loConsulta.AppendLine("                                Nom_Cli                  CHAR(100) COLLATE DATABASE_DEFAULT,")
            loConsulta.AppendLine("                                Porcentaje               DECIMAL(28, 10),")
            loConsulta.AppendLine("                                Mon_DesC                 DECIMAL(28, 10),")
            loConsulta.AppendLine("                                Mon_RecC                 DECIMAL(28, 10),")
            loConsulta.AppendLine("                                Mon_BruC                 DECIMAL(28, 10),")
			loConsulta.AppendLine("                                Mon_ExeC                 DECIMAL(28, 10),")
            loConsulta.AppendLine("                                Mon_ImpC                 DECIMAL(28, 10),")
            loConsulta.AppendLine("                                Mon_DesNC                DECIMAL(28, 10),")
            loConsulta.AppendLine("                                Mon_RecNC                DECIMAL(28, 10),")
            loConsulta.AppendLine("                                Mon_BruNC                DECIMAL(28, 10),")
			loConsulta.AppendLine("                                Mon_ExeNC                DECIMAL(28, 10),")
            loConsulta.AppendLine("                                Mon_ImpNC                DECIMAL(28, 10),")
			loConsulta.AppendLine("                                Fact_BI	                DECIMAL(28, 10),")
			loConsulta.AppendLine("                                Fact_IMP                 DECIMAL(28, 10),")
            loConsulta.AppendLine("                                Fact_EXE                 DECIMAL(28, 10),")
			loConsulta.AppendLine("                                Fact_EXO                 DECIMAL(28, 10),")
            loConsulta.AppendLine("                                Fact_NS	                DECIMAL(28, 10),")
			loConsulta.AppendLine("                                Fact_SDCF                DECIMAL(28, 10),")
			loConsulta.AppendLine("                                Fact_Retenido	        DECIMAL(28, 10),")
            loConsulta.AppendLine("                                Ncr_BI                   DECIMAL(28, 10),")
            loConsulta.AppendLine("                                Ncr_IMP	                DECIMAL(28, 10),")
            loConsulta.AppendLine("                                Ncr_EXE	                DECIMAL(28, 10),")
            loConsulta.AppendLine("                                Ncr_EXO	                DECIMAL(28, 10),")
			loConsulta.AppendLine("                                Ncr_NS	                DECIMAL(28, 10),")
            loConsulta.AppendLine("                                Ncr_SDCF	                DECIMAL(28, 10),")
            loConsulta.AppendLine("                                Fiscal                   BIT,")
            loConsulta.AppendLine("                                Orden                    INTEGER,")
            loConsulta.AppendLine("                                Grupo                    INTEGER")
			loConsulta.AppendLine("                            );  	")
            loConsulta.AppendLine("")
			loConsulta.AppendLine("")
			loConsulta.AppendLine("--'**************************************************************************************")
            loConsulta.AppendLine("--' Selecciona los registros correspondientes a los 'No Contribuyentes', sin agrupar    *")
            loConsulta.AppendLine("--' (Solo FACT y RETIVA).									                            *")
            loConsulta.AppendLine("--'************************************************************************************")
            loConsulta.AppendLine("INSERT INTO #tmpResultados  (Tipo_Operacion, Fecha1,Fecha2,Dia_Sem,Cod_Suc,Cod_Caj,Impresora,")
			loConsulta.AppendLine("                            Doc_Ini, Doc_Fin, Doc_Ncr, Mon_Otr, Numero_Documento, Tipo_Documento,")
            loConsulta.AppendLine("                            Documento_AfectadoNC, Documento_Afectado, Comprobante_Retencion,")
			loConsulta.AppendLine("                            Monto_Retenido, Ventas_No_Sujetas, Exportacion,")
			loConsulta.AppendLine("                            Rif, Nom_Cli, Porcentaje, Mon_DesC, Mon_RecC, Mon_BruC, Mon_ExeC,")
            loConsulta.AppendLine("                            Mon_ImpC, Mon_DesNC, Mon_RecNC, Mon_BruNC, Mon_ExeNC, Mon_ImpNC,")
            loConsulta.AppendLine("                            Fact_BI, Fact_IMP, Fact_EXE, Fact_EXO, Fact_NS, Fact_SDCF, Fact_Retenido,")
            loConsulta.AppendLine("                            Ncr_BI, Ncr_IMP, Ncr_EXE, Ncr_EXO, Ncr_NS, Ncr_SDCF, Fiscal)")
            loConsulta.AppendLine("SELECT		(CASE T.Cod_Tip ")
			loConsulta.AppendLine("                    WHEN 'FACT' THEN 'A'")
            loConsulta.AppendLine("                    WHEN 'RETIVA' THEN 'B'")
            loConsulta.AppendLine("                    WHEN 'N/CR' THEN 'C'")
            loConsulta.AppendLine("                    ELSE 'D'")
            loConsulta.AppendLine("            END)																	AS Tipo_Operacion,			")
			loConsulta.AppendLine("			T.Fecha1																AS Fecha1,					")
            loConsulta.AppendLine("			CAST(T.Fecha2 AS NCHAR(10))												AS Fecha2,					")
			loConsulta.AppendLine("			Dias_Semana.Dia_Sem														AS Dia_Sem, 				")
            loConsulta.AppendLine("			T.Cod_Suc																AS Cod_Suc, 				")
            loConsulta.AppendLine("			T.Cod_Caj																AS Cod_Caj, 				")
			loConsulta.AppendLine("			T.Impresora																AS Impresora,				")
            loConsulta.AppendLine("			(F.Documento) 														    AS Doc_Ini, 				")
			loConsulta.AppendLine("			(F.Documento) 														    AS Doc_Fin, 				")
            loConsulta.AppendLine("			''				 														AS Doc_Ncr,                 ")
            loConsulta.AppendLine("			(T.Mon_Otr)															    AS Mon_Otr, 				")
            loConsulta.AppendLine("			F.Documento																AS Numero_Documento,		")
            loConsulta.AppendLine("			''																		AS Tipo_Documento, 			")
			loConsulta.AppendLine("			''																		AS Documento_AfectadoNC,	")
            loConsulta.AppendLine("			''																		AS Documento_Afectado, 		")
            loConsulta.AppendLine("			''																		AS Comprobante_Retencion, 	")
            loConsulta.AppendLine("			@lnCero																	AS Monto_Retenido, 			")
            loConsulta.AppendLine("			@lnCero																	AS Ventas_No_Sujetas, 		")
			loConsulta.AppendLine("			@lnCero																	AS Exportacion,				")
            loConsulta.AppendLine("			''																		AS Rif,						")
			loConsulta.AppendLine("			''																		AS Nom_Cli,					")
			loConsulta.AppendLine("			(T.Porcentaje)														    AS Porcentaje,				")
            loConsulta.AppendLine("			@lnCero 																AS Mon_DesC,				")
            loConsulta.AppendLine("			@lnCero 																AS Mon_RecC,				")
            loConsulta.AppendLine("			@lnCero 																AS Mon_BruC,				")
            loConsulta.AppendLine("			@lnCero 																AS Mon_ExeC,				")
			loConsulta.AppendLine("			@lnCero 																AS Mon_ImpC,				")
            loConsulta.AppendLine("			(T.Por_Des*T.Base/100)												    AS Mon_DesNC,				")
			loConsulta.AppendLine("			(T.Por_Rec*T.Base/100)												    AS Mon_RecNC,				")
			loConsulta.AppendLine("			(CASE WHEN T.Impuesto  = 0 THEN @lnCero ELSE T.Base END)				AS Mon_BruNC,				")
            loConsulta.AppendLine("			T.Exento															    AS Mon_ExeNC,				")
            loConsulta.AppendLine("			T.Impuesto															    AS Mon_ImpNC, 				")
            loConsulta.AppendLine("			(CASE WHEN T.Cod_Tip = 'FACT' THEN T.Base		ELSE @lnCero END)	    AS Fact_BI,					")
            loConsulta.AppendLine("			(CASE WHEN T.Cod_Tip = 'FACT' THEN T.Impuesto	ELSE @lnCero END)	    AS Fact_IMP,				")
			loConsulta.AppendLine("			(CASE WHEN T.Cod_Tip = 'FACT' THEN T.Exento		ELSE @lnCero END)	    AS Fact_EXE,				")
            loConsulta.AppendLine("			@lnCero																	AS Fact_EXO,				")
            loConsulta.AppendLine("			@lnCero																	AS Fact_NS,					")
            loConsulta.AppendLine("			@lnCero																	AS Fact_SDCF,				")
            loConsulta.AppendLine("			(CASE WHEN T.Cod_Tip = 'RETIVA' THEN T.Exento	ELSE @lnCero END)	    AS Fact_Retenido,			")
			loConsulta.AppendLine("			(CASE WHEN T.Cod_Tip = 'N/CR' THEN -(CASE WHEN T.Impuesto  = 0 THEN @lnCero ELSE T.Base END) ELSE @lnCero END) AS Ncr_B,")
            loConsulta.AppendLine("			(CASE WHEN T.Cod_Tip = 'N/CR' THEN -T.Impuesto	ELSE @lnCero END)	    AS Ncr_IMP,					")
			loConsulta.AppendLine("			(CASE WHEN T.Cod_Tip = 'N/CR' THEN -T.Exento	ELSE @lnCero END)	    AS Ncr_EXE,					")
			loConsulta.AppendLine("			@lnCero																	AS Ncr_EXO,					")
            loConsulta.AppendLine("			@lnCero																	AS Ncr_NS,					")
			loConsulta.AppendLine("		    @lnCero																	AS Ncr_SDCF,")
            loConsulta.AppendLine("		    0                                                                       AS Fiscal")
			loConsulta.AppendLine("FROM		#tmpImpuestoDistribuido AS T																		")
			loConsulta.AppendLine("	JOIN	#tmpDias AS Dias_Semana ON Dias_Semana.Dia = T.Dia													")
            loConsulta.AppendLine("	LEFT JOIN #tmpImpuestoDistribuido AS F ON F.Fecha2 = T.Fecha2												")
            loConsulta.AppendLine("		AND	F.Cod_Caj = T.Cod_Caj")
            loConsulta.AppendLine("		AND	F.Impresora = T.Impresora")
            loConsulta.AppendLine("		AND	F.Documento = T.Documento")
			loConsulta.AppendLine("		AND	F.Numero_Documento = T.Numero_Documento")
            loConsulta.AppendLine("		AND	F.Cod_Tip	= 'FACT'")
            loConsulta.AppendLine("		AND	T.Cod_Tip	= 'FACT'")
            loConsulta.AppendLine("		AND F.Fiscal = 0")
            loConsulta.AppendLine("		AND T.Fiscal = 0")
			loConsulta.AppendLine("WHERE		T.Fiscal = 0")
            loConsulta.AppendLine("   AND		T.Cod_Tip <> 'N/CR'																					")
			loConsulta.AppendLine("")
			loConsulta.AppendLine("")
            loConsulta.AppendLine("--'**************************************************************************************")
            loConsulta.AppendLine("--' Selecciona los registros correspondientes a los 'No Contribuyentes', sin agrupar    *")
            loConsulta.AppendLine("--' (Solo N/CR).									                                    *")
            loConsulta.AppendLine("--'**************************************************************************************")
			loConsulta.AppendLine("INSERT INTO #tmpResultados  (Tipo_Operacion, Fecha1,Fecha2,Dia_Sem,Cod_Suc,Cod_Caj,Impresora,")
            loConsulta.AppendLine("                            Doc_Ini, Doc_Fin, Doc_Ncr, Mon_Otr, Numero_Documento, Tipo_Documento,")
			loConsulta.AppendLine("                            Documento_AfectadoNC, Documento_Afectado, Comprobante_Retencion,")
			loConsulta.AppendLine("                            Monto_Retenido, Ventas_No_Sujetas, Exportacion,")
            loConsulta.AppendLine("                            Rif, Nom_Cli, Porcentaje, Mon_DesC, Mon_RecC, Mon_BruC, Mon_ExeC,")
            loConsulta.AppendLine("                            Mon_ImpC, Mon_DesNC, Mon_RecNC, Mon_BruNC, Mon_ExeNC, Mon_ImpNC,")
            loConsulta.AppendLine("                            Fact_BI, Fact_IMP, Fact_EXE, Fact_EXO, Fact_NS, Fact_SDCF, Fact_Retenido,")
            loConsulta.AppendLine("                            Ncr_BI, Ncr_IMP, Ncr_EXE, Ncr_EXO, Ncr_NS, Ncr_SDCF, Fiscal)")
			loConsulta.AppendLine("SELECT		(CASE T.Cod_Tip ")
            loConsulta.AppendLine("                    WHEN 'FACT' THEN 'A'")
            loConsulta.AppendLine("                    WHEN 'RETIVA' THEN 'B'")
            loConsulta.AppendLine("                    WHEN 'N/CR' THEN 'C'")
            loConsulta.AppendLine("                    ELSE 'D'")
			loConsulta.AppendLine("            END)																	AS Tipo_Operacion,			")
            loConsulta.AppendLine("			T.Fecha1																AS Fecha1,					")
			loConsulta.AppendLine("			CAST(T.Fecha2 AS NCHAR(10))												AS Fecha2,					")
            loConsulta.AppendLine("			Dias_Semana.Dia_Sem														AS Dia_Sem, 				")
            loConsulta.AppendLine("			T.Cod_Suc																AS Cod_Suc, 				")
			loConsulta.AppendLine("			T.Cod_Caj																AS Cod_Caj, 				")
            loConsulta.AppendLine("			T.Impresora																AS Impresora,				")
			loConsulta.AppendLine("			''				 														AS Doc_Ini, 				")
            loConsulta.AppendLine("			''				 														AS Doc_Fin, 				")
            loConsulta.AppendLine("			F.Documento		 														AS Doc_Ncr,                 ")
            loConsulta.AppendLine("			T.Mon_Otr   															AS Mon_Otr, 				")
            loConsulta.AppendLine("			F.Documento 															AS Numero_Documento,		")
			loConsulta.AppendLine("			''																		AS Tipo_Documento, 			")
            loConsulta.AppendLine("			ISNULL(CASE WHEN D.Fis_Afectado='' THEN D.Doc_Afectado ELSE D.Fis_Afectado END, '')	AS Documento_AfectadoNC,	")
            loConsulta.AppendLine("			''																		AS Documento_Afectado, 		")
            loConsulta.AppendLine("			''																		AS Comprobante_Retencion, 	")
            loConsulta.AppendLine("			@lnCero																	AS Monto_Retenido, 			")
			loConsulta.AppendLine("			@lnCero																	AS Ventas_No_Sujetas, 		")
            loConsulta.AppendLine("			@lnCero																	AS Exportacion,				")
			loConsulta.AppendLine("			''																		AS Rif,						")
			loConsulta.AppendLine("			''																		AS Nom_Cli,					")
            loConsulta.AppendLine("			T.Porcentaje    														AS Porcentaje,				")
            loConsulta.AppendLine("			@lnCero 																AS Mon_DesC,				")
            loConsulta.AppendLine("			@lnCero 																AS Mon_RecC,				")
            loConsulta.AppendLine("			@lnCero 																AS Mon_BruC,				")
			loConsulta.AppendLine("			@lnCero 																AS Mon_ExeC,				")
            loConsulta.AppendLine("			@lnCero 																AS Mon_ImpC,				")
			loConsulta.AppendLine("			(T.Por_Des*T.Base/100)													AS Mon_DesNC,				")
			loConsulta.AppendLine("			(T.Por_Rec*T.Base/100)													AS Mon_RecNC,				")
            loConsulta.AppendLine("			(CASE  WHEN T.Impuesto =0 THEN @lnCero ELSE T.Base END)				    AS Mon_BruNC,				")
            loConsulta.AppendLine("			T.Exento															    AS Mon_ExeNC,				")
            loConsulta.AppendLine("			T.Impuesto															    AS Mon_ImpNC, 				")
            loConsulta.AppendLine("			(CASE WHEN T.Cod_Tip = 'FACT' THEN T.Base		ELSE @lnCero END)    	AS Fact_BI,					")
			loConsulta.AppendLine("			(CASE WHEN T.Cod_Tip = 'FACT' THEN T.Impuesto	ELSE @lnCero END)    	AS Fact_IMP,				")
            loConsulta.AppendLine("			(CASE WHEN T.Cod_Tip = 'FACT' THEN T.Exento		ELSE @lnCero END)     	AS Fact_EXE,				")
            loConsulta.AppendLine("			@lnCero																	AS Fact_EXO,				")
            loConsulta.AppendLine("			@lnCero																	AS Fact_NS,					")
            loConsulta.AppendLine("			@lnCero																	AS Fact_SDCF,				")
			loConsulta.AppendLine("			(CASE WHEN T.Cod_Tip = 'RETIVA' THEN T.Exento	ELSE @lnCero END)	    AS Fact_Retenido,			")
            loConsulta.AppendLine("			(CASE WHEN T.Cod_Tip = 'N/CR' THEN -(CASE  WHEN T.Impuesto =0 THEN @lnCero ELSE T.Base END) ELSE @lnCero END) AS Ncr_BI,")
			loConsulta.AppendLine("			(CASE WHEN T.Cod_Tip = 'N/CR' THEN -T.Impuesto	ELSE @lnCero END)	    AS Ncr_IMP,					")
			loConsulta.AppendLine("			(CASE WHEN T.Cod_Tip = 'N/CR' THEN -T.Exento	ELSE @lnCero END)	    AS Ncr_EXE,					")
            loConsulta.AppendLine("			@lnCero																	AS Ncr_EXO,					")
			loConsulta.AppendLine("			@lnCero																	AS Ncr_NS,					")
            loConsulta.AppendLine("			@lnCero																	AS Ncr_SDCF,")
			loConsulta.AppendLine("		    0                                                                       AS Fiscal")
			loConsulta.AppendLine("FROM		#tmpImpuestoDistribuido AS T																		")
            loConsulta.AppendLine("	JOIN	#tmpDias AS Dias_Semana ON Dias_Semana.Dia = T.Dia													")
            loConsulta.AppendLine("	LEFT JOIN #tmpImpuestoDistribuido AS F ON F.Fecha2 = T.Fecha2												")
            loConsulta.AppendLine("		AND	F.Cod_Caj = T.Cod_Caj																				")
            loConsulta.AppendLine("		AND	F.Impresora = T.Impresora																			")
			loConsulta.AppendLine("		AND	F.Documento = T.Documento																			")
            loConsulta.AppendLine("		AND	F.Numero_Documento = T.Numero_Documento																")
            loConsulta.AppendLine("		AND	F.Cod_Tip	= 'N/CR'																				")
            loConsulta.AppendLine("		AND	T.Cod_Tip	= 'N/CR'    																			")
            loConsulta.AppendLine("		AND F.Fiscal = 0																						")
			loConsulta.AppendLine("		AND T.Fiscal = 0																						")
            loConsulta.AppendLine("	LEFT JOIN #tmpDevoluciones AS D 																			")
			loConsulta.AppendLine("		ON	D.Numero_Documento = T.Numero_Documento																")
			loConsulta.AppendLine("		AND	D.Documento = T.Documento																			")
            loConsulta.AppendLine("		AND	D.Tipo_Documento = T.Cod_Tip																		")
            loConsulta.AppendLine("WHERE		T.Fiscal = 0																						")
            loConsulta.AppendLine("   AND		T.Cod_Tip = 'N/CR'																					")
            loConsulta.AppendLine("")
			loConsulta.AppendLine("--'**************************************************************************************")
            loConsulta.AppendLine("--' Selecciona los registros correspondientes a los 'Contribuyentes', sin agrupar       *")
			loConsulta.AppendLine("--'**************************************************************************************")
			loConsulta.AppendLine("INSERT INTO #tmpResultados  (Tipo_Operacion, Fecha1, Fecha2, Dia_Sem, Cod_Suc, Cod_Caj, Impresora,")
            loConsulta.AppendLine("                            Doc_Ini, Doc_Fin, Doc_Ncr, Mon_Otr, Numero_Documento, Tipo_Documento,")
            loConsulta.AppendLine("                            Documento_AfectadoNC, Documento_Afectado, Comprobante_Retencion,")
            loConsulta.AppendLine("                            Monto_Retenido, Ventas_No_Sujetas, Exportacion,")
            loConsulta.AppendLine("                            Rif, Nom_Cli, Porcentaje, Mon_DesC, Mon_RecC, Mon_BruC, Mon_ExeC,")
			loConsulta.AppendLine("                            Mon_ImpC, Mon_DesNC, Mon_RecNC, Mon_BruNC, Mon_ExeNC, Mon_ImpNC,")
            loConsulta.AppendLine("                            Fact_BI, Fact_IMP, Fact_EXE, Fact_EXO, Fact_NS, Fact_SDCF, Fact_Retenido,")
            loConsulta.AppendLine("                            Ncr_BI, Ncr_IMP, Ncr_EXE, Ncr_EXO, Ncr_NS, Ncr_SDCF, Fiscal)")
            loConsulta.AppendLine("     ")
            loConsulta.AppendLine("SELECT		(CASE T.Cod_Tip ")
			loConsulta.AppendLine("                    WHEN 'FACT' THEN 'A'")
            loConsulta.AppendLine("                    WHEN 'RETIVA' THEN 'B'")
			loConsulta.AppendLine("                    WHEN 'N/CR' THEN 'C'")
            loConsulta.AppendLine("                    ELSE 'D'")
            loConsulta.AppendLine("            END)																	AS Tipo_Operacion,			")
			loConsulta.AppendLine("			T.Fecha1																AS Fecha1,					")
            loConsulta.AppendLine("			CAST(T.Fecha2 AS NCHAR(10))												AS Fecha2,					")
			loConsulta.AppendLine("			Dias_Semana.Dia_Sem														AS Dia_Sem, 				")
            loConsulta.AppendLine("			T.Cod_Suc																AS Cod_Suc, 				")
            loConsulta.AppendLine("			T.Cod_Caj																AS Cod_Caj, 				")
            loConsulta.AppendLine("			T.Impresora																AS Impresora,				")
            loConsulta.AppendLine("			''																		AS Doc_Ini, 				")
			loConsulta.AppendLine("			''																		AS Doc_Fin, 				")
            loConsulta.AppendLine("			''				 														AS Doc_Ncr, 				")
            loConsulta.AppendLine("			T.Mon_Otr																AS Mon_Otr, 				")
            loConsulta.AppendLine("			CASE WHEN Cod_Tip = 'RETIVA'																		")
            loConsulta.AppendLine("				THEN																							")
			loConsulta.AppendLine("					ISNULL(D.Numero_Comprobante, T.Numero_Documento)											")
            loConsulta.AppendLine("				ELSE																							")
			loConsulta.AppendLine("					(CASE WHEN T.Documento=''																	")
			loConsulta.AppendLine("						THEN T.Numero_Documento																	")
            loConsulta.AppendLine("						ELSE T.Documento																		")
            loConsulta.AppendLine("					END)																						")
            loConsulta.AppendLine("			END																		AS Numero_Documento,		")
            loConsulta.AppendLine("			T.Cod_Tip																AS Tipo_Documento, 			")
			loConsulta.AppendLine("			''                                                                  	AS Documento_AfectadoNC, 	")
            loConsulta.AppendLine("			ISNULL(CASE WHEN D.Fis_Afectado='' THEN D.Doc_Afectado ELSE D.Fis_Afectado END, '')	AS Documento_Afectado, 	")
			loConsulta.AppendLine("			ISNULL(D.Numero_Comprobante, '')										AS Comprobante_Retencion,	")
			loConsulta.AppendLine("			T.Monto_Retenido														AS Monto_Retenido, 			")
            loConsulta.AppendLine("			T.Ventas_No_Sujetas														AS Ventas_No_Sujetas,		")
            loConsulta.AppendLine("			T.Exportacion															AS Exportacion,				")
            loConsulta.AppendLine("			T.Rif																	AS Rif,						")
            loConsulta.AppendLine("			T.Nom_Cli																AS Nom_Cli,					")
			loConsulta.AppendLine("			T.Porcentaje															AS Porcentaje,				")
            loConsulta.AppendLine("			T.Por_Des*T.Base/100    												AS Mon_DesC,				")
            loConsulta.AppendLine("			T.Por_Rec*T.Base/100    												AS Mon_RecC,				")
            loConsulta.AppendLine("			T.Base																	AS Mon_BruC,				")
            loConsulta.AppendLine("			T.Exento																AS Mon_ExeC,				")
			loConsulta.AppendLine("			T.Impuesto																AS Mon_ImpC,				")
            loConsulta.AppendLine("			@lnCero 																AS Mon_DesNC,				")
			loConsulta.AppendLine("			@lnCero 																AS Mon_RecNC,				")
			loConsulta.AppendLine("			@lnCero 																AS Mon_BruNC,				")
            loConsulta.AppendLine("			@lnCero 																AS Mon_ExeNC,				")
			loConsulta.AppendLine("			@lnCero 																AS Mon_ImpNC, 				")
            loConsulta.AppendLine("			(CASE WHEN T.Cod_Tip = 'FACT' THEN T.Base		ELSE @lnCero END)		AS Fact_BI,					")
			loConsulta.AppendLine("			(CASE WHEN T.Cod_Tip = 'FACT' THEN T.Impuesto	ELSE @lnCero END)		AS Fact_IMP,				")
			loConsulta.AppendLine("			(CASE WHEN T.Cod_Tip = 'FACT' THEN T.Exento		ELSE @lnCero END)		AS Fact_EXE,				")
            loConsulta.AppendLine("			@lnCero																	AS Fact_EXO,				")
            loConsulta.AppendLine("			@lnCero																	AS Fact_NS,					")
            loConsulta.AppendLine("			@lnCero																	AS Fact_SDCF,				")
            loConsulta.AppendLine("			(CASE WHEN T.Cod_Tip = 'RETIVA' THEN T.Exento	ELSE @lnCero END)		AS Fact_Retenido,			")
			loConsulta.AppendLine("			(CASE WHEN T.Cod_Tip = 'N/CR' THEN T.Base		ELSE @lnCero END)		AS Ncr_BI,					")
            loConsulta.AppendLine("			(CASE WHEN T.Cod_Tip = 'N/CR' THEN T.Impuesto	ELSE @lnCero END)		AS Ncr_IMP,					")
            loConsulta.AppendLine("			(CASE WHEN T.Cod_Tip = 'N/CR' THEN T.Exento		ELSE @lnCero END)		AS Ncr_EXE,					")
            loConsulta.AppendLine("			@lnCero																	AS Ncr_EXO,					")
            loConsulta.AppendLine("			@lnCero																	AS Ncr_NS,					")
			loConsulta.AppendLine("			@lnCero																	AS Ncr_SDCF,")
            loConsulta.AppendLine("		    1                                                                       AS Fiscal")
			loConsulta.AppendLine("FROM		#tmpImpuestoDistribuido AS T																		")
			loConsulta.AppendLine("	JOIN	#tmpDias AS Dias_Semana ON Dias_Semana.Dia = T.Dia													")
            loConsulta.AppendLine("	LEFT JOIN #tmpDevoluciones AS D 																			")
            loConsulta.AppendLine("		ON	D.Numero_Documento = T.Numero_Documento																")
            loConsulta.AppendLine("		AND	D.Documento = T.Documento																			")
            loConsulta.AppendLine("		AND	D.Tipo_Documento = T.Cod_Tip																		")
			loConsulta.AppendLine("WHERE		T.Fiscal = 1																						")
            loConsulta.AppendLine("")
			loConsulta.AppendLine("DROP TABLE #tmpDevoluciones")
            loConsulta.AppendLine("DROP TABLE #tmpImpuestoDistribuido")
			loConsulta.AppendLine("")
			loConsulta.AppendLine("--'**************************************************************************************")
            loConsulta.AppendLine("--' Enumera los resultados en el orden final.                                           *")
            loConsulta.AppendLine("--'**************************************************************************************")
            loConsulta.AppendLine("UPDATE  #tmpResultados")
            loConsulta.AppendLine("SET     Orden = X.Orden")
			loConsulta.AppendLine("FROM (  SELECT  ROW_NUMBER() OVER(ORDER BY Fecha1, Impresora, Tipo_Operacion, Numero_Documento, Doc_Ncr, Tipo_Documento) AS Orden,")
            loConsulta.AppendLine("                Fecha1, Impresora, Tipo_Operacion, Numero_Documento, Doc_Ncr, Tipo_Documento")
            loConsulta.AppendLine("        FROM    #tmpResultados")
            loConsulta.AppendLine(") AS x")
            loConsulta.AppendLine("WHERE   x.Fecha1 = #tmpResultados.Fecha1")
			loConsulta.AppendLine("    AND x.Impresora = #tmpResultados.Impresora")
            loConsulta.AppendLine("    AND x.Tipo_Operacion = #tmpResultados.Tipo_Operacion")
			loConsulta.AppendLine("    AND x.Numero_Documento = #tmpResultados.Numero_Documento")
            loConsulta.AppendLine("    AND x.Doc_Ncr = #tmpResultados.Doc_Ncr")
            loConsulta.AppendLine("    AND x.Tipo_Documento = #tmpResultados.Tipo_Documento")
			loConsulta.AppendLine("")
            loConsulta.AppendLine("")
			loConsulta.AppendLine("CREATE CLUSTERED INDEX PK_tmpResultados_Orden")
            loConsulta.AppendLine("ON #tmpResultados([Orden])")
            loConsulta.AppendLine("")
            loConsulta.AppendLine("--'**************************************************************************************")
            loConsulta.AppendLine("--' Genera núnmeros de grupo: para agrupar las filas 'manteniendo el orden'.            *")
			loConsulta.AppendLine("--'**************************************************************************************")
            loConsulta.AppendLine("DECLARE @lnPosicion INT; ")
            loConsulta.AppendLine("DECLARE @lnGrupo INT; ")
            loConsulta.AppendLine("DECLARE @lcTipo CHAR(2); ")
            loConsulta.AppendLine("DECLARE @lnTotal INT; ")
			loConsulta.AppendLine("")
            loConsulta.AppendLine("SET @lnPosicion = 0;")
			loConsulta.AppendLine("SET @lnGrupo = 0;")
			loConsulta.AppendLine("SET @lnTotal = (SELECT COUNT(*) FROM #tmpResultados);")
            loConsulta.AppendLine("SET @lcTipo = '';")
            loConsulta.AppendLine("")
            loConsulta.AppendLine("SET NOCOUNT ON;")
            loConsulta.AppendLine("")
			loConsulta.AppendLine("WHILE (@lnPosicion <@lnTotal)")
            loConsulta.AppendLine("BEGIN")
			loConsulta.AppendLine("    SET @lnPosicion = @lnPosicion + 1;")
			loConsulta.AppendLine("    ")
            loConsulta.AppendLine("    DECLARE @lcNuevoTipo CHAR(2);")
            loConsulta.AppendLine("    DECLARE @lcTipo_Operacion CHAR(1);")
            loConsulta.AppendLine("    DECLARE @llFiscal BIT;")
            loConsulta.AppendLine("    ")
			loConsulta.AppendLine("    SELECT  @lcTipo_Operacion = Tipo_Operacion,")
            loConsulta.AppendLine("            @llFiscal = Fiscal")
            loConsulta.AppendLine("    FROM    #tmpResultados ")
            loConsulta.AppendLine("    WHERE   Orden = @lnPosicion;")
            loConsulta.AppendLine("    ")
			loConsulta.AppendLine("        ")
            loConsulta.AppendLine("    IF (@lcTipo_Operacion = 'A')")
			loConsulta.AppendLine("    BEGIN ")
			loConsulta.AppendLine("        IF (@llFiscal = 0)")
            loConsulta.AppendLine("            SET @lcNuevoTipo = 'F1';")
			loConsulta.AppendLine("        ELSE ")
            loConsulta.AppendLine("            SET @lcNuevoTipo = 'F2';")
			loConsulta.AppendLine("    END")
			loConsulta.AppendLine("    ELSE IF (@lcTipo_Operacion = 'B')")
            loConsulta.AppendLine("    BEGIN ")
            loConsulta.AppendLine("        IF (@llFiscal = 0)")
            loConsulta.AppendLine("            SET @lcNuevoTipo = 'R1';")
            loConsulta.AppendLine("        ELSE ")
			loConsulta.AppendLine("            SET @lcNuevoTipo = 'R2';")
            loConsulta.AppendLine("    END")
            loConsulta.AppendLine("    ELSE IF (@lcTipo_Operacion = 'C')")
            loConsulta.AppendLine("    BEGIN ")
            loConsulta.AppendLine("        IF (@llFiscal = 0)")
			loConsulta.AppendLine("            SET @lcNuevoTipo = 'N1';")
            loConsulta.AppendLine("        ELSE ")
			loConsulta.AppendLine("            SET @lcNuevoTipo = 'N2';")
			loConsulta.AppendLine("    END")
            loConsulta.AppendLine("    ELSE IF (@lcTipo_Operacion = 'D')")
            loConsulta.AppendLine("    BEGIN ")
            loConsulta.AppendLine("        IF (@llFiscal = 0)")
            loConsulta.AppendLine("            SET @lcNuevoTipo = 'O1';")
			loConsulta.AppendLine("        ELSE ")
            loConsulta.AppendLine("            SET @lcNuevoTipo = 'O2';")
			loConsulta.AppendLine("    END")
			loConsulta.AppendLine("    ")
            loConsulta.AppendLine("    IF (@lcNuevoTipo <> @lcTipo)")
            loConsulta.AppendLine("    BEGIN")
            loConsulta.AppendLine("        SET @lcTipo = @lcNuevoTipo;")
            loConsulta.AppendLine("        SET @lnGrupo = @lnGrupo + 1;")
			loConsulta.AppendLine("    END ")
            loConsulta.AppendLine("    ")
            loConsulta.AppendLine("    UPDATE  #tmpResultados")
            loConsulta.AppendLine("    SET     Grupo = @lnGrupo")
            loConsulta.AppendLine("    WHERE   Orden = @lnPosicion;")
			loConsulta.AppendLine("    ")
            loConsulta.AppendLine("END")
			loConsulta.AppendLine("")
            loConsulta.AppendLine("SET NOCOUNT OFF;")
            loConsulta.AppendLine("")
			loConsulta.AppendLine("--'**************************************************************************************")
            loConsulta.AppendLine("--' Resultado final agrupado.                                                           *")
			loConsulta.AppendLine("--'**************************************************************************************")
            loConsulta.AppendLine("SELECT      Grupo, Fecha1, Fecha2, Dia_Sem, Cod_Suc, Cod_Caj, Impresora,")
            loConsulta.AppendLine("            MIN(Doc_Ini)            AS Doc_Ini, ")
            loConsulta.AppendLine("            MAX(Doc_Fin)            AS Doc_Fin, ")
            loConsulta.AppendLine("            MIN(Doc_Ncr)            AS Doc_Ncr, ")
			loConsulta.AppendLine("            SUM(Mon_Otr)            AS Mon_Otr, ")
            loConsulta.AppendLine("            (CASE WHEN Tipo_Documento = '' THEN '' ELSE Numero_Documento END)   As Numero_Documento,")
            loConsulta.AppendLine("            Tipo_Documento          AS Tipo_Documento,")
            loConsulta.AppendLine("            Documento_Afectado      AS Documento_Afectado,")
            loConsulta.AppendLine("            Documento_AfectadoNC    AS Documento_AfectadoNC,")
			loConsulta.AppendLine("            Comprobante_Retencion   AS Comprobante_Retencion,")
            loConsulta.AppendLine("            SUM(Monto_Retenido)     AS Monto_Retenido, ")
			loConsulta.AppendLine("            SUM(Ventas_No_Sujetas)  AS Ventas_No_Sujetas, ")
			loConsulta.AppendLine("            SUM(Ventas_No_Sujetas)  AS Ventas_No_Sujetas, ")
            loConsulta.AppendLine("            Rif                     AS Rif, ")
            loConsulta.AppendLine("            Nom_Cli                 AS Nom_Cli,")
            loConsulta.AppendLine("            MAX(Porcentaje)         AS Porcentaje,")
            loConsulta.AppendLine("            SUM(Mon_DesC)           AS Mon_DesC, ")
			loConsulta.AppendLine("            SUM(Mon_RecC)           AS Mon_RecC, ")
            loConsulta.AppendLine("            SUM(Mon_BruC)           AS Mon_BruC, ")
			loConsulta.AppendLine("            SUM(Mon_ExeC)           AS Mon_ExeC, ")
			loConsulta.AppendLine("            SUM(Mon_ImpC)           AS Mon_ImpC, ")
            loConsulta.AppendLine("            SUM(Mon_DesNC)          AS Mon_DesNC, ")
            loConsulta.AppendLine("            SUM(Mon_RecNC)          AS Mon_RecNC, ")
            loConsulta.AppendLine("            SUM(Mon_BruNC)          AS Mon_BruNC, ")
            loConsulta.AppendLine("            SUM(Mon_ExeNC)          AS Mon_ExeNC, ")
			loConsulta.AppendLine("            SUM(Mon_ImpNC)          AS Mon_ImpNC, ")
            loConsulta.AppendLine("            SUM(Fact_BI)            AS Fact_BI, ")
            loConsulta.AppendLine("            SUM(Fact_IMP)           AS Fact_IMP, ")
            loConsulta.AppendLine("            SUM(Fact_EXE)           AS Fact_EXE, ")
            loConsulta.AppendLine("            SUM(Fact_EXO)           AS Fact_EXO, ")
            loConsulta.AppendLine("            SUM(Fact_NS)            AS Fact_NS, ")
			loConsulta.AppendLine("            SUM(Fact_SDCF)          AS Fact_SDCF, ")
            loConsulta.AppendLine("            SUM(Fact_Retenido)      AS Fact_Retenido, ")
			loConsulta.AppendLine("            SUM(Ncr_BI)             AS Ncr_BI, ")
			loConsulta.AppendLine("            SUM(Ncr_IMP)            AS Ncr_IMP, ")
            loConsulta.AppendLine("            SUM(Ncr_EXE)            AS Ncr_EXE, ")
			loConsulta.AppendLine("            SUM(Ncr_EXO)            AS Ncr_EXO, ")
            loConsulta.AppendLine("            SUM(Ncr_NS)             AS Ncr_NS, ")
			loConsulta.AppendLine("            SUM(Ncr_SDCF)           AS Ncr_SDCF")
			loConsulta.AppendLine("FROM        #tmpResultados")
            loConsulta.AppendLine("GROUP BY    Fecha1, Fecha2, Dia_Sem, Cod_Suc, Cod_Caj,")
            loConsulta.AppendLine("            Impresora, Tipo_Operacion, Grupo,")
            loConsulta.AppendLine("            (CASE WHEN Tipo_Documento = '' THEN '' ELSE Numero_Documento END), ")
			loConsulta.AppendLine("            Tipo_Documento, Grupo, Documento_Afectado, Documento_AfectadoNC,")
            loConsulta.AppendLine("            Comprobante_Retencion, Rif, Nom_Cli")
            loConsulta.AppendLine("ORDER BY    Fecha2 ASC, Impresora ASC, Grupo")
            loConsulta.AppendLine("")
            loConsulta.AppendLine("            ")
			loConsulta.AppendLine("DROP TABLE #tmpDias;")
			loConsulta.AppendLine("--DROP TABLE #tmpRegistros;")
            loConsulta.AppendLine("DROP TABLE #tmpResultados;")
            loConsulta.AppendLine("")
            loConsulta.AppendLine("")
            loConsulta.AppendLine("")


            Dim loServicios As New cusDatos.goDatos

			'Me.mEscribirConsulta(loConsulta.ToString())
            'Dim lcConexion AS String = "Data Source= Galileo; Initial Catalog= Factory_Administrativo_ga08c06;User Id= factory;Password = factory;"
            'Dim laDatosReporte As DataSet = loServicios.mObtenerTodosSinEsquema("SQLSERVER", lcConexion, loConsulta.ToString, "curReportes")
            Dim laDatosReporte As DataSet = loServicios.mObtenerTodosSinEsquema(loConsulta.ToString, "curReportes")

            '-------------------------------------------------------------------------------------------------------
            ' Verificando si el select (tabla nº0) trae registros
            '-------------------------------------------------------------------------------------------------------

            If (laDatosReporte.Tables(0).Rows.Count <= 0) Then
                Me.WbcAdministradorMensajeModal.mMostrarMensajeModal("Información", _
                                          "No se Encontraron Registros para los Parámetros Especificados. ", _
                                           vis3Controles.wbcAdministradorMensajeModal.enumTipoMensaje.KN_Informacion, _
                                           "350px", _
                                           "200px")
            End If


            loObjetoReporte = cusAplicacion.goReportes.mCargarReporte("rLVentas_Dacron", laDatosReporte)

            Me.mTraducirReporte(loObjetoReporte)

            Me.mFormatearCamposReporte(loObjetoReporte)

            Me.crvrLVentas_Resumido.ReportSource = loObjetoReporte

        Catch loExcepcion As Exception

            Me.WbcAdministradorMensajeModal.mMostrarMensajeModal("Error", _
                          "No se pudo Completar el Proceso: " & loExcepcion.Message, _
                           vis3Controles.wbcAdministradorMensajeModal.enumTipoMensaje.KN_Error, _
                           "auto", _
                           "auto")

        End Try

    End Sub

    Protected Sub Page_Unload(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Unload

        Try

            loObjetoReporte.Close()

        Catch loExcepcion As Exception

        End Try

    End Sub

End Class
'-------------------------------------------------------------------------------------------'
' Fin del codigo																			'
'-------------------------------------------------------------------------------------------'
' RJG: 16/10/13: Codigo inicial (A partir de rLVentas_Resumido_75).							'
'-------------------------------------------------------------------------------------------'
