'-------------------------------------------------------------------------------------------'
' Inicio del codigo
'-------------------------------------------------------------------------------------------'
' Importando librerias 
'-------------------------------------------------------------------------------------------'
Imports System.Data

'-------------------------------------------------------------------------------------------'
' Inicio de clase "rMInventarios_Articulos "
'-------------------------------------------------------------------------------------------'
Partial Class rMInventarios_Articulos
    Inherits vis2formularios.frmReporte

    Dim loObjetoReporte As CrystalDecisions.CrystalReports.Engine.ReportDocument

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load

        Try

            Dim lcParametro0Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(0))
            Dim lcParametro0Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(0))
            Dim lcParametro1Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(1), goServicios.enuOpcionesRedondeo.KN_FechaInicioDelDia)
            Dim lcParametro1Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(1), goServicios.enuOpcionesRedondeo.KN_FechaFinDelDia)
            Dim lcParametro2Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(2))
            Dim lcParametro2Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(2))
            Dim lcParametro3Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(3))
            Dim lcParametro3Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(3))
            Dim lcParametro4Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(4))
            Dim lcParametro4Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(4))
            Dim lcParametro5Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(5))
            Dim lcParametro5Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(5))
            Dim lcParametro6Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(6))
            Dim lcParametro6Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(6))
            Dim lcParametro7Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(7))
            Dim lcParametro7Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(7))
            Dim lcParametro8Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(8))
            Dim lcParametro8Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(8))
            Dim lcParametro9Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(9))
            Dim lcParametro9Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(9))
            Dim lcParametro10Desde As String = goServicios.mObtenerListaFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(10))

            Dim lcParametro11Desde As String = goServicios.mObtenerListaFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(11))

            Dim lcParametro12Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(12))
            Dim lcParametro12Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(12))
            Dim lcParametro13Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(13))
            Dim lcParametro13Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(13))

            Dim lcOrdenamiento As String = cusAplicacion.goReportes.pcOrden
            Dim lcCosto As String = "Cos_Pro1"
            Dim loComandoSeleccionar As New StringBuilder()

            Select Case lcParametro11Desde
                Case "'Promedio MP'"
                    lcCosto = "Cos_Pro1"
                Case "'Ultimo MP'"
                    lcCosto = "Cos_Ult1"
                Case "'Anterior MP'"
                    lcCosto = "Cos_Ant1"
                Case "'Promedio MS'"
                    lcCosto = "Cos_Pro2"
                Case "'Ultimo MS'"
                    lcCosto = "Cos_Ult2"
                Case "'Anterior MS'"
                    lcCosto = "Cos_Ant2"
            End Select

            '---------------------------------------------------------------------------------------------------------------'
            ' El código del Almacén de Tránsito se requiere para los Traslados entre Almacénes Confirmados o Procesados.	'
            '---------------------------------------------------------------------------------------------------------------'
            Dim lcAlmacenTransito As String
            lcAlmacenTransito = goServicios.mObtenerCampoFormatoSQL(goOpciones.mObtener("CODALMTRA", "C"))

            Select Case lcParametro10Desde

                Case "'Todos'"

                    ' Select de la tabla de Ajustes
                    loComandoSeleccionar.AppendLine("SELECT		'Ajustes'								AS	Operacion, ")
                    loComandoSeleccionar.AppendLine("			Ajustes.Documento						AS	Documento, ")
                    loComandoSeleccionar.AppendLine("			Renglones_Ajustes.Cod_Art				AS	Cod_Art, ")
                    loComandoSeleccionar.AppendLine("			Ajustes.Fec_Ini							AS	Fec_Ini, ")
                    loComandoSeleccionar.AppendLine("			Renglones_Ajustes.Renglon				AS	Renglon, ")
                    loComandoSeleccionar.AppendLine("			'No Aplica'								AS	Cliente, ")
                    loComandoSeleccionar.AppendLine("			Renglones_Ajustes.Cod_Alm				AS	Cod_Alm, ")
                    loComandoSeleccionar.AppendLine("			(CASE WHEN Renglones_Ajustes.Tipo = 'Salida' THEN Renglones_Ajustes.Can_Art1 ELSE 0.0 END)		AS	Can_Sal, ")
                    loComandoSeleccionar.AppendLine("			(CASE WHEN Renglones_Ajustes.Tipo = 'Entrada'  THEN Renglones_Ajustes.Can_Art1 ELSE 0.0 END)		AS	Can_Ent, ")
                    loComandoSeleccionar.AppendLine("			Renglones_Ajustes.Tipo					AS	Tipo, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Ajustes." & lcCosto & "       AS	Cos_Pro, ")
                    loComandoSeleccionar.AppendLine(" 			Articulos.Nom_Art						AS	Nom_Art, ")
                    loComandoSeleccionar.AppendLine(" 			" & lcParametro11Desde & "	            AS	Costo ")
                    loComandoSeleccionar.AppendLine("INTO		#curTemporal ")
                    loComandoSeleccionar.AppendLine("FROM		Ajustes, ")
                    loComandoSeleccionar.AppendLine("			Renglones_Ajustes, ")
                    loComandoSeleccionar.AppendLine("			Articulos ")
                    loComandoSeleccionar.AppendLine("WHERE		Ajustes.Documento		=	Renglones_Ajustes.Documento ")
                    loComandoSeleccionar.AppendLine(" 		AND	Articulos.Cod_Art		=	Renglones_Ajustes.Cod_Art ")
                    loComandoSeleccionar.AppendLine(" 		AND	Ajustes.Status			=	'Confirmado' ")
                    loComandoSeleccionar.AppendLine(" 		AND	Renglones_Ajustes.Tipo	IN	('Entrada', 'Salida') ")
                    loComandoSeleccionar.AppendLine(" 		AND	Articulos.Cod_Art				BETWEEN " & lcParametro0Desde)
                    loComandoSeleccionar.AppendLine(" 			AND	" & lcParametro0Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND	Ajustes.Fec_Ini					BETWEEN " & lcParametro1Desde)
                    loComandoSeleccionar.AppendLine(" 			AND	" & lcParametro1Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND	Renglones_Ajustes.Cod_Alm		BETWEEN " & lcParametro2Desde)
                    loComandoSeleccionar.AppendLine(" 			AND	" & lcParametro2Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND	Articulos.Cod_Dep				BETWEEN " & lcParametro3Desde)
                    loComandoSeleccionar.AppendLine(" 			AND	" & lcParametro3Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND	Articulos.Cod_Sec				BETWEEN " & lcParametro4Desde)
                    loComandoSeleccionar.AppendLine(" 			AND	" & lcParametro4Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND	Articulos.Cod_Mar				BETWEEN " & lcParametro5Desde)
                    loComandoSeleccionar.AppendLine(" 			AND	" & lcParametro5Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND	Articulos.Cod_Cla				BETWEEN " & lcParametro6Desde)
                    loComandoSeleccionar.AppendLine(" 			AND	" & lcParametro6Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND	Articulos.Cod_Tip				BETWEEN " & lcParametro7Desde)
                    loComandoSeleccionar.AppendLine(" 			AND	" & lcParametro7Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND	Articulos.Cod_Pro				BETWEEN " & lcParametro8Desde)
                    loComandoSeleccionar.AppendLine(" 			AND	" & lcParametro8Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND	Articulos.Cod_Suc				BETWEEN " & lcParametro9Desde)
                    loComandoSeleccionar.AppendLine(" 			AND	" & lcParametro9Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND	Articulos.Cod_Uni1				BETWEEN " & lcParametro12Desde)
                    loComandoSeleccionar.AppendLine(" 			AND	" & lcParametro12Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND	Articulos.Cod_Ubi				BETWEEN " & lcParametro13Desde)
                    loComandoSeleccionar.AppendLine(" 			AND	" & lcParametro13Hasta)

                    ' Union con Select de la tabla de Traslados en las Salidas
                    loComandoSeleccionar.AppendLine("UNION ALL ")
                    loComandoSeleccionar.AppendLine("SELECT		'Traslados'								AS	Operacion, ")
                    loComandoSeleccionar.AppendLine(" 			Traslados.Documento						AS	Documento, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Traslados.Cod_Art				AS	Cod_Art, ")
                    loComandoSeleccionar.AppendLine(" 			Traslados.Fec_Ini						AS	Fec_Ini, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Traslados.Renglon				AS	Renglon, ")
                    loComandoSeleccionar.AppendLine(" 			'No Aplica'								AS	Cliente, ")
                    loComandoSeleccionar.AppendLine(" 			Traslados.Alm_Ori						AS	Cod_Alm, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Traslados.Can_Art1			AS	Can_Sal, ")
                    loComandoSeleccionar.AppendLine(" 			0.0										AS	Can_Ent, ")
                    loComandoSeleccionar.AppendLine(" 			'Salida'								AS	Tipo, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Traslados." & lcCosto & "     AS	Cos_Pro, ")
                    loComandoSeleccionar.AppendLine(" 			Articulos.Nom_Art						AS	Nom_Art, ")
                    loComandoSeleccionar.AppendLine(" 			" & lcParametro11Desde & "	            AS	Costo ")
                    loComandoSeleccionar.AppendLine("FROM		Traslados, ")
                    loComandoSeleccionar.AppendLine("			Renglones_Traslados, ")
                    loComandoSeleccionar.AppendLine("			Articulos ")
                    loComandoSeleccionar.AppendLine("WHERE		Traslados.Documento		=	Renglones_Traslados.Documento ")
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Art		=	Renglones_Traslados.Cod_Art ")
                    loComandoSeleccionar.AppendLine(" 		AND Traslados.Status		IN ('Confirmado', 'Procesado') ")
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Art				BETWEEN " & lcParametro0Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro0Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Traslados.Fec_Ini				BETWEEN " & lcParametro1Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro1Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Traslados.Alm_Ori				BETWEEN " & lcParametro2Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro2Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Dep				BETWEEN " & lcParametro3Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro3Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Sec				BETWEEN " & lcParametro4Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro4Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Mar				BETWEEN " & lcParametro5Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro5Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Cla				BETWEEN " & lcParametro6Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro6Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Tip				BETWEEN " & lcParametro7Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro7Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Pro				BETWEEN " & lcParametro8Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro8Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Traslados.Cod_Suc				BETWEEN " & lcParametro9Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro9Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Uni1				BETWEEN " & lcParametro12Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro12Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Ubi				BETWEEN " & lcParametro13Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro13Hasta)

                    ' Union con Select de la tabla de Traslados en las Entradas
                    loComandoSeleccionar.AppendLine("UNION ALL ")
                    loComandoSeleccionar.AppendLine("SELECT		'Traslados'								AS	Operacion, ")
                    loComandoSeleccionar.AppendLine(" 			Traslados.Documento						AS	Documento, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Traslados.Cod_Art				AS	Cod_Art, ")
                    loComandoSeleccionar.AppendLine(" 			Traslados.Fec_Ini						AS	Fec_Ini, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Traslados.Renglon				AS	Renglon, ")
                    loComandoSeleccionar.AppendLine(" 			'No Aplica'								AS	Cliente, ")	
                    loComandoSeleccionar.AppendLine(" 			CASE Traslados.Status					")
                    loComandoSeleccionar.AppendLine(" 				WHEN 'Confirmado'	THEN " & lcAlmacenTransito)
                    loComandoSeleccionar.AppendLine(" 				WHEN 'Procesado'	THEN Traslados.Alm_Des")
                    loComandoSeleccionar.AppendLine(" 			END										AS	Cod_Alm, ")	
                    loComandoSeleccionar.AppendLine(" 			0.0										AS	Can_Sal, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Traslados.Can_Art1			AS	Can_Ent, ")
                    loComandoSeleccionar.AppendLine(" 			'Entrada'								AS	Tipo, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Traslados." & lcCosto & "     AS	Cos_Pro, ")
                    loComandoSeleccionar.AppendLine(" 			Articulos.Nom_Art						AS	Nom_Art, ")
                    loComandoSeleccionar.AppendLine(" 			" & lcParametro11Desde & "	            AS	Costo ")
                    loComandoSeleccionar.AppendLine("FROM		Traslados, ")
                    loComandoSeleccionar.AppendLine("			Renglones_Traslados, ")
                    loComandoSeleccionar.AppendLine("			Articulos ")
                    loComandoSeleccionar.AppendLine("WHERE		Traslados.Documento		=	Renglones_Traslados.Documento ")
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Art		=	Renglones_Traslados.Cod_Art ")
                    loComandoSeleccionar.AppendLine(" 		AND Traslados.Status		IN ('Confirmado', 'Procesado') ")
                    loComandoSeleccionar.AppendLine("		AND Articulos.Cod_Art			BETWEEN " & lcParametro0Desde)
                    loComandoSeleccionar.AppendLine("			AND " & lcParametro0Hasta)
                    loComandoSeleccionar.AppendLine("		AND Traslados.Fec_Ini			BETWEEN " & lcParametro1Desde)
                    loComandoSeleccionar.AppendLine("			AND " & lcParametro1Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND	(CASE	Traslados.Status				")
                    loComandoSeleccionar.AppendLine(" 				WHEN 'Confirmado' THEN " & lcAlmacenTransito & "")
                    loComandoSeleccionar.AppendLine(" 				ELSE Traslados.Alm_Des				" )
                    loComandoSeleccionar.AppendLine(" 			END)						BETWEEN " & lcParametro2Desde)
                    loComandoSeleccionar.AppendLine("			AND " & lcParametro2Hasta)
                    loComandoSeleccionar.AppendLine("		AND Articulos.Cod_Dep			BETWEEN " & lcParametro3Desde)
                    loComandoSeleccionar.AppendLine("			AND " & lcParametro3Hasta)
                    loComandoSeleccionar.AppendLine("		AND Articulos.Cod_Sec			BETWEEN " & lcParametro4Desde)
                    loComandoSeleccionar.AppendLine("			AND " & lcParametro4Hasta)
                    loComandoSeleccionar.AppendLine("		AND Articulos.Cod_Mar			BETWEEN " & lcParametro5Desde)
                    loComandoSeleccionar.AppendLine("			AND " & lcParametro5Hasta)
                    loComandoSeleccionar.AppendLine("		AND Articulos.Cod_Cla			BETWEEN " & lcParametro6Desde)
                    loComandoSeleccionar.AppendLine("			AND " & lcParametro6Hasta)
                    loComandoSeleccionar.AppendLine("		AND Articulos.Cod_Tip			BETWEEN " & lcParametro7Desde)
                    loComandoSeleccionar.AppendLine("			AND " & lcParametro7Hasta)
                    loComandoSeleccionar.AppendLine("		AND Articulos.Cod_Pro			BETWEEN " & lcParametro8Desde)
                    loComandoSeleccionar.AppendLine("			AND " & lcParametro8Hasta)
                    loComandoSeleccionar.AppendLine("		AND Traslados.Cod_Suc			BETWEEN " & lcParametro9Desde)
                    loComandoSeleccionar.AppendLine("			AND " & lcParametro9Hasta)
                    loComandoSeleccionar.AppendLine("		AND Articulos.Cod_Uni1			BETWEEN " & lcParametro12Desde)
					loComandoSeleccionar.AppendLine("			AND " & lcParametro12Hasta)
					loComandoSeleccionar.AppendLine("		AND Articulos.Cod_Ubi			BETWEEN " & lcParametro13Desde)
					loComandoSeleccionar.AppendLine("			AND " & lcParametro13Hasta)

                    ' Union con Select de la tabla de Entregas
                    loComandoSeleccionar.AppendLine("UNION ALL ")
                    loComandoSeleccionar.AppendLine("SELECT			'Entregas'							AS	Operacion, ")
                    loComandoSeleccionar.AppendLine(" 				Entregas.Documento					AS	Documento, ")
                    loComandoSeleccionar.AppendLine(" 				Renglones_Entregas.Cod_Art			AS	Cod_Art, ")
                    loComandoSeleccionar.AppendLine(" 				Entregas.Fec_Ini					AS	Fec_Ini, ")
                    loComandoSeleccionar.AppendLine(" 				Renglones_Entregas.Renglon			AS	Renglon, ")
                    loComandoSeleccionar.AppendLine(" 				Entregas.Cod_Cli					AS	Cliente, ")
                    loComandoSeleccionar.AppendLine(" 				Renglones_Entregas.Cod_Alm			AS	Cod_Alm, ")
                    loComandoSeleccionar.AppendLine(" 				Renglones_Entregas.Can_Art1			AS	Can_Sal, ")
                    loComandoSeleccionar.AppendLine(" 				0.0									AS	Can_Ent, ")
                    loComandoSeleccionar.AppendLine(" 				'Salida'							AS	Tipo, ")
                    loComandoSeleccionar.AppendLine(" 				Renglones_Entregas." & lcCosto & "  AS	Cos_Pro, ")
                    loComandoSeleccionar.AppendLine(" 				Articulos.Nom_Art					AS	Nom_Art, ")
                    loComandoSeleccionar.AppendLine(" 				" & lcParametro11Desde & "	        AS	Costo ")
                    loComandoSeleccionar.AppendLine("FROM			Entregas, ")
                    loComandoSeleccionar.AppendLine("				Renglones_Entregas, ")
                    loComandoSeleccionar.AppendLine("				Articulos ")
                    loComandoSeleccionar.AppendLine("WHERE			Entregas.Documento			=	Renglones_Entregas.Documento ")
                    loComandoSeleccionar.AppendLine(" 			AND Articulos.Cod_Art			=	Renglones_Entregas.Cod_Art ")
                    loComandoSeleccionar.AppendLine(" 				AND Entregas.Status			IN	('Confirmado', 'Afectado', 'Procesado') ")
                    loComandoSeleccionar.AppendLine(" 			AND Articulos.Cod_Art				BETWEEN " & lcParametro0Desde)
                    loComandoSeleccionar.AppendLine(" 				AND " & lcParametro0Hasta)
                    loComandoSeleccionar.AppendLine(" 			AND Entregas.Fec_Ini				BETWEEN " & lcParametro1Desde)
                    loComandoSeleccionar.AppendLine(" 				AND " & lcParametro1Hasta)
                    loComandoSeleccionar.AppendLine(" 			AND Renglones_Entregas.Cod_Alm		BETWEEN " & lcParametro2Desde)
                    loComandoSeleccionar.AppendLine(" 				AND " & lcParametro2Hasta)
                    loComandoSeleccionar.AppendLine(" 			AND Articulos.Cod_Dep				BETWEEN " & lcParametro3Desde)
                    loComandoSeleccionar.AppendLine(" 				AND " & lcParametro3Hasta)
                    loComandoSeleccionar.AppendLine(" 			AND Articulos.Cod_Sec				BETWEEN " & lcParametro4Desde)
                    loComandoSeleccionar.AppendLine(" 				AND " & lcParametro4Hasta)
                    loComandoSeleccionar.AppendLine(" 			AND Articulos.Cod_Mar				BETWEEN " & lcParametro5Desde)
                    loComandoSeleccionar.AppendLine(" 				AND " & lcParametro5Hasta)
                    loComandoSeleccionar.AppendLine(" 			AND Articulos.Cod_Cla				BETWEEN " & lcParametro6Desde)
                    loComandoSeleccionar.AppendLine(" 				AND " & lcParametro6Hasta)
                    loComandoSeleccionar.AppendLine(" 			AND Articulos.Cod_Tip				BETWEEN " & lcParametro7Desde)
                    loComandoSeleccionar.AppendLine(" 				AND " & lcParametro7Hasta)
                    loComandoSeleccionar.AppendLine(" 			AND Articulos.Cod_Pro				BETWEEN " & lcParametro8Desde)
                    loComandoSeleccionar.AppendLine(" 				AND " & lcParametro8Hasta)
                    loComandoSeleccionar.AppendLine(" 			AND Entregas.Cod_Suc				BETWEEN " & lcParametro9Desde)
                    loComandoSeleccionar.AppendLine(" 				AND " & lcParametro9Hasta)
                    loComandoSeleccionar.AppendLine(" 			AND Articulos.Cod_Uni1				BETWEEN " & lcParametro12Desde)
                    loComandoSeleccionar.AppendLine(" 				AND " & lcParametro12Hasta)
                    loComandoSeleccionar.AppendLine(" 			AND Articulos.Cod_Ubi				BETWEEN " & lcParametro13Desde)
                    loComandoSeleccionar.AppendLine(" 				AND " & lcParametro13Hasta)

                    ' Union con Select de la tabla de Facturas
                    loComandoSeleccionar.AppendLine("UNION ALL ")
                    loComandoSeleccionar.AppendLine("SELECT			'Facturas'							AS	Operacion, ")
                    loComandoSeleccionar.AppendLine(" 				Facturas.Documento					AS	Documento, ")
                    loComandoSeleccionar.AppendLine(" 				Renglones_Facturas.Cod_Art			AS	Cod_Art, ")
                    loComandoSeleccionar.AppendLine(" 				Facturas.Fec_Ini					AS	Fec_Ini, ")
                    loComandoSeleccionar.AppendLine(" 				Renglones_Facturas.Renglon			AS	Renglon, ")
                    loComandoSeleccionar.AppendLine(" 				Facturas.Cod_Cli					AS	Cliente, ")
                    loComandoSeleccionar.AppendLine(" 				Renglones_Facturas.Cod_Alm			AS	Cod_Alm, ")
                    loComandoSeleccionar.AppendLine(" 				Renglones_Facturas.Can_Art1			AS	Can_Sal, ")
                    loComandoSeleccionar.AppendLine(" 				0.0									AS	Can_Ent, ")
                    loComandoSeleccionar.AppendLine(" 				'Salida'							AS	Tipo, ")
                    loComandoSeleccionar.AppendLine(" 				Renglones_Facturas." & lcCosto & "  AS	Cos_Pro, ")
                    loComandoSeleccionar.AppendLine(" 				Articulos.Nom_Art					AS	Nom_Art, ")
                    loComandoSeleccionar.AppendLine(" 				" & lcParametro11Desde & "	        AS	Costo ")
                    loComandoSeleccionar.AppendLine("FROM			Facturas, ")
                    loComandoSeleccionar.AppendLine(" 				Renglones_Facturas, ")
                    loComandoSeleccionar.AppendLine(" 				Articulos ")
                    loComandoSeleccionar.AppendLine("WHERE			Facturas.Documento			=	Renglones_Facturas.Documento ")
                    loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Art			=	Renglones_Facturas.Cod_Art ")
                    loComandoSeleccionar.AppendLine("			AND Facturas.Status				IN	('Confirmado', 'Afectado', 'Procesado') ")
                    loComandoSeleccionar.AppendLine("			AND Renglones_Facturas.Tip_Ori			<>	'Entregas' ")
                    loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Art				BETWEEN " & lcParametro0Desde)
                    loComandoSeleccionar.AppendLine("				AND " & lcParametro0Hasta)
                    loComandoSeleccionar.AppendLine("			AND Facturas.Fec_Ini				BETWEEN " & lcParametro1Desde)
                    loComandoSeleccionar.AppendLine("				AND " & lcParametro1Hasta)
                    loComandoSeleccionar.AppendLine("			AND Renglones_Facturas.Cod_Alm		BETWEEN " & lcParametro2Desde)
                    loComandoSeleccionar.AppendLine("				AND " & lcParametro2Hasta)
                    loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Dep				BETWEEN " & lcParametro3Desde)
                    loComandoSeleccionar.AppendLine("				AND " & lcParametro3Hasta)
                    loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Sec				BETWEEN " & lcParametro4Desde)
                    loComandoSeleccionar.AppendLine("				AND " & lcParametro4Hasta)
                    loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Mar				BETWEEN " & lcParametro5Desde)
                    loComandoSeleccionar.AppendLine("				AND " & lcParametro5Hasta)
                    loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Cla				BETWEEN " & lcParametro6Desde)
                    loComandoSeleccionar.AppendLine("				AND " & lcParametro6Hasta)
                    loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Tip				BETWEEN " & lcParametro7Desde)
                    loComandoSeleccionar.AppendLine("				AND " & lcParametro7Hasta)
                    loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Pro				BETWEEN " & lcParametro8Desde)
                    loComandoSeleccionar.AppendLine("				AND " & lcParametro8Hasta)
                    loComandoSeleccionar.AppendLine("			AND Facturas.Cod_Suc				BETWEEN " & lcParametro9Desde)
                    loComandoSeleccionar.AppendLine("				AND " & lcParametro9Hasta)
                    loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Uni1				BETWEEN " & lcParametro12Desde)
                    loComandoSeleccionar.AppendLine("				AND " & lcParametro12Hasta)
                    loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Ubi				BETWEEN " & lcParametro13Desde)
                    loComandoSeleccionar.AppendLine("				AND " & lcParametro13Hasta)

                    ' Union con Select de la tabla de Recepciones
                    loComandoSeleccionar.AppendLine("UNION ALL ")
                    loComandoSeleccionar.AppendLine("SELECT			'Recepciones'						AS	Operacion, ")
                    loComandoSeleccionar.AppendLine(" 				Recepciones.Documento				AS	Documento, ")
                    loComandoSeleccionar.AppendLine(" 				Renglones_Recepciones.Cod_Art		AS	Cod_Art, ")
                    loComandoSeleccionar.AppendLine(" 				Recepciones.Fec_Ini					AS	Fec_Ini, ")
                    loComandoSeleccionar.AppendLine(" 				Renglones_Recepciones.Renglon		AS	Renglon, ")
                    loComandoSeleccionar.AppendLine(" 				Recepciones.Cod_Pro					AS	Cliente, ")
                    loComandoSeleccionar.AppendLine(" 				Renglones_Recepciones.Cod_Alm		AS	Cod_Alm, ")
                    loComandoSeleccionar.AppendLine(" 				0.0									AS	Can_Sal, ")
                    loComandoSeleccionar.AppendLine(" 				Renglones_Recepciones.Can_Art1		AS	Can_Ent, ")
                    loComandoSeleccionar.AppendLine(" 				'Entrada'							AS	Tipo, ")
                    loComandoSeleccionar.AppendLine(" 				Renglones_Recepciones." & lcCosto & " AS	Cos_Pro, ")
                    loComandoSeleccionar.AppendLine(" 				Articulos.Nom_Art					AS	Nom_Art, ")
                    loComandoSeleccionar.AppendLine(" 				" & lcParametro11Desde & "	        AS	Costo ")
                    loComandoSeleccionar.AppendLine("FROM			Recepciones, ")
                    loComandoSeleccionar.AppendLine(" 				Renglones_Recepciones, ")
                    loComandoSeleccionar.AppendLine(" 				Articulos ")
                    loComandoSeleccionar.AppendLine("WHERE		Recepciones.Documento			=	Renglones_Recepciones.Documento ")
                    loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Art			=	Renglones_Recepciones.Cod_Art ")
                    loComandoSeleccionar.AppendLine("			AND Recepciones.Status			IN	('Confirmado', 'Afectado', 'Procesado') ")
                    loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Art				BETWEEN " & lcParametro0Desde)
                    loComandoSeleccionar.AppendLine("				AND " & lcParametro0Hasta)
                    loComandoSeleccionar.AppendLine("			AND Recepciones.Fec_Ini				BETWEEN " & lcParametro1Desde)
                    loComandoSeleccionar.AppendLine("				AND " & lcParametro1Hasta)
                    loComandoSeleccionar.AppendLine("			AND Renglones_Recepciones.Cod_Alm	BETWEEN " & lcParametro2Desde)
                    loComandoSeleccionar.AppendLine("				AND " & lcParametro2Hasta)
                    loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Dep				BETWEEN " & lcParametro3Desde)
                    loComandoSeleccionar.AppendLine("				AND " & lcParametro3Hasta)
                    loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Sec				BETWEEN " & lcParametro4Desde)
                    loComandoSeleccionar.AppendLine("				AND " & lcParametro4Hasta)
                    loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Mar				BETWEEN " & lcParametro5Desde)
                    loComandoSeleccionar.AppendLine("				AND " & lcParametro5Hasta)
                    loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Cla				BETWEEN " & lcParametro6Desde)
                    loComandoSeleccionar.AppendLine("				AND " & lcParametro6Hasta)
                    loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Tip				BETWEEN " & lcParametro7Desde)
                    loComandoSeleccionar.AppendLine("				AND " & lcParametro7Hasta)
                    loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Pro				BETWEEN " & lcParametro8Desde)
                    loComandoSeleccionar.AppendLine("				AND " & lcParametro8Hasta)
                    loComandoSeleccionar.AppendLine("			AND Recepciones.Cod_Suc				BETWEEN " & lcParametro9Desde)
                    loComandoSeleccionar.AppendLine("				AND " & lcParametro9Hasta)
                    loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Uni1				BETWEEN " & lcParametro12Desde)
                    loComandoSeleccionar.AppendLine("				AND " & lcParametro12Hasta)
                    loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Ubi				BETWEEN " & lcParametro13Desde)
                    loComandoSeleccionar.AppendLine("				AND " & lcParametro13Hasta)

                    ' Union con Select de la tabla de Compras
                    loComandoSeleccionar.AppendLine("UNION ALL ")
                    loComandoSeleccionar.AppendLine("SELECT			'Compras'							AS	Operacion, ")
                    loComandoSeleccionar.AppendLine("				Compras.Documento					AS	Documento, ")
                    loComandoSeleccionar.AppendLine("				Renglones_Compras.Cod_Art			AS	Cod_Art, ")
                    loComandoSeleccionar.AppendLine("				Compras.Fec_Ini						AS	Fec_Ini, ")
                    loComandoSeleccionar.AppendLine("				Renglones_Compras.Renglon			AS	Renglon, ")
                    loComandoSeleccionar.AppendLine("				Compras.Cod_Pro						AS	Cliente, ")
                    loComandoSeleccionar.AppendLine("				Renglones_Compras.Cod_Alm			AS	Cod_Alm, ")
                    loComandoSeleccionar.AppendLine("				0.0									AS	Can_Sal, ")
                    loComandoSeleccionar.AppendLine("				Renglones_Compras.Can_Art1			AS	Can_Ent, ")
                    loComandoSeleccionar.AppendLine("				'Entrada'							AS	Tipo, ")
                    loComandoSeleccionar.AppendLine("				Renglones_Compras." & lcCosto & "   AS	Cos_Pro, ")
                    loComandoSeleccionar.AppendLine("				Articulos.Nom_Art					AS	Nom_Art, ")
                    loComandoSeleccionar.AppendLine("				" & lcParametro11Desde & "	        AS	Costo ")
                    loComandoSeleccionar.AppendLine("FROM			Compras, ")
                    loComandoSeleccionar.AppendLine("				Renglones_Compras, ")
                    loComandoSeleccionar.AppendLine("				Articulos ")
                    loComandoSeleccionar.AppendLine("WHERE			Compras.Documento				=	Renglones_Compras.Documento ")
                    loComandoSeleccionar.AppendLine("				AND Articulos.Cod_Art			=	Renglones_Compras.Cod_Art ")
                    loComandoSeleccionar.AppendLine("				AND Compras.Status				IN	('Confirmado', 'Afectado', 'Procesado') ")
                    loComandoSeleccionar.AppendLine(" 				AND Renglones_Compras.Tip_Ori	<>	'Recepciones' ")
                    loComandoSeleccionar.AppendLine("				AND Articulos.Cod_Art			BETWEEN " & lcParametro0Desde)
                    loComandoSeleccionar.AppendLine("					AND " & lcParametro0Hasta)
                    loComandoSeleccionar.AppendLine("				AND Compras.Fec_Ini				BETWEEN " & lcParametro1Desde)
                    loComandoSeleccionar.AppendLine("					AND " & lcParametro1Hasta)
                    loComandoSeleccionar.AppendLine("				AND Renglones_Compras.Cod_Alm	BETWEEN " & lcParametro2Desde)
                    loComandoSeleccionar.AppendLine("					AND " & lcParametro2Hasta)
                    loComandoSeleccionar.AppendLine("				AND Articulos.Cod_Dep			BETWEEN " & lcParametro3Desde)
                    loComandoSeleccionar.AppendLine("					AND " & lcParametro3Hasta)
                    loComandoSeleccionar.AppendLine("				AND Articulos.Cod_Sec			BETWEEN " & lcParametro4Desde)
                    loComandoSeleccionar.AppendLine("					AND " & lcParametro4Hasta)
                    loComandoSeleccionar.AppendLine("				AND Articulos.Cod_Mar			BETWEEN " & lcParametro5Desde)
                    loComandoSeleccionar.AppendLine("					AND " & lcParametro5Hasta)
                    loComandoSeleccionar.AppendLine("				AND Articulos.Cod_Cla			BETWEEN " & lcParametro6Desde)
                    loComandoSeleccionar.AppendLine("					AND " & lcParametro6Hasta)
                    loComandoSeleccionar.AppendLine("				AND Articulos.Cod_Tip			BETWEEN " & lcParametro7Desde)
                    loComandoSeleccionar.AppendLine("					AND " & lcParametro7Hasta)
                    loComandoSeleccionar.AppendLine("				AND Articulos.Cod_Pro			BETWEEN " & lcParametro8Desde)
                    loComandoSeleccionar.AppendLine("					AND " & lcParametro8Hasta)
                    loComandoSeleccionar.AppendLine("				AND Compras.Cod_Suc				BETWEEN " & lcParametro9Desde)
                    loComandoSeleccionar.AppendLine("					AND " & lcParametro9Hasta)
                    loComandoSeleccionar.AppendLine("				AND Articulos.Cod_Uni1			BETWEEN " & lcParametro12Desde)
                    loComandoSeleccionar.AppendLine("					AND " & lcParametro12Hasta)
                    loComandoSeleccionar.AppendLine("				AND Articulos.Cod_Ubi			BETWEEN " & lcParametro13Desde)
                    loComandoSeleccionar.AppendLine("					AND " & lcParametro13Hasta)

                    ' Union con Select de la tabla de Devoluciones_Clientes
                    loComandoSeleccionar.AppendLine("UNION ALL ")
                    loComandoSeleccionar.AppendLine("SELECT			'Dev_Cli'								AS	Operacion, ")
                    loComandoSeleccionar.AppendLine(" 				Devoluciones_Clientes.Documento			AS	Documento, ")
                    loComandoSeleccionar.AppendLine(" 				Renglones_DClientes.Cod_Art				AS	Cod_Art, ")
                    loComandoSeleccionar.AppendLine(" 				Devoluciones_Clientes.Fec_Ini			AS	Fec_Ini, ")
                    loComandoSeleccionar.AppendLine(" 				Renglones_DClientes.Renglon				AS	Renglon, ")
                    loComandoSeleccionar.AppendLine(" 				Devoluciones_Clientes.Cod_Cli			AS	Cliente, ")
                    loComandoSeleccionar.AppendLine(" 				Renglones_DClientes.Cod_Alm				AS	Cod_Alm, ")
                    loComandoSeleccionar.AppendLine(" 				0.0										AS	Can_Sal, ")
                    loComandoSeleccionar.AppendLine(" 				Renglones_DClientes.Can_Art1			AS	Can_Ent, ")
                    loComandoSeleccionar.AppendLine(" 				'Entrada'								AS	Tipo, ")
                    loComandoSeleccionar.AppendLine(" 				Renglones_DClientes." & lcCosto & "     AS	Cos_Pro, ")
                    loComandoSeleccionar.AppendLine(" 				Articulos.Nom_Art						AS	Nom_Art, ")
                    loComandoSeleccionar.AppendLine(" 				" & lcParametro11Desde & "	            AS	Costo ")
                    loComandoSeleccionar.AppendLine("FROM			Devoluciones_Clientes, ")
                    loComandoSeleccionar.AppendLine(" 				Renglones_DClientes, ")
                    loComandoSeleccionar.AppendLine(" 				Articulos ")
                    loComandoSeleccionar.AppendLine("WHERE			Devoluciones_Clientes.Documento		=	Renglones_DClientes.Documento ")
                    loComandoSeleccionar.AppendLine(" 			AND Articulos.Cod_Art					=	Renglones_DClientes.Cod_Art ")
                    loComandoSeleccionar.AppendLine(" 			AND Devoluciones_Clientes.Status		IN	('Confirmado', 'Afectado', 'Procesado') ")
                    loComandoSeleccionar.AppendLine(" 			AND Articulos.Cod_Art				BETWEEN " & lcParametro0Desde)
                    loComandoSeleccionar.AppendLine(" 				AND " & lcParametro0Hasta)
                    loComandoSeleccionar.AppendLine(" 			AND Devoluciones_Clientes.Fec_Ini	BETWEEN " & lcParametro1Desde)
                    loComandoSeleccionar.AppendLine(" 				AND " & lcParametro1Hasta)
                    loComandoSeleccionar.AppendLine(" 			AND Renglones_DClientes.Cod_Alm		BETWEEN " & lcParametro2Desde)
                    loComandoSeleccionar.AppendLine(" 				AND " & lcParametro2Hasta)
                    loComandoSeleccionar.AppendLine(" 			AND Articulos.Cod_Dep				BETWEEN " & lcParametro3Desde)
                    loComandoSeleccionar.AppendLine(" 				AND " & lcParametro3Hasta)
                    loComandoSeleccionar.AppendLine(" 			AND Articulos.Cod_Sec				BETWEEN " & lcParametro4Desde)
                    loComandoSeleccionar.AppendLine(" 				AND " & lcParametro4Hasta)
                    loComandoSeleccionar.AppendLine(" 			AND Articulos.Cod_Mar				BETWEEN " & lcParametro5Desde)
                    loComandoSeleccionar.AppendLine(" 				AND " & lcParametro5Hasta)
                    loComandoSeleccionar.AppendLine(" 			AND Articulos.Cod_Cla				BETWEEN " & lcParametro6Desde)
                    loComandoSeleccionar.AppendLine(" 				AND " & lcParametro6Hasta)
                    loComandoSeleccionar.AppendLine(" 			AND Articulos.Cod_Tip				BETWEEN " & lcParametro7Desde)
                    loComandoSeleccionar.AppendLine(" 				AND " & lcParametro7Hasta)
                    loComandoSeleccionar.AppendLine(" 			AND Articulos.Cod_Pro				BETWEEN " & lcParametro8Desde)
                    loComandoSeleccionar.AppendLine(" 				AND " & lcParametro8Hasta)
                    loComandoSeleccionar.AppendLine(" 			AND Devoluciones_Clientes.Cod_Suc	BETWEEN " & lcParametro9Desde)
                    loComandoSeleccionar.AppendLine(" 				AND " & lcParametro9Hasta)
                    loComandoSeleccionar.AppendLine(" 			AND Articulos.Cod_Uni1				BETWEEN " & lcParametro12Desde)
                    loComandoSeleccionar.AppendLine(" 				AND " & lcParametro12Hasta)
                    loComandoSeleccionar.AppendLine(" 			AND Articulos.Cod_Ubi				BETWEEN " & lcParametro13Desde)
                    loComandoSeleccionar.AppendLine(" 				AND " & lcParametro13Hasta)

                    ' Union con Select de la tabla de Devoluciones_Proveedores
                    loComandoSeleccionar.AppendLine("UNION ALL ")
                    loComandoSeleccionar.AppendLine("SELECT		'Dev_Pro'								AS	Operacion, ")
                    loComandoSeleccionar.AppendLine(" 			Devoluciones_Proveedores.Documento		AS	Documento, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_DProveedores.Cod_Art			AS	Cod_Art, ")
                    loComandoSeleccionar.AppendLine(" 			Devoluciones_Proveedores.Fec_Ini		AS	Fec_Ini, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_DProveedores.Renglon			AS	Renglon, ")
                    loComandoSeleccionar.AppendLine(" 			Devoluciones_Proveedores.Cod_Pro		AS	Cliente, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_DProveedores.Cod_Alm			AS	Cod_Alm, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_DProveedores.Can_Art1			AS	Can_Sal, ")
                    loComandoSeleccionar.AppendLine(" 			0.0										AS	Can_Ent, ")
                    loComandoSeleccionar.AppendLine(" 			'Salida'								AS	Tipo, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_DProveedores." & lcCosto & "  AS	Cos_Pro, ")
                    loComandoSeleccionar.AppendLine(" 			Articulos.Nom_Art						AS	Nom_Art, ")
                    loComandoSeleccionar.AppendLine(" 			" & lcParametro11Desde & "	            AS	Costo ")
                    loComandoSeleccionar.AppendLine("FROM		Devoluciones_Proveedores, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_DProveedores, ")
                    loComandoSeleccionar.AppendLine(" 			Articulos ")
                    loComandoSeleccionar.AppendLine("WHERE		Devoluciones_Proveedores.Documento	=	Renglones_DProveedores.Documento ")
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Art					=	Renglones_DProveedores.Cod_Art ")
                    loComandoSeleccionar.AppendLine(" 		AND Devoluciones_Proveedores.Status		IN	('Confirmado', 'Afectado', 'Procesado') ")
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Art					BETWEEN " & lcParametro0Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro0Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Devoluciones_Proveedores.Fec_Ini	BETWEEN " & lcParametro1Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro1Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Renglones_DProveedores.Cod_Alm		BETWEEN " & lcParametro2Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro2Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Dep					BETWEEN " & lcParametro3Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro3Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Sec					BETWEEN " & lcParametro4Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro4Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Mar					BETWEEN " & lcParametro5Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro5Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Cla					BETWEEN " & lcParametro6Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro6Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Tip					BETWEEN " & lcParametro7Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro7Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Pro					BETWEEN " & lcParametro8Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro8Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Devoluciones_Proveedores.Cod_Suc	BETWEEN " & lcParametro9Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro9Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Uni1					BETWEEN " & lcParametro12Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro12Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Ubi					BETWEEN " & lcParametro13Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro13Hasta)

                Case "'Ajustes_Entrada'"

                    ' Select de la tabla de Ajustes solo para las Entradas
                    loComandoSeleccionar.AppendLine("SELECT		'Ajustes'							AS	Operacion, ")
                    loComandoSeleccionar.AppendLine("			Ajustes.Documento					AS	Documento, ")
                    loComandoSeleccionar.AppendLine("			Renglones_Ajustes.Cod_Art			AS	Cod_Art, ")
                    loComandoSeleccionar.AppendLine("			Ajustes.Fec_Ini						AS	Fec_Ini, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Ajustes.Renglon			AS	Renglon, ")
                    loComandoSeleccionar.AppendLine(" 			'No Aplica'							AS	Cliente, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Ajustes.Cod_Alm			AS	Cod_Alm, ")
                    loComandoSeleccionar.AppendLine(" 			0.00                                AS	Can_Sal, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Ajustes.Can_Art1			AS	Can_Ent, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Ajustes.Tipo				AS	Tipo, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Ajustes." & lcCosto & "   AS	Cos_Pro, ")
                    loComandoSeleccionar.AppendLine(" 			Articulos.Nom_Art					AS	Nom_Art, ")
                    loComandoSeleccionar.AppendLine(" 			" & lcParametro11Desde & "	        AS	Costo ")
                    loComandoSeleccionar.AppendLine("INTO		#curTemporal ")
                    loComandoSeleccionar.AppendLine("FROM		Ajustes, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Ajustes, ")
                    loComandoSeleccionar.AppendLine(" 			Articulos ")
                    loComandoSeleccionar.AppendLine("WHERE		Ajustes.Documento				=	Renglones_Ajustes.Documento ")
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Art				=	Renglones_Ajustes.Cod_Art ")
                    loComandoSeleccionar.AppendLine(" 		AND Renglones_Ajustes.Tipo			=   'Entrada'  ")
                    loComandoSeleccionar.AppendLine(" 		AND Ajustes.Status					=	'Confirmado' ")
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Art			BETWEEN " & lcParametro0Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro0Hasta)
                    loComandoSeleccionar.AppendLine("		AND Ajustes.Fec_Ini				BETWEEN " & lcParametro1Desde)
                    loComandoSeleccionar.AppendLine("			AND " & lcParametro1Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Renglones_Ajustes.Cod_Alm	BETWEEN " & lcParametro2Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro2Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Dep			BETWEEN " & lcParametro3Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro3Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Sec			BETWEEN " & lcParametro4Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro4Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Mar			BETWEEN " & lcParametro5Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro5Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Cla			BETWEEN " & lcParametro6Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro6Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Tip			BETWEEN " & lcParametro7Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro7Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Pro			BETWEEN " & lcParametro8Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro8Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Ajustes.Cod_Suc				BETWEEN " & lcParametro9Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro9Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Uni1			BETWEEN " & lcParametro12Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro12Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Ubi			BETWEEN " & lcParametro13Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro13Hasta)

                Case "'Ajustes_Salida'"

                    ' Select de la tabla de Ajustes solo para las Salidas
                    loComandoSeleccionar.AppendLine("SELECT		'Ajustes'							AS	Operacion, ")
                    loComandoSeleccionar.AppendLine(" 			Ajustes.Documento					AS	Documento, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Ajustes.Cod_Art			AS	Cod_Art, ")
                    loComandoSeleccionar.AppendLine(" 			Ajustes.Fec_Ini						AS	Fec_Ini, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Ajustes.Renglon			AS	Renglon, ")
                    loComandoSeleccionar.AppendLine(" 			'No Aplica'							AS	Cliente, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Ajustes.Cod_Alm			AS	Cod_Alm, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Ajustes.Can_Art1			AS	Can_Sal, ")
                    loComandoSeleccionar.AppendLine(" 			0.00                                AS	Can_Ent, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Ajustes.Tipo				AS	Tipo, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Ajustes." & lcCosto & "   AS	Cos_Pro, ")
                    loComandoSeleccionar.AppendLine(" 			Articulos.Nom_Art					AS	Nom_Art, ")
                    loComandoSeleccionar.AppendLine(" 			" & lcParametro11Desde & "	        AS	Costo ")
                    loComandoSeleccionar.AppendLine("INTO		#curTemporal ")
                    loComandoSeleccionar.AppendLine("FROM		Ajustes, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Ajustes, ")
                    loComandoSeleccionar.AppendLine(" 			Articulos ")
                    loComandoSeleccionar.AppendLine("WHERE		Ajustes.Documento			=	Renglones_Ajustes.Documento ")
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Art			=	Renglones_Ajustes.Cod_Art ")
                    loComandoSeleccionar.AppendLine(" 		AND Renglones_Ajustes.Tipo      =   'Salida'  ")
                    loComandoSeleccionar.AppendLine(" 		AND Ajustes.Status				=	'Confirmado' ")
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Art			BETWEEN " & lcParametro0Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro0Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Ajustes.Fec_Ini				BETWEEN " & lcParametro1Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro1Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Renglones_Ajustes.Cod_Alm	BETWEEN " & lcParametro2Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro2Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Dep			BETWEEN " & lcParametro3Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro3Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Sec			BETWEEN " & lcParametro4Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro4Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Mar			BETWEEN " & lcParametro5Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro5Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Cla			BETWEEN " & lcParametro6Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro6Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Tip			BETWEEN " & lcParametro7Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro7Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Pro			BETWEEN " & lcParametro8Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro8Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Ajustes.Cod_Suc			BETWEEN " & lcParametro9Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro9Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Uni1			BETWEEN " & lcParametro12Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro12Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Ubi			BETWEEN " & lcParametro13Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro13Hasta)

                Case "'Traslados_Salida'"

                    ' Union con Select de la tabla de Traslados en las Salidas
                    loComandoSeleccionar.AppendLine("SELECT		'Traslados'							AS	Operacion, ")
                    loComandoSeleccionar.AppendLine(" 			Traslados.Documento					AS	Documento, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Traslados.Cod_Art			AS	Cod_Art, ")
                    loComandoSeleccionar.AppendLine(" 			Traslados.Fec_Ini					AS	Fec_Ini, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Traslados.Renglon			AS	Renglon, ")
                    loComandoSeleccionar.AppendLine(" 			'No Aplica'							AS	Cliente, ") 
                    loComandoSeleccionar.AppendLine(" 			Traslados.Alm_Ori					AS	Cod_Alm, ")	
                    loComandoSeleccionar.AppendLine(" 			Renglones_Traslados.Can_Art1		AS	Can_Sal, ")
                    loComandoSeleccionar.AppendLine(" 			0.0									AS	Can_Ent, ")
                    loComandoSeleccionar.AppendLine(" 			'Salida'							AS	Tipo, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Traslados." & lcCosto & " AS	Cos_Pro, ")
                    loComandoSeleccionar.AppendLine(" 			Articulos.Nom_Art					AS	Nom_Art, ")
                    loComandoSeleccionar.AppendLine(" 			" & lcParametro11Desde & "	        AS	Costo ")
                    loComandoSeleccionar.AppendLine("INTO		#curTemporal ")
                    loComandoSeleccionar.AppendLine("FROM		Traslados, ")
                    loComandoSeleccionar.AppendLine("			Renglones_Traslados, ")
                    loComandoSeleccionar.AppendLine("			Articulos ")
                    loComandoSeleccionar.AppendLine("WHERE		Traslados.Documento				=	Renglones_Traslados.Documento ")
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Art				=	Renglones_Traslados.Cod_Art ")
                    loComandoSeleccionar.AppendLine(" 		AND Traslados.Status				IN ('Confirmado', 'Procesado') ")
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Art				BETWEEN " & lcParametro0Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro0Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Traslados.Fec_Ini				BETWEEN " & lcParametro1Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro1Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Traslados.Alm_Ori				BETWEEN " & lcParametro2Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro2Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Dep				BETWEEN " & lcParametro3Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro3Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Sec				BETWEEN " & lcParametro4Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro4Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Mar				BETWEEN " & lcParametro5Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro5Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Cla				BETWEEN " & lcParametro6Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro6Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Tip				BETWEEN " & lcParametro7Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro7Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Pro				BETWEEN " & lcParametro8Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro8Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Traslados.Cod_Suc				BETWEEN " & lcParametro9Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro9Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Uni1				BETWEEN " & lcParametro12Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro12Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Ubi				BETWEEN " & lcParametro13Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro13Hasta)

                Case "'Traslados_Entrada'"

                    ' Union con Select de la tabla de Traslados en las Entradas
                    loComandoSeleccionar.AppendLine("SELECT		'Traslados'							AS	Operacion, ")
                    loComandoSeleccionar.AppendLine(" 			Traslados.Documento						AS	Documento, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Traslados.Cod_Art				AS	Cod_Art, ")
                    loComandoSeleccionar.AppendLine(" 			Traslados.Fec_Ini						AS	Fec_Ini, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Traslados.Renglon				AS	Renglon, ")
                    loComandoSeleccionar.AppendLine(" 			'No Aplica'								AS	Cliente, ")	
                    loComandoSeleccionar.AppendLine(" 			CASE Traslados.Status					")
                    loComandoSeleccionar.AppendLine(" 				WHEN 'Confirmado'	THEN " & lcAlmacenTransito)
                    loComandoSeleccionar.AppendLine(" 				WHEN 'Procesado'	THEN Traslados.Alm_Des")
                    loComandoSeleccionar.AppendLine(" 			END										AS	Cod_Alm, ")	 
                    loComandoSeleccionar.AppendLine(" 			0.0										AS	Can_Sal, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Traslados.Can_Art1			AS	Can_Ent, ")
                    loComandoSeleccionar.AppendLine(" 			'Entrada'								AS	Tipo, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Traslados." & lcCosto & "     AS	Cos_Pro, ")
                    loComandoSeleccionar.AppendLine(" 			Articulos.Nom_Art						AS	Nom_Art, ")
                    loComandoSeleccionar.AppendLine(" 			" & lcParametro11Desde & "	            AS	Costo ")
                    loComandoSeleccionar.AppendLine("INTO		#curTemporal ")
                    loComandoSeleccionar.AppendLine("FROM		Traslados, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Traslados, ")
                    loComandoSeleccionar.AppendLine(" 			Articulos ")
                    loComandoSeleccionar.AppendLine("WHERE		Traslados.Documento					=	Renglones_Traslados.Documento ")
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Art					=	Renglones_Traslados.Cod_Art ")
                    loComandoSeleccionar.AppendLine(" 		AND Traslados.Status					IN ('Confirmado', 'Procesado') ")
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Art				BETWEEN " & lcParametro0Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro0Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Traslados.Fec_Ini				BETWEEN " & lcParametro1Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro1Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND	(CASE	Traslados.Status				")
                    loComandoSeleccionar.AppendLine(" 				WHEN 'Confirmado' THEN " & lcAlmacenTransito & "")
                    loComandoSeleccionar.AppendLine(" 				ELSE Traslados.Alm_Des				" )
                    loComandoSeleccionar.AppendLine(" 			END)							BETWEEN " & lcParametro2Desde)
                    loComandoSeleccionar.AppendLine("			AND " & lcParametro2Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Dep				BETWEEN " & lcParametro3Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro3Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Sec				BETWEEN " & lcParametro4Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro4Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Mar				BETWEEN " & lcParametro5Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro5Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Cla				BETWEEN " & lcParametro6Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro6Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Tip				BETWEEN " & lcParametro7Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro7Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Pro				BETWEEN " & lcParametro8Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro8Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Suc				BETWEEN " & lcParametro9Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro9Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Uni1				BETWEEN " & lcParametro12Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro12Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Ubi				BETWEEN " & lcParametro13Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro13Hasta)

                Case "'Facturas_Venta'"

                    ' Union con Select de la tabla de Facturas
                    loComandoSeleccionar.AppendLine("SELECT		'Facturas'							AS	Operacion, ")
                    loComandoSeleccionar.AppendLine("			Facturas.Documento					AS	Documento, ")
                    loComandoSeleccionar.AppendLine("			Renglones_Facturas.Cod_Art			AS	Cod_Art, ")
                    loComandoSeleccionar.AppendLine("			Facturas.Fec_Ini					AS	Fec_Ini, ")
                    loComandoSeleccionar.AppendLine("			Renglones_Facturas.Renglon			AS	Renglon, ")
                    loComandoSeleccionar.AppendLine("			Facturas.Cod_Cli					AS	Cliente, ")
                    loComandoSeleccionar.AppendLine("			Renglones_Facturas.Cod_Alm			AS	Cod_Alm, ")
                    loComandoSeleccionar.AppendLine("			Renglones_Facturas.Can_Art1			AS	Can_Sal, ")
                    loComandoSeleccionar.AppendLine("			0.0									AS	Can_Ent, ")
                    loComandoSeleccionar.AppendLine("			'Salida'							AS	Tipo, ")
                    loComandoSeleccionar.AppendLine("			Renglones_Facturas." & lcCosto & "  AS	Cos_Pro, ")
                    loComandoSeleccionar.AppendLine("			Articulos.Nom_Art					AS	Nom_Art, ")
                    loComandoSeleccionar.AppendLine("			" & lcParametro11Desde & "	        AS	Costo ")
                    loComandoSeleccionar.AppendLine("INTO		#curTemporal ")
                    loComandoSeleccionar.AppendLine("FROM		Facturas, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Facturas, ")
                    loComandoSeleccionar.AppendLine(" 			Articulos ")
                    loComandoSeleccionar.AppendLine("WHERE		Facturas.Documento			=	Renglones_Facturas.Documento ")
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Art			=	Renglones_Facturas.Cod_Art ")
                    loComandoSeleccionar.AppendLine(" 		AND Facturas.Status				IN	('Confirmado', 'Afectado', 'Procesado') ")
                    loComandoSeleccionar.AppendLine(" 		AND Renglones_Facturas.Tip_Ori	<>	'Entregas' ")
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Art				BETWEEN " & lcParametro0Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro0Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Facturas.Fec_Ini				BETWEEN " & lcParametro1Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro1Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Renglones_Facturas.Cod_Alm		BETWEEN " & lcParametro2Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro2Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Dep				BETWEEN " & lcParametro3Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro3Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Sec				BETWEEN " & lcParametro4Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro4Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Mar				BETWEEN " & lcParametro5Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro5Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Cla				BETWEEN " & lcParametro6Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro6Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Tip				BETWEEN " & lcParametro7Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro7Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Pro				BETWEEN " & lcParametro8Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro8Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Facturas.Cod_Suc				BETWEEN " & lcParametro9Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro9Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Uni1				BETWEEN " & lcParametro12Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro12Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Ubi				BETWEEN " & lcParametro13Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro13Hasta)

                Case "'Facturas_Compra'"

                    ' Union con Select de la tabla de Compras
                    loComandoSeleccionar.AppendLine("SELECT		'Compras'							AS	Operacion, ")
                    loComandoSeleccionar.AppendLine(" 			Compras.Documento					AS	Documento, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Compras.Cod_Art			AS	Cod_Art, ")
                    loComandoSeleccionar.AppendLine(" 			Compras.Fec_Ini						AS	Fec_Ini, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Compras.Renglon			AS	Renglon, ")
                    loComandoSeleccionar.AppendLine(" 			Compras.Cod_Pro						AS	Cliente, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Compras.Cod_Alm			AS	Cod_Alm, ")
                    loComandoSeleccionar.AppendLine(" 			0.0									AS	Can_Sal, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Compras.Can_Art1			AS	Can_Ent, ")
                    loComandoSeleccionar.AppendLine(" 			'Entrada'							AS	Tipo, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Compras." & lcCosto & "   AS	Cos_Pro, ")
                    loComandoSeleccionar.AppendLine(" 			Articulos.Nom_Art					AS	Nom_Art, ")
                    loComandoSeleccionar.AppendLine("			" & lcParametro11Desde & "			AS	Costo ")
                    loComandoSeleccionar.AppendLine("INTO		#curTemporal ")
                    loComandoSeleccionar.AppendLine("FROM		Compras, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Compras, ")
                    loComandoSeleccionar.AppendLine(" 			Articulos ")
                    loComandoSeleccionar.AppendLine("WHERE		Compras.Documento			=	Renglones_Compras.Documento ")
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Art			=	Renglones_Compras.Cod_Art ")
                    loComandoSeleccionar.AppendLine(" 		AND Compras.Status				IN	('Confirmado', 'Afectado', 'Procesado') ")
                    loComandoSeleccionar.AppendLine(" 		AND Renglones_Compras.Tip_Ori	<>	'Recepciones' ")
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Art			BETWEEN " & lcParametro0Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro0Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Compras.Fec_Ini				BETWEEN " & lcParametro1Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro1Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Renglones_Compras.Cod_Alm	BETWEEN " & lcParametro2Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro2Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Dep			BETWEEN " & lcParametro3Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro3Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Sec			BETWEEN " & lcParametro4Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro4Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Mar			BETWEEN " & lcParametro5Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro5Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Cla			BETWEEN " & lcParametro6Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro6Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Tip			BETWEEN " & lcParametro7Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro7Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Pro			BETWEEN " & lcParametro8Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro8Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Compras.Cod_Suc			BETWEEN " & lcParametro9Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro9Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Uni1			BETWEEN " & lcParametro12Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro12Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Ubi			BETWEEN " & lcParametro13Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro13Hasta)

                Case "'Notas_Entrega'"

                    ' Union con Select de la tabla de Entregas
                    loComandoSeleccionar.AppendLine("SELECT		'Entregas'							AS	Operacion, ")
                    loComandoSeleccionar.AppendLine("			Entregas.Documento					AS	Documento, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Entregas.Cod_Art			AS	Cod_Art, ")
                    loComandoSeleccionar.AppendLine(" 			Entregas.Fec_Ini					AS	Fec_Ini, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Entregas.Renglon			AS	Renglon, ")
                    loComandoSeleccionar.AppendLine(" 			Entregas.Cod_Cli					AS	Cliente, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Entregas.Cod_Alm			AS	Cod_Alm, ")
                    loComandoSeleccionar.AppendLine(" 			0.0									AS	Can_Sal, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Entregas.Can_Art1			AS	Can_Ent, ")
                    loComandoSeleccionar.AppendLine(" 			'Salida'							AS	Tipo, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Entregas." & lcCosto & "  AS	Cos_Pro, ")
                    loComandoSeleccionar.AppendLine(" 			Articulos.Nom_Art					AS	Nom_Art, ")
                    loComandoSeleccionar.AppendLine(" 			" & lcParametro11Desde & "	        AS	Costo ")
                    loComandoSeleccionar.AppendLine("INTO		 #curTemporal ")
                    loComandoSeleccionar.AppendLine("FROM		Entregas, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Entregas, ")
                    loComandoSeleccionar.AppendLine(" 			Articulos ")
                    loComandoSeleccionar.AppendLine("WHERE		Entregas.Documento		=	Renglones_Entregas.Documento ")
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Art		=	Renglones_Entregas.Cod_Art ")
                    loComandoSeleccionar.AppendLine(" 		AND Entregas.Status			IN	('Confirmado', 'Afectado', 'Procesado') ")
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Art			BETWEEN " & lcParametro0Desde)
                    loComandoSeleccionar.AppendLine("			AND " & lcParametro0Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Entregas.Fec_Ini			BETWEEN " & lcParametro1Desde)
                    loComandoSeleccionar.AppendLine("	 		AND " & lcParametro1Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Renglones_Entregas.Cod_Alm	BETWEEN " & lcParametro2Desde)
                    loComandoSeleccionar.AppendLine("			AND " & lcParametro2Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Dep			BETWEEN " & lcParametro3Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro3Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Sec			BETWEEN " & lcParametro4Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro4Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Mar			BETWEEN " & lcParametro5Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro5Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Cla			BETWEEN " & lcParametro6Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro6Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Tip			BETWEEN " & lcParametro7Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro7Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Pro			BETWEEN " & lcParametro8Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro8Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Entregas.Cod_Suc			BETWEEN " & lcParametro9Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro9Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Uni1			BETWEEN " & lcParametro12Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro12Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Ubi			BETWEEN " & lcParametro13Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro13Hasta)

                Case "'Notas_Recepcion'"

                    ' Union con Select de la tabla de Recepciones
                    loComandoSeleccionar.AppendLine("SELECT 	'Recepciones'							AS	Operacion, ")
                    loComandoSeleccionar.AppendLine(" 			Recepciones.Documento					AS	Documento, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Recepciones.Cod_Art			AS	Cod_Art, ")
                    loComandoSeleccionar.AppendLine(" 			Recepciones.Fec_Ini						AS	Fec_Ini, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Recepciones.Renglon			AS	Renglon, ")
                    loComandoSeleccionar.AppendLine(" 			Recepciones.Cod_Pro						AS	Cliente, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Recepciones.Cod_Alm			AS	Cod_Alm, ")
                    loComandoSeleccionar.AppendLine(" 			0.0										AS	Can_Sal, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Recepciones.Can_Art1			AS	Can_Ent, ")
                    loComandoSeleccionar.AppendLine(" 			'Entrada'								AS	Tipo, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Recepciones." & lcCosto & "	AS	Cos_Pro, ")
                    loComandoSeleccionar.AppendLine(" 			Articulos.Nom_Art						AS	Nom_Art, ")
                    loComandoSeleccionar.AppendLine(" 			" & lcParametro11Desde & "				AS	Costo ")
                    loComandoSeleccionar.AppendLine("INTO		#curTemporal ")
                    loComandoSeleccionar.AppendLine("FROM		Recepciones, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_Recepciones, ")
                    loComandoSeleccionar.AppendLine(" 			Articulos ")
                    loComandoSeleccionar.AppendLine("WHERE		Recepciones.Documento		=	Renglones_Recepciones.Documento ")
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Art			=	Renglones_Recepciones.Cod_Art ")
                    loComandoSeleccionar.AppendLine(" 		AND Recepciones.Status			IN	('Confirmado', 'Afectado', 'Procesado') ")
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Art				BETWEEN " & lcParametro0Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro0Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Recepciones.Fec_Ini				BETWEEN " & lcParametro1Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro1Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Renglones_Recepciones.Cod_Alm	BETWEEN " & lcParametro2Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro2Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Dep				BETWEEN " & lcParametro3Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro3Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Sec				BETWEEN " & lcParametro4Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro4Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Mar				BETWEEN " & lcParametro5Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro5Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Cla				BETWEEN " & lcParametro6Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro6Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Tip				BETWEEN " & lcParametro7Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro7Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Pro				BETWEEN " & lcParametro8Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro8Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Recepciones.Cod_Suc				BETWEEN " & lcParametro9Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro9Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Uni1				BETWEEN " & lcParametro12Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro12Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Ubi				BETWEEN " & lcParametro13Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro13Hasta)

                Case "'Devolucion_Ventas'"

                    ' Union con Select de la tabla de Devoluciones_Clientes
                    loComandoSeleccionar.AppendLine("SELECT		'Dev_Cli'								AS	Operacion, ")
                    loComandoSeleccionar.AppendLine("			Devoluciones_Clientes.Documento			AS	Documento, ")
                    loComandoSeleccionar.AppendLine("			Renglones_DClientes.Cod_Art				AS	Cod_Art, ")
                    loComandoSeleccionar.AppendLine("			Devoluciones_Clientes.Fec_Ini			AS	Fec_Ini, ")
                    loComandoSeleccionar.AppendLine("			Renglones_DClientes.Renglon				AS	Renglon, ")
                    loComandoSeleccionar.AppendLine("			Devoluciones_Clientes.Cod_Cli			AS	Cliente, ")
                    loComandoSeleccionar.AppendLine("			Renglones_DClientes.Cod_Alm				AS	Cod_Alm, ")
                    loComandoSeleccionar.AppendLine("			0.0										AS	Can_Sal, ")
                    loComandoSeleccionar.AppendLine("			Renglones_DClientes.Can_Art1			AS	Can_Ent, ")
                    loComandoSeleccionar.AppendLine("			'Entrada'								AS	Tipo, ")
                    loComandoSeleccionar.AppendLine("			Renglones_DClientes." & lcCosto & "		AS	Cos_Pro, ")
                    loComandoSeleccionar.AppendLine("			Articulos.Nom_Art						AS	Nom_Art, ")
                    loComandoSeleccionar.AppendLine("			" & lcParametro11Desde & "	    		AS	Costo ")
                    loComandoSeleccionar.AppendLine("INTO		#curTemporal ")
                    loComandoSeleccionar.AppendLine("FROM		Devoluciones_Clientes, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_DClientes, ")
                    loComandoSeleccionar.AppendLine(" 			Articulos ")
                    loComandoSeleccionar.AppendLine("WHERE		Devoluciones_Clientes.Documento		=	Renglones_DClientes.Documento ")
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Art					=	Renglones_DClientes.Cod_Art ")
                    loComandoSeleccionar.AppendLine(" 		AND Devoluciones_Clientes.Status		IN	('Confirmado', 'Afectado', 'Procesado') ")
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Art				BETWEEN " & lcParametro0Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro0Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Devoluciones_Clientes.Fec_Ini	BETWEEN " & lcParametro1Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro1Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Renglones_DClientes.Cod_Alm		BETWEEN " & lcParametro2Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro2Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Dep				BETWEEN " & lcParametro3Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro3Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Sec				BETWEEN " & lcParametro4Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro4Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Mar				BETWEEN " & lcParametro5Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro5Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Cla				BETWEEN " & lcParametro6Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro6Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Tip				BETWEEN " & lcParametro7Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro7Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Pro				BETWEEN " & lcParametro8Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro8Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Devoluciones_Clientes.Cod_Suc	BETWEEN " & lcParametro9Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro9Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Uni1				BETWEEN " & lcParametro12Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro12Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Ubi				BETWEEN " & lcParametro13Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro13Hasta)

                Case "'Devolucion_Compras'"

                    ' Union con Select de la tabla de Devoluciones_Proveedores
                    loComandoSeleccionar.AppendLine("SELECT		'Dev_Pro'								AS	Operacion, ")
                    loComandoSeleccionar.AppendLine(" 			Devoluciones_Proveedores.Documento		AS	Documento, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_DProveedores.Cod_Art			AS	Cod_Art, ")
                    loComandoSeleccionar.AppendLine(" 			Devoluciones_Proveedores.Fec_Ini		AS	Fec_Ini, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_DProveedores.Renglon			AS	Renglon, ")
                    loComandoSeleccionar.AppendLine(" 			Devoluciones_Proveedores.Cod_Pro		AS	Cliente, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_DProveedores.Cod_Alm			AS	Cod_Alm, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_DProveedores.Can_Art1			AS	Can_Sal, ")
                    loComandoSeleccionar.AppendLine(" 			0.0										AS	Can_Ent, ")
                    loComandoSeleccionar.AppendLine(" 			'Salida'								AS	Tipo, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_DProveedores." & lcCosto & "  AS	Cos_Pro, ")
                    loComandoSeleccionar.AppendLine(" 			Articulos.Nom_Art						AS	Nom_Art, ")
                    loComandoSeleccionar.AppendLine(" 			" & lcParametro11Desde & "	            AS	Costo ")
                    loComandoSeleccionar.AppendLine("INTO		#curTemporal ")
                    loComandoSeleccionar.AppendLine("FROM		Devoluciones_Proveedores, ")
                    loComandoSeleccionar.AppendLine(" 			Renglones_DProveedores, ")
                    loComandoSeleccionar.AppendLine(" 			Articulos ")
                    loComandoSeleccionar.AppendLine("WHERE		Devoluciones_Proveedores.Documento	=	Renglones_DProveedores.Documento ")
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Art					=	Renglones_DProveedores.Cod_Art ")
                    loComandoSeleccionar.AppendLine(" 		AND Devoluciones_Proveedores.Status		IN	('Confirmado', 'Afectado', 'Procesado') ")
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Art					BETWEEN " & lcParametro0Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro0Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Devoluciones_Proveedores.Fec_Ini	BETWEEN " & lcParametro1Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro1Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Renglones_DProveedores.Cod_Alm		BETWEEN " & lcParametro2Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro2Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Dep					BETWEEN " & lcParametro3Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro3Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Sec					BETWEEN " & lcParametro4Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro4Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Mar					BETWEEN " & lcParametro5Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro5Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Cla					BETWEEN " & lcParametro6Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro6Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Tip					BETWEEN " & lcParametro7Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro7Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Pro					BETWEEN " & lcParametro8Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro8Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Devoluciones_Proveedores.Cod_Suc	BETWEEN " & lcParametro9Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro9Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Uni1					BETWEEN " & lcParametro12Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro12Hasta)
                    loComandoSeleccionar.AppendLine(" 		AND Articulos.Cod_Ubi					BETWEEN " & lcParametro13Desde)
                    loComandoSeleccionar.AppendLine(" 			AND " & lcParametro13Hasta)

            End Select

            loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("SELECT		Operacion, ")
            loComandoSeleccionar.AppendLine("			Documento, ")
            loComandoSeleccionar.AppendLine("			Cod_Art, ")
            loComandoSeleccionar.AppendLine("			Fec_Ini, ")
            loComandoSeleccionar.AppendLine("			Renglon, ")
            loComandoSeleccionar.AppendLine("			Cliente, ")
            loComandoSeleccionar.AppendLine("			Cod_Alm, ")
            loComandoSeleccionar.AppendLine("			Can_Sal, ")
            loComandoSeleccionar.AppendLine("			Can_Ent, ")
            loComandoSeleccionar.AppendLine("			Tipo, ")
            loComandoSeleccionar.AppendLine("			Cos_Pro, ")
            loComandoSeleccionar.AppendLine("			(Cos_Pro * Can_Sal)							AS	Cos_Pro_Sal, ")
            loComandoSeleccionar.AppendLine("			(Cos_Pro * Can_Ent)							AS	Cos_Pro_Ent, ")
            loComandoSeleccionar.AppendLine("			((Cos_Pro * Can_Ent) - (Cos_Pro * Can_Sal))	AS	Cos_Tot, ")
            loComandoSeleccionar.AppendLine("			Nom_Art, ")
            loComandoSeleccionar.AppendLine("			Costo ")
            loComandoSeleccionar.AppendLine("FROM		#curTemporal ")
            loComandoSeleccionar.AppendLine("ORDER BY	" & lcOrdenamiento)
            loComandoSeleccionar.AppendLine("")

            'Me.mEscribirConsulta(loComandoSeleccionar.ToString())



            Dim loServicios As New cusDatos.goDatos

            Dim laDatosReporte As DataSet = loServicios.mObtenerTodosSinEsquema(loComandoSeleccionar.ToString, "curReportes")


            '-------------------------------------------------------------------------------------------------------
            ' Verificando si el select (tabla nº0) trae registros
            '-------------------------------------------------------------------------------------------------------

            If (laDatosReporte.Tables(0).Rows.Count <= 0) Then
                Me.WbcAdministradorMensajeModal.mMostrarMensajeModal("Información", _
                                          "No se Encontraron Registros para los Parámetros Especificados. ", _
                                           vis3Controles.wbcAdministradorMensajeModal.enumTipoMensaje.KN_Informacion, _
                                           "350px", _
                                           "200px")
            End If

            loObjetoReporte = cusAplicacion.goReportes.mCargarReporte("rMInventarios_Articulos", laDatosReporte)

            Me.mTraducirReporte(loObjetoReporte)

            Me.mFormatearCamposReporte(loObjetoReporte)

            Me.crvrMInventarios_Articulos.ReportSource = loObjetoReporte

        Catch loExcepcion As Exception

            Me.WbcAdministradorMensajeModal.mMostrarMensajeModal("Error", _
                          "No se pudo Completar el Proceso: " & loExcepcion.Message, _
                           vis3Controles.wbcAdministradorMensajeModal.enumTipoMensaje.KN_Error, _
                           "auto", _
                           "auto")

        End Try

    End Sub

    Protected Sub Page_Unload(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Unload

        Try

            loObjetoReporte.Close()

        Catch loExcepcion As Exception

        End Try

    End Sub

End Class
'-------------------------------------------------------------------------------------------'
' Fin del codigo
'-------------------------------------------------------------------------------------------'
' JJD: 30/09/08: Codigo inicial
'-------------------------------------------------------------------------------------------'
' CMS: 12/05/09: Ordenamiento 
'-------------------------------------------------------------------------------------------'
' AAP: 29/06/09: Filtro "Sucursal"
'-------------------------------------------------------------------------------------------'
' JJD: 24/07/09: Se desgloso por origen. Ajuste, Traslados, Devoluciones Clientes, etc.
'-------------------------------------------------------------------------------------------'
' CMS: 19/08/09: Verificacion de registros y filtro cod_ubi
'-------------------------------------------------------------------------------------------'
' RJG: 14/03/10: Corecciones varias: no mostraba todos los documentos, corrección en		'
'				 Traslados, Compras, Entregas. Ajustados Status de documentos de Compra y	'
'				 Venta (agregados los Afectados y Procesados).								'
'-------------------------------------------------------------------------------------------'
' RJG: 08/12/10: Ajustado Estatus de Facturas de Venta: Ahora omite las facturas de venta	'
'				 pendientes e incluye las confirmadas.										'
'-------------------------------------------------------------------------------------------'
' MAT: 17/03/11: Mejora en la vista de diseño.												'
'-------------------------------------------------------------------------------------------'
' RJG: 15/05/12: Corrección de los filtros de almacén (en traslados) y de sucursal.			'
'-------------------------------------------------------------------------------------------'
