Imports System.Data
Partial Class rOperaciones_Empresa
    Inherits vis2Formularios.frmReporte


    Dim loObjetoReporte As CrystalDecisions.CrystalReports.Engine.ReportDocument

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load


        Dim lcParametro0Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(0), goServicios.enuOpcionesRedondeo.KN_FechaInicioDelDia)
        Dim lcParametro0Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(0), goServicios.enuOpcionesRedondeo.KN_FechaFinDelDia)
        Dim loComandoSeleccionar As New StringBuilder()

        Dim lcOrdenamiento As String = cusAplicacion.goReportes.pcOrden


        Try

            'Variables necesarias para crear tabla con los meses del intervalo de fechas ingresado
            loComandoSeleccionar.AppendLine("DECLARE @Fin AS DATETIME; ")
            loComandoSeleccionar.AppendLine("DECLARE @ini AS DATETIME; ")
            loComandoSeleccionar.AppendLine("DECLARE @lnContador INT; ")
            loComandoSeleccionar.AppendLine("DECLARE @lnMeses	INT; ")
            loComandoSeleccionar.AppendLine("CREATE TABLE #tmpLlenarMeses(año int, mes int) ")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine("SET @Fin = CAST(" & lcParametro0Hasta & " AS DATETIME) ")
            loComandoSeleccionar.AppendLine("SET @ini = CAST(" & lcParametro0Desde & " AS DATETIME) ")
            loComandoSeleccionar.AppendLine("SET @lnContador = 0; ")
            loComandoSeleccionar.AppendLine("SET @lnMeses = DATEDIFF(MONTH,@ini,@Fin)+1 ")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine("WHILE(@lnContador < @lnMeses) ")
            loComandoSeleccionar.AppendLine("BEGIN ")
            loComandoSeleccionar.AppendLine("	INSERT INTO #tmpLlenarMeses (año,mes) ")
            loComandoSeleccionar.AppendLine("		VALUES(YEAR(DATEADD(MONTH,@lnContador,@ini)), MONTH(DATEADD(MONTH,@lnContador,@ini))) ")
            loComandoSeleccionar.AppendLine("	SET @lnContador = @lnContador +1 ")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine("END; ")

            loComandoSeleccionar.AppendLine("SELECT	año, ")
            loComandoSeleccionar.AppendLine("		mes, ")
            loComandoSeleccionar.AppendLine("		SUM(Aju_m)		AS Aju_m, ")
            loComandoSeleccionar.AppendLine("		SUM(Aju_d)		AS Aju_d, ")
            loComandoSeleccionar.AppendLine("		SUM(Tras_m)		AS Tras_m, ")
            loComandoSeleccionar.AppendLine("		SUM(Tras_d)		AS Tras_d, ")
            loComandoSeleccionar.AppendLine("		SUM(Fact_m)		AS Fact_m, ")
            loComandoSeleccionar.AppendLine("		SUM(Fact_d)		AS Fact_d, ")
            loComandoSeleccionar.AppendLine("		SUM(Cob_m)		AS Cob_m, ")
            loComandoSeleccionar.AppendLine("		SUM(Cob_d)		AS Cob_d, ")
            loComandoSeleccionar.AppendLine("		SUM(CXC_m)		AS CXC_m, ")
            loComandoSeleccionar.AppendLine("		SUM(CXC_d)		AS CXC_d, ")
            loComandoSeleccionar.AppendLine("		SUM(Com_m)		AS Com_m, ")
            loComandoSeleccionar.AppendLine("		SUM(Com_d)		AS Com_d, ")
            loComandoSeleccionar.AppendLine("		SUM(Pag_m)		AS Pag_m, ")
            loComandoSeleccionar.AppendLine("		SUM(Pag_d)		AS Pag_d, ")
            loComandoSeleccionar.AppendLine("		SUM(CXP_m)		AS CXP_m, ")
            loComandoSeleccionar.AppendLine("		SUM(CXP_d)		AS CXP_d, ")
            loComandoSeleccionar.AppendLine("		SUM(Ord_m)		AS Ord_m, ")
            loComandoSeleccionar.AppendLine("		SUM(Ord_d)		AS Ord_d, ")
            loComandoSeleccionar.AppendLine("		SUM(Dep_m)		AS Dep_m, ")
            loComandoSeleccionar.AppendLine("		SUM(Dep_d)		AS Dep_d, ")
            loComandoSeleccionar.AppendLine("		SUM(MOC_m)		AS MOC_m, ")
            loComandoSeleccionar.AppendLine("		SUM(MOC_d)		AS MOC_d, ")
            loComandoSeleccionar.AppendLine("		SUM(MOB_m)		AS MOB_m, ")
            loComandoSeleccionar.AppendLine("		SUM(MOB_d)		AS MOB_d")
            loComandoSeleccionar.AppendLine("INTO #tmpInformacion")
            loComandoSeleccionar.AppendLine("FROM")
            loComandoSeleccionar.AppendLine("(")
            loComandoSeleccionar.AppendLine("--Informacion de ajustes")
            loComandoSeleccionar.AppendLine("SELECT YEAR(Fec_ini)	AS Año, ")
            loComandoSeleccionar.AppendLine("	   MONTH(fec_ini)	AS Mes, ")
            loComandoSeleccionar.AppendLine("                    'Ajustes'		AS tabla, ")
            loComandoSeleccionar.AppendLine("	   SUM(mon_net)		AS Aju_m, ")
            loComandoSeleccionar.AppendLine("	   Count(documento)	AS Aju_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Tras_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Tras_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Fact_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Fact_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Cob_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Cob_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS CXC_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS CXC_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Com_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Com_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Pag_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Pag_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS CXP_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS CXP_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Ord_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Ord_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Dep_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Dep_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS MOC_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS MOC_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS MOB_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS MOB_d ")
            loComandoSeleccionar.AppendLine("FROM Ajustes ")
            loComandoSeleccionar.AppendLine("WHERE Fec_ini BETWEEN " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("       AND " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("       AND status <> 'Anulado'")
            loComandoSeleccionar.AppendLine("GROUP BY YEAR(Fec_ini), MONTH(fec_ini) ")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine("UNION ALL ")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine("--Informacion de Traslados ")
            loComandoSeleccionar.AppendLine("SELECT YEAR(Fec_ini)	AS Año, ")
            loComandoSeleccionar.AppendLine("	   MONTH(fec_ini)	AS Mes, ")
            loComandoSeleccionar.AppendLine("                        'Traslados'		AS tabla, ")
            loComandoSeleccionar.AppendLine("	   0				AS Aju_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Aju_d, ")
            loComandoSeleccionar.AppendLine("	   SUM(mon_bru)		AS Tras_m, ")
            loComandoSeleccionar.AppendLine("	   Count(documento)	AS Tras_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Fact_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Fact_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Cob_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Cob_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS CXC_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS CXC_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Com_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Com_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Pag_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Pag_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS CXP_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS CXP_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Ord_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Ord_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Dep_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Dep_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS MOC_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS MOC_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS MOB_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS MOB_d ")
            loComandoSeleccionar.AppendLine("FROM traslados ")
            loComandoSeleccionar.AppendLine("WHERE Fec_ini BETWEEN " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("       AND " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("       AND status <> 'Anulado'")
            loComandoSeleccionar.AppendLine("GROUP BY YEAR(Fec_ini), MONTH(fec_ini) ")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine("UNION ALL ")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine("--Informacion de Facturas ")
            loComandoSeleccionar.AppendLine("SELECT YEAR(Fec_ini)	AS Año, ")
            loComandoSeleccionar.AppendLine("	   MONTH(fec_ini)	AS Mes, ")
            loComandoSeleccionar.AppendLine("                            'Facturas'		AS tabla, ")
            loComandoSeleccionar.AppendLine("	   0				AS Aju_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Aju_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Tras_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Tras_d, ")
            loComandoSeleccionar.AppendLine("	   SUM(mon_net)		AS Fact_m, ")
            loComandoSeleccionar.AppendLine("	   Count(documento)	AS Fact_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Cob_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Cob_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS CXC_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS CXC_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Com_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Com_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Pag_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Pag_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS CXP_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS CXP_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Ord_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Ord_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Dep_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Dep_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS MOC_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS MOC_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS MOB_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS MOB_d ")
            loComandoSeleccionar.AppendLine("FROM facturas ")
            loComandoSeleccionar.AppendLine("WHERE Fec_ini BETWEEN " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("       AND " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("       AND status <> 'Anulado'")
            loComandoSeleccionar.AppendLine("GROUP BY YEAR(Fec_ini), MONTH(fec_ini) ")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine("UNION ALL ")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine("--Informacion de Cobros ")
            loComandoSeleccionar.AppendLine("SELECT YEAR(Fec_ini)	AS Año, ")
            loComandoSeleccionar.AppendLine("	   MONTH(fec_ini)	AS Mes, ")
            loComandoSeleccionar.AppendLine("                                'Cobros'		AS tabla, ")
            loComandoSeleccionar.AppendLine("	   0				AS Aju_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Aju_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Tras_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Tras_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Fact_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Fact_d, ")
            loComandoSeleccionar.AppendLine("	   SUM(mon_net)		AS Cob_m, ")
            loComandoSeleccionar.AppendLine("	   Count(documento)	AS Cob_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS CXC_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS CXC_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Com_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Com_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Pag_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Pag_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS CXP_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS CXP_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Ord_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Ord_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Dep_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Dep_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS MOC_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS MOC_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS MOB_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS MOB_d ")
            loComandoSeleccionar.AppendLine("FROM Cobros ")
            loComandoSeleccionar.AppendLine("WHERE Fec_ini BETWEEN " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("       AND " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("       AND status <> 'Anulado'")
            loComandoSeleccionar.AppendLine("GROUP BY YEAR(Fec_ini), MONTH(fec_ini) ")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine("UNION ALL ")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine("--Informacion de Cuentas Cobrar ")
            loComandoSeleccionar.AppendLine("SELECT YEAR(Fec_ini)	AS Año, ")
            loComandoSeleccionar.AppendLine("	   MONTH(fec_ini)	AS Mes, ")
            loComandoSeleccionar.AppendLine("                                    'CxC'			AS tabla, ")
            loComandoSeleccionar.AppendLine("	   0				AS Aju_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Aju_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Tras_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Tras_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Fact_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Fact_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Cob_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Cob_d, ")
            loComandoSeleccionar.AppendLine("	   SUM(mon_net)		AS CXC_m, ")
            loComandoSeleccionar.AppendLine("	   Count(documento)	AS CXC_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Com_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Com_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Pag_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Pag_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS CXP_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS CXP_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Ord_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Ord_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Dep_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Dep_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS MOC_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS MOC_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS MOB_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS MOB_d ")
            loComandoSeleccionar.AppendLine("FROM Cuentas_Cobrar ")
            loComandoSeleccionar.AppendLine("WHERE COD_TIP IN ('ISLR','RETIVA','RETPAT') ")
            loComandoSeleccionar.AppendLine("    AND Fec_ini BETWEEN " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("       AND " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("       AND status <> 'Anulado'")
            loComandoSeleccionar.AppendLine("GROUP BY YEAR(Fec_ini), MONTH(fec_ini) ")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine("UNION ALL ")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine("--Informacion de Compras ")
            loComandoSeleccionar.AppendLine("SELECT YEAR(Fec_ini)	AS Año, ")
            loComandoSeleccionar.AppendLine("	   MONTH(fec_ini)	AS Mes, ")
            loComandoSeleccionar.AppendLine("                                        'Compras'		AS tabla, ")
            loComandoSeleccionar.AppendLine("	   0				AS Aju_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Aju_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Tras_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Tras_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Fact_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Fact_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Cob_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Cob_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS CXC_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS CXC_d, ")
            loComandoSeleccionar.AppendLine("	   SUM(mon_net)		AS Com_m, ")
            loComandoSeleccionar.AppendLine("	   Count(documento)	AS Com_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Pag_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Pag_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS CXP_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS CXP_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Ord_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Ord_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Dep_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Dep_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS MOC_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS MOC_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS MOB_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS MOB_d ")
            loComandoSeleccionar.AppendLine("FROM compras ")
            loComandoSeleccionar.AppendLine("WHERE Fec_ini BETWEEN " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("       AND " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("       AND status <> 'Anulado'")
            loComandoSeleccionar.AppendLine("GROUP BY YEAR(Fec_ini), MONTH(fec_ini) ")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine("UNION ALL ")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine("--Informacion de Pagos ")
            loComandoSeleccionar.AppendLine("SELECT YEAR(Fec_ini)	AS Año, ")
            loComandoSeleccionar.AppendLine("	   MONTH(fec_ini)	AS Mes, ")
            loComandoSeleccionar.AppendLine("                                            'Pagos'		AS tabla, ")
            loComandoSeleccionar.AppendLine("	   0				AS Aju_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Aju_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Tras_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Tras_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Fact_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Fact_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Cob_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Cob_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS CXC_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS CXC_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Com_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Com_d, ")
            loComandoSeleccionar.AppendLine("	   SUM(mon_net)		AS Pag_m, ")
            loComandoSeleccionar.AppendLine("	   Count(documento)	AS Pag_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS CXP_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS CXP_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Ord_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Ord_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Dep_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Dep_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS MOC_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS MOC_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS MOB_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS MOB_d ")
            loComandoSeleccionar.AppendLine("FROM Pagos ")
            loComandoSeleccionar.AppendLine("WHERE Fec_ini BETWEEN " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("       AND " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("       AND status <> 'Anulado'")
            loComandoSeleccionar.AppendLine("GROUP BY YEAR(Fec_ini), MONTH(fec_ini) ")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine("UNION ALL ")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine("--Informacion de Cuentas por Pagar ")
            loComandoSeleccionar.AppendLine("SELECT YEAR(Fec_ini)	AS Año, ")
            loComandoSeleccionar.AppendLine("	   MONTH(fec_ini)	AS Mes, ")
            loComandoSeleccionar.AppendLine("     'CxP'		        AS tabla, ")
            loComandoSeleccionar.AppendLine("	   0				AS Aju_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Aju_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Tras_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Tras_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Fact_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Fact_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Cob_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Cob_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS CXC_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS CXC_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Com_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Com_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Pag_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Pag_d, ")
            loComandoSeleccionar.AppendLine("	   SUM(mon_net)		AS CXP_m, ")
            loComandoSeleccionar.AppendLine("	   Count(documento)	AS CXP_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Ord_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Ord_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Dep_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Dep_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS MOC_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS MOC_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS MOB_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS MOB_d ")
            loComandoSeleccionar.AppendLine("FROM Cuentas_pagar ")
            loComandoSeleccionar.AppendLine("WHERE COD_TIP IN ('ISLR','RETIVA','RETPAT') ")
            loComandoSeleccionar.AppendLine("   And Fec_ini BETWEEN " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("       AND " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("       AND status <> 'Anulado'")
            loComandoSeleccionar.AppendLine("GROUP BY YEAR(Fec_ini), MONTH(fec_ini) ")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine("UNION ALL ")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine("--Informacion de Ordenes de Pagos ")
            loComandoSeleccionar.AppendLine("SELECT YEAR(Fec_ini)	AS Año, ")
            loComandoSeleccionar.AppendLine("	   MONTH(fec_ini)	AS Mes, ")
            loComandoSeleccionar.AppendLine("      'OrdPag'		    AS tabla, ")
            loComandoSeleccionar.AppendLine("	   0				AS Aju_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Aju_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Tras_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Tras_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Fact_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Fact_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Cob_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Cob_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS CXC_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS CXC_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Com_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Com_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Pag_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Pag_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS CXP_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS CXP_d, ")
            loComandoSeleccionar.AppendLine("	   SUM(mon_net)		AS Ord_m, ")
            loComandoSeleccionar.AppendLine("	   Count(documento)	AS Ord_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Dep_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Dep_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS MOC_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS MOC_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS MOB_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS MOB_d ")
            loComandoSeleccionar.AppendLine("FROM Ordenes_Pagos ")
            loComandoSeleccionar.AppendLine("WHERE Fec_ini BETWEEN " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("       AND " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("       AND status <> 'Anulado'")
            loComandoSeleccionar.AppendLine("GROUP BY YEAR(Fec_ini), MONTH(fec_ini) ")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine("UNION ALL ")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine("--Informacion de Depositos ")
            loComandoSeleccionar.AppendLine("SELECT YEAR(Fec_ini)	AS Año, ")
            loComandoSeleccionar.AppendLine("	   MONTH(fec_ini)	AS Mes, ")
            loComandoSeleccionar.AppendLine("      'Depositos'		AS tabla, ")
            loComandoSeleccionar.AppendLine("	   0				AS Aju_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Aju_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Tras_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Tras_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Fact_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Fact_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Cob_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Cob_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS CXC_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS CXC_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Com_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Com_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Pag_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Pag_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS CXP_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS CXP_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Ord_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Ord_d, ")
            loComandoSeleccionar.AppendLine("	   SUM(mon_net)		AS Dep_m, ")
            loComandoSeleccionar.AppendLine("	   Count(documento)	AS Dep_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS MOC_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS MOC_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS MOB_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS MOB_d ")
            loComandoSeleccionar.AppendLine("FROM Depositos ")
            loComandoSeleccionar.AppendLine("WHERE Fec_ini BETWEEN " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("       AND " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("       AND status <> 'Anulado'")
            loComandoSeleccionar.AppendLine("GROUP BY YEAR(Fec_ini), MONTH(fec_ini) ")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine("UNION ALL ")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine("--Informacion de Movimientos de Cajas ")
            loComandoSeleccionar.AppendLine("SELECT YEAR(Fec_ini)	AS Año, ")
            loComandoSeleccionar.AppendLine("	   MONTH(fec_ini)	AS Mes, ")
            loComandoSeleccionar.AppendLine("     'MC'				AS tabla, ")
            loComandoSeleccionar.AppendLine("	   0				AS Aju_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Aju_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Tras_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Tras_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Fact_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Fact_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Cob_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Cob_d, ")
            loComandoSeleccionar.AppendLine("      0				AS CXC_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS CXC_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Com_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Com_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Pag_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Pag_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS CXP_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS CXP_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Ord_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Ord_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Dep_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Dep_d, ")
            loComandoSeleccionar.AppendLine("	   SUM(mon_deb-mon_hab)	AS MOC_m, ")
            loComandoSeleccionar.AppendLine("	  Count(documento)	AS MOC_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS MOB_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS MOB_d ")
            loComandoSeleccionar.AppendLine("FROM movimientos_cajas ")
            loComandoSeleccionar.AppendLine("WHERE Fec_ini BETWEEN " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("       AND " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("       AND status <> 'Anulado'")
            loComandoSeleccionar.AppendLine("GROUP BY YEAR(Fec_ini), MONTH(fec_ini) ")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine("UNION ALL ")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine("--Informacion de Movimientos Bancos ")
            loComandoSeleccionar.AppendLine("SELECT YEAR(Fec_ini)	AS Año, ")
            loComandoSeleccionar.AppendLine("	   MONTH(fec_ini)	AS Mes, ")
            loComandoSeleccionar.AppendLine("      'MB'		        AS tabla, ")
            loComandoSeleccionar.AppendLine("	   0				AS Aju_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Aju_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Tras_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Tras_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Fact_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Fact_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Cob_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Cob_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS CXC_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS CXC_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Com_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Com_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Pag_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Pag_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS CXP_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS CXP_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Ord_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Ord_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS Dep_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS Dep_d, ")
            loComandoSeleccionar.AppendLine("	   0				AS MOC_m, ")
            loComandoSeleccionar.AppendLine("	   0				AS MOC_d, ")
            loComandoSeleccionar.AppendLine("	   SUM(mon_deb-mon_hab)	AS MOB_m, ")
            loComandoSeleccionar.AppendLine("	   Count(documento)	AS MOB_d ")
            loComandoSeleccionar.AppendLine("FROM movimientos_cuentas ")
            loComandoSeleccionar.AppendLine("WHERE Fec_ini BETWEEN " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("       AND " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("       AND status <> 'Anulado'")
            loComandoSeleccionar.AppendLine("GROUP BY YEAR(Fec_ini), MONTH(fec_ini)) AS  Information ")
            loComandoSeleccionar.AppendLine("Group by AÑO, MES ")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine("SELECT	#tmpLlenarMeses.año, ")
            loComandoSeleccionar.AppendLine("		#tmpLlenarMeses.mes, ")
            loComandoSeleccionar.AppendLine("	   COALESCE(#tmpInformacion.Aju_m,0)	AS Aju_m, ")
            loComandoSeleccionar.AppendLine("	   COALESCE(#tmpInformacion.Aju_d,0)	AS Aju_d, ")
            loComandoSeleccionar.AppendLine("	   COALESCE(#tmpInformacion.Tras_m,0)	AS Tras_m, ")
            loComandoSeleccionar.AppendLine("	   COALESCE(#tmpInformacion.Tras_d,0)	AS Tras_d, ")
            loComandoSeleccionar.AppendLine("	   COALESCE(#tmpInformacion.Fact_m,0)	AS Fact_m, ")
            loComandoSeleccionar.AppendLine("	   COALESCE(#tmpInformacion.Fact_d,0)	AS Fact_d, ")
            loComandoSeleccionar.AppendLine("	   COALESCE(#tmpInformacion.Cob_m,0)	AS Cob_m, ")
            loComandoSeleccionar.AppendLine("	   COALESCE(#tmpInformacion.Cob_d,0)	AS Cob_d, ")
            loComandoSeleccionar.AppendLine("	   COALESCE(#tmpInformacion.CXC_m,0)	AS CXC_m, ")
            loComandoSeleccionar.AppendLine("	   COALESCE(#tmpInformacion.CXC_d,0)	AS CXC_d, ")
            loComandoSeleccionar.AppendLine("	   COALESCE(#tmpInformacion.Com_m,0)	AS Com_m, ")
            loComandoSeleccionar.AppendLine("	   COALESCE(#tmpInformacion.Com_d,0)	AS Com_d, ")
            loComandoSeleccionar.AppendLine("	   COALESCE(#tmpInformacion.Pag_m,0)	AS Pag_m, ")
            loComandoSeleccionar.AppendLine("	   COALESCE(#tmpInformacion.Pag_d,0)	AS Pag_d, ")
            loComandoSeleccionar.AppendLine("	   COALESCE(#tmpInformacion.CXP_m,0)	AS CXP_m, ")
            loComandoSeleccionar.AppendLine("	   COALESCE(#tmpInformacion.CXP_d,0)	AS CXP_d, ")
            loComandoSeleccionar.AppendLine("	   COALESCE(#tmpInformacion.Ord_m,0)	AS Ord_m, ")
            loComandoSeleccionar.AppendLine("	   COALESCE(#tmpInformacion.Ord_d,0)	AS Ord_d, ")
            loComandoSeleccionar.AppendLine("	   COALESCE(#tmpInformacion.Dep_m,0)	AS Dep_m, ")
            loComandoSeleccionar.AppendLine("	   COALESCE(#tmpInformacion.Dep_d,0)	AS Dep_d, ")
            loComandoSeleccionar.AppendLine("	   COALESCE(#tmpInformacion.MOC_m,0)	AS MOC_m, ")
            loComandoSeleccionar.AppendLine("	   COALESCE(#tmpInformacion.MOC_d,0)	AS MOC_d, ")
            loComandoSeleccionar.AppendLine("	   COALESCE(#tmpInformacion.MOB_m,0)	AS MOB_m, ")
            loComandoSeleccionar.AppendLine("	   COALESCE(#tmpInformacion.MOB_d,0)	AS MOB_d ")
            loComandoSeleccionar.AppendLine("FROM #tmpLlenarMeses ")
            loComandoSeleccionar.AppendLine("	LEFT JOIN #tmpInformacion ON #tmpInformacion.año = #tmpLlenarMeses.año ")
            loComandoSeleccionar.AppendLine("		AND #tmpInformacion.mes = #tmpLlenarMeses.mes  ")
            loComandoSeleccionar.AppendLine("ORDER BY #tmpLlenarMeses.año, #tmpLlenarMeses.mes ")
            loComandoSeleccionar.AppendLine(" ")
            loComandoSeleccionar.AppendLine("DROP TABLE #tmpLlenarMeses ")
            loComandoSeleccionar.AppendLine("DROP TABLE #tmpInformacion ")

            'Me.mEscribirConsulta(loComandoSeleccionar.ToString())
            Dim loServicios As New cusDatos.goDatos

            Dim laDatosReporte As DataSet = loServicios.mObtenerTodosSinEsquema(loComandoSeleccionar.ToString(), "curReportes")

            loObjetoReporte = cusAplicacion.goReportes.mCargarReporte("rOperaciones_Empresa", laDatosReporte)

            Me.mTraducirReporte(loObjetoReporte)

            Me.mFormatearCamposReporte(loObjetoReporte)

            Me.crvrOperaciones_Empresa.ReportSource = loObjetoReporte


        Catch loExcepcion As Exception

            Me.WbcAdministradorMensajeModal.mMostrarMensajeModal("Error", _
                          "No se pudo Completar el Proceso: " & loExcepcion.Message, _
                           vis3Controles.wbcAdministradorMensajeModal.enumTipoMensaje.KN_Error, _
                           "auto", _
                           "auto")

        End Try

    End Sub



    Protected Sub Page_Unload(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Unload
        Try

            loObjetoReporte.Close()

        Catch loExcepcion As Exception


        End Try
    End Sub

End Class
'-------------------------------------------------------------------------------------------'
' Fin del codigo
'-------------------------------------------------------------------------------------------'
' EAG:  10/10/15 Codigo inicial
'-------------------------------------------------------------------------------------------' 
