'-------------------------------------------------------------------------------------------'
' Inicio del codigo
'-------------------------------------------------------------------------------------------'
' Importando librerias 
'-------------------------------------------------------------------------------------------'
Imports System.Data

'-------------------------------------------------------------------------------------------'
' Inicio de clase "rRInventarios_Articulos"
'-------------------------------------------------------------------------------------------'
Partial Class rRInventarios_Articulos
    Inherits vis2formularios.frmReporte

    Dim loObjetoReporte As CrystalDecisions.CrystalReports.Engine.ReportDocument
    
    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load

        Dim lcParametro0Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(0), goServicios.enuOpcionesRedondeo.KN_FechaInicioDelDia)
        Dim lcParametro0Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(0), goServicios.enuOpcionesRedondeo.KN_FechaFinDelDia)
        Dim lcParametro1Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(1), goServicios.enuOpcionesRedondeo.KN_FechaInicioDelDia)
        Dim lcParametro1Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(1), goServicios.enuOpcionesRedondeo.KN_FechaFinDelDia)
        Dim lcParametro2Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(2), goServicios.enuOpcionesRedondeo.KN_FechaInicioDelDia)
        Dim lcParametro2Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(2), goServicios.enuOpcionesRedondeo.KN_FechaFinDelDia)
        Dim lcParametro3Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(3), goServicios.enuOpcionesRedondeo.KN_FechaInicioDelDia)
        Dim lcParametro3Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(3), goServicios.enuOpcionesRedondeo.KN_FechaFinDelDia)
        Dim lcParametro4Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(4), goServicios.enuOpcionesRedondeo.KN_FechaInicioDelDia)
        Dim lcParametro4Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(4), goServicios.enuOpcionesRedondeo.KN_FechaFinDelDia)
        Dim lcParametro5Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(5), goServicios.enuOpcionesRedondeo.KN_FechaInicioDelDia)
        Dim lcParametro5Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(5), goServicios.enuOpcionesRedondeo.KN_FechaFinDelDia)
        Dim lcParametro6Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(6), goServicios.enuOpcionesRedondeo.KN_FechaInicioDelDia)
        Dim lcParametro6Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(6), goServicios.enuOpcionesRedondeo.KN_FechaFinDelDia)
        Dim lcParametro7Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(7), goServicios.enuOpcionesRedondeo.KN_FechaInicioDelDia)
        Dim lcParametro7Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(7), goServicios.enuOpcionesRedondeo.KN_FechaFinDelDia)
        Dim lcParametro8Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(8), goServicios.enuOpcionesRedondeo.KN_FechaInicioDelDia)
        Dim lcParametro8Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(8), goServicios.enuOpcionesRedondeo.KN_FechaFinDelDia)
        Dim lcParametro9Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(9), goServicios.enuOpcionesRedondeo.KN_FechaInicioDelDia)
        Dim lcParametro9Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(9), goServicios.enuOpcionesRedondeo.KN_FechaFinDelDia)
        Dim lcParametro10Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(10), goServicios.enuOpcionesRedondeo.KN_FechaInicioDelDia)
        Dim lcParametro10Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(10), goServicios.enuOpcionesRedondeo.KN_FechaFinDelDia)
        Dim lcParametro11Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(11), goServicios.enuOpcionesRedondeo.KN_FechaInicioDelDia)
        Dim lcParametro11Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(11), goServicios.enuOpcionesRedondeo.KN_FechaFinDelDia)


        Dim lcOrdenamiento As String = cusAplicacion.goReportes.pcOrden
         Dim lcAlmacenTransito As String
            lcAlmacenTransito = goServicios.mObtenerCampoFormatoSQL(goOpciones.mObtener("CODALMTRA", "C"))



        Try

            Dim loComandoSeleccionar As New StringBuilder()

            '-------------------------------------------------------------------------------------------'
            ' Select para ubicar el Stock Inicial a partir de la tabla de Ajustes de Inventarios 
            '-------------------------------------------------------------------------------------------'
            loComandoSeleccionar.AppendLine(" SELECT	Renglones_Ajustes.Cod_Art																		AS	Cod_Art, ")
            loComandoSeleccionar.AppendLine("			Articulos.Nom_Art																				AS	Nom_Art, ")
            loComandoSeleccionar.AppendLine("			SUM(CASE WHEN Renglones_Ajustes.Tipo = 'Entrada' THEN Renglones_Ajustes.Can_Art1 ELSE 0 END)	AS	Can_IniE, ")
            loComandoSeleccionar.AppendLine("			SUM(CASE WHEN Renglones_Ajustes.Tipo = 'Salida' THEN Renglones_Ajustes.Can_Art1 ELSE 0 END)		AS	Can_IniS ")
            loComandoSeleccionar.AppendLine(" INTO		#TablaTemporalAjustes ")
            loComandoSeleccionar.AppendLine(" FROM		Ajustes, ")
            loComandoSeleccionar.AppendLine("			Renglones_Ajustes, ")
            loComandoSeleccionar.AppendLine("			Articulos ")
            loComandoSeleccionar.AppendLine(" WHERE		Ajustes.Documento					=	Renglones_Ajustes.Documento ")
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Art				=	Renglones_Ajustes.Cod_Art ")
            loComandoSeleccionar.AppendLine("			AND Ajustes.Status					=	'Confirmado' ")
            loComandoSeleccionar.AppendLine("			AND Renglones_Ajustes.Tipo			IN	('Entrada', 'Salida') ")
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Art				BETWEEN " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("			AND Ajustes.Fec_Ini					< " & lcParametro1Desde)
            loComandoSeleccionar.AppendLine("			AND Renglones_Ajustes.Cod_Alm		BETWEEN " & lcParametro2Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro2Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Dep				BETWEEN " & lcParametro3Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro3Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Sec				BETWEEN " & lcParametro4Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro4Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Mar				BETWEEN " & lcParametro5Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro5Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Cla				BETWEEN " & lcParametro6Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro6Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Tip				BETWEEN " & lcParametro7Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro7Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Pro				BETWEEN " & lcParametro8Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro8Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Uni1				BETWEEN " & lcParametro9Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro9Hasta)
            loComandoSeleccionar.AppendLine("			AND Ajustes.Cod_Suc					BETWEEN " & lcParametro10Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro10Hasta)
            loComandoSeleccionar.AppendLine("           AND Articulos.Cod_Ubi				BETWEEN " & lcParametro11Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro11Hasta)
            loComandoSeleccionar.AppendLine(" GROUP BY	Renglones_Ajustes.Cod_Art, ")
            loComandoSeleccionar.AppendLine("			Articulos.Nom_Art ")

            '-------------------------------------------------------------------------------------------'
            ' Select para ubicar el Stock Inicial a partir de la tabla de Compras 
            '-------------------------------------------------------------------------------------------'
            loComandoSeleccionar.AppendLine("SELECT		Renglones_Compras.Cod_Art			AS	Cod_Art, ")
            loComandoSeleccionar.AppendLine("			Articulos.Nom_Art					AS	Nom_Art, ")
            loComandoSeleccionar.AppendLine("			SUM(Renglones_Compras.Can_Art1)		AS	Can_IniE, ")
            loComandoSeleccionar.AppendLine("			0.00								AS	Can_IniS ")
            loComandoSeleccionar.AppendLine("INTO		#TablaTemporalCompras ")
            loComandoSeleccionar.AppendLine("FROM		Compras, ")
            loComandoSeleccionar.AppendLine("			Renglones_Compras, ")
            loComandoSeleccionar.AppendLine("			Articulos ")
            loComandoSeleccionar.AppendLine("WHERE		Compras.Documento					=	Renglones_Compras.Documento ")
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Art				=	Renglones_Compras.Cod_Art ")
            loComandoSeleccionar.AppendLine("			AND Compras.Status					IN	('Confirmado', 'Afectado', 'Procesado') ")
            loComandoSeleccionar.AppendLine("			AND Renglones_Compras.Tip_Ori		<>	'Recepciones' ")
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Art				BETWEEN " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("			AND Compras.Fec_Ini					< " & lcParametro1Desde)
            loComandoSeleccionar.AppendLine("			AND Renglones_Compras.Cod_Alm		BETWEEN " & lcParametro2Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro2Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Dep				BETWEEN " & lcParametro3Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro3Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Sec				BETWEEN " & lcParametro4Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro4Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Mar				BETWEEN " & lcParametro5Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro5Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Cla				BETWEEN " & lcParametro6Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro6Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Tip				BETWEEN " & lcParametro7Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro7Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Pro				BETWEEN " & lcParametro8Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro8Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Uni1				BETWEEN " & lcParametro9Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro9Hasta)
            loComandoSeleccionar.AppendLine("			AND Compras.Cod_Suc					BETWEEN " & lcParametro10Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro10Hasta)
            loComandoSeleccionar.AppendLine("           AND Articulos.Cod_Ubi				BETWEEN " & lcParametro11Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro11Hasta)
            loComandoSeleccionar.AppendLine("GROUP BY	Renglones_Compras.Cod_Art, ")
            loComandoSeleccionar.AppendLine("			Articulos.Nom_Art ")

            '-------------------------------------------------------------------------------------------'
            ' Select para ubicar el Stock Inicial a partir de la tabla de Notas de Recepciones
            '-------------------------------------------------------------------------------------------'
            loComandoSeleccionar.AppendLine(" SELECT	Renglones_Recepciones.Cod_Art		AS	Cod_Art, ")
            loComandoSeleccionar.AppendLine("			Articulos.Nom_Art					AS	Nom_Art, ")
            loComandoSeleccionar.AppendLine("			SUM(Renglones_Recepciones.Can_Art1)	AS	Can_IniE, ")
            loComandoSeleccionar.AppendLine("			0.00								AS	Can_IniS ")
            loComandoSeleccionar.AppendLine(" INTO		#TablaTemporalRecepciones ")
            loComandoSeleccionar.AppendLine(" FROM		Recepciones, ")
            loComandoSeleccionar.AppendLine("			Renglones_Recepciones, ")
            loComandoSeleccionar.AppendLine("			Articulos ")
            loComandoSeleccionar.AppendLine(" WHERE		Recepciones.Documento				=	Renglones_Recepciones.Documento ")
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Art				=	Renglones_Recepciones.Cod_Art ")
            loComandoSeleccionar.AppendLine("			AND Recepciones.Status				IN	('Confirmado', 'Afectado', 'Procesado') ")
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Art				BETWEEN " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("			AND Recepciones.Fec_Ini				< " & lcParametro1Desde)
            loComandoSeleccionar.AppendLine("			AND Renglones_Recepciones.Cod_Alm	BETWEEN " & lcParametro2Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro2Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Dep				BETWEEN " & lcParametro3Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro3Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Sec				BETWEEN " & lcParametro4Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro4Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Mar				BETWEEN " & lcParametro5Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro5Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Cla				BETWEEN " & lcParametro6Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro6Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Tip				BETWEEN " & lcParametro7Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro7Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Pro				BETWEEN " & lcParametro8Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro8Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Uni1				BETWEEN " & lcParametro9Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro9Hasta)
            loComandoSeleccionar.AppendLine("			AND Recepciones.Cod_Suc				BETWEEN " & lcParametro10Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro10Hasta)
            loComandoSeleccionar.AppendLine("           AND Articulos.Cod_Ubi				BETWEEN " & lcParametro11Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro11Hasta)
            loComandoSeleccionar.AppendLine(" GROUP BY	Renglones_Recepciones.Cod_Art, ")
            loComandoSeleccionar.AppendLine("			Articulos.Nom_Art ")
            
            '-------------------------------------------------------------------------------------------'
            ' Select para ubicar el Stock Inicial a partir de la tabla de Devoluciones de Venta
            '-------------------------------------------------------------------------------------------'
            loComandoSeleccionar.AppendLine("SELECT		Renglones_DClientes.Cod_Art				AS	Cod_Art, ")
            loComandoSeleccionar.AppendLine("			Articulos.Nom_Art						AS	Nom_Art, ")
            loComandoSeleccionar.AppendLine("			SUM(Renglones_DClientes.Can_Art1)		AS	Can_IniE, ")
            loComandoSeleccionar.AppendLine("			0.00									AS	Can_IniS ")
            loComandoSeleccionar.AppendLine("INTO		#TablaTemporalDevClientes ")
            loComandoSeleccionar.AppendLine("FROM		Devoluciones_Clientes, ")
            loComandoSeleccionar.AppendLine("			Renglones_DClientes, ")
            loComandoSeleccionar.AppendLine("			Articulos ")
            loComandoSeleccionar.AppendLine("WHERE		Devoluciones_Clientes.Documento		=	Renglones_DClientes.Documento ")
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Art				=	Renglones_DClientes.Cod_Art ")
            loComandoSeleccionar.AppendLine("			AND Devoluciones_Clientes.Status	IN	('Confirmado', 'Afectado', 'Procesado') ")
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Art				BETWEEN " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("			AND Devoluciones_Clientes.Fec_Ini < " & lcParametro1Desde)
            loComandoSeleccionar.AppendLine("			AND Renglones_DClientes.Cod_Alm		BETWEEN " & lcParametro2Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro2Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Dep				BETWEEN " & lcParametro3Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro3Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Sec				BETWEEN " & lcParametro4Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro4Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Mar				BETWEEN " & lcParametro5Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro5Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Cla				BETWEEN " & lcParametro6Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro6Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Tip				BETWEEN " & lcParametro7Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro7Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Pro				BETWEEN " & lcParametro8Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro8Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Uni1				BETWEEN " & lcParametro9Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro9Hasta)
            loComandoSeleccionar.AppendLine("			AND Devoluciones_Clientes.Cod_Suc	BETWEEN " & lcParametro10Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro10Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Ubi				BETWEEN " & lcParametro11Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro11Hasta)
            loComandoSeleccionar.AppendLine("GROUP BY	Renglones_DClientes.Cod_Art, ")
            loComandoSeleccionar.AppendLine("			Articulos.Nom_Art ")


			 '-------------------------------------------------------------------------------------------'
            ' Select para ubicar el Stock Inicial a partir de la tabla de Traslados en las Entradas
            '-------------------------------------------------------------------------------------------'
            loComandoSeleccionar.AppendLine(" SELECT	Renglones_Traslados.Cod_Art				AS	Cod_Art, ")
            loComandoSeleccionar.AppendLine("			Articulos.Nom_Art						AS	Nom_Art, ")
            loComandoSeleccionar.AppendLine("			SUM(Renglones_Traslados.Can_Art1)		AS	Can_IniE, ")
            loComandoSeleccionar.AppendLine("			0.00									AS	Can_IniS ")
            loComandoSeleccionar.AppendLine(" INTO		#TablaTemporalTrasladosEntradas ")
            loComandoSeleccionar.AppendLine(" FROM		Traslados, ")
            loComandoSeleccionar.AppendLine("			Renglones_Traslados, ")
            loComandoSeleccionar.AppendLine("			Articulos ")
            loComandoSeleccionar.AppendLine(" WHERE		Traslados.Documento				=	Renglones_Traslados.Documento ")
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Art			=	Renglones_Traslados.Cod_Art ")
            loComandoSeleccionar.AppendLine("			AND Traslados.Status			IN ('Confirmado', 'Procesado') ") 
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Art				BETWEEN " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("			AND Traslados.Fec_Ini < " & lcParametro1Desde)
            loComandoSeleccionar.AppendLine("			AND (CASE Traslados.Status " )
            loComandoSeleccionar.AppendLine("					WHEN 'Confirmado' THEN " & lcAlmacenTransito)
            loComandoSeleccionar.AppendLine("					ELSE Traslados.Alm_Des ")
            loComandoSeleccionar.AppendLine("				END)	BETWEEN " & lcParametro2Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro2Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Dep				BETWEEN " & lcParametro3Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro3Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Sec				BETWEEN " & lcParametro4Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro4Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Mar				BETWEEN " & lcParametro5Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro5Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Cla				BETWEEN " & lcParametro6Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro6Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Tip				BETWEEN " & lcParametro7Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro7Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Pro				BETWEEN " & lcParametro8Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro8Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Uni1				BETWEEN " & lcParametro9Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro9Hasta)
            loComandoSeleccionar.AppendLine("			AND Traslados.Cod_Suc				BETWEEN " & lcParametro10Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro10Hasta)
            loComandoSeleccionar.AppendLine("           AND Articulos.Cod_Ubi				BETWEEN " & lcParametro11Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro11Hasta)
            loComandoSeleccionar.AppendLine("GROUP BY	Renglones_Traslados.Cod_Art, ")
            loComandoSeleccionar.AppendLine("			Articulos.Nom_Art")
	
            '-------------------------------------------------------------------------------------------'
            ' Select para ubicar el Stock Inicial a partir de la tabla de Facturas de Ventas
            '-------------------------------------------------------------------------------------------'
            loComandoSeleccionar.AppendLine("SELECT		Renglones_Facturas.Cod_Art			AS	Cod_Art, ")
            loComandoSeleccionar.AppendLine("			Articulos.Nom_Art					AS	Nom_Art, ")
            loComandoSeleccionar.AppendLine("			0.00								AS	Can_IniE, ")
            loComandoSeleccionar.AppendLine("			SUM(Renglones_Facturas.Can_Art1)	AS	Can_IniS ")
            loComandoSeleccionar.AppendLine("INTO		#TablaTemporalFacturas ")
            loComandoSeleccionar.AppendLine("FROM		Facturas, ")
            loComandoSeleccionar.AppendLine("			Renglones_Facturas, ")
            loComandoSeleccionar.AppendLine("			Articulos ")
            loComandoSeleccionar.AppendLine("WHERE		Facturas.Documento					=	Renglones_Facturas.Documento ")
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Art				=	Renglones_Facturas.Cod_Art ")
            loComandoSeleccionar.AppendLine("			AND Facturas.Status					IN	('Confirmado', 'Afectado', 'Procesado') ")
            loComandoSeleccionar.AppendLine("			AND Renglones_Facturas.Tip_Ori		<>	'Entregas' ")
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Art				BETWEEN " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("			AND Facturas.Fec_Ini				< " & lcParametro1Desde)
            loComandoSeleccionar.AppendLine("			AND Renglones_Facturas.Cod_Alm		BETWEEN " & lcParametro2Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro2Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Dep				BETWEEN " & lcParametro3Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro3Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Sec				BETWEEN " & lcParametro4Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro4Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Mar				BETWEEN " & lcParametro5Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro5Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Cla				BETWEEN " & lcParametro6Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro6Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Tip				BETWEEN " & lcParametro7Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro7Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Pro				BETWEEN " & lcParametro8Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro8Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Uni1				BETWEEN " & lcParametro9Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro9Hasta)
            loComandoSeleccionar.AppendLine("			AND Facturas.Cod_Suc				BETWEEN " & lcParametro10Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro10Hasta)
            loComandoSeleccionar.AppendLine("           AND Articulos.Cod_Ubi				BETWEEN " & lcParametro11Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro11Hasta)
            loComandoSeleccionar.AppendLine("GROUP BY	Renglones_Facturas.Cod_Art, ")
            loComandoSeleccionar.AppendLine("			Articulos.Nom_Art ")

            '-------------------------------------------------------------------------------------------'
            ' Select para ubicar el Stock Inicial a partir de la tabla de Notas de Entregas
            '-------------------------------------------------------------------------------------------'
            loComandoSeleccionar.AppendLine("SELECT		Renglones_Entregas.Cod_Art			AS	Cod_Art, ")
            loComandoSeleccionar.AppendLine("			Articulos.Nom_Art					AS	Nom_Art, ")
            loComandoSeleccionar.AppendLine("			0.00								AS	Can_IniE, ")
            loComandoSeleccionar.AppendLine("			SUM(Renglones_Entregas.Can_Art1)	AS	Can_IniS ")
            loComandoSeleccionar.AppendLine("INTO		#TablaTemporalEntregas ")
            loComandoSeleccionar.AppendLine("FROM		Entregas, ")
            loComandoSeleccionar.AppendLine("			Renglones_Entregas, ")
            loComandoSeleccionar.AppendLine("			Articulos ")
            loComandoSeleccionar.AppendLine("WHERE		Entregas.Documento					=	Renglones_Entregas.Documento ")
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Art				=	Renglones_Entregas.Cod_Art ")
            loComandoSeleccionar.AppendLine("			AND Entregas.Status					IN	('Confirmado', 'Afectado', 'Procesado') ")
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Art				BETWEEN " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("			AND Entregas.Fec_Ini				< " & lcParametro1Desde)
            loComandoSeleccionar.AppendLine("			AND Renglones_Entregas.Cod_Alm		BETWEEN " & lcParametro2Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro2Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Dep				BETWEEN " & lcParametro3Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro3Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Sec				BETWEEN " & lcParametro4Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro4Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Mar				BETWEEN " & lcParametro5Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro5Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Cla				BETWEEN " & lcParametro6Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro6Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Tip				BETWEEN " & lcParametro7Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro7Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Pro				BETWEEN " & lcParametro8Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro8Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Uni1				BETWEEN " & lcParametro9Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro9Hasta)
            loComandoSeleccionar.AppendLine("			AND Entregas.Cod_Suc				BETWEEN " & lcParametro10Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro10Hasta)
            loComandoSeleccionar.AppendLine("           AND Articulos.Cod_Ubi				BETWEEN " & lcParametro11Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro11Hasta)
            loComandoSeleccionar.AppendLine("GROUP BY	Renglones_Entregas.Cod_Art, ")
            loComandoSeleccionar.AppendLine("			Articulos.Nom_Art ")
            
            '-------------------------------------------------------------------------------------------'
            ' Select para ubicar el Stock Inicial a partir de la tabla de Devoluciones de Compra
            '-------------------------------------------------------------------------------------------'
            loComandoSeleccionar.AppendLine(" SELECT	Renglones_DProveedores.Cod_Art				AS	Cod_Art, ")
            loComandoSeleccionar.AppendLine("			Articulos.Nom_Art							AS	Nom_Art, ")
            loComandoSeleccionar.AppendLine("			0.00										AS	Can_IniE, ")
            loComandoSeleccionar.AppendLine("			SUM(Renglones_DProveedores.Can_Art1)		AS	Can_IniS ")
            loComandoSeleccionar.AppendLine(" INTO		#TablaTemporalDevProveedores ")
            loComandoSeleccionar.AppendLine(" FROM		Devoluciones_Proveedores, ")
            loComandoSeleccionar.AppendLine("			Renglones_DProveedores, ")
            loComandoSeleccionar.AppendLine("			Articulos ")
            loComandoSeleccionar.AppendLine(" WHERE		Devoluciones_Proveedores.Documento	=	Renglones_DProveedores.Documento ")
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Art				=	Renglones_DProveedores.Cod_Art ")
            loComandoSeleccionar.AppendLine("			AND Devoluciones_Proveedores.Status	IN	('Confirmado', 'Afectado', 'Procesado') ")
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Art				BETWEEN " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("			AND Devoluciones_Proveedores.Fec_Ini < " & lcParametro1Desde)
            loComandoSeleccionar.AppendLine("			AND Renglones_DProveedores.Cod_Alm	BETWEEN " & lcParametro2Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro2Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Dep				BETWEEN " & lcParametro3Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro3Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Sec				BETWEEN " & lcParametro4Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro4Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Mar				BETWEEN " & lcParametro5Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro5Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Cla				BETWEEN " & lcParametro6Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro6Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Tip				BETWEEN " & lcParametro7Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro7Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Pro				BETWEEN " & lcParametro8Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro8Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Uni1				BETWEEN " & lcParametro9Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro9Hasta)
            loComandoSeleccionar.AppendLine("			AND Devoluciones_Proveedores.Cod_Suc	BETWEEN " & lcParametro10Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro10Hasta)
            loComandoSeleccionar.AppendLine("           AND Articulos.Cod_Ubi				BETWEEN " & lcParametro11Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro11Hasta)
            loComandoSeleccionar.AppendLine(" GROUP BY	Renglones_DProveedores.Cod_Art, ")
            loComandoSeleccionar.AppendLine("			Articulos.Nom_Art")
            
            '-------------------------------------------------------------------------------------------'
            ' Select para ubicar el Stock Inicial a partir de la tabla de Traslados en las Salidas
            '-------------------------------------------------------------------------------------------'
            loComandoSeleccionar.AppendLine(" SELECT	Renglones_Traslados.Cod_Art				AS	Cod_Art, ")
            loComandoSeleccionar.AppendLine("			Articulos.Nom_Art						AS	Nom_Art, ")
            loComandoSeleccionar.AppendLine("			0.00									AS	Can_IniE, ")
            loComandoSeleccionar.AppendLine("			SUM(Renglones_Traslados.Can_Art1)		AS	Can_IniS ")
            loComandoSeleccionar.AppendLine(" INTO		#TablaTemporalTrasladosSalidas ")
            loComandoSeleccionar.AppendLine(" FROM		Traslados, ")
            loComandoSeleccionar.AppendLine("			Renglones_Traslados, ")
            loComandoSeleccionar.AppendLine("			Articulos ")
            loComandoSeleccionar.AppendLine(" WHERE		Traslados.Documento					=	Renglones_Traslados.Documento ")
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Art				=	Renglones_Traslados.Cod_Art ")
            loComandoSeleccionar.AppendLine("			AND Traslados.Status		IN ('Confirmado', 'Procesado') ") 
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Art				BETWEEN " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("			AND Traslados.Fec_Ini		< " & lcParametro1Desde)
            loComandoSeleccionar.AppendLine("			AND Traslados.Alm_Ori		BETWEEN " & lcParametro2Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro2Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Dep				BETWEEN " & lcParametro3Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro3Hasta)
			loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Sec				BETWEEN " & lcParametro4Desde)
			loComandoSeleccionar.AppendLine("				AND " & lcParametro4Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Mar				BETWEEN " & lcParametro5Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro5Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Cla				BETWEEN " & lcParametro6Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro6Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Tip				BETWEEN " & lcParametro7Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro7Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Pro				BETWEEN " & lcParametro8Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro8Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Uni1				BETWEEN " & lcParametro9Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro9Hasta)
            loComandoSeleccionar.AppendLine("			AND Traslados.Cod_Suc				BETWEEN " & lcParametro10Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro10Hasta)
            loComandoSeleccionar.AppendLine("           AND Articulos.Cod_Ubi				BETWEEN " & lcParametro11Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro11Hasta)
            loComandoSeleccionar.AppendLine(" GROUP BY	Renglones_Traslados.Cod_Art, ")
            loComandoSeleccionar.AppendLine("			Articulos.Nom_Art")

			'-------------------------------------------------------------------------------------------'
            ' Union de los diferentes select para obtener el stock inicial
            '-------------------------------------------------------------------------------------------'
            loComandoSeleccionar.AppendLine("SELECT	* ")
            loComandoSeleccionar.AppendLine("INTO		#TablaTemporalCantidades1 ")
            loComandoSeleccionar.AppendLine("FROM		#TablaTemporalAjustes ")
            loComandoSeleccionar.AppendLine("UNION ALL ")
            loComandoSeleccionar.AppendLine("SELECT	* ")
            loComandoSeleccionar.AppendLine("FROM		#TablaTemporalEntregas ")
            loComandoSeleccionar.AppendLine("UNION ALL ")
            loComandoSeleccionar.AppendLine("SELECT	* ")
            loComandoSeleccionar.AppendLine("FROM		#TablaTemporalRecepciones ")
            loComandoSeleccionar.AppendLine("UNION ALL ")
            loComandoSeleccionar.AppendLine("SELECT	* ")
            loComandoSeleccionar.AppendLine("FROM		#TablaTemporalDevClientes ")
            loComandoSeleccionar.AppendLine("UNION ALL ")
            loComandoSeleccionar.AppendLine("SELECT	* ")
            loComandoSeleccionar.AppendLine("FROM		#TablaTemporalTrasladosEntradas ")
            loComandoSeleccionar.AppendLine("UNION ALL ")
            loComandoSeleccionar.AppendLine("SELECT	* ")
            loComandoSeleccionar.AppendLine("FROM		#TablaTemporalFacturas ")
            loComandoSeleccionar.AppendLine("UNION ALL ")
            loComandoSeleccionar.AppendLine("SELECT	* ")
            loComandoSeleccionar.AppendLine("FROM		#TablaTemporalEntregas ")
            loComandoSeleccionar.AppendLine("UNION ALL ")
            loComandoSeleccionar.AppendLine("SELECT	* ")
            loComandoSeleccionar.AppendLine("FROM		#TablaTemporalDevProveedores ")
            loComandoSeleccionar.AppendLine("UNION ALL ")
            loComandoSeleccionar.AppendLine("SELECT	* ")
            loComandoSeleccionar.AppendLine("FROM		#TablaTemporalTrasladosSalidas ")
            
			
            loComandoSeleccionar.AppendLine("SELECT		Cod_Art							AS	Cod_Art, ")
            loComandoSeleccionar.AppendLine("			SUM(Can_IniE)					AS	Can_IniE, ")
            loComandoSeleccionar.AppendLine("			SUM(Can_IniS)					AS	Can_IniS ")
            loComandoSeleccionar.AppendLine("INTO		#TablaTemporalCantidades2 ")
            loComandoSeleccionar.AppendLine("FROM		#TablaTemporalCantidades1 ")
            loComandoSeleccionar.AppendLine("GROUP BY	Cod_Art, Nom_Art ")

            loComandoSeleccionar.AppendLine("SELECT		Cod_Art							AS	Cod_Art, ")
            loComandoSeleccionar.AppendLine("			(Can_IniE - Can_IniS)			AS	Can_Ini	")
            loComandoSeleccionar.AppendLine("INTO		#TablaTemporalCantidadesIniciales ")
            loComandoSeleccionar.AppendLine("FROM		#TablaTemporalCantidades2 ")

            '-------------------------------------------------------------------------------------------'
            ' Movimientos de Entradas de Productos 
            '-------------------------------------------------------------------------------------------'
            ' Select de la tabla de Ajustes (Entradas)
            '-------------------------------------------------------------------------------------------'
            loComandoSeleccionar.AppendLine(" SELECT	Renglones_Ajustes.Cod_Art			AS	Cod_Art, ")
            loComandoSeleccionar.AppendLine("			Articulos.Nom_Art					AS	Nom_Art, ")
            loComandoSeleccionar.AppendLine("			0.00								AS	Can_Com, ")
            loComandoSeleccionar.AppendLine("			Renglones_Ajustes.Can_Art1			AS	Can_Ent, ")
            loComandoSeleccionar.AppendLine("			0.00								AS	Can_Ven, ")
            loComandoSeleccionar.AppendLine("			0.00								AS	Can_Sal ")
            loComandoSeleccionar.AppendLine(" INTO		#TablaTemporalEntradasAjustes1 ")
            loComandoSeleccionar.AppendLine(" FROM		Ajustes, ")
            loComandoSeleccionar.AppendLine("			Renglones_Ajustes, ")
            loComandoSeleccionar.AppendLine("			Articulos ")
            loComandoSeleccionar.AppendLine(" WHERE		Ajustes.Documento					=	Renglones_Ajustes.Documento ")
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Art				=	Renglones_Ajustes.Cod_Art ")
            loComandoSeleccionar.AppendLine("			AND Ajustes.Status					=	'Confirmado' ")
            loComandoSeleccionar.AppendLine("			AND Renglones_Ajustes.Tipo			=	'Entrada' ")
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Art				BETWEEN " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("			AND Ajustes.Fec_Ini					BETWEEN " & lcParametro1Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro1Hasta)
            loComandoSeleccionar.AppendLine("			AND Renglones_Ajustes.Cod_Alm		BETWEEN " & lcParametro2Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro2Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Dep				BETWEEN " & lcParametro3Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro3Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Sec				BETWEEN " & lcParametro4Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro4Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Mar				BETWEEN " & lcParametro5Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro5Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Cla				BETWEEN " & lcParametro6Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro6Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Tip				BETWEEN " & lcParametro7Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro7Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Pro				BETWEEN " & lcParametro8Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro8Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Uni1				BETWEEN " & lcParametro9Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro9Hasta)
            loComandoSeleccionar.AppendLine("			AND Ajustes.Cod_Suc					BETWEEN " & lcParametro10Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro10Hasta)
            loComandoSeleccionar.AppendLine("           AND Articulos.Cod_Ubi    Between " & lcParametro11Desde)
            loComandoSeleccionar.AppendLine("           AND " & lcParametro11Hasta)

            '-------------------------------------------------------------------------------------------'
            ' Select de la tabla de Recepciones (Entradas)
            '-------------------------------------------------------------------------------------------'
            loComandoSeleccionar.AppendLine(" SELECT	Renglones_Recepciones.Cod_Art		AS	Cod_Art, ")
            loComandoSeleccionar.AppendLine("			Articulos.Nom_Art					AS	Nom_Art, ")
            loComandoSeleccionar.AppendLine("			Renglones_Recepciones.Can_Art1		AS	Can_Com, ")
            loComandoSeleccionar.AppendLine("			0.00								AS	Can_Ent, ")
            loComandoSeleccionar.AppendLine("			0.00								AS	Can_Ven, ")
            loComandoSeleccionar.AppendLine("			0.00								AS	Can_Sal ")
            loComandoSeleccionar.AppendLine(" INTO		#TablaTemporalEntradasRecepciones1 ")
            loComandoSeleccionar.AppendLine(" FROM		Recepciones, ")
            loComandoSeleccionar.AppendLine("			Renglones_Recepciones, ")
            loComandoSeleccionar.AppendLine("			Articulos ")
            loComandoSeleccionar.AppendLine(" WHERE		Recepciones.Documento				=	Renglones_Recepciones.Documento ")
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Art				=	Renglones_Recepciones.Cod_Art ")
            loComandoSeleccionar.AppendLine("			And Recepciones.Status				IN	('Confirmado', 'Afectado', 'Procesado') ")
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Art				BETWEEN " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("			And Recepciones.Fec_Ini				BETWEEN " & lcParametro1Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro1Hasta)
            loComandoSeleccionar.AppendLine("			And Renglones_Recepciones.Cod_Alm	BETWEEN " & lcParametro2Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro2Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Dep				BETWEEN " & lcParametro3Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro3Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Sec				BETWEEN " & lcParametro4Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro4Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Mar				BETWEEN " & lcParametro5Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro5Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Cla				BETWEEN " & lcParametro6Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro6Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Tip				BETWEEN " & lcParametro7Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro7Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Pro				BETWEEN " & lcParametro8Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro8Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Uni1				BETWEEN " & lcParametro9Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro9Hasta)
            loComandoSeleccionar.AppendLine("			And Recepciones.Cod_Suc				BETWEEN " & lcParametro10Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro10Hasta)
            loComandoSeleccionar.AppendLine("           And Articulos.Cod_Ubi    Between " & lcParametro11Desde)
            loComandoSeleccionar.AppendLine("           And " & lcParametro11Hasta)

            '-------------------------------------------------------------------------------------------'
            ' Select de la tabla de Facturas de Compras (Entradas)
            '-------------------------------------------------------------------------------------------'
            loComandoSeleccionar.AppendLine(" SELECT	Renglones_Compras.Cod_Art			AS	Cod_Art, ")
            loComandoSeleccionar.AppendLine("			Articulos.Nom_Art					AS	Nom_Art, ")
            loComandoSeleccionar.AppendLine("			Renglones_Compras.Can_Art1			AS	Can_Com, ")
            loComandoSeleccionar.AppendLine("			0.00								AS	Can_Ent, ")
            loComandoSeleccionar.AppendLine("			0.00								AS	Can_Ven, ")
            loComandoSeleccionar.AppendLine("			0.00								AS	Can_Sal ")
            loComandoSeleccionar.AppendLine(" INTO		#TablaTemporalEntradasCompras1 ")
            loComandoSeleccionar.AppendLine(" FROM		Compras, ")
            loComandoSeleccionar.AppendLine("			Renglones_Compras, ")
            loComandoSeleccionar.AppendLine("			Articulos ")
            loComandoSeleccionar.AppendLine(" WHERE		Compras.Documento					=	Renglones_Compras.Documento ")
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Art				=	Renglones_Compras.Cod_Art ")
            loComandoSeleccionar.AppendLine("			And Compras.Status					IN	('Confirmado', 'Afectado', 'Procesado') ")
            loComandoSeleccionar.AppendLine("			And Renglones_Compras.Tip_Ori		<>	'Recepciones' ")
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Art				BETWEEN " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("			And Compras.Fec_Ini					BETWEEN " & lcParametro1Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro1Hasta)
            loComandoSeleccionar.AppendLine("			And Renglones_Compras.Cod_Alm		BETWEEN " & lcParametro2Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro2Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Dep				BETWEEN " & lcParametro3Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro3Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Sec				BETWEEN " & lcParametro4Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro4Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Mar				BETWEEN " & lcParametro5Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro5Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Cla				BETWEEN " & lcParametro6Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro6Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Tip				BETWEEN " & lcParametro7Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro7Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Pro				BETWEEN " & lcParametro8Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro8Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Uni1				BETWEEN " & lcParametro9Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro9Hasta)
            loComandoSeleccionar.AppendLine("			And Compras.Cod_Suc					BETWEEN " & lcParametro10Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro10Hasta)
            loComandoSeleccionar.AppendLine("           And Articulos.Cod_Ubi    Between " & lcParametro11Desde)
            loComandoSeleccionar.AppendLine("           And " & lcParametro11Hasta)
            
            '-------------------------------------------------------------------------------------------'
            ' Select de la tabla de Devoluciones de Clientes (Entradas)
            '-------------------------------------------------------------------------------------------'
            loComandoSeleccionar.AppendLine(" SELECT	Renglones_DClientes.Cod_Art			AS	Cod_Art, ")
            loComandoSeleccionar.AppendLine("			Articulos.Nom_Art					AS	Nom_Art, ")
            loComandoSeleccionar.AppendLine("			0.00								AS	Can_Com, ")
            loComandoSeleccionar.AppendLine("			Renglones_DClientes.Can_Art1		AS	Can_Ent, ")
            loComandoSeleccionar.AppendLine("			0.00								AS	Can_Ven, ")
            loComandoSeleccionar.AppendLine("			0.00								AS	Can_Sal ")
            loComandoSeleccionar.AppendLine(" INTO		#TablaTemporalEntradasDevoluciones1 ")
            loComandoSeleccionar.AppendLine(" FROM		Devoluciones_Clientes, ")
            loComandoSeleccionar.AppendLine("			Renglones_DClientes, ")
            loComandoSeleccionar.AppendLine("			Articulos ")
            loComandoSeleccionar.AppendLine(" WHERE		Devoluciones_Clientes.Documento		=	Renglones_DClientes.Documento ")
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Art				=	Renglones_DClientes.Cod_Art ")
            loComandoSeleccionar.AppendLine("			And Devoluciones_Clientes.Status	IN	('Confirmado', 'Afectado', 'Procesado') ")
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Art				BETWEEN " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("			And Devoluciones_Clientes.Fec_Ini	BETWEEN " & lcParametro1Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro1Hasta)
            loComandoSeleccionar.AppendLine("			And Renglones_DClientes.Cod_Alm		BETWEEN " & lcParametro2Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro2Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Dep				BETWEEN " & lcParametro3Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro3Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Sec				BETWEEN " & lcParametro4Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro4Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Mar				BETWEEN " & lcParametro5Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro5Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Cla				BETWEEN " & lcParametro6Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro6Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Tip				BETWEEN " & lcParametro7Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro7Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Pro				BETWEEN " & lcParametro8Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro8Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Uni1				BETWEEN " & lcParametro9Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro9Hasta)
            loComandoSeleccionar.AppendLine("			And Devoluciones_Clientes.Cod_Suc	BETWEEN " & lcParametro10Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro10Hasta)
            loComandoSeleccionar.AppendLine("           And Articulos.Cod_Ubi    Between " & lcParametro11Desde)
            loComandoSeleccionar.AppendLine("           And " & lcParametro11Hasta)
            
            '-------------------------------------------------------------------------------------------'
            ' Select de la tabla de Traslados (Entradas)
            '-------------------------------------------------------------------------------------------'
            loComandoSeleccionar.AppendLine(" SELECT	Renglones_Traslados.Cod_Art			AS	Cod_Art, ")
            loComandoSeleccionar.AppendLine("			Articulos.Nom_Art					AS	Nom_Art, ")
            loComandoSeleccionar.AppendLine("			0.00								AS	Can_Com, ")
            loComandoSeleccionar.AppendLine("			Renglones_Traslados.Can_Art1		AS	Can_Ent, ")
            loComandoSeleccionar.AppendLine("			0.00								AS	Can_Ven, ")
            loComandoSeleccionar.AppendLine("			0.00								AS	Can_Sal ")
            loComandoSeleccionar.AppendLine(" INTO		#TablaTemporalEntradasTraslados1 ")
            loComandoSeleccionar.AppendLine(" FROM		Traslados, ")
            loComandoSeleccionar.AppendLine("			Renglones_Traslados, ")
            loComandoSeleccionar.AppendLine("			Articulos ")
            loComandoSeleccionar.AppendLine(" WHERE		Traslados.Documento				=	Renglones_Traslados.Documento ")
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Art			=	Renglones_Traslados.Cod_Art ")
            loComandoSeleccionar.AppendLine("			AND Traslados.Status			IN ('Confirmado', 'Procesado') ") 
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Art				BETWEEN " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("			AND Traslados.Fec_Ini BETWEEN " & lcParametro1Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro1Hasta)
            loComandoSeleccionar.AppendLine("			AND (CASE Traslados.Status " )
            loComandoSeleccionar.AppendLine("					WHEN 'Confirmado' THEN " & lcAlmacenTransito)
            loComandoSeleccionar.AppendLine("					ELSE Traslados.Alm_Des ")
            loComandoSeleccionar.AppendLine("				END)	BETWEEN " & lcParametro2Desde)
            loComandoSeleccionar.AppendLine("				AND " & lcParametro2Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Dep				BETWEEN " & lcParametro3Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro3Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Sec				BETWEEN " & lcParametro4Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro4Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Mar				BETWEEN " & lcParametro5Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro5Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Cla				BETWEEN " & lcParametro6Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro6Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Tip				BETWEEN " & lcParametro7Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro7Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Pro				BETWEEN " & lcParametro8Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro8Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Uni1				BETWEEN " & lcParametro9Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro9Hasta)
            loComandoSeleccionar.AppendLine("			AND Traslados.Cod_Suc				BETWEEN " & lcParametro10Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro10Hasta)
            loComandoSeleccionar.AppendLine("           AND Articulos.Cod_Ubi    Between " & lcParametro11Desde)
            loComandoSeleccionar.AppendLine("           AND " & lcParametro11Hasta)

            '-------------------------------------------------------------------------------------------'
            ' Movimientos de Salidas de Productos 
            '-------------------------------------------------------------------------------------------'
            ' Select de la tabla de Ajustes (Salidas)
            '-------------------------------------------------------------------------------------------'
            loComandoSeleccionar.AppendLine(" SELECT	Renglones_Ajustes.Cod_Art			AS	Cod_Art, ")
            loComandoSeleccionar.AppendLine("			Articulos.Nom_Art					AS	Nom_Art, ")
            loComandoSeleccionar.AppendLine("			0.00								AS	Can_Com, ")
            loComandoSeleccionar.AppendLine("			0.00								AS	Can_Ent, ")
            loComandoSeleccionar.AppendLine("			0.00								AS	Can_Ven, ")
            loComandoSeleccionar.AppendLine("			Renglones_Ajustes.Can_Art1			AS	Can_Sal ")
            loComandoSeleccionar.AppendLine(" INTO		#TablaTemporalSalidasAjustes1 ")
            loComandoSeleccionar.AppendLine(" FROM		Ajustes, ")
            loComandoSeleccionar.AppendLine("			Renglones_Ajustes, ")
            loComandoSeleccionar.AppendLine("			Articulos ")
            loComandoSeleccionar.AppendLine(" WHERE		Ajustes.Documento					=	Renglones_Ajustes.Documento ")
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Art				=	Renglones_Ajustes.Cod_Art ")
            loComandoSeleccionar.AppendLine("			And Ajustes.Status					=	'Confirmado' ")
            loComandoSeleccionar.AppendLine("			And Renglones_Ajustes.Tipo			=	'Salida' ")
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Art				BETWEEN " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("			And Ajustes.Fec_Ini					BETWEEN " & lcParametro1Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro1Hasta)
            loComandoSeleccionar.AppendLine("			And Renglones_Ajustes.Cod_Alm		BETWEEN " & lcParametro2Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro2Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Dep				BETWEEN " & lcParametro3Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro3Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Sec				BETWEEN " & lcParametro4Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro4Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Mar				BETWEEN " & lcParametro5Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro5Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Cla				BETWEEN " & lcParametro6Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro6Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Tip				BETWEEN " & lcParametro7Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro7Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Pro				BETWEEN " & lcParametro8Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro8Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Uni1				BETWEEN " & lcParametro9Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro9Hasta)
            loComandoSeleccionar.AppendLine("			And Ajustes.Cod_Suc					BETWEEN " & lcParametro10Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro10Hasta)
            loComandoSeleccionar.AppendLine("           And Articulos.Cod_Ubi				BETWEEN " & lcParametro11Desde)
            loComandoSeleccionar.AppendLine("           And " & lcParametro11Hasta)

            '-------------------------------------------------------------------------------------------'
            ' Select de la tabla de Entregas (Salidas)
            '-------------------------------------------------------------------------------------------'
            loComandoSeleccionar.AppendLine(" SELECT	Renglones_Entregas.Cod_Art			AS	Cod_Art, ")
            loComandoSeleccionar.AppendLine("			Articulos.Nom_Art					AS	Nom_Art, ")
            loComandoSeleccionar.AppendLine("			0.00								AS	Can_Com, ")
            loComandoSeleccionar.AppendLine("			0.00								AS	Can_Ent, ")
            loComandoSeleccionar.AppendLine("			Renglones_Entregas.Can_Art1			AS	Can_Ven, ")
            loComandoSeleccionar.AppendLine("			0.00								AS	Can_Sal ")
            loComandoSeleccionar.AppendLine(" INTO		#TablaTemporalSalidasEntregas1 ")
            loComandoSeleccionar.AppendLine(" FROM		Entregas, ")
            loComandoSeleccionar.AppendLine("			Renglones_Entregas, ")
            loComandoSeleccionar.AppendLine("			Articulos ")
            loComandoSeleccionar.AppendLine(" WHERE		Entregas.Documento					=	Renglones_Entregas.Documento ")
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Art				=	Renglones_Entregas.Cod_Art ")
            loComandoSeleccionar.AppendLine("			AND Entregas.Status					IN	('Confirmado', 'Afectado', 'Procesado') ")
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Art				BETWEEN " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("			AND Entregas.Fec_Ini				BETWEEN " & lcParametro1Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro1Hasta)
            loComandoSeleccionar.AppendLine("			AND Renglones_Entregas.Cod_Alm		BETWEEN " & lcParametro2Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro2Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Dep				BETWEEN " & lcParametro3Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro3Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Sec				BETWEEN " & lcParametro4Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro4Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Mar				BETWEEN " & lcParametro5Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro5Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Cla				BETWEEN " & lcParametro6Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro6Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Tip				BETWEEN " & lcParametro7Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro7Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Pro				BETWEEN " & lcParametro8Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro8Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Uni1				BETWEEN " & lcParametro9Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro9Hasta)
            loComandoSeleccionar.AppendLine("			AND Entregas.Cod_Suc				BETWEEN " & lcParametro10Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro10Hasta)
            loComandoSeleccionar.AppendLine("           AND Articulos.Cod_Ubi				BETWEEN " & lcParametro11Desde)
            loComandoSeleccionar.AppendLine("           AND " & lcParametro11Hasta)

            '-------------------------------------------------------------------------------------------'
            ' Select de la tabla de Facturas de Ventas (Salidas)
            '-------------------------------------------------------------------------------------------'
            loComandoSeleccionar.AppendLine(" SELECT	Renglones_Facturas.Cod_Art			AS	Cod_Art, ")
            loComandoSeleccionar.AppendLine("			Articulos.Nom_Art					AS	Nom_Art, ")
            loComandoSeleccionar.AppendLine("			0.00								AS	Can_Com, ")
            loComandoSeleccionar.AppendLine("			0.00								AS	Can_Ent, ")
            loComandoSeleccionar.AppendLine("			Renglones_Facturas.Can_Art1			AS	Can_Ven, ")
            loComandoSeleccionar.AppendLine("			0.00								AS	Can_Sal ")
            loComandoSeleccionar.AppendLine(" INTO		#TablaTemporalSalidasVentas1 ")
            loComandoSeleccionar.AppendLine(" FROM		Facturas, ")
            loComandoSeleccionar.AppendLine("			Renglones_Facturas, ")
            loComandoSeleccionar.AppendLine("			Articulos ")
            loComandoSeleccionar.AppendLine(" WHERE		Facturas.Documento					=	Renglones_Facturas.Documento ")
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Art				=	Renglones_Facturas.Cod_Art ")
            loComandoSeleccionar.AppendLine("			AND Facturas.Status					IN	('Confirmado', 'Afectado', 'Procesado') ")
            loComandoSeleccionar.AppendLine("			AND Renglones_Facturas.Tip_Ori		<>	'Entregas' ")
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Art				BETWEEN " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("			AND Facturas.Fec_Ini				BETWEEN " & lcParametro1Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro1Hasta)
            loComandoSeleccionar.AppendLine("			AND Renglones_Facturas.Cod_Alm		BETWEEN " & lcParametro2Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro2Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Dep				BETWEEN " & lcParametro3Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro3Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Sec				BETWEEN " & lcParametro4Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro4Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Mar				BETWEEN " & lcParametro5Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro5Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Cla				BETWEEN " & lcParametro6Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro6Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Tip				BETWEEN " & lcParametro7Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro7Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Pro				BETWEEN " & lcParametro8Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro8Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Uni1				BETWEEN " & lcParametro9Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro9Hasta)
            loComandoSeleccionar.AppendLine("			AND Facturas.Cod_Suc				BETWEEN " & lcParametro10Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro10Hasta)
            loComandoSeleccionar.AppendLine("           AND Articulos.Cod_Ubi				BETWEEN " & lcParametro11Desde)
            loComandoSeleccionar.AppendLine("           AND " & lcParametro11Hasta)
            
            
            '-------------------------------------------------------------------------------------------'
            ' Select de la tabla de Devoluciones de Proveedores (Salidas)
            '-------------------------------------------------------------------------------------------'
            loComandoSeleccionar.AppendLine(" SELECT	Renglones_DProveedores.Cod_Art		AS	Cod_Art, ")
            loComandoSeleccionar.AppendLine("			Articulos.Nom_Art					AS	Nom_Art, ")
            loComandoSeleccionar.AppendLine("			0.00								AS	Can_Com, ")
            loComandoSeleccionar.AppendLine("			0.00								AS	Can_Ent, ")
            loComandoSeleccionar.AppendLine("			0.00								AS	Can_Ven, ")
            loComandoSeleccionar.AppendLine("			Renglones_DProveedores.Can_Art1		AS	Can_Sal ")
            loComandoSeleccionar.AppendLine(" INTO		#TablaTemporalSalidasDevoluciones1 ")
            loComandoSeleccionar.AppendLine(" FROM		Devoluciones_Proveedores, ")
            loComandoSeleccionar.AppendLine("			Renglones_DProveedores, ")
            loComandoSeleccionar.AppendLine("			Articulos ")
            loComandoSeleccionar.AppendLine(" WHERE		Devoluciones_Proveedores.Documento	=	Renglones_DProveedores.Documento ")
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Art				=	Renglones_DProveedores.Cod_Art ")
            loComandoSeleccionar.AppendLine("			AND Devoluciones_Proveedores.Status	IN	('Confirmado', 'Afectado', 'Procesado') ")
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Art				BETWEEN " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("			AND Devoluciones_Proveedores.Fec_Ini BETWEEN " & lcParametro1Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro1Hasta)
            loComandoSeleccionar.AppendLine("			AND Renglones_DProveedores.Cod_Alm	BETWEEN " & lcParametro2Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro2Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Dep				BETWEEN " & lcParametro3Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro3Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Sec				BETWEEN " & lcParametro4Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro4Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Mar				BETWEEN " & lcParametro5Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro5Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Cla				BETWEEN " & lcParametro6Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro6Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Tip				BETWEEN " & lcParametro7Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro7Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Pro				BETWEEN " & lcParametro8Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro8Hasta)
            loComandoSeleccionar.AppendLine("			AND Articulos.Cod_Uni1				BETWEEN " & lcParametro9Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro9Hasta)
            loComandoSeleccionar.AppendLine("			AND Devoluciones_Proveedores.Cod_Suc	BETWEEN " & lcParametro10Desde)
            loComandoSeleccionar.AppendLine("			AND " & lcParametro10Hasta)
            loComandoSeleccionar.AppendLine("           AND Articulos.Cod_Ubi    			BETWEEN " & lcParametro11Desde)
            loComandoSeleccionar.AppendLine("           AND " & lcParametro11Hasta)
          
			'-------------------------------------------------------------------------------------------'
            ' Select de la tabla de Traslados (Salidas)
            '-------------------------------------------------------------------------------------------'
            loComandoSeleccionar.AppendLine(" SELECT	Renglones_Traslados.Cod_Art			AS	Cod_Art, ")
            loComandoSeleccionar.AppendLine("			Articulos.Nom_Art					AS	Nom_Art, ")
            loComandoSeleccionar.AppendLine("			0.00								AS	Can_Com, ")
            loComandoSeleccionar.AppendLine("			0.00								AS	Can_Ent, ")
            loComandoSeleccionar.AppendLine("			0.00								AS	Can_Ven, ")
            loComandoSeleccionar.AppendLine("			Renglones_Traslados.Can_Art1		AS	Can_Sal ")
            loComandoSeleccionar.AppendLine(" INTO		#TablaTemporalSalidasTraslados1 ")
            loComandoSeleccionar.AppendLine(" FROM		Traslados, ")
            loComandoSeleccionar.AppendLine("			Renglones_Traslados, ")
            loComandoSeleccionar.AppendLine("			Articulos ")
            loComandoSeleccionar.AppendLine(" WHERE		Traslados.Documento					=	Renglones_Traslados.Documento ")
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Art				=	Renglones_Traslados.Cod_Art ")
            loComandoSeleccionar.AppendLine("			AND Traslados.Status				IN ('Confirmado', 'Procesado') ") 
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Art				BETWEEN " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("			And Traslados.Fec_Ini BETWEEN " & lcParametro1Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro1Hasta)
            loComandoSeleccionar.AppendLine("			And Traslados.Alm_Ori	BETWEEN " & lcParametro2Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro2Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Dep				BETWEEN " & lcParametro3Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro3Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Sec				BETWEEN " & lcParametro4Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro4Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Mar				BETWEEN " & lcParametro5Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro5Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Cla				BETWEEN " & lcParametro6Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro6Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Tip				BETWEEN " & lcParametro7Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro7Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Pro				BETWEEN " & lcParametro8Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro8Hasta)
            loComandoSeleccionar.AppendLine("			And Articulos.Cod_Uni1				BETWEEN " & lcParametro9Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro9Hasta)
            loComandoSeleccionar.AppendLine("			And Traslados.Cod_Suc				BETWEEN " & lcParametro10Desde)
            loComandoSeleccionar.AppendLine("			And " & lcParametro10Hasta)
            loComandoSeleccionar.AppendLine("           And Articulos.Cod_Ubi				BETWEEN " & lcParametro11Desde)
            loComandoSeleccionar.AppendLine("           And " & lcParametro11Hasta)

            '-------------------------------------------------------------------------------------------'
            ' Union de los selects desde las tablas temporales 
            '-------------------------------------------------------------------------------------------'
            loComandoSeleccionar.AppendLine(" SELECT	Cod_Art				AS	Cod_Art, ")
            loComandoSeleccionar.AppendLine("			Nom_Art				AS	Nom_Art, ")
            loComandoSeleccionar.AppendLine("			Can_Com				AS	Can_Com, ")
            loComandoSeleccionar.AppendLine("			Can_Ent				AS	Can_Ent, ")
            loComandoSeleccionar.AppendLine("			Can_Ven				AS	Can_Ven, ")
            loComandoSeleccionar.AppendLine("			Can_Sal				AS	Can_Sal ")
            loComandoSeleccionar.AppendLine(" INTO		#TablaTemporalMovimientos1 ")
            loComandoSeleccionar.AppendLine(" FROM		#TablaTemporalEntradasAjustes1 ")
            loComandoSeleccionar.AppendLine(" UNION ALL ")
            loComandoSeleccionar.AppendLine(" SELECT	Cod_Art				AS	Cod_Art, ")
            loComandoSeleccionar.AppendLine("			Nom_Art				AS	Nom_Art, ")
            loComandoSeleccionar.AppendLine("			Can_Com				AS	Can_Com, ")
            loComandoSeleccionar.AppendLine("			Can_Ent				AS	Can_Ent, ")
            loComandoSeleccionar.AppendLine("			Can_Ven				AS	Can_Ven, ")
            loComandoSeleccionar.AppendLine("			Can_Sal				AS	Can_Sal ")
            loComandoSeleccionar.AppendLine(" FROM		#TablaTemporalEntradasRecepciones1 ")
            loComandoSeleccionar.AppendLine(" UNION ALL ")
            loComandoSeleccionar.AppendLine(" SELECT	Cod_Art				AS	Cod_Art, ")
            loComandoSeleccionar.AppendLine("			Nom_Art				AS	Nom_Art, ")
            loComandoSeleccionar.AppendLine("			Can_Com				AS	Can_Com, ")
            loComandoSeleccionar.AppendLine("			Can_Ent				AS	Can_Ent, ")
            loComandoSeleccionar.AppendLine("			Can_Ven				AS	Can_Ven, ")
            loComandoSeleccionar.AppendLine("			Can_Sal				AS	Can_Sal ")
            loComandoSeleccionar.AppendLine(" FROM		#TablaTemporalEntradasCompras1 ")
            loComandoSeleccionar.AppendLine(" UNION ALL ")
            loComandoSeleccionar.AppendLine(" SELECT	Cod_Art				AS	Cod_Art, ")
            loComandoSeleccionar.AppendLine("			Nom_Art				AS	Nom_Art, ")
            loComandoSeleccionar.AppendLine("			Can_Com				AS	Can_Com, ")
            loComandoSeleccionar.AppendLine("			Can_Ent				AS	Can_Ent, ")
            loComandoSeleccionar.AppendLine("			Can_Ven				AS	Can_Ven, ")
            loComandoSeleccionar.AppendLine("			Can_Sal				AS	Can_Sal ")
            loComandoSeleccionar.AppendLine(" FROM		#TablaTemporalEntradasDevoluciones1 ")
            loComandoSeleccionar.AppendLine(" UNION ALL ")
            loComandoSeleccionar.AppendLine(" SELECT	Cod_Art				AS	Cod_Art, ")
            loComandoSeleccionar.AppendLine("			Nom_Art				AS	Nom_Art, ")
            loComandoSeleccionar.AppendLine("			Can_Com				AS	Can_Com, ")
            loComandoSeleccionar.AppendLine("			Can_Ent				AS	Can_Ent, ")
            loComandoSeleccionar.AppendLine("			Can_Ven				AS	Can_Ven, ")
            loComandoSeleccionar.AppendLine("			Can_Sal				AS	Can_Sal ")
            loComandoSeleccionar.AppendLine(" FROM		#TablaTemporalEntradasTraslados1 ")
            loComandoSeleccionar.AppendLine(" UNION ALL ")
            loComandoSeleccionar.AppendLine(" SELECT	Cod_Art				AS	Cod_Art, ")
            loComandoSeleccionar.AppendLine("			Nom_Art				AS	Nom_Art, ")
            loComandoSeleccionar.AppendLine("			Can_Com				AS	Can_Com, ")
            loComandoSeleccionar.AppendLine("			Can_Ent				AS	Can_Ent, ")
            loComandoSeleccionar.AppendLine("			Can_Ven				AS	Can_Ven, ")
            loComandoSeleccionar.AppendLine("			Can_Sal				AS	Can_Sal ")
            loComandoSeleccionar.AppendLine(" FROM		#TablaTemporalSalidasAjustes1 ")
            loComandoSeleccionar.AppendLine(" UNION ALL ")
            loComandoSeleccionar.AppendLine(" SELECT	Cod_Art				AS	Cod_Art, ")
            loComandoSeleccionar.AppendLine("			Nom_Art				AS	Nom_Art, ")
            loComandoSeleccionar.AppendLine("			Can_Com				AS	Can_Com, ")
            loComandoSeleccionar.AppendLine("			Can_Ent				AS	Can_Ent, ")
            loComandoSeleccionar.AppendLine("			Can_Ven				AS	Can_Ven, ")
            loComandoSeleccionar.AppendLine("			Can_Sal				AS	Can_Sal ")
            loComandoSeleccionar.AppendLine(" FROM		#TablaTemporalSalidasEntregas1 ")
            loComandoSeleccionar.AppendLine(" UNION ALL ")
            loComandoSeleccionar.AppendLine(" SELECT	Cod_Art				AS	Cod_Art, ")
            loComandoSeleccionar.AppendLine("			Nom_Art				AS	Nom_Art, ")
            loComandoSeleccionar.AppendLine("			Can_Com				AS	Can_Com, ")
            loComandoSeleccionar.AppendLine("			Can_Ent				AS	Can_Ent, ")
            loComandoSeleccionar.AppendLine("			Can_Ven				AS	Can_Ven, ")
            loComandoSeleccionar.AppendLine("			Can_Sal				AS	Can_Sal ")
            loComandoSeleccionar.AppendLine(" FROM		#TablaTemporalSalidasVentas1 ")
            loComandoSeleccionar.AppendLine(" UNION ALL ")
            loComandoSeleccionar.AppendLine(" SELECT	Cod_Art				AS	Cod_Art, ")
            loComandoSeleccionar.AppendLine("			Nom_Art				AS	Nom_Art, ")
            loComandoSeleccionar.AppendLine("			Can_Com				AS	Can_Com, ")
            loComandoSeleccionar.AppendLine("			Can_Ent				AS	Can_Ent, ")
            loComandoSeleccionar.AppendLine("			Can_Ven				AS	Can_Ven, ")
            loComandoSeleccionar.AppendLine("			Can_Sal				AS	Can_Sal ")
            loComandoSeleccionar.AppendLine(" FROM		#TablaTemporalSalidasDevoluciones1 ")
            loComandoSeleccionar.AppendLine(" UNION ALL ")
            loComandoSeleccionar.AppendLine(" SELECT	Cod_Art				AS	Cod_Art, ")
            loComandoSeleccionar.AppendLine("			Nom_Art				AS	Nom_Art, ")
            loComandoSeleccionar.AppendLine("			Can_Com				AS	Can_Com, ")
            loComandoSeleccionar.AppendLine("			Can_Ent				AS	Can_Ent, ")
            loComandoSeleccionar.AppendLine("			Can_Ven				AS	Can_Ven, ")
            loComandoSeleccionar.AppendLine("			Can_Sal				AS	Can_Sal ")
            loComandoSeleccionar.AppendLine(" FROM		#TablaTemporalSalidasTraslados1 ")

            '-------------------------------------------------------------------------------------------'
            ' Suma de las cantidades luego de la unificacion de los selects
            '-------------------------------------------------------------------------------------------'
            loComandoSeleccionar.AppendLine(" SELECT	Cod_Art				AS	Cod_Art, ")
            loComandoSeleccionar.AppendLine("			Nom_Art				AS	Nom_Art, ")
            loComandoSeleccionar.AppendLine("			SUM(Can_Com)		AS	Can_Com, ")
            loComandoSeleccionar.AppendLine("			SUM(Can_Ent)		AS	Can_Ent, ")
            loComandoSeleccionar.AppendLine("			SUM(Can_Ven)		AS	Can_Ven, ")
            loComandoSeleccionar.AppendLine("			SUM(Can_Sal)		AS	Can_Sal ")
            loComandoSeleccionar.AppendLine(" INTO		#TablaTemporalMovimientos2 ")
            loComandoSeleccionar.AppendLine(" FROM		#TablaTemporalMovimientos1 ")
            loComandoSeleccionar.AppendLine(" GROUP BY	Cod_Art, ")
            loComandoSeleccionar.AppendLine("			Nom_Art ")

            '-------------------------------------------------------------------------------------------'
            ' Union del select de movimientos stock inicial y movimients actuales
            '-------------------------------------------------------------------------------------------'
            loComandoSeleccionar.AppendLine(" SELECT	#TablaTemporalMovimientos2.Cod_Art					AS	Cod_Art, ")
            loComandoSeleccionar.AppendLine("			#TablaTemporalMovimientos2.Nom_Art					AS	Nom_Art, ")
            loComandoSeleccionar.AppendLine("			#TablaTemporalCantidadesIniciales.Can_Ini			AS	Can_Ini,  ")
            loComandoSeleccionar.AppendLine("			#TablaTemporalMovimientos2.Can_Com					AS	Can_Com, ")
            loComandoSeleccionar.AppendLine("			#TablaTemporalMovimientos2.Can_Ent					AS	Can_Ent, ")
            loComandoSeleccionar.AppendLine("			#TablaTemporalMovimientos2.Can_Ven					AS	Can_Ven, ")
            loComandoSeleccionar.AppendLine("			#TablaTemporalMovimientos2.Can_Sal					AS	Can_Sal ")
            loComandoSeleccionar.AppendLine(" INTO		#TablaTemporalMovimientos3 ")
            loComandoSeleccionar.AppendLine(" FROM		#TablaTemporalMovimientos2 ")
            loComandoSeleccionar.AppendLine("LEFT JOIN #TablaTemporalCantidadesIniciales ON #TablaTemporalCantidadesIniciales.Cod_Art = #TablaTemporalMovimientos2.Cod_Art")

            '-------------------------------------------------------------------------------------------'
            ' Conversion de los valores NULL en valores numericos
            '-------------------------------------------------------------------------------------------'
            loComandoSeleccionar.AppendLine(" SELECT	Cod_Art												AS	Cod_Art, ")
            loComandoSeleccionar.AppendLine(" 			Nom_Art												AS	Nom_Art, ")
            loComandoSeleccionar.AppendLine(" 			(CASE WHEN Can_Ini IS NULL THEN 0 ELSE Can_Ini END)	AS	Can_Ini, ")
            loComandoSeleccionar.AppendLine(" 			(CASE WHEN Can_Com IS NULL THEN 0 ELSE Can_Com END) AS	Can_Com, ")
            loComandoSeleccionar.AppendLine(" 			(CASE WHEN Can_Ent IS NULL THEN 0 ELSE Can_Ent END)	AS	Can_Ent, ")
            loComandoSeleccionar.AppendLine(" 			(CASE WHEN Can_Ven IS NULL THEN 0 ELSE Can_Ven END)	AS	Can_Ven, ")
            loComandoSeleccionar.AppendLine(" 			(CASE WHEN Can_Sal IS NULL THEN 0 ELSE Can_Sal END) AS	Can_Sal ")
            loComandoSeleccionar.AppendLine(" INTO		#TablaTemporalMovimientos4 ")
            loComandoSeleccionar.AppendLine(" FROM		#TablaTemporalMovimientos3 ")

            '-------------------------------------------------------------------------------------------'
            ' Calculo del Stock Final
            '-------------------------------------------------------------------------------------------'
            loComandoSeleccionar.AppendLine(" SELECT	Cod_Art												AS	Cod_Art, ")
            loComandoSeleccionar.AppendLine(" 			Nom_Art								                AS	Nom_Art, ")
            loComandoSeleccionar.AppendLine(" 			Can_Ini												AS	Can_Ini, ")
            loComandoSeleccionar.AppendLine(" 			Can_Com												AS	Can_Com, ")
            loComandoSeleccionar.AppendLine(" 			Can_Ent												AS	Can_Ent, ")
            loComandoSeleccionar.AppendLine(" 			Can_Ven												AS	Can_Ven, ")
            loComandoSeleccionar.AppendLine(" 			Can_Sal												AS	Can_Sal, ")
            loComandoSeleccionar.AppendLine(" 			(Can_Ini + Can_Com + Can_Ent - Can_Ven - Can_Sal)	AS	Can_Fin ")
            loComandoSeleccionar.AppendLine(" INTO		#TablaTemporalMovimientos5 ")
            loComandoSeleccionar.AppendLine(" FROM		#TablaTemporalMovimientos4 ")

            '-------------------------------------------------------------------------------------------'
            ' Calculo del Stock Final
            '-------------------------------------------------------------------------------------------'
            loComandoSeleccionar.AppendLine(" SELECT	#TablaTemporalMovimientos5.Cod_Art					AS	Cod_Art, ")
            loComandoSeleccionar.AppendLine(" 			#TablaTemporalMovimientos5.Nom_Art					AS	Nom_Art, ")
            loComandoSeleccionar.AppendLine(" 			Articulos.Cod_Uni1									AS	Cod_Uni1, ")
            loComandoSeleccionar.AppendLine(" 			#TablaTemporalMovimientos5.Can_Ini					AS	Can_Ini, ")
            loComandoSeleccionar.AppendLine(" 			#TablaTemporalMovimientos5.Can_Com					AS	Can_Com, ")
            loComandoSeleccionar.AppendLine(" 			#TablaTemporalMovimientos5.Can_Ent					AS	Can_Ent, ")
            loComandoSeleccionar.AppendLine(" 			#TablaTemporalMovimientos5.Can_Ven					AS	Can_Ven, ")
            loComandoSeleccionar.AppendLine(" 			#TablaTemporalMovimientos5.Can_Sal					AS	Can_Sal, ")
            loComandoSeleccionar.AppendLine(" 			#TablaTemporalMovimientos5.Can_Fin					AS	Can_Fin ")
            loComandoSeleccionar.AppendLine(" FROM		Articulos, #TablaTemporalMovimientos5 ")
            loComandoSeleccionar.AppendLine(" WHERE		Articulos.Cod_Art	=	#TablaTemporalMovimientos5.Cod_Art ")
            loComandoSeleccionar.AppendLine("ORDER BY      " & lcOrdenamiento)
            
            loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("")
            
            loComandoSeleccionar.AppendLine("DROP TABLE #TablaTemporalAjustes  ")
			loComandoSeleccionar.AppendLine("DROP TABLE #TablaTemporalCompras  ")
			loComandoSeleccionar.AppendLine("DROP TABLE #TablaTemporalRecepciones")
			loComandoSeleccionar.AppendLine("DROP TABLE #TablaTemporalDevClientes")
			loComandoSeleccionar.AppendLine("DROP TABLE #TablaTemporalTrasladosEntradas	")
			loComandoSeleccionar.AppendLine("DROP TABLE #TablaTemporalFacturas	")
			loComandoSeleccionar.AppendLine("DROP TABLE #TablaTemporalEntregas   ")
			loComandoSeleccionar.AppendLine("DROP TABLE #TablaTemporalDevProveedores ")
			loComandoSeleccionar.AppendLine("DROP TABLE #TablaTemporalTrasladosSalidas	")
			loComandoSeleccionar.AppendLine("DROP TABLE #TablaTemporalCantidades1")
			loComandoSeleccionar.AppendLine("DROP TABLE #TablaTemporalCantidades2  ")
			loComandoSeleccionar.AppendLine("DROP TABLE #TablaTemporalCantidadesIniciales  ")
			loComandoSeleccionar.AppendLine("DROP TABLE #TablaTemporalEntradasAjustes1	  ")
			loComandoSeleccionar.AppendLine("DROP TABLE #TablaTemporalEntradasCompras1	   ")
			loComandoSeleccionar.AppendLine("DROP TABLE #TablaTemporalEntradasRecepciones1   ")
			loComandoSeleccionar.AppendLine("DROP TABLE #TablaTemporalEntradasDevoluciones1	")
			loComandoSeleccionar.AppendLine("DROP TABLE #TablaTemporalEntradasTraslados1 ")
			loComandoSeleccionar.AppendLine("DROP TABLE #TablaTemporalSalidasAjustes1  ")
			loComandoSeleccionar.AppendLine("DROP TABLE #TablaTemporalSalidasVentas1 ")
			loComandoSeleccionar.AppendLine("DROP TABLE #TablaTemporalSalidasDevoluciones1   ")
			loComandoSeleccionar.AppendLine("DROP TABLE #TablaTemporalSalidasTraslados1	 ")
			loComandoSeleccionar.AppendLine("DROP TABLE #TablaTemporalSalidasEntregas1   ")
			loComandoSeleccionar.AppendLine("DROP TABLE #TablaTemporalMovimientos1	")
			loComandoSeleccionar.AppendLine("DROP TABLE #TablaTemporalMovimientos2   ")
			loComandoSeleccionar.AppendLine("DROP TABLE #TablaTemporalMovimientos3   ")
			loComandoSeleccionar.AppendLine("DROP TABLE #TablaTemporalMovimientos4	")
			loComandoSeleccionar.AppendLine("DROP TABLE #TablaTemporalMovimientos5  ")   
			

            Dim loServicios As New cusDatos.goDatos

            Dim laDatosReporte As DataSet = loServicios.mObtenerTodosSinEsquema(loComandoSeleccionar.ToString(), "curReportes")

            'Me.mEscribirConsulta(loComandoSeleccionar.ToString())
            '-------------------------------------------------------------------------------------------------------
            ' Verificando si el select (tabla nº0) trae registros
            '-------------------------------------------------------------------------------------------------------

            If (laDatosReporte.Tables(0).Rows.Count <= 0) Then
                Me.WbcAdministradorMensajeModal.mMostrarMensajeModal("Información", _
                                          "No se Encontraron Registros para los Parámetros Especificados. ", _
                                           vis3Controles.wbcAdministradorMensajeModal.enumTipoMensaje.KN_Informacion, _
                                           "350px", _
                                           "200px")
            End If

            loObjetoReporte = cusAplicacion.goReportes.mCargarReporte("rRInventarios_Articulos", laDatosReporte)

            Me.mTraducirReporte(loObjetoReporte)

            Me.mFormatearCamposReporte(loObjetoReporte)

            Me.crvrRInventarios_Articulos.ReportSource = loObjetoReporte

        Catch loExcepcion As Exception

            Me.WbcAdministradorMensajeModal.mMostrarMensajeModal("Error", _
                          "No se pudo Completar el Proceso: " & loExcepcion.Message, _
                           vis3Controles.wbcAdministradorMensajeModal.enumTipoMensaje.KN_Error, _
                           "auto", _
                           "auto")

        End Try

    End Sub

    Protected Sub Page_Unload(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Unload

        Try

            loObjetoReporte.Close()

        Catch loExcepcion As Exception

        End Try

    End Sub

End Class
'-------------------------------------------------------------------------------------------'
' Fin del codigo
'-------------------------------------------------------------------------------------------'
' JJD: 13/10/08: Codigo inicial
'-------------------------------------------------------------------------------------------'
' JJD: 14/10/08: Continuacion de la programacion
'-------------------------------------------------------------------------------------------'
' CMS:  12/05/09: Ordenamiento 
'-------------------------------------------------------------------------------------------'
' AAP:  29/06/09: Filtro "Sucursal"
'-------------------------------------------------------------------------------------------
' CMS:  11/08/09: Verificacion de registros y se agregaro el filtro_ Ubicación
'-------------------------------------------------------------------------------------------'
' RJG: 08/12/10: Ajustado Estatus de Facturas de Venta: Ahora omite las facturas de venta	'
'				 pendientes e incluye las confirmadas.										'
'-------------------------------------------------------------------------------------------'
' MAT: 21/07/11: Adición de nueva columna diferencia. Ajuste de la vista de diseño			'
'-------------------------------------------------------------------------------------------'
' MAT: 26/07/11: Ajuste del Select															'
'-------------------------------------------------------------------------------------------'
' MAT: 15/08/11: Ajuste del Select(Adicion de las tablas Traslados y devoluciones de compra)															'
'-------------------------------------------------------------------------------------------'
' MAT: 29/09/11: Ajuste del Select(Eliminación del filtro Status, no aplica)				'
'-------------------------------------------------------------------------------------------'
' RJG: 15/05/12: Se ajutaron los filtros de sucursal y de almacén.							'
'-------------------------------------------------------------------------------------------'
