'-------------------------------------------------------------------------------------------'
' Inicio del codigo
'-------------------------------------------------------------------------------------------'
' Importando librerias 
'-------------------------------------------------------------------------------------------'
Imports System.Data

'-------------------------------------------------------------------------------------------'
' Inicio de clase "rRVentas_CBancarias"
'-------------------------------------------------------------------------------------------'
Partial Class rRVentas_CBancarias
    Inherits vis2Formularios.frmReporte

    Dim loObjetoReporte As CrystalDecisions.CrystalReports.Engine.ReportDocument

	Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
		
		Dim lcParametro0Desde	As  String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(0),goServicios.enuOpcionesRedondeo.KN_FechaInicioDelDia)
		Dim lcParametro0Hasta	As  String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(0),goServicios.enuOpcionesRedondeo.KN_FechaFinDelDia)

        Dim lcOrdenamiento As String = cusAplicacion.goReportes.pcOrden

	Try
	
		Dim loComandoSeleccionar As New StringBuilder()

            '-------------------------------------------------------------------------------------------'
            ' 1 - Select de Cobros
            '-------------------------------------------------------------------------------------------'
            loComandoSeleccionar.AppendLine(" SELECT	CONVERT(NCHAR(10), Cobros.Fec_Ini, 103)					AS	Fec_Ini, ")
            loComandoSeleccionar.AppendLine("			CONVERT(NCHAR(10), Cobros.Fec_Ini, 112)					AS	Fecha2,	")
            loComandoSeleccionar.AppendLine(" 			Detalles_Cobros.Tip_Ope									AS	Tip_Ope, ")
            loComandoSeleccionar.AppendLine(" 			Detalles_Cobros.Num_Doc									AS	Num_Doc, ")
            loComandoSeleccionar.AppendLine(" 			Detalles_Cobros.Mon_Net									AS	Mon_Net, ")
            loComandoSeleccionar.AppendLine(" 			0.00													AS	CMon_Com, ")
            loComandoSeleccionar.AppendLine(" 			0.00													AS	CMon_Ret ")
            loComandoSeleccionar.AppendLine(" INTO		#TablaTemporalCobrosNoTarjetas1 ")
            loComandoSeleccionar.AppendLine(" FROM		Cobros, Detalles_Cobros ") 
            loComandoSeleccionar.AppendLine(" WHERE		Cobros.Documento				=	Detalles_Cobros.Documento ")
            loComandoSeleccionar.AppendLine("           AND	Detalles_Cobros.Tip_Ope		<>	'Tarjeta' ")
            loComandoSeleccionar.AppendLine("           AND Cobros.Fec_Ini              BETWEEN " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("           AND " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("           AND Cobros.Status <> 'Anulado'")

            loComandoSeleccionar.AppendLine(" SELECT	CONVERT(NCHAR(10), Cobros.Fec_Ini, 103)					AS	Fec_Ini, ")
            loComandoSeleccionar.AppendLine("			CONVERT(NCHAR(10), Cobros.Fec_Ini, 112)					AS	Fecha2, ")
            loComandoSeleccionar.AppendLine(" 			Detalles_Cobros.Tip_Ope									AS	Tip_Ope, ")
            loComandoSeleccionar.AppendLine(" 			Detalles_Cobros.Num_Doc									AS	Num_Doc, ")
            loComandoSeleccionar.AppendLine(" 			Detalles_Cobros.Mon_Net									AS	Mon_Net, ")
            loComandoSeleccionar.AppendLine("			((Detalles_Cobros.Mon_Net * Tarjetas.Por_Com) / 100)	AS	CMon_Com, ")
            loComandoSeleccionar.AppendLine("			((Detalles_Cobros.Mon_Net * Tarjetas.Por_Ret) / 100)	AS	CMon_Ret ")
            loComandoSeleccionar.AppendLine(" INTO		#TablaTemporalCobrosTarjetas1 ")
            loComandoSeleccionar.AppendLine(" FROM		Cobros, Detalles_Cobros, Tarjetas ") 
            loComandoSeleccionar.AppendLine(" WHERE		Cobros.Documento				=	Detalles_Cobros.Documento ")
            loComandoSeleccionar.AppendLine("           AND	Tarjetas.Cod_Tar			=	Detalles_Cobros.Cod_Tar ")
            loComandoSeleccionar.AppendLine("           AND	Detalles_Cobros.Tip_Ope		=	'Tarjeta' ")
            loComandoSeleccionar.AppendLine("           AND Cobros.Fec_Ini              BETWEEN " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("           AND " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("           AND Cobros.Status <> 'Anulado'")

            loComandoSeleccionar.AppendLine(" SELECT	Fec_Ini										AS	Fec_Ini, ")
            loComandoSeleccionar.AppendLine("			Fecha2										AS	Fecha2, ")
            loComandoSeleccionar.AppendLine(" 			Tip_Ope										AS	Tip_Ope, ")
            loComandoSeleccionar.AppendLine(" 			COUNT(Mon_Net)								AS	Cuantas, ")
            loComandoSeleccionar.AppendLine(" 			SUM(Mon_Net)								AS	Monto, ")
            loComandoSeleccionar.AppendLine("			SUM(CMon_Com)								AS	CMon_Com, ")
            loComandoSeleccionar.AppendLine("			SUM(CMon_Ret)								AS	CMon_Ret ")
            loComandoSeleccionar.AppendLine(" INTO		#TablaTemporalCobros1 ")
            loComandoSeleccionar.AppendLine(" FROM		#TablaTemporalCobrosNoTarjetas1 ")
			loComandoSeleccionar.AppendLine(" GROUP BY	Fecha2, Fec_Ini, Tip_Ope ")
			loComandoSeleccionar.AppendLine(" UNION ALL ")
            loComandoSeleccionar.AppendLine(" SELECT	Fec_Ini										AS	Fec_Ini, ")
            loComandoSeleccionar.AppendLine("			Fecha2										AS	Fecha2, ")
            loComandoSeleccionar.AppendLine(" 			Tip_Ope										AS	Tip_Ope, ")
            loComandoSeleccionar.AppendLine(" 			COUNT(Mon_Net)								AS	Cuantas, ")
            loComandoSeleccionar.AppendLine(" 			SUM(Mon_Net)								AS	Monto, ")
            loComandoSeleccionar.AppendLine("			SUM(CMon_Com)								AS	CMon_Com, ")
            loComandoSeleccionar.AppendLine("			SUM(CMon_Ret)								AS	CMon_Ret ")
            loComandoSeleccionar.AppendLine(" FROM		#TablaTemporalCobrosTarjetas1 ")
			loComandoSeleccionar.AppendLine(" GROUP BY	Fecha2, Fec_Ini, Tip_Ope ")
			loComandoSeleccionar.AppendLine(" ORDER BY	1, 2, 5 ")
			
            '-------------------------------------------------------------------------------------------'
            ' 2 - Select de las Ventas
            '-------------------------------------------------------------------------------------------'
            loComandoSeleccionar.AppendLine(" SELECT	Tip_Doc																			AS	Tip_Doc, ")
            loComandoSeleccionar.AppendLine("			Cod_Tip																			AS	Cod_Tip, ") 
            loComandoSeleccionar.AppendLine("			CONVERT(NCHAR(10), Cuentas_Cobrar.Fec_Ini, 103)									AS	Fecha1,	")
            loComandoSeleccionar.AppendLine("			CONVERT(NCHAR(10), Cuentas_Cobrar.Fec_Ini, 112)									AS	Fecha2,	")
            loComandoSeleccionar.AppendLine("			(CASE WHEN Cod_Tip = 'FACT' THEN Cuentas_Cobrar.Documento ELSE SPACE(10) END)	AS	Documento, ")
            loComandoSeleccionar.AppendLine("			Cuentas_Cobrar.Status															AS	Status,	")
            loComandoSeleccionar.AppendLine("			Cuentas_Cobrar.Mon_Bru															AS	Mon_Bru, ")
            loComandoSeleccionar.AppendLine("			(Cuentas_Cobrar.Mon_Imp1 + Cuentas_Cobrar.Mon_Imp2 + Cuentas_Cobrar.Mon_Imp3)	AS	Mon_Imp, ")
            loComandoSeleccionar.AppendLine("			Cuentas_Cobrar.Mon_Net															AS	Mon_Net	")
            loComandoSeleccionar.AppendLine(" INTO		#TablaTemporalDocumentos1 ")
            loComandoSeleccionar.AppendLine(" FROM		Cuentas_Cobrar ")
            loComandoSeleccionar.AppendLine(" WHERE		(Cuentas_Cobrar.Cod_Tip			=	'FACT' ")
            loComandoSeleccionar.AppendLine("			OR	Cuentas_Cobrar.Cod_Tip		=	'N/CR') ")
            loComandoSeleccionar.AppendLine("			AND Cuentas_Cobrar.Status		<>	'Anulado' ")
            loComandoSeleccionar.AppendLine("           AND Cuentas_Cobrar.Fec_Ini		BETWEEN " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("           AND " & lcParametro0Hasta)

            loComandoSeleccionar.AppendLine(" SELECT	Fecha1																AS	Fecha1, ")
            loComandoSeleccionar.AppendLine("			Fecha2																AS	Fecha2, ")
            loComandoSeleccionar.AppendLine("			SUM(CASE WHEN Tip_Doc	=	'Debito' THEN 1 ELSE 0	END)			AS	Can_Fac, ")
            loComandoSeleccionar.AppendLine("			SUM(CASE WHEN Tip_Doc	<>	'Debito' THEN 0	ELSE 1	END)			AS	Can_NCR, ")
            loComandoSeleccionar.AppendLine("			SUM(CASE WHEN Cod_Tip	=	'FACT' THEN Mon_Bru	ELSE 0.00 END)		AS	Mon_BruF, ")
            loComandoSeleccionar.AppendLine("			SUM(CASE WHEN Cod_Tip	<>	'FACT' THEN Mon_Bru	ELSE 0.00 END)		AS	Mon_BruNC, ")
            loComandoSeleccionar.AppendLine("			SUM(CASE WHEN Cod_Tip	=	'FACT' THEN Mon_Imp	ELSE 0.00 END)		AS	Mon_ImpF, ")
            loComandoSeleccionar.AppendLine("			SUM(CASE WHEN Cod_Tip	<>	'FACT' THEN Mon_Imp	ELSE 0.00 END)		AS	Mon_ImpNC, ")
            loComandoSeleccionar.AppendLine("			SUM(CASE WHEN Cod_Tip	=	'FACT' THEN Mon_Net	ELSE 0.00 END)		AS	Mon_NetF, ")
            loComandoSeleccionar.AppendLine("			SUM(CASE WHEN Cod_Tip	<>	'FACT' THEN Mon_Net	ELSE 0.00 END)		AS	Mon_NetNC, ")
            loComandoSeleccionar.AppendLine("			MIN((CASE WHEN Cod_Tip	=	'FACT' THEN Documento  END))			AS	Doc_Ini, ")
            loComandoSeleccionar.AppendLine("			MAX(Documento)														AS	Doc_Fin ")
            loComandoSeleccionar.AppendLine(" INTO		#TablaTemporalFacturas1 ")
            loComandoSeleccionar.AppendLine(" FROM		#TablaTemporalDocumentos1 ")
            loComandoSeleccionar.AppendLine(" GROUP BY	Fecha2, Fecha1 ")

            loComandoSeleccionar.AppendLine(" SELECT	Fecha1																AS	VenFecha1, ")
            loComandoSeleccionar.AppendLine("			Fecha2																AS	VenFecha2, ")
            loComandoSeleccionar.AppendLine("			Can_Fac																AS	VenCan_Doc, ")
            loComandoSeleccionar.AppendLine("			Mon_BruF															AS	VenMon_BruF, ")
            loComandoSeleccionar.AppendLine("			0.00																AS	VenMon_BruNC, ")
            loComandoSeleccionar.AppendLine("			Mon_ImpF															AS	VenMon_ImpF, ")
            loComandoSeleccionar.AppendLine("			0.00																AS	VenMon_ImpNC, ")
            loComandoSeleccionar.AppendLine("			Mon_NetF															AS	VenMon_NetF, ")
            loComandoSeleccionar.AppendLine("			0.00																AS	VenMon_NetNC, ")
            loComandoSeleccionar.AppendLine("			(Mon_BruF - Mon_BruNC)												AS	VenMon_Bru, ")
            loComandoSeleccionar.AppendLine("			(Mon_ImpF - Mon_ImpNC)												AS	VenMon_Imp, ")
            loComandoSeleccionar.AppendLine("			(Mon_NetF - Mon_NetNC)												AS	VenMon_Net, ")
            loComandoSeleccionar.AppendLine("			Doc_Ini																AS	VenDoc_Ini, ")
            loComandoSeleccionar.AppendLine("			Doc_Fin																AS	VenDoc_Fin ")
            loComandoSeleccionar.AppendLine(" INTO		#TablaTemporalFacturas2 ")
            loComandoSeleccionar.AppendLine(" FROM		#TablaTemporalFacturas1 ")

            loComandoSeleccionar.AppendLine(" SELECT	Fecha1																AS	VenFecha1, ")
            loComandoSeleccionar.AppendLine("			Fecha2																AS	VenFecha2, ")
            loComandoSeleccionar.AppendLine("			SUM(CASE WHEN Tip_Doc	<>	'Debito' THEN 1 ELSE 0	END)			AS	VenCan_Doc, ")
            loComandoSeleccionar.AppendLine("			0.00																AS	VenMon_BruF, ")
            loComandoSeleccionar.AppendLine("			SUM(CASE WHEN Tip_Doc	<>	'Debito' THEN Mon_Bru	ELSE 0.00 END)	AS	VenMon_BruNC, ")
            loComandoSeleccionar.AppendLine("			0.00																AS	VenMon_ImpF, ")
            loComandoSeleccionar.AppendLine("			SUM(CASE WHEN Tip_Doc	<>	'Debito' THEN Mon_Imp	ELSE 0.00 END)	AS	VenMon_ImpNC, ")
            loComandoSeleccionar.AppendLine("			0.00																AS	VenMon_NetF, ")
            loComandoSeleccionar.AppendLine("			SUM(CASE WHEN Tip_Doc	<>	'Debito' THEN Mon_Net	ELSE 0.00 END)	AS	VenMon_NetNC, ")
            loComandoSeleccionar.AppendLine("			0.00																AS	VenMon_Bru, ")
            loComandoSeleccionar.AppendLine("			0.00																AS	VenMon_Imp, ")
            loComandoSeleccionar.AppendLine("			0.00																AS	VenMon_Net, ")
            loComandoSeleccionar.AppendLine("			SPACE(10)															AS	VenDoc_Ini, ")
            loComandoSeleccionar.AppendLine("			SPACE(10)															AS	VenDoc_Fin ")
            loComandoSeleccionar.AppendLine(" INTO		#TablaTemporalNotasCredito1 ")
            loComandoSeleccionar.AppendLine(" FROM		#TablaTemporalDocumentos1 ")
            loComandoSeleccionar.AppendLine(" GROUP BY	Fecha2, Fecha1 ")

            loComandoSeleccionar.AppendLine(" SELECT	'Facturas'															AS	VenTip_Doc, ")
            loComandoSeleccionar.AppendLine(" 			#TablaTemporalFacturas2.*  ")
            loComandoSeleccionar.AppendLine(" INTO		#TablaTemporalVentas1 ")
            loComandoSeleccionar.AppendLine(" FROM		#TablaTemporalFacturas2 ")
            loComandoSeleccionar.AppendLine(" UNION ALL ")
            loComandoSeleccionar.AppendLine(" SELECT	'NCredito'															AS	VenTip_Doc, ")
			loComandoSeleccionar.AppendLine("			#TablaTemporalNotasCredito1.* ")
            loComandoSeleccionar.AppendLine(" FROM		#TablaTemporalNotasCredito1 ")

            '-------------------------------------------------------------------------------------------'
            ' 3 - Select de las Relaciones de Descuentos por Facturas
            '-------------------------------------------------------------------------------------------'
			loComandoSeleccionar.AppendLine(" SELECT	CONVERT(NCHAR(10), Cuentas_Cobrar.Fec_Ini, 103)		AS	DscFec_Ini, ")
			loComandoSeleccionar.AppendLine("			CONVERT(NCHAR(10), Cuentas_Cobrar.Fec_Ini, 112)		AS	DscFecha2, ")
			loComandoSeleccionar.AppendLine(" 			Cuentas_Cobrar.Documento							AS	DscDocumento, ")
			loComandoSeleccionar.AppendLine(" 			Cuentas_Cobrar.Por_Des								AS	DscPor_Des, ")
			loComandoSeleccionar.AppendLine(" 			Cuentas_Cobrar.Mon_Des								AS	DscMon_Des, ")
			loComandoSeleccionar.AppendLine(" 			Cuentas_Cobrar.Mon_Bru								AS	DscMon_Bru, ")
			loComandoSeleccionar.AppendLine(" 			Cuentas_Cobrar.Mon_Net								AS	DscMon_Net ")
			loComandoSeleccionar.AppendLine(" INTO		#TablaTemporalDescuentos1 ")
			loComandoSeleccionar.AppendLine(" FROM		Cuentas_Cobrar ")
			loComandoSeleccionar.AppendLine(" WHERE		Cuentas_Cobrar.Cod_Tip			=	'FACT' ")
            loComandoSeleccionar.AppendLine("			AND	Cuentas_Cobrar.Por_Des		>	0.00 ")
            loComandoSeleccionar.AppendLine("           AND Cuentas_Cobrar.Status		<>	'Anulado' ")
            loComandoSeleccionar.AppendLine("           AND Cuentas_Cobrar.Fec_Ini		Between " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("           AND " & lcParametro0Hasta)
			loComandoSeleccionar.AppendLine(" ORDER BY	Cuentas_Cobrar.Fec_Ini ")

            '-------------------------------------------------------------------------------------------'
            ' 4 - Select de las Relaciones de Cheques
            '-------------------------------------------------------------------------------------------'
			loComandoSeleccionar.AppendLine(" SELECT	CONVERT(NCHAR(10), Cobros.Fec_Ini, 103)	AS	ChFec_Ini, ")
			loComandoSeleccionar.AppendLine("			CONVERT(NCHAR(10), Cobros.Fec_Ini, 112)	AS	ChFecha2, ")
			loComandoSeleccionar.AppendLine(" 			Detalles_Cobros.Documento				AS	ChDocumento, ")
			loComandoSeleccionar.AppendLine(" 			Detalles_Cobros.Num_Doc					AS	ChNum_Doc, ")
			loComandoSeleccionar.AppendLine(" 			Detalles_Cobros.Mon_Net					AS	ChMon_Net, ")
			loComandoSeleccionar.AppendLine(" 			Bancos.Nom_Ban							AS	ChNom_Ban	")
			loComandoSeleccionar.AppendLine(" INTO		#TablaTemporalCheques1 ")
			loComandoSeleccionar.AppendLine(" FROM		Cobros INNER JOIN Detalles_Cobros ")
			loComandoSeleccionar.AppendLine(" 			ON Cobros.Documento				=	Detalles_Cobros.Documento, ")
			loComandoSeleccionar.AppendLine(" 			Bancos ")
			loComandoSeleccionar.AppendLine(" WHERE		Detalles_Cobros.Cod_Ban			=	Bancos.Cod_Ban ")
			loComandoSeleccionar.AppendLine("           AND Detalles_Cobros.Tip_Ope 	=	'Cheque' ")
            loComandoSeleccionar.AppendLine("           AND Cobros.Fec_Ini		Between " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("           AND " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("           AND Cobros.status <> 'Anulado'")
			loComandoSeleccionar.AppendLine(" ORDER BY	Cobros.Fec_Ini ")

            '-------------------------------------------------------------------------------------------'
            ' 5 - Select de las Tarjetas
            '-------------------------------------------------------------------------------------------'
            loComandoSeleccionar.AppendLine(" SELECT	Cobros.Documento										AS	TDocumento, ")
            loComandoSeleccionar.AppendLine(" 			CONVERT(NCHAR(10), Cobros.Fec_Ini, 103)					AS	TFec_Ini, ")
            loComandoSeleccionar.AppendLine(" 			CONVERT(NCHAR(10), Cobros.Fec_Ini, 112)					AS	TFecha2, ")
            loComandoSeleccionar.AppendLine(" 			Cobros.Cod_Ven											AS	TCod_Ven, ")
            loComandoSeleccionar.AppendLine(" 			Detalles_Cobros.Cod_Tar									AS	TCod_Tar, ")
            loComandoSeleccionar.AppendLine(" 			Detalles_Cobros.Num_Doc									AS	TNum_Doc, ")
            loComandoSeleccionar.AppendLine(" 			Detalles_Cobros.Mon_Net									AS	TMon_Net, ")
            loComandoSeleccionar.AppendLine(" 			Tarjetas.Por_Com										AS	TPor_Com, ")
            loComandoSeleccionar.AppendLine(" 			(Detalles_Cobros.Mon_Net * (Tarjetas.Por_Com / 100))	AS  TMon_Com, ")
            loComandoSeleccionar.AppendLine(" 			Tarjetas.Por_Ret										AS	TPor_Ret, ")
            loComandoSeleccionar.AppendLine(" 			(Detalles_Cobros.Mon_Net * (Tarjetas.Por_Ret / 100))	AS  TMon_Ret, ")
            loComandoSeleccionar.AppendLine(" 			Tarjetas.Cod_Tip										AS	TCod_Tip ")
            loComandoSeleccionar.AppendLine(" INTO		#TablaTemporalTarjetas1 ")
            loComandoSeleccionar.AppendLine(" FROM		Cobros INNER JOIN Detalles_Cobros ")
            loComandoSeleccionar.AppendLine(" 			ON Cobros.Documento				=	Detalles_Cobros.Documento, ")
            loComandoSeleccionar.AppendLine(" 			Tarjetas ")
            loComandoSeleccionar.AppendLine(" WHERE		Tarjetas.Cod_Tar				=	Detalles_Cobros.Cod_Tar ")
            loComandoSeleccionar.AppendLine("           AND Cobros.Fec_Ini				Between " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("           AND " & lcParametro0Hasta)
            loComandoSeleccionar.AppendLine("           AND Cobros.status <> 'Anulado'")
            loComandoSeleccionar.AppendLine(" ORDER BY	Cobros.Fec_Ini ")

            '-------------------------------------------------------------------------------------------'
            ' 6 - Select de Comisiones
            '-------------------------------------------------------------------------------------------'
            loComandoSeleccionar.AppendLine(" SELECT	CONVERT(NCHAR(10), Facturas.Fec_Ini, 103)	                AS	Fec_Ini, ")
            loComandoSeleccionar.AppendLine("			CONVERT(NCHAR(10), Facturas.Fec_Ini, 112)	                AS	Fecha2, ")
            loComandoSeleccionar.AppendLine("           Facturas.Cod_Ven							                AS	Cod_Ven, ")
            loComandoSeleccionar.AppendLine("           Vendedores.Nom_Ven							                AS	Nom_Ven, ")
            loComandoSeleccionar.AppendLine("           Vendedores.Por_Ven							                AS	Por_Ven, ")
            loComandoSeleccionar.AppendLine("           (Renglones_Facturas.Mon_Bru)				                AS  Mon_Bru, ")
            loComandoSeleccionar.AppendLine("           (Renglones_Facturas.Mon_Net + Renglones_Facturas.Mon_Imp1)  AS  Mon_Net, ")
            loComandoSeleccionar.AppendLine("           (Renglones_Facturas.Can_Art1)				                AS  Pares ")
            loComandoSeleccionar.AppendLine(" INTO		#TablaTemporalComisiones1 ")
            loComandoSeleccionar.AppendLine(" FROM		Facturas, ")
            loComandoSeleccionar.AppendLine("           Renglones_Facturas, ")
            loComandoSeleccionar.AppendLine("           Vendedores ")
            loComandoSeleccionar.AppendLine(" WHERE		Facturas.Documento				=   Renglones_Facturas.Documento ") 
            loComandoSeleccionar.AppendLine("           AND Facturas.Status				<>	'Anulado' ")
            loComandoSeleccionar.AppendLine("           AND Facturas.Cod_Ven			=   Vendedores.Cod_Ven ")
            loComandoSeleccionar.AppendLine("           AND Facturas.Fec_Ini			Between " & lcParametro0Desde)
            loComandoSeleccionar.AppendLine("           AND " & lcParametro0Hasta)

            loComandoSeleccionar.AppendLine(" SELECT	Fec_Ini						                AS	Fec_Ini, ")
            loComandoSeleccionar.AppendLine("			Fecha2						                AS	Fecha2, ")
            loComandoSeleccionar.AppendLine(" 			Cod_Ven										AS	Cod_Ven, ")
            loComandoSeleccionar.AppendLine(" 			Nom_Ven										AS	Nom_Ven, ")
            loComandoSeleccionar.AppendLine(" 			Por_Ven										AS	Por_Ven, ")
            loComandoSeleccionar.AppendLine(" 			COUNT(*)									AS  Cuantos, ")
            loComandoSeleccionar.AppendLine(" 			SUM(Mon_Bru)								AS  Mon_Bru, ")
            loComandoSeleccionar.AppendLine(" 			SUM(Mon_Net)								AS  Mon_Net, ")
            loComandoSeleccionar.AppendLine(" 			SUM(Mon_Bru * (Por_Ven / 100))				AS  Mon_Com, ")
            loComandoSeleccionar.AppendLine(" 			SUM(Pares)									AS  Pares ")
            loComandoSeleccionar.AppendLine(" INTO		#TablaTemporalComisiones2 ")
            loComandoSeleccionar.AppendLine(" FROM		#TablaTemporalComisiones1 ")
            loComandoSeleccionar.AppendLine(" GROUP BY	Fecha2, Fec_Ini, Cod_Ven, Nom_Ven, Por_Ven ")
            loComandoSeleccionar.AppendLine(" ORDER BY	Fecha2, Cod_Ven, Nom_Ven, Por_Ven; ")

            '-------------------------------------------------------------------------------------------'
            ' Union de las tablas involucradas
            '-------------------------------------------------------------------------------------------'
            loComandoSeleccionar.AppendLine(" WITH curTemporal AS ( ")

            loComandoSeleccionar.AppendLine(" SELECT	1											AS	Orden, ")
            loComandoSeleccionar.AppendLine(" 			'RelCob'									AS	Tipo, ")
            loComandoSeleccionar.AppendLine(" 			Fec_Ini										AS	Fec_Ini,") 
            loComandoSeleccionar.AppendLine(" 			Fecha2										AS	Fecha2,") 
            loComandoSeleccionar.AppendLine(" 			Tip_Ope										AS	Tip_Ope, ")
            loComandoSeleccionar.AppendLine(" 			Cuantas										AS	Cuantas, ")
            loComandoSeleccionar.AppendLine(" 			Monto										AS	Monto, ")
            loComandoSeleccionar.AppendLine(" 			CMon_Com									AS	CMon_Com, ")
            loComandoSeleccionar.AppendLine(" 			CMon_Ret									AS	CMon_Ret, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(30)									AS  Cod_Ven, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(30)									AS  Nom_Ven, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS  Por_Ven, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS  Cuantos, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS  Mon_Bru, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS  Mon_Net, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS  Mon_Com, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	Pares, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	TDocumento, ")
            loComandoSeleccionar.AppendLine(" 			Fec_Ini										AS	TFec_Ini, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(30)									AS	TCod_Ven, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(30)									AS	TCod_Tar, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(30)									AS	TNum_Doc, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	TMon_Net, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	TPor_Com, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	TMon_Com, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	TPor_Ret, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	TMon_Ret, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	TCod_Tip, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	Doc_Ini, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	Doc_Fin, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	ChMon_Net, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	ChDocumento, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(20)									AS	ChNum_Doc, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(30)									AS	ChNom_Ban, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	DscDocumento, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	DscPor_Des, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	DscMon_Des, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	DscMon_Bru, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	DscMon_Net, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	VenCan_Doc, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	VenTip_Doc, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	VenMon_Bru, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	VenMon_BruF, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	VenMon_BruNC, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	VenDoc_Ini, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	VenDoc_Fin ")
            loComandoSeleccionar.AppendLine(" FROM		#TablaTemporalCobros1 ")
            loComandoSeleccionar.AppendLine(" UNION ALL ")

            loComandoSeleccionar.AppendLine(" SELECT	2											AS	Orden, ")
            loComandoSeleccionar.AppendLine(" 			'RelVen'									AS	Tipo, ")
            loComandoSeleccionar.AppendLine(" 			VenFecha1									AS	Fec_Ini,") 
            loComandoSeleccionar.AppendLine(" 			VenFecha2									AS	Fecha2,") 
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	Tip_Ope, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	Cuantas, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	Monto, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	CMon_Com, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	CMon_Ret, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(30)									AS  Cod_Ven, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(30)									AS  Nom_Ven, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS  Por_Ven, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS  Cuantos, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS  Mon_Bru, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS  Mon_Net, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS  Mon_Com, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	Pares, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	TDocumento, ")
            loComandoSeleccionar.AppendLine(" 			VenFecha1									AS	TFec_Ini, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(30)									AS	TCod_Ven, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(30)									AS	TCod_Tar, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(30)									AS	TNum_Doc, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	TMon_Net, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	TPor_Com, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	TMon_Com, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	TPor_Ret, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	TMon_Ret, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	TCod_Tip, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	Doc_Ini, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	Doc_Fin, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	ChMon_Net, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	ChDocumento, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(20)									AS	ChNum_Doc, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(30)									AS	ChNom_Ban, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	DscDocumento, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	DscPor_Des, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	DscMon_Des, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	DscMon_Bru, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	DscMon_Net, ")
            loComandoSeleccionar.AppendLine(" 			VenCan_Doc									AS	VenCan_Doc, ")
            loComandoSeleccionar.AppendLine(" 			VenTip_Doc									AS	VenTip_Doc, ")
            loComandoSeleccionar.AppendLine(" 			VenMon_Bru									AS	VenMon_Bru, ")
            loComandoSeleccionar.AppendLine(" 			VenMon_BruF									AS	VenMon_BruF, ")
            loComandoSeleccionar.AppendLine(" 			VenMon_BruNC								AS	VenMon_BruNC, ")
            loComandoSeleccionar.AppendLine(" 			VenDoc_Ini									AS	VenDoc_Ini, ")
            loComandoSeleccionar.AppendLine(" 			VenDoc_Fin									AS	VenDoc_Fin ")
            loComandoSeleccionar.AppendLine(" FROM		#TablaTemporalVentas1 ")
            loComandoSeleccionar.AppendLine(" UNION ALL ")


            loComandoSeleccionar.AppendLine(" SELECT	3											AS	Orden, ")
            loComandoSeleccionar.AppendLine(" 			'RelDes'									AS	Tipo, ")
            loComandoSeleccionar.AppendLine(" 			DscFec_Ini									AS	Fec_Ini,") 
            loComandoSeleccionar.AppendLine(" 			DscFecha2									AS	Fecha2,") 
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	Tip_Ope, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	Cuantas, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	Monto, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	CMon_Com, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	CMon_Ret, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(30)									AS  Cod_Ven, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(30)									AS  Nom_Ven, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS  Por_Ven, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS  Cuantos, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS  Mon_Bru, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS  Mon_Net, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS  Mon_Com, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	Pares, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	TDocumento, ")
            loComandoSeleccionar.AppendLine(" 			DscFec_Ini									AS	TFec_Ini, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(30)									AS	TCod_Ven, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(30)									AS	TCod_Tar, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(30)									AS	TNum_Doc, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	TMon_Net, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	TPor_Com, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	TMon_Com, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	TPor_Ret, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	TMon_Ret, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	TCod_Tip, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	Doc_Ini, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	Doc_Fin, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	ChMon_Net, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	ChDocumento, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(20)									AS	ChNum_Doc, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(30)									AS	ChNom_Ban, ")
            loComandoSeleccionar.AppendLine(" 			DscDocumento								AS	DscDocumento, ")
            loComandoSeleccionar.AppendLine(" 			DscPor_Des									AS	DscPor_Des, ")
            loComandoSeleccionar.AppendLine(" 			DscMon_Des									AS	DscMon_Des, ")
            loComandoSeleccionar.AppendLine(" 			DscMon_Bru									AS	DscMon_Bru, ")
            loComandoSeleccionar.AppendLine(" 			DscMon_Net									AS	DscMon_Net, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	VenCan_Doc, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	VenTip_Doc, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	VenMon_Bru, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	VenMon_BruF, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	VenMon_BruNC, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	VenDoc_Ini, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	VenDoc_Fin ")
            loComandoSeleccionar.AppendLine(" FROM		#TablaTemporalDescuentos1 ")
            loComandoSeleccionar.AppendLine(" UNION ALL ")

            loComandoSeleccionar.AppendLine(" SELECT	4											AS	Orden, ")
            loComandoSeleccionar.AppendLine(" 			'RelChe'									AS	Tipo, ")
            loComandoSeleccionar.AppendLine(" 			ChFec_Ini									AS	Fec_Ini,") 
            loComandoSeleccionar.AppendLine(" 			ChFecha2									AS	Fecha2,") 
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	Tip_Ope, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	Cuantas, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	Monto, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	CMon_Com, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	CMon_Ret, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(30)									AS  Cod_Ven, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(30)									AS  Nom_Ven, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS  Por_Ven, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS  Cuantos, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS  Mon_Bru, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS  Mon_Net, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS  Mon_Com, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	Pares, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	TDocumento, ")
            loComandoSeleccionar.AppendLine(" 			ChFec_Ini									AS	TFec_Ini, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(30)									AS	TCod_Ven, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(30)									AS	TCod_Tar, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(30)									AS	TNum_Doc, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	TMon_Net, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	TPor_Com, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	TMon_Com, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	TPor_Ret, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	TMon_Ret, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	TCod_Tip, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	Doc_Ini, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	Doc_Fin, ")
            loComandoSeleccionar.AppendLine(" 			ChMon_Net									AS	ChMon_Net, ")
            loComandoSeleccionar.AppendLine(" 			ChDocumento									AS	ChDocumento, ")
            loComandoSeleccionar.AppendLine(" 			ChNum_Doc									AS	ChNum_Doc, ")
            loComandoSeleccionar.AppendLine(" 			ChNom_Ban									AS	ChNom_Ban, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	DscDocumento, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	DscPor_Des, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	DscMon_Des, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	DscMon_Bru, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	DscMon_Net, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	VenCan_Doc, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	VenTip_Doc, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	VenMon_Bru, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	VenMon_BruF, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	VenMon_BruNC, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	VenDoc_Ini, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	VenDoc_Fin ")
            loComandoSeleccionar.AppendLine(" FROM		#TablaTemporalCheques1 ")
            loComandoSeleccionar.AppendLine(" UNION ALL ")

			loComandoSeleccionar.AppendLine(" SELECT	5											AS	Orden, ")
            loComandoSeleccionar.AppendLine(" 			'RelTar'									AS	Tipo, ")
            loComandoSeleccionar.AppendLine(" 			TFec_Ini									AS	Fec_Ini, ")
            loComandoSeleccionar.AppendLine(" 			TFecha2										AS	Fecha2,") 
            loComandoSeleccionar.AppendLine(" 			SPACE(20)									AS	Tip_Ope, ") 
            loComandoSeleccionar.AppendLine(" 			0.00										AS	Cuantas, ") 
            loComandoSeleccionar.AppendLine(" 			0.00										AS	Monto, ") 
            loComandoSeleccionar.AppendLine(" 			0.00										AS	CMon_Com, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	CMon_Ret, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(30)									AS  Cod_Ven, ") 
            loComandoSeleccionar.AppendLine(" 			SPACE(30)									AS  Nom_Ven, ") 
            loComandoSeleccionar.AppendLine(" 			0.00										AS  Por_Ven, ") 
            loComandoSeleccionar.AppendLine(" 			0.00										AS  Cuantos, ") 
            loComandoSeleccionar.AppendLine(" 			0.00										AS  Mon_Bru, ") 
            loComandoSeleccionar.AppendLine(" 			0.00										AS  Mon_Net, ") 
            loComandoSeleccionar.AppendLine(" 			0.00										AS  Mon_Com, ") 
            loComandoSeleccionar.AppendLine(" 			0.00										AS  Pares, ")
            loComandoSeleccionar.AppendLine(" 			TDocumento									AS	TDocumento, ") 
            loComandoSeleccionar.AppendLine(" 			TFec_Ini									AS	TFec_Ini, ") 
            loComandoSeleccionar.AppendLine(" 			TCod_Ven									AS	TCod_Ven, ") 
            loComandoSeleccionar.AppendLine(" 			TCod_Tar									AS	TCod_Tar, ") 
            loComandoSeleccionar.AppendLine(" 			TNum_Doc									AS	TNum_Doc, ") 
            loComandoSeleccionar.AppendLine(" 			TMon_Net									AS	TMon_Net, ") 
            loComandoSeleccionar.AppendLine(" 			TPor_Com									AS	TPor_Com, ") 
            loComandoSeleccionar.AppendLine(" 			TMon_Com									AS	TMon_Com, ") 
            loComandoSeleccionar.AppendLine(" 			TPor_Ret									AS	TPor_Ret, ") 
            loComandoSeleccionar.AppendLine(" 			TMon_Ret									AS  TMon_Ret, ") 
            loComandoSeleccionar.AppendLine(" 			TCod_Tip									AS	TCod_Tip, ") 
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	Doc_Ini, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	Doc_Fin, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	ChMon_Net, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	ChDocumento, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(20)									AS	ChNum_Doc, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(30)									AS	ChNom_Ban, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	DscDocumento, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	DscPor_Des, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	DscMon_Des, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	DscMon_Bru, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	DscMon_Net, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	VenCan_Doc, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	VenTip_Doc, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	VenMon_Bru, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	VenMon_BruF, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	VenMon_BruNC, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	VenDoc_Ini, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	VenDoc_Fin ")
            loComandoSeleccionar.AppendLine(" FROM		#TablaTemporalTarjetas1 ") 
            loComandoSeleccionar.AppendLine(" UNION ALL ")

            loComandoSeleccionar.AppendLine(" SELECT	6											AS	Orden,")
            loComandoSeleccionar.AppendLine(" 			'RelCom'									AS	Tipo,")
            loComandoSeleccionar.AppendLine(" 			Fec_Ini										AS	Fec_Ini, ")
            loComandoSeleccionar.AppendLine(" 			Fecha2										AS	Fecha2,") 
            loComandoSeleccionar.AppendLine(" 			SPACE(20)									AS	Tip_Ope, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	Cuantas, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	Monto, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	CMon_Com, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	CMon_Ret, ")
            loComandoSeleccionar.AppendLine(" 			Cod_Ven										AS	Cod_Ven, ")
            loComandoSeleccionar.AppendLine(" 			Nom_Ven										AS	Nom_Ven, ")
            loComandoSeleccionar.AppendLine(" 			Por_Ven										AS	Por_Ven, ")
            loComandoSeleccionar.AppendLine(" 			Cuantos										AS	Cuantos, ")
            loComandoSeleccionar.AppendLine(" 			Mon_Bru										AS	Mon_Bru, ")
            loComandoSeleccionar.AppendLine(" 			Mon_Net										AS	Mon_Net, ")
            loComandoSeleccionar.AppendLine(" 			Mon_Com										AS	Mon_Com, ")
            loComandoSeleccionar.AppendLine(" 			Pares										AS	Pares, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	TDocumento, ")
            loComandoSeleccionar.AppendLine(" 			Fec_Ini										AS	TFec_Ini, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(30)									AS	TCod_Ven, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(30)									AS	TCod_Tar, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(30)									AS	TNum_Doc, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	TMon_Net, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	TPor_Com, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	TMon_Com, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	TPor_Ret, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	TMon_Ret, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	TCod_Tip, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	Doc_Ini, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	Doc_Fin, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	ChMon_Net, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	ChDocumento, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(20)									AS	ChNum_Doc, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(30)									AS	ChNom_Ban, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	DscDocumento, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	DscPor_Des, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	DscMon_Des, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	DscMon_Bru, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	DscMon_Net, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	VenCan_Doc, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	VenTip_Doc, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	VenMon_Bru, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	VenMon_BruF, ")
            loComandoSeleccionar.AppendLine(" 			0.00										AS	VenMon_BruNC, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	VenDoc_Ini, ")
            loComandoSeleccionar.AppendLine(" 			SPACE(10)									AS	VenDoc_Fin ")
            loComandoSeleccionar.AppendLine(" FROM		#TablaTemporalComisiones2 ")

			loComandoSeleccionar.AppendLine(" ) ")

            loComandoSeleccionar.AppendLine(" SELECT	Orden, ")
            loComandoSeleccionar.AppendLine(" 			Tipo, ")
            loComandoSeleccionar.AppendLine(" 			Fec_Ini,") 
            loComandoSeleccionar.AppendLine(" 			Tip_Ope, ")
            loComandoSeleccionar.AppendLine(" 			Cuantas, ")
            loComandoSeleccionar.AppendLine(" 			Monto, ")
            loComandoSeleccionar.AppendLine(" 			CMon_Com, ")
            loComandoSeleccionar.AppendLine(" 			CMon_Ret, ")
            loComandoSeleccionar.AppendLine(" 			Cod_Ven, ")
            loComandoSeleccionar.AppendLine(" 			Nom_Ven, ")
            loComandoSeleccionar.AppendLine(" 			Por_Ven, ")
            loComandoSeleccionar.AppendLine(" 			Cuantos, ")
            loComandoSeleccionar.AppendLine(" 			Mon_Bru, ")
            loComandoSeleccionar.AppendLine(" 			Mon_Net, ")
            loComandoSeleccionar.AppendLine(" 			Mon_Com, ")
            loComandoSeleccionar.AppendLine(" 			Pares, ")
            loComandoSeleccionar.AppendLine(" 			TDocumento, ")
            loComandoSeleccionar.AppendLine(" 			TFec_Ini, ")
            loComandoSeleccionar.AppendLine(" 			TCod_Ven, ")
            loComandoSeleccionar.AppendLine(" 			TCod_Tar, ")
            loComandoSeleccionar.AppendLine(" 			TNum_Doc, ")
            loComandoSeleccionar.AppendLine(" 			TMon_Net, ")
            loComandoSeleccionar.AppendLine(" 			TPor_Com, ")
            loComandoSeleccionar.AppendLine(" 			TMon_Com, ")
            loComandoSeleccionar.AppendLine(" 			TPor_Ret, ")
            loComandoSeleccionar.AppendLine(" 			TMon_Ret, ")
            loComandoSeleccionar.AppendLine(" 			TCod_Tip, ")
            loComandoSeleccionar.AppendLine(" 			Doc_Ini, ")
            loComandoSeleccionar.AppendLine(" 			Doc_Fin, ")
            loComandoSeleccionar.AppendLine(" 			ChMon_Net, ")
            loComandoSeleccionar.AppendLine(" 			ChDocumento, ")
            loComandoSeleccionar.AppendLine(" 			ChNum_Doc, ")
            loComandoSeleccionar.AppendLine(" 			ChNom_Ban, ")
            loComandoSeleccionar.AppendLine(" 			DscDocumento, ")
            loComandoSeleccionar.AppendLine(" 			DscPor_Des, ")
            loComandoSeleccionar.AppendLine(" 			DscMon_Des, ")
            loComandoSeleccionar.AppendLine(" 			DscMon_Bru, ")
            loComandoSeleccionar.AppendLine(" 			DscMon_Net, ")
            loComandoSeleccionar.AppendLine(" 			VenCan_Doc, ")
            loComandoSeleccionar.AppendLine(" 			VenTip_Doc, ")
            loComandoSeleccionar.AppendLine(" 			VenMon_Bru, ")
            loComandoSeleccionar.AppendLine(" 			VenMon_BruF, ")
            loComandoSeleccionar.AppendLine(" 			VenMon_BruNC, ")
            loComandoSeleccionar.AppendLine(" 			VenDoc_Ini, ")
            loComandoSeleccionar.AppendLine(" 			VenDoc_Fin ")
            loComandoSeleccionar.AppendLine(" FROM		curTemporal ")
            'loComandoSeleccionar.AppendLine(" ORDER BY	Fecha2 ASC, Orden ")
            loComandoSeleccionar.AppendLine("ORDER BY   " & lcOrdenamiento & ", Orden")


            Dim loServicios As New cusDatos.goDatos

            Dim laDatosReporte As DataSet = loServicios.mObtenerTodosSinEsquema(loComandoSeleccionar.ToString, "curReportes")

            '-------------------------------------------------------------------------------------------------------
            ' Verificando si el select (tabla nº0) trae registros
            '-------------------------------------------------------------------------------------------------------

            If (laDatosReporte.Tables(0).Rows.Count <= 0) Then
                Me.WbcAdministradorMensajeModal.mMostrarMensajeModal("Información", _
                                          "No se Encontraron Registros para los Parámetros Especificados. ", _
                                           vis3Controles.wbcAdministradorMensajeModal.enumTipoMensaje.KN_Informacion, _
                                           "350px", _
                                           "200px")
            End If

            loObjetoReporte	=  cusAplicacion.goReportes.mCargarReporte("rRVentas_CBancarias", laDatosReporte)
 
            Me.mTraducirReporte(loObjetoReporte)

			Me.mFormatearCamposReporte(loObjetoReporte)

            Me.crvrRVentas_CBancarias.ReportSource =	 loObjetoReporte	

        Catch loExcepcion As Exception

            Me.WbcAdministradorMensajeModal.mMostrarMensajeModal("Error", _
                          "No se pudo Completar el Proceso: " & loExcepcion.Message, _
                           vis3Controles.wbcAdministradorMensajeModal.enumTipoMensaje.KN_Error, _
                           "auto", _
                           "auto")

        End Try
	
	End Sub

	Protected Sub Page_Unload(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Unload

	Try 

		loObjetoReporte.Close()

	Catch loExcepcion As Exception

	End Try
	
	End Sub

End Class
'-------------------------------------------------------------------------------------------'
' Fin del codigo
'-------------------------------------------------------------------------------------------'
' JJD: 29/07/08: Codigo inicial
'-------------------------------------------------------------------------------------------'
' JJD: 30/07/08: Ajustes a los campos que se traia el reporte
'-------------------------------------------------------------------------------------------'
' JJD: 10/10/08: Adecuacion segun los parametros del reporte original
'-------------------------------------------------------------------------------------------'
' JJD: 11/10/08: Continuacion de la adecuacion segun los parametros del reporte original
'-------------------------------------------------------------------------------------------'
' JJD: 13/10/08: Continuacion de la adecuacion segun los parametros del reporte original
'-------------------------------------------------------------------------------------------'
' JJD: 25/10/08: Ajustes a la busqueda de los cheques y las tarjetas
'-------------------------------------------------------------------------------------------'
' CMS:  14/08/09: Metodo de ordenamiento, verificacionde registros
'-------------------------------------------------------------------------------------------'