'-------------------------------------------------------------------------------------------'
' Inicio del codigo
'-------------------------------------------------------------------------------------------'
' Importando librerias 
'-------------------------------------------------------------------------------------------'
Imports System.Data

'-------------------------------------------------------------------------------------------'
' Inicio de clase "rTop10_Clientes"
'-------------------------------------------------------------------------------------------'
Partial Class rTop10_Clientes
    Inherits vis2Formularios.frmReporte

    Dim loObjetoReporte As CrystalDecisions.CrystalReports.Engine.ReportDocument

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load

        Try
            Dim lcParametro0Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(0), goServicios.enuOpcionesRedondeo.KN_FechaInicioDelDia)
            Dim lcParametro0Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(0), goServicios.enuOpcionesRedondeo.KN_FechaFinDelDia)
            Dim lcParametro1Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(1))
            Dim lcParametro1Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(1))
            Dim lcParametro2Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(2))
            Dim lcParametro2Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(2))
            Dim lcParametro3Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(3))
            Dim lcParametro3Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(3))
            Dim lcParametro4Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(4))
            Dim lcParametro4Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(4))
            Dim lcParametro5Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(5))
            Dim lcParametro5Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(5))
            Dim lcParametro6Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(6))
            Dim lcParametro6Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(6))
            Dim lcParametro7Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(7))
            Dim lcParametro7Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(7))
            Dim lcParametro8Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(8))
            Dim lcParametro9Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(9))
            Dim lcParametro9Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(9))
            Dim lcParametro10Desde As String = goServicios.mObtenerListaFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(10))
            Dim lcParametro11Desde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(11))
            Dim lcParametro11Hasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(11))

            Dim lcOrdenamiento As String = cusAplicacion.goReportes.pcOrden

            Dim loComandoSeleccionar As New StringBuilder()

            loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("	SET NOCOUNT ON;")
            loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("CREATE TABLE #tmpTop10Clientes")
            loComandoSeleccionar.AppendLine("		(		Seccion			CHAR(30),")
            loComandoSeleccionar.AppendLine("				Cod_Cli			CHAR(10),")
            loComandoSeleccionar.AppendLine("				Nom_Cli			CHAR(100),")
            loComandoSeleccionar.AppendLine("				Cifra1			DECIMAL(28, 10),")
            loComandoSeleccionar.AppendLine("				Cifra2			DECIMAL(28, 10),")
            loComandoSeleccionar.AppendLine("				Cifra3			DECIMAL(28, 10),")
            loComandoSeleccionar.AppendLine("				Cifra4			DECIMAL(28, 10)")
            loComandoSeleccionar.AppendLine("		)")
            loComandoSeleccionar.AppendLine("		")
            loComandoSeleccionar.AppendLine("--*******************************************************************************************")
            loComandoSeleccionar.AppendLine("-- Clientes con más Ventas (Montos)															*	")
            loComandoSeleccionar.AppendLine("--*******************************************************************************************")
            loComandoSeleccionar.AppendLine("INSERT INTO #tmpTop10Clientes(Seccion, Cod_Cli, Nom_Cli, Cifra1, Cifra2, Cifra3, Cifra4)")
            loComandoSeleccionar.AppendLine("SELECT")
            loComandoSeleccionar.AppendLine("		'01_ventas'					AS Seccion,")
            loComandoSeleccionar.AppendLine("		#tablaVentas.Cod_Cli		AS Cod_Cli,")
            loComandoSeleccionar.AppendLine("		#tablaVentas.Nom_Cli		AS Nom_Cli,")
            loComandoSeleccionar.AppendLine("		#tablaVentas.Cantidad		AS Cifra1,")
            loComandoSeleccionar.AppendLine("		#tablaVentas.Monto_Ventas	AS Cifra2,")
            loComandoSeleccionar.AppendLine("		0 							AS Cifra3,")
            loComandoSeleccionar.AppendLine("		0 							AS Cifra4")
            loComandoSeleccionar.AppendLine("FROM(")
            loComandoSeleccionar.AppendLine("			SELECT	TOP 10")
            loComandoSeleccionar.AppendLine("					Facturas.Cod_Cli					AS Cod_Cli,")
            loComandoSeleccionar.AppendLine("					Clientes.Nom_Cli					AS Nom_Cli,")
            loComandoSeleccionar.AppendLine("					SUM(Renglones_Facturas.Can_Art1)	AS Cantidad,")
            loComandoSeleccionar.AppendLine("					SUM(Renglones_Facturas.Mon_Net)		AS Monto_Ventas")
            loComandoSeleccionar.AppendLine("			FROM	Facturas")
            loComandoSeleccionar.AppendLine("			JOIN Clientes ON Facturas.Cod_Cli = Clientes.Cod_Cli")
            loComandoSeleccionar.AppendLine("			JOIN Renglones_Facturas ON Facturas.Documento = Renglones_Facturas.Documento")
            loComandoSeleccionar.AppendLine("			JOIN func_varcharlist_to_table(" & lcParametro8Desde & ") tablaStatus ON Facturas.Status = tablaStatus.item")
            loComandoSeleccionar.AppendLine("			WHERE	Facturas.Status <> 'Anulado'")
            loComandoSeleccionar.AppendLine("					AND Facturas.Fec_Ini BETWEEN " & lcParametro0Desde & " AND" & lcParametro0Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Facturas.Cod_Cli BETWEEN " & lcParametro1Desde & " AND " & lcParametro1Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Clientes.Cod_Tip BETWEEN " & lcParametro2Desde & " AND " & lcParametro2Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Clientes.Cod_Cla BETWEEN " & lcParametro3Desde & " AND " & lcParametro3Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Clientes.Cod_Zon BETWEEN " & lcParametro4Desde & " AND " & lcParametro4Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Clientes.Cod_Pai BETWEEN " & lcParametro5Desde & " AND " & lcParametro5Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Facturas.Cod_Ven BETWEEN " & lcParametro6Desde & " AND " & lcParametro6Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Facturas.Cod_Mon BETWEEN " & lcParametro7Desde & " AND " & lcParametro7Hasta & "")
            loComandoSeleccionar.AppendLine("					AND ( (" & lcParametro10Desde & "='Igual' AND Facturas.Cod_Rev BETWEEN " & lcParametro9Desde & " AND " & lcParametro9Hasta & ") OR")
            loComandoSeleccionar.AppendLine("						(" & lcParametro10Desde & "<>'Igual' AND Facturas.Cod_Rev NOT BETWEEN " & lcParametro9Desde & " AND " & lcParametro9Hasta & ") )")
            loComandoSeleccionar.AppendLine("					AND Facturas.Cod_Suc BETWEEN " & lcParametro11Desde & " AND " & lcParametro11Hasta & "")
            loComandoSeleccionar.AppendLine("			GROUP BY Facturas.Cod_Cli, Clientes.Nom_Cli")
            loComandoSeleccionar.AppendLine("			ORDER BY SUM(Renglones_Facturas.Mon_Net) DESC")
            loComandoSeleccionar.AppendLine("	) AS #tablaVentas; ")
            loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("		")
            loComandoSeleccionar.AppendLine("--*******************************************************************************************")
            loComandoSeleccionar.AppendLine("-- Clientes con más Ganancias (Montos)														*	")
            loComandoSeleccionar.AppendLine("--*******************************************************************************************")
            loComandoSeleccionar.AppendLine("INSERT INTO #tmpTop10Clientes(Seccion, Cod_Cli, Nom_Cli, Cifra1, Cifra2, Cifra3, Cifra4)")
            loComandoSeleccionar.AppendLine("SELECT")
            loComandoSeleccionar.AppendLine("		'02_ganancias'				AS Seccion,")
            loComandoSeleccionar.AppendLine("		#tablaVentas.Cod_Cli		AS Cod_Cli,")
            loComandoSeleccionar.AppendLine("		#tablaVentas.Nom_Cli		AS Nom_Cli,")
            loComandoSeleccionar.AppendLine("		#tablaVentas.Monto_Ventas	AS Cifra1,")
            loComandoSeleccionar.AppendLine("		#tablaVentas.Monto_Costos	AS Cifra2,")
            loComandoSeleccionar.AppendLine("		#tablaVentas.Ganancias		AS Cifra3,")
            loComandoSeleccionar.AppendLine("		#tablaVentas.Por_Ganancias	AS Cifra4")
            loComandoSeleccionar.AppendLine("FROM(")
            loComandoSeleccionar.AppendLine("			SELECT	TOP 10")
            loComandoSeleccionar.AppendLine("					Facturas.Cod_Cli																			AS Cod_Cli,")
            loComandoSeleccionar.AppendLine("					Clientes.Nom_Cli																			AS Nom_Cli,")
            loComandoSeleccionar.AppendLine("					SUM(Renglones_Facturas.Mon_Net)																AS Monto_Ventas,")
            loComandoSeleccionar.AppendLine("					SUM(Renglones_Facturas.Can_Art1*Renglones_Facturas.Cos_Pro1)								AS Monto_Costos,")
            loComandoSeleccionar.AppendLine("					SUM(Renglones_Facturas.Mon_Net - Renglones_Facturas.Can_Art1*Renglones_Facturas.Cos_Pro1)	AS Ganancias,")
            loComandoSeleccionar.AppendLine("					SUM(Renglones_Facturas.Mon_Net - Renglones_Facturas.Can_Art1*Renglones_Facturas.Cos_Pro1)")
            loComandoSeleccionar.AppendLine("						/SUM(Renglones_Facturas.Mon_Net)*100													AS Por_Ganancias")
            loComandoSeleccionar.AppendLine("			FROM	Facturas")
            loComandoSeleccionar.AppendLine("			JOIN Clientes ON Facturas.Cod_Cli = Clientes.Cod_Cli")
            loComandoSeleccionar.AppendLine("			JOIN Renglones_Facturas ON Facturas.Documento = Renglones_Facturas.Documento")
            loComandoSeleccionar.AppendLine("			JOIN func_varcharlist_to_table(" & lcParametro8Desde & ") tablaStatus ON Facturas.Status = tablaStatus.item")
            loComandoSeleccionar.AppendLine("			WHERE	Facturas.Status <> 'Anulado'")
            loComandoSeleccionar.AppendLine("					AND Facturas.Fec_Ini BETWEEN " & lcParametro0Desde & " AND" & lcParametro0Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Facturas.Cod_Cli BETWEEN " & lcParametro1Desde & " AND " & lcParametro1Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Clientes.Cod_Tip BETWEEN " & lcParametro2Desde & " AND " & lcParametro2Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Clientes.Cod_Cla BETWEEN " & lcParametro3Desde & " AND " & lcParametro3Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Clientes.Cod_Zon BETWEEN " & lcParametro4Desde & " AND " & lcParametro4Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Clientes.Cod_Pai BETWEEN " & lcParametro5Desde & " AND " & lcParametro5Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Facturas.Cod_Ven BETWEEN " & lcParametro6Desde & " AND " & lcParametro6Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Facturas.Cod_Mon BETWEEN " & lcParametro7Desde & " AND " & lcParametro7Hasta & "")
            loComandoSeleccionar.AppendLine("					AND ( (" & lcParametro10Desde & "='Igual' AND Facturas.Cod_Rev BETWEEN " & lcParametro9Desde & " AND " & lcParametro9Hasta & ") OR")
            loComandoSeleccionar.AppendLine("						(" & lcParametro10Desde & "<>'Igual' AND Facturas.Cod_Rev NOT BETWEEN " & lcParametro9Desde & " AND " & lcParametro9Hasta & ") )")
            loComandoSeleccionar.AppendLine("					AND Facturas.Cod_Suc BETWEEN " & lcParametro11Desde & " AND " & lcParametro11Hasta & "")
            loComandoSeleccionar.AppendLine("			GROUP BY Facturas.Cod_Cli, Clientes.Nom_Cli")
            loComandoSeleccionar.AppendLine("			ORDER BY SUM(Renglones_Facturas.Mon_Net) DESC")
            loComandoSeleccionar.AppendLine("	) AS #tablaVentas; ")
            loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("		")
            loComandoSeleccionar.AppendLine("--*******************************************************************************************")
            loComandoSeleccionar.AppendLine("-- Clientes con más Unidades Vendidas (Cantidad)											*	")
            loComandoSeleccionar.AppendLine("--*******************************************************************************************")
            loComandoSeleccionar.AppendLine("INSERT INTO #tmpTop10Clientes(Seccion, Cod_Cli, Nom_Cli, Cifra1, Cifra2, Cifra3, Cifra4)")
            loComandoSeleccionar.AppendLine("SELECT")
            loComandoSeleccionar.AppendLine("		'03_unidades_vendidas'		AS Seccion,")
            loComandoSeleccionar.AppendLine("		#tablaVentas.Cod_Cli		AS Cod_Cli,")
            loComandoSeleccionar.AppendLine("		#tablaVentas.Nom_Cli		AS Nom_Cli,	")
            loComandoSeleccionar.AppendLine("		#tablaVentas.Cantidad		AS Cifra1,  ")
            loComandoSeleccionar.AppendLine("		#tablaVentas.Monto_Ventas	AS Cifra2,  ")
            loComandoSeleccionar.AppendLine("		0							AS Cifra3,  ")
            loComandoSeleccionar.AppendLine("		0							AS Cifra4")
            loComandoSeleccionar.AppendLine("FROM(")
            loComandoSeleccionar.AppendLine("			SELECT	TOP 10")
            loComandoSeleccionar.AppendLine("					Facturas.Cod_Cli					AS Cod_Cli,")
            loComandoSeleccionar.AppendLine("					Clientes.Nom_Cli					AS Nom_Cli,")
            loComandoSeleccionar.AppendLine("					SUM(Renglones_Facturas.Can_Art1)	AS Cantidad,")
            loComandoSeleccionar.AppendLine("					SUM(Renglones_Facturas.Mon_Net)		AS Monto_Ventas")
            loComandoSeleccionar.AppendLine("			FROM	Facturas")
            loComandoSeleccionar.AppendLine("			JOIN Clientes ON Facturas.Cod_Cli = Clientes.Cod_Cli")
            loComandoSeleccionar.AppendLine("			JOIN Renglones_Facturas ON Facturas.Documento = Renglones_Facturas.Documento")
            loComandoSeleccionar.AppendLine("			JOIN func_varcharlist_to_table(" & lcParametro8Desde & ") tablaStatus ON Facturas.Status = tablaStatus.item")
            loComandoSeleccionar.AppendLine("			WHERE	Facturas.Status <> 'Anulado'")
            loComandoSeleccionar.AppendLine("					AND Facturas.Fec_Ini BETWEEN " & lcParametro0Desde & " AND" & lcParametro0Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Facturas.Cod_Cli BETWEEN " & lcParametro1Desde & " AND " & lcParametro1Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Clientes.Cod_Tip BETWEEN " & lcParametro2Desde & " AND " & lcParametro2Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Clientes.Cod_Cla BETWEEN " & lcParametro3Desde & " AND " & lcParametro3Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Clientes.Cod_Zon BETWEEN " & lcParametro4Desde & " AND " & lcParametro4Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Clientes.Cod_Pai BETWEEN " & lcParametro5Desde & " AND " & lcParametro5Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Facturas.Cod_Ven BETWEEN " & lcParametro6Desde & " AND " & lcParametro6Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Facturas.Cod_Mon BETWEEN " & lcParametro7Desde & " AND " & lcParametro7Hasta & "")
            loComandoSeleccionar.AppendLine("					AND ( (" & lcParametro10Desde & "='Igual' AND Facturas.Cod_Rev BETWEEN " & lcParametro9Desde & " AND " & lcParametro9Hasta & ") OR")
            loComandoSeleccionar.AppendLine("						(" & lcParametro10Desde & "<>'Igual' AND Facturas.Cod_Rev NOT BETWEEN " & lcParametro9Desde & " AND " & lcParametro9Hasta & ") )")
            loComandoSeleccionar.AppendLine("					AND Facturas.Cod_Suc BETWEEN " & lcParametro11Desde & " AND " & lcParametro11Hasta & "")
            loComandoSeleccionar.AppendLine("			GROUP BY Facturas.Cod_Cli, Clientes.Nom_Cli")
            loComandoSeleccionar.AppendLine("			ORDER BY SUM(Renglones_Facturas.Can_Art1) DESC")
            loComandoSeleccionar.AppendLine("	) AS #tablaVentas; ")
            loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("--*******************************************************************************************")
            loComandoSeleccionar.AppendLine("-- Clientes con más Unidades Devueltas (Cantidad)											*	")
            loComandoSeleccionar.AppendLine("--*******************************************************************************************")
            loComandoSeleccionar.AppendLine("INSERT INTO #tmpTop10Clientes(Seccion, Cod_Cli, Nom_Cli, Cifra1, Cifra2, Cifra3, Cifra4)")
            loComandoSeleccionar.AppendLine("SELECT")
            loComandoSeleccionar.AppendLine("		'04_unidades_devueltas'			AS Seccion,")
            loComandoSeleccionar.AppendLine("		#tablaDev.Cod_Cli				AS Cod_Cli,")
            loComandoSeleccionar.AppendLine("		#tablaDev.Nom_Cli				AS Nom_Cli,	")
            loComandoSeleccionar.AppendLine("		#tablaDev.Cantidad				AS Cifra1,  ")
            loComandoSeleccionar.AppendLine("		#tablaDev.Monto_Devoluciones	AS Cifra2,  ")
            loComandoSeleccionar.AppendLine("		0								AS Cifra3,  ")
            loComandoSeleccionar.AppendLine("		0								AS Cifra4")
            loComandoSeleccionar.AppendLine("FROM	(	SELECT TOP 10")
            loComandoSeleccionar.AppendLine("					Clientes.Cod_Cli,")
            loComandoSeleccionar.AppendLine("					Clientes.Nom_Cli,")
            loComandoSeleccionar.AppendLine("					SUM(Renglones_dClientes.Can_Art1) AS Cantidad,")
            loComandoSeleccionar.AppendLine("					SUM(Renglones_dClientes.Mon_Net) AS Monto_Devoluciones")
            loComandoSeleccionar.AppendLine("			FROM	Devoluciones_Clientes")
            loComandoSeleccionar.AppendLine("			JOIN Clientes ON Devoluciones_Clientes.Cod_Cli = Clientes.Cod_Cli")
            loComandoSeleccionar.AppendLine("			JOIN Renglones_dClientes ON Devoluciones_Clientes.Documento = Renglones_dClientes.Documento")
            loComandoSeleccionar.AppendLine("			JOIN func_varcharlist_to_table(" & lcParametro8Desde & ") tablaStatus ON Devoluciones_Clientes.Status = tablaStatus.item")
            loComandoSeleccionar.AppendLine("			WHERE	Devoluciones_Clientes.Status <> 'Anulado'")
            loComandoSeleccionar.AppendLine("					AND Devoluciones_Clientes.Fec_Ini BETWEEN " & lcParametro0Desde & " AND" & lcParametro0Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Devoluciones_Clientes.Cod_Cli BETWEEN " & lcParametro1Desde & " AND " & lcParametro1Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Clientes.Cod_Tip BETWEEN " & lcParametro2Desde & " AND " & lcParametro2Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Clientes.Cod_Cla BETWEEN " & lcParametro3Desde & " AND " & lcParametro3Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Clientes.Cod_Zon BETWEEN " & lcParametro4Desde & " AND " & lcParametro4Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Clientes.Cod_Pai BETWEEN " & lcParametro5Desde & " AND " & lcParametro5Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Devoluciones_Clientes.Cod_Ven BETWEEN " & lcParametro6Desde & " AND " & lcParametro6Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Devoluciones_Clientes.Cod_Mon BETWEEN " & lcParametro7Desde & " AND " & lcParametro7Hasta & "")
            loComandoSeleccionar.AppendLine("					AND ( (" & lcParametro10Desde & "='Igual' AND Devoluciones_Clientes.Cod_Rev BETWEEN " & lcParametro9Desde & " AND " & lcParametro9Hasta & ") OR")
            loComandoSeleccionar.AppendLine("						(" & lcParametro10Desde & "<>'Igual' AND Devoluciones_Clientes.Cod_Rev NOT BETWEEN " & lcParametro9Desde & " AND " & lcParametro9Hasta & ") )")
            loComandoSeleccionar.AppendLine("					AND Devoluciones_Clientes.Cod_Suc BETWEEN " & lcParametro11Desde & " AND " & lcParametro11Hasta & "")
            loComandoSeleccionar.AppendLine("			GROUP BY Clientes.Cod_Cli, Clientes.Nom_Cli")
            loComandoSeleccionar.AppendLine("			ORDER BY SUM(Renglones_dClientes.Can_Art1) DESC")
            loComandoSeleccionar.AppendLine("	) AS #tablaDev; ")
            loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("--*******************************************************************************************")
            loComandoSeleccionar.AppendLine("-- Clientes con más Unidades Devueltas (Cantidad)											*	")
            loComandoSeleccionar.AppendLine("--*******************************************************************************************")
            loComandoSeleccionar.AppendLine("INSERT INTO #tmpTop10Clientes(Seccion, Cod_Cli, Nom_Cli, Cifra1, Cifra2, Cifra3, Cifra4)")
            loComandoSeleccionar.AppendLine("SELECT")
            loComandoSeleccionar.AppendLine("		'05_cheques_devueltos'				AS Seccion,")
            loComandoSeleccionar.AppendLine("		#tablaCheques.Cod_Cli				AS Cod_Cli,")
            loComandoSeleccionar.AppendLine("		#tablaCheques.Nom_Cli				AS Nom_Cli,	")
            loComandoSeleccionar.AppendLine("		#tablaCheques.Documentos			AS Cifra1,  ")
            loComandoSeleccionar.AppendLine("		#tablaCheques.Monto_Devoluciones	AS Cifra2,  ")
            loComandoSeleccionar.AppendLine("		0									AS Cifra3,  ")
            loComandoSeleccionar.AppendLine("		0									AS Cifra4")
            loComandoSeleccionar.AppendLine("FROM	(	SELECT TOP 10")
            loComandoSeleccionar.AppendLine("					Clientes.Cod_Cli				AS Cod_Cli,")
            loComandoSeleccionar.AppendLine("					Clientes.Nom_Cli				AS Nom_Cli,")
            loComandoSeleccionar.AppendLine("					COUNT(Cuentas_Cobrar.Documento) AS Documentos,")
            loComandoSeleccionar.AppendLine("					SUM(Cuentas_Cobrar.Mon_Net)		AS Monto_Devoluciones")
            loComandoSeleccionar.AppendLine("			FROM	Cuentas_Cobrar")
            loComandoSeleccionar.AppendLine("			JOIN Clientes ON Cuentas_Cobrar.Cod_Cli = Clientes.Cod_Cli")
            loComandoSeleccionar.AppendLine("			JOIN func_varcharlist_to_table(" & lcParametro8Desde & ") tablaStatus ON Cuentas_Cobrar.Status = tablaStatus.item")
            loComandoSeleccionar.AppendLine("			WHERE	Cuentas_Cobrar.Status <> 'Anulado'")
            loComandoSeleccionar.AppendLine("					AND Cuentas_Cobrar.Fec_Ini BETWEEN " & lcParametro0Desde & " AND" & lcParametro0Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Cuentas_Cobrar.Cod_Cli BETWEEN " & lcParametro1Desde & " AND " & lcParametro1Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Clientes.Cod_Tip BETWEEN " & lcParametro2Desde & " AND " & lcParametro2Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Clientes.Cod_Cla BETWEEN " & lcParametro3Desde & " AND " & lcParametro3Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Clientes.Cod_Zon BETWEEN " & lcParametro4Desde & " AND " & lcParametro4Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Clientes.Cod_Pai BETWEEN " & lcParametro5Desde & " AND " & lcParametro5Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Cuentas_Cobrar.Cod_Ven BETWEEN " & lcParametro6Desde & " AND " & lcParametro6Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Cuentas_Cobrar.Cod_Mon BETWEEN " & lcParametro7Desde & " AND " & lcParametro7Hasta & "")
            loComandoSeleccionar.AppendLine("					AND ( (" & lcParametro10Desde & "='Igual' AND Cuentas_Cobrar.Cod_Rev BETWEEN " & lcParametro9Desde & " AND " & lcParametro9Hasta & ") OR")
            loComandoSeleccionar.AppendLine("						(" & lcParametro10Desde & "<>'Igual' AND Cuentas_Cobrar.Cod_Rev NOT BETWEEN " & lcParametro9Desde & " AND " & lcParametro9Hasta & ") )")
            loComandoSeleccionar.AppendLine("					AND Cuentas_Cobrar.Cod_Suc BETWEEN " & lcParametro11Desde & " AND " & lcParametro11Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Cuentas_Cobrar.Cod_Tip = 'CHEQ'")
            loComandoSeleccionar.AppendLine("			GROUP BY Clientes.Cod_Cli, Clientes.Nom_Cli")
            loComandoSeleccionar.AppendLine("			ORDER BY SUM(Cuentas_Cobrar.Mon_Net) DESC")
            loComandoSeleccionar.AppendLine("	) AS #tablaCheques; ")
            loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("--*******************************************************************************************")
            loComandoSeleccionar.AppendLine("-- Clientes con más Cuentas Pendientes (Monto)											*	")
            loComandoSeleccionar.AppendLine("--*******************************************************************************************")
            loComandoSeleccionar.AppendLine("INSERT INTO #tmpTop10Clientes(Seccion, Cod_Cli, Nom_Cli, Cifra1, Cifra2, Cifra3, Cifra4)")
            loComandoSeleccionar.AppendLine("SELECT")
            loComandoSeleccionar.AppendLine("		'06_cuentas_pendientes'				AS Seccion,")
            loComandoSeleccionar.AppendLine("		#tablaCuentas.Cod_Cli				AS Cod_Cli,")
            loComandoSeleccionar.AppendLine("		#tablaCuentas.Nom_Cli				AS Nom_Cli,	")
            loComandoSeleccionar.AppendLine("		#tablaCuentas.Documentos			AS Cifra1,  ")
            loComandoSeleccionar.AppendLine("		#tablaCuentas.Monto_Cuentas			AS Cifra2,  ")
            loComandoSeleccionar.AppendLine("		0									AS Cifra3,  ")
            loComandoSeleccionar.AppendLine("		0									AS Cifra4")
            loComandoSeleccionar.AppendLine("FROM	(	SELECT TOP 10")
            loComandoSeleccionar.AppendLine("					Clientes.Cod_Cli				AS Cod_Cli,")
            loComandoSeleccionar.AppendLine("					Clientes.Nom_Cli				AS Nom_Cli,")
            loComandoSeleccionar.AppendLine("					COUNT(Cuentas_Cobrar.Documento) AS Documentos,")
            loComandoSeleccionar.AppendLine("					SUM(Cuentas_Cobrar.Mon_Net)		AS Monto_Cuentas")
            loComandoSeleccionar.AppendLine("			FROM	Cuentas_Cobrar")
            loComandoSeleccionar.AppendLine("			JOIN Clientes ON Cuentas_Cobrar.Cod_Cli = Clientes.Cod_Cli")
            loComandoSeleccionar.AppendLine("			JOIN func_varcharlist_to_table(" & lcParametro8Desde & ") tablaStatus ON Cuentas_Cobrar.Status = tablaStatus.item")
            loComandoSeleccionar.AppendLine("			WHERE	Cuentas_Cobrar.Status <> 'Anulado'")
            loComandoSeleccionar.AppendLine("					AND Cuentas_Cobrar.Fec_Ini BETWEEN " & lcParametro0Desde & " AND" & lcParametro0Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Cuentas_Cobrar.Cod_Cli BETWEEN " & lcParametro1Desde & " AND " & lcParametro1Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Clientes.Cod_Tip BETWEEN " & lcParametro2Desde & " AND " & lcParametro2Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Clientes.Cod_Cla BETWEEN " & lcParametro3Desde & " AND " & lcParametro3Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Clientes.Cod_Zon BETWEEN " & lcParametro4Desde & " AND " & lcParametro4Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Clientes.Cod_Pai BETWEEN " & lcParametro5Desde & " AND " & lcParametro5Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Cuentas_Cobrar.Cod_Ven BETWEEN " & lcParametro6Desde & " AND " & lcParametro6Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Cuentas_Cobrar.Cod_Mon BETWEEN " & lcParametro7Desde & " AND " & lcParametro7Hasta & "")
            loComandoSeleccionar.AppendLine("					AND ( (" & lcParametro10Desde & "='Igual' AND Cuentas_Cobrar.Cod_Rev BETWEEN " & lcParametro9Desde & " AND " & lcParametro9Hasta & ") OR")
            loComandoSeleccionar.AppendLine("						(" & lcParametro10Desde & "<>'Igual' AND Cuentas_Cobrar.Cod_Rev NOT BETWEEN " & lcParametro9Desde & " AND " & lcParametro9Hasta & ") )")
            loComandoSeleccionar.AppendLine("					AND Cuentas_Cobrar.Cod_Suc BETWEEN " & lcParametro11Desde & " AND " & lcParametro11Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Cuentas_Cobrar.Cod_Tip = 'FACT'")
            loComandoSeleccionar.AppendLine("					AND DATEDIFF(DAY,GETDATE(),Cuentas_Cobrar.Fec_Fin) >= 0 -- Pendientes")
            loComandoSeleccionar.AppendLine("			GROUP BY Clientes.Cod_Cli, Clientes.Nom_Cli")
            loComandoSeleccionar.AppendLine("			ORDER BY SUM(Cuentas_Cobrar.Mon_Net) DESC")
            loComandoSeleccionar.AppendLine("	) AS #tablaCuentas; ")
            loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("--*******************************************************************************************")
            loComandoSeleccionar.AppendLine("-- Clientes con más Cuentas Vencidas (Monto)												*	")
            loComandoSeleccionar.AppendLine("--*******************************************************************************************")
            loComandoSeleccionar.AppendLine("INSERT INTO #tmpTop10Clientes(Seccion, Cod_Cli, Nom_Cli, Cifra1, Cifra2, Cifra3, Cifra4)")
            loComandoSeleccionar.AppendLine("SELECT")
            loComandoSeleccionar.AppendLine("		'07_cuentas_vencidas'				AS Seccion,")
            loComandoSeleccionar.AppendLine("		#tablaCuentas.Cod_Cli				AS Cod_Cli,")
            loComandoSeleccionar.AppendLine("		#tablaCuentas.Nom_Cli				AS Nom_Cli,	")
            loComandoSeleccionar.AppendLine("		#tablaCuentas.Documentos			AS Cifra1,  ")
            loComandoSeleccionar.AppendLine("		#tablaCuentas.Monto_Cuentas			AS Cifra2,  ")
            loComandoSeleccionar.AppendLine("		0									AS Cifra3,  ")
            loComandoSeleccionar.AppendLine("		0									AS Cifra4")
            loComandoSeleccionar.AppendLine("FROM	(	SELECT TOP 10")
            loComandoSeleccionar.AppendLine("					Clientes.Cod_Cli				AS Cod_Cli,")
            loComandoSeleccionar.AppendLine("					Clientes.Nom_Cli				AS Nom_Cli,")
            loComandoSeleccionar.AppendLine("					COUNT(Cuentas_Cobrar.Documento) AS Documentos,")
            loComandoSeleccionar.AppendLine("					SUM(Cuentas_Cobrar.Mon_Net)		AS Monto_Cuentas")
            loComandoSeleccionar.AppendLine("			FROM	Cuentas_Cobrar")
            loComandoSeleccionar.AppendLine("			JOIN Clientes ON Cuentas_Cobrar.Cod_Cli = Clientes.Cod_Cli")
            loComandoSeleccionar.AppendLine("			JOIN func_varcharlist_to_table(" & lcParametro8Desde & ") tablaStatus ON Cuentas_Cobrar.Status = tablaStatus.item")
            loComandoSeleccionar.AppendLine("			WHERE	Cuentas_Cobrar.Status <> 'Anulado'")
            loComandoSeleccionar.AppendLine("					AND Cuentas_Cobrar.Fec_Ini BETWEEN " & lcParametro0Desde & " AND" & lcParametro0Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Cuentas_Cobrar.Cod_Cli BETWEEN " & lcParametro1Desde & " AND " & lcParametro1Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Clientes.Cod_Tip BETWEEN " & lcParametro2Desde & " AND " & lcParametro2Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Clientes.Cod_Cla BETWEEN " & lcParametro3Desde & " AND " & lcParametro3Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Clientes.Cod_Zon BETWEEN " & lcParametro4Desde & " AND " & lcParametro4Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Clientes.Cod_Pai BETWEEN " & lcParametro5Desde & " AND " & lcParametro5Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Cuentas_Cobrar.Cod_Ven BETWEEN " & lcParametro6Desde & " AND " & lcParametro6Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Cuentas_Cobrar.Cod_Mon BETWEEN " & lcParametro7Desde & " AND " & lcParametro7Hasta & "")
            loComandoSeleccionar.AppendLine("					AND ( (" & lcParametro10Desde & "='Igual' AND Cuentas_Cobrar.Cod_Rev BETWEEN " & lcParametro9Desde & " AND " & lcParametro9Hasta & ") OR")
            loComandoSeleccionar.AppendLine("						(" & lcParametro10Desde & "<>'Igual' AND Cuentas_Cobrar.Cod_Rev NOT BETWEEN " & lcParametro9Desde & " AND " & lcParametro9Hasta & ") )")
            loComandoSeleccionar.AppendLine("					AND Cuentas_Cobrar.Cod_Suc BETWEEN " & lcParametro11Desde & " AND " & lcParametro11Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Cuentas_Cobrar.Cod_Tip = 'FACT'")
            loComandoSeleccionar.AppendLine("					AND DATEDIFF(DAY,GETDATE(),Cuentas_Cobrar.Fec_Fin) < 0 -- Vencidas")
            loComandoSeleccionar.AppendLine("			GROUP BY Clientes.Cod_Cli, Clientes.Nom_Cli")
            loComandoSeleccionar.AppendLine("			ORDER BY SUM(Cuentas_Cobrar.Mon_Net) DESC")
            loComandoSeleccionar.AppendLine("	) AS #tablaCuentas; ")
            loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("--*******************************************************************************************")
            loComandoSeleccionar.AppendLine("-- Clientes con más Cuentas Cobros (Monto)												*	")
            loComandoSeleccionar.AppendLine("--*******************************************************************************************")
            loComandoSeleccionar.AppendLine("INSERT INTO #tmpTop10Clientes(Seccion, Cod_Cli, Nom_Cli, Cifra1, Cifra2, Cifra3, Cifra4)")
            loComandoSeleccionar.AppendLine("SELECT")
            loComandoSeleccionar.AppendLine("		'08_cobros'				AS Seccion,")
            loComandoSeleccionar.AppendLine("		#tablaCobros.Cod_Cli				AS Cod_Cli,")
            loComandoSeleccionar.AppendLine("		#tablaCobros.Nom_Cli				AS Nom_Cli,	")
            loComandoSeleccionar.AppendLine("		#tablaCobros.Documentos			AS Cifra1,  ")
            loComandoSeleccionar.AppendLine("		#tablaCobros.Monto_Cobros			AS Cifra2,  ")
            loComandoSeleccionar.AppendLine("		0									AS Cifra3,  ")
            loComandoSeleccionar.AppendLine("		0									AS Cifra4")
            loComandoSeleccionar.AppendLine("FROM	(	SELECT TOP 10")
            loComandoSeleccionar.AppendLine("					Cobros.Cod_Cli			AS Cod_Cli,")
            loComandoSeleccionar.AppendLine("					Clientes.Nom_Cli		AS Nom_Cli,")
            loComandoSeleccionar.AppendLine("					COUNT(Cobros.Documento) AS Documentos,")
            loComandoSeleccionar.AppendLine("					SUM(Cobros.Mon_Net)		AS Monto_Cobros")
            loComandoSeleccionar.AppendLine("			FROM	Cobros")
            loComandoSeleccionar.AppendLine("			JOIN Clientes ON Cobros.Cod_Cli = Clientes.Cod_Cli")
            loComandoSeleccionar.AppendLine("			JOIN func_varcharlist_to_table(" & lcParametro8Desde & ") tablaStatus ON Cobros.Status = tablaStatus.item")
            loComandoSeleccionar.AppendLine("			WHERE	Cobros.Status <> 'Anulado'")
            loComandoSeleccionar.AppendLine("					AND Cobros.Fec_Ini BETWEEN " & lcParametro0Desde & " AND" & lcParametro0Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Cobros.Cod_Cli BETWEEN " & lcParametro1Desde & " AND " & lcParametro1Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Clientes.Cod_Tip BETWEEN " & lcParametro2Desde & " AND " & lcParametro2Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Clientes.Cod_Cla BETWEEN " & lcParametro3Desde & " AND " & lcParametro3Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Clientes.Cod_Zon BETWEEN " & lcParametro4Desde & " AND " & lcParametro4Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Clientes.Cod_Pai BETWEEN " & lcParametro5Desde & " AND " & lcParametro5Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Cobros.Cod_Ven BETWEEN " & lcParametro6Desde & " AND " & lcParametro6Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Cobros.Cod_Mon BETWEEN " & lcParametro7Desde & " AND " & lcParametro7Hasta & "")
            loComandoSeleccionar.AppendLine("					AND ( (" & lcParametro10Desde & "='Igual' AND Cobros.Cod_Rev BETWEEN " & lcParametro9Desde & " AND " & lcParametro9Hasta & ") OR")
            loComandoSeleccionar.AppendLine("						(" & lcParametro10Desde & "<>'Igual' AND Cobros.Cod_Rev NOT BETWEEN " & lcParametro9Desde & " AND " & lcParametro9Hasta & ") )")
            loComandoSeleccionar.AppendLine("					AND Cobros.Cod_Suc BETWEEN " & lcParametro11Desde & " AND " & lcParametro11Hasta & "")
            loComandoSeleccionar.AppendLine("			GROUP BY Cobros.Cod_Cli, Clientes.Nom_Cli")
            loComandoSeleccionar.AppendLine("			ORDER BY COUNT(Cobros.Documento) DESC")
            loComandoSeleccionar.AppendLine("	) AS #tablaCobros; ")
            loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("--*******************************************************************************************")
            loComandoSeleccionar.AppendLine("-- Clientes que Pagan más Rápido (Dias)														*	")
            loComandoSeleccionar.AppendLine("--*******************************************************************************************")
            loComandoSeleccionar.AppendLine("INSERT INTO #tmpTop10Clientes(Seccion, Cod_Cli, Nom_Cli, Cifra1, Cifra2, Cifra3, Cifra4)")
            loComandoSeleccionar.AppendLine("SELECT")
            loComandoSeleccionar.AppendLine("		'09_pagos_rapidos'					AS Seccion,")
            loComandoSeleccionar.AppendLine("		#tablaDiasPagar.Cod_Cli				AS Cod_Cli,")
            loComandoSeleccionar.AppendLine("		#tablaDiasPagar.Nom_Cli				AS Nom_Cli,	")
            loComandoSeleccionar.AppendLine("		#tablaDiasPagar.Dias				AS Cifra1,  ")
            loComandoSeleccionar.AppendLine("		0									AS Cifra2,  ")
            loComandoSeleccionar.AppendLine("		0									AS Cifra3,  ")
            loComandoSeleccionar.AppendLine("		0									AS Cifra4")
            loComandoSeleccionar.AppendLine("FROM	(	SELECT TOP 10")
            loComandoSeleccionar.AppendLine("					Cobros.Cod_Cli											AS 	Cod_Cli,")
            loComandoSeleccionar.AppendLine("					Clientes.Nom_Cli										AS 	Nom_Cli,")
            loComandoSeleccionar.AppendLine("					AVG(DATEDIFF(DAY,Cuentas_Cobrar.Fec_Ini,Cobros.Fec_Ini))AS Dias")
            loComandoSeleccionar.AppendLine("			FROM	Cobros")
            loComandoSeleccionar.AppendLine("			JOIN Clientes ON Cobros.Cod_Cli = Clientes.Cod_Cli")
            loComandoSeleccionar.AppendLine("			JOIN Renglones_Cobros ON Cobros.Documento = Renglones_Cobros.Documento")
            loComandoSeleccionar.AppendLine("			JOIN Cuentas_Cobrar ON (Renglones_Cobros.Doc_Ori = Cuentas_Cobrar.Documento AND Renglones_Cobros.Cod_Tip = Cuentas_Cobrar.Cod_Tip)")
            loComandoSeleccionar.AppendLine("			JOIN func_varcharlist_to_table(" & lcParametro8Desde & ") tablaStatus ON Cobros.Status = tablaStatus.item")
            loComandoSeleccionar.AppendLine("			WHERE	Cobros.Status <> 'Anulado'")
            loComandoSeleccionar.AppendLine("					AND	Cuentas_Cobrar.Status <> 'Anulado'")
            loComandoSeleccionar.AppendLine("					AND Cobros.Fec_Ini BETWEEN " & lcParametro0Desde & " AND" & lcParametro0Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Cobros.Cod_Cli BETWEEN " & lcParametro1Desde & " AND " & lcParametro1Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Clientes.Cod_Tip BETWEEN " & lcParametro2Desde & " AND " & lcParametro2Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Clientes.Cod_Cla BETWEEN " & lcParametro3Desde & " AND " & lcParametro3Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Clientes.Cod_Zon BETWEEN " & lcParametro4Desde & " AND " & lcParametro4Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Clientes.Cod_Pai BETWEEN " & lcParametro5Desde & " AND " & lcParametro5Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Cobros.Cod_Ven BETWEEN " & lcParametro6Desde & " AND " & lcParametro6Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Cobros.Cod_Mon BETWEEN " & lcParametro7Desde & " AND " & lcParametro7Hasta & "")
            loComandoSeleccionar.AppendLine("					AND ( (" & lcParametro10Desde & "='Igual' AND Cobros.Cod_Rev BETWEEN " & lcParametro9Desde & " AND " & lcParametro9Hasta & ") OR")
            loComandoSeleccionar.AppendLine("						(" & lcParametro10Desde & "<>'Igual' AND Cobros.Cod_Rev NOT BETWEEN " & lcParametro9Desde & " AND " & lcParametro9Hasta & ") )")
            loComandoSeleccionar.AppendLine("					AND Cobros.Cod_Suc BETWEEN " & lcParametro11Desde & " AND " & lcParametro11Hasta & "")
            loComandoSeleccionar.AppendLine("			GROUP BY Cobros.Cod_Cli, Clientes.Nom_Cli")
            loComandoSeleccionar.AppendLine("			ORDER BY AVG(DATEDIFF(DAY,Cuentas_Cobrar.Fec_Ini,Cobros.Fec_Ini)) ASC")
            loComandoSeleccionar.AppendLine("	) AS #tablaDiasPagar; ")
            loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("--*******************************************************************************************")
            loComandoSeleccionar.AppendLine("-- Clientes que Tardan más en Pagar (Dias)												*	")
            loComandoSeleccionar.AppendLine("--*******************************************************************************************")
            loComandoSeleccionar.AppendLine("INSERT INTO #tmpTop10Clientes(Seccion, Cod_Cli, Nom_Cli, Cifra1, Cifra2, Cifra3, Cifra4)")
            loComandoSeleccionar.AppendLine("SELECT")
            loComandoSeleccionar.AppendLine("		'10_pagos_lentos'					AS Seccion,")
            loComandoSeleccionar.AppendLine("		#tablaDiasPagar.Cod_Cli				AS Cod_Cli,")
            loComandoSeleccionar.AppendLine("		#tablaDiasPagar.Nom_Cli				AS Nom_Cli,	")
            loComandoSeleccionar.AppendLine("		#tablaDiasPagar.Dias				AS Cifra1,  ")
            loComandoSeleccionar.AppendLine("		0									AS Cifra2,  ")
            loComandoSeleccionar.AppendLine("		0									AS Cifra3,  ")
            loComandoSeleccionar.AppendLine("		0									AS Cifra4")
            loComandoSeleccionar.AppendLine("FROM	(	SELECT TOP 10")
            loComandoSeleccionar.AppendLine("					Cobros.Cod_Cli											AS 	Cod_Cli,")
            loComandoSeleccionar.AppendLine("					Clientes.Nom_Cli										AS 	Nom_Cli,")
            loComandoSeleccionar.AppendLine("					AVG(DATEDIFF(DAY,Cuentas_Cobrar.Fec_Ini,Cobros.Fec_Ini))AS Dias")
            loComandoSeleccionar.AppendLine("			FROM	Cobros")
            loComandoSeleccionar.AppendLine("			JOIN Clientes ON Cobros.Cod_Cli = Clientes.Cod_Cli")
            loComandoSeleccionar.AppendLine("			JOIN Renglones_Cobros ON Cobros.Documento = Renglones_Cobros.Documento")
            loComandoSeleccionar.AppendLine("			JOIN Cuentas_Cobrar ON (Renglones_Cobros.Doc_Ori = Cuentas_Cobrar.Documento AND Renglones_Cobros.Cod_Tip = Cuentas_Cobrar.Cod_Tip)")
            loComandoSeleccionar.AppendLine("			JOIN func_varcharlist_to_table(" & lcParametro8Desde & ") tablaStatus ON Cobros.Status = tablaStatus.item")
            loComandoSeleccionar.AppendLine("			WHERE	Cobros.Status <> 'Anulado'")
            loComandoSeleccionar.AppendLine("					AND	Cuentas_Cobrar.Status <> 'Anulado'")
            loComandoSeleccionar.AppendLine("					AND Cobros.Fec_Ini BETWEEN " & lcParametro0Desde & " AND" & lcParametro0Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Cobros.Cod_Cli BETWEEN " & lcParametro1Desde & " AND " & lcParametro1Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Clientes.Cod_Tip BETWEEN " & lcParametro2Desde & " AND " & lcParametro2Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Clientes.Cod_Cla BETWEEN " & lcParametro3Desde & " AND " & lcParametro3Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Clientes.Cod_Zon BETWEEN " & lcParametro4Desde & " AND " & lcParametro4Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Clientes.Cod_Pai BETWEEN " & lcParametro5Desde & " AND " & lcParametro5Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Cobros.Cod_Ven BETWEEN " & lcParametro6Desde & " AND " & lcParametro6Hasta & "")
            loComandoSeleccionar.AppendLine("					AND Cobros.Cod_Mon BETWEEN " & lcParametro7Desde & " AND " & lcParametro7Hasta & "")
            loComandoSeleccionar.AppendLine("					AND ( (" & lcParametro10Desde & "='Igual' AND Cobros.Cod_Rev BETWEEN " & lcParametro9Desde & " AND " & lcParametro9Hasta & ") OR")
            loComandoSeleccionar.AppendLine("						(" & lcParametro10Desde & "<>'Igual' AND Cobros.Cod_Rev NOT BETWEEN " & lcParametro9Desde & " AND " & lcParametro9Hasta & ") )")
            loComandoSeleccionar.AppendLine("					AND Cobros.Cod_Suc BETWEEN " & lcParametro11Desde & " AND " & lcParametro11Hasta & "")
            loComandoSeleccionar.AppendLine("			GROUP BY Cobros.Cod_Cli, Clientes.Nom_Cli")
            loComandoSeleccionar.AppendLine("			ORDER BY AVG(DATEDIFF(DAY,Cuentas_Cobrar.Fec_Ini,Cobros.Fec_Ini)) DESC")
            loComandoSeleccionar.AppendLine("	) AS #tablaDiasPagar; ")
            loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("SELECT	Seccion,")
            loComandoSeleccionar.AppendLine("		Cod_Cli,")
            loComandoSeleccionar.AppendLine("		Nom_Cli,")
            loComandoSeleccionar.AppendLine("		Cifra1,")
            loComandoSeleccionar.AppendLine("		Cifra2,")
            loComandoSeleccionar.AppendLine("		Cifra3,")
            loComandoSeleccionar.AppendLine("		Cifra4,")
            loComandoSeleccionar.AppendLine("		" & goOpciones.pnDecimalesParaCantidad & " AS NumDecCant")
            loComandoSeleccionar.AppendLine("FROM	#tmpTop10Clientes")
            loComandoSeleccionar.AppendLine("")
            loComandoSeleccionar.AppendLine("DROP TABLE #tmpTop10Clientes")
            loComandoSeleccionar.AppendLine("")
            
			'Me.mEscribirConsulta(loComandoSeleccionar.ToString())
			
            Dim loServicios As New cusDatos.goDatos

            Dim laDatosReporte As DataSet = loServicios.mObtenerTodosSinEsquema(loComandoSeleccionar.ToString, "curReportes", 1800)

            If (laDatosReporte.Tables(0).Rows.Count <= 0) Then
                Me.WbcAdministradorMensajeModal.mMostrarMensajeModal("Información", _
                                          "No se Encontraron Registros para los Parámetros Especificados. ", _
                                           vis3Controles.wbcAdministradorMensajeModal.enumTipoMensaje.KN_Informacion, _
                                           "350px", _
                                           "200px")
            End If

            loObjetoReporte = cusAplicacion.goReportes.mCargarReporte("rTop10_Clientes", laDatosReporte)

            Me.mTraducirReporte(loObjetoReporte)

            Me.mFormatearCamposReporte(loObjetoReporte)

            Me.crvrTop10_Clientes.ReportSource = loObjetoReporte

        Catch loExcepcion As Exception

            Me.WbcAdministradorMensajeModal.mMostrarMensajeModal("Error", _
                          "No se pudo Completar el Proceso: " & loExcepcion.Message & ", StackTrace: " & loExcepcion.StackTrace, _
                           vis3Controles.wbcAdministradorMensajeModal.enumTipoMensaje.KN_Error, _
                           "auto", _
                           "auto")

        End Try

    End Sub

    Protected Sub Page_Unload(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Unload

        Try

            loObjetoReporte.Close()

        Catch loExcepcion As Exception

        End Try

    End Sub

End Class
'-------------------------------------------------------------------------------------------'
' Fin del codigo																			'
'-------------------------------------------------------------------------------------------'
' DLC: 01/07/10: Codigo inicial.															'
'-------------------------------------------------------------------------------------------'
' DLC: 06/07/10: La consulta a la base de datos, se pasó a ejecutar a traves de				'
'                un procedimiento almacenado.												'
'-------------------------------------------------------------------------------------------'
' RJG: 28/08/12: La consulta se sacó del SP (y funciones anidadas). Se optimizó la consulta '
'				 para disminuir el tiempo de ejecución.										'	
'-------------------------------------------------------------------------------------------'
