'-------------------------------------------------------------------------------------------'
' Inicio del codigo
'-------------------------------------------------------------------------------------------'
' Importando librerias 
'-------------------------------------------------------------------------------------------'
Imports System.Data

'-------------------------------------------------------------------------------------------'
' Inicio de clase "rVInventario_Fecha"
'-------------------------------------------------------------------------------------------'
Partial Class rVInventario_Fecha

    Inherits vis2formularios.frmReporte

    Dim loObjetoReporte As CrystalDecisions.CrystalReports.Engine.ReportDocument

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load

        Try

            Dim lcArticuloDesde 	As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(0))
            Dim lcArticuloHasta 	As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(0))
            Dim lcNombreDesde 		As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(1))
            Dim lcNombreHasta 		As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(1))
            Dim lcDepartamentoDesde As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(2))
            Dim lcDepartamentoHasta As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(2))
            Dim lcProveedorDesde 	As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(3))
            Dim lcProveedorHasta 	As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(3))
            Dim ldFecha				As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(4), goServicios.enuOpcionesRedondeo.KN_FechaFinDelDia)
			Dim lcAlmacenDesde		As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(5))
            Dim lcAlmacenHasta		As String
            Dim lcMonedaDesde		As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(6))
            Dim lcMonedaHasta		As String
            Dim lcParametro7Desde	As String = goServicios.mObtenerListaFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(7))
			Dim lcSucursalDesde		As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosIniciales(8))
            Dim lcSucursalHasta		As String = goServicios.mObtenerCampoFormatoSQL(cusAplicacion.goReportes.paParametrosFinales(8))

			Dim lcOrdenamiento As String = cusAplicacion.goReportes.pcOrden
            Dim loComandoSeleccionar As New StringBuilder()
            
           
            'Almacen'
            If lcAlmacenDesde = "''" Then
                lcAlmacenHasta = "'zzzzzzz'"
            Else
                lcAlmacenHasta = lcAlmacenDesde
            End If

            'Moneda'
            If lcMonedaDesde = "''" Then
                lcMonedaHasta = "'zzzzzzz'"
            Else
                lcMonedaHasta = lcMonedaDesde
            End If

            Dim lcCosto As String = ""
            
            Select Case lcParametro7Desde
                Case "'Promedio MP'"
                    lcCosto = "Promedio1"
                Case "'Ultimo MP'"
                    lcCosto = "Ultimo1"
                Case "'Anterior MP'"
                    lcCosto = "Anterior1"
                Case "'Promedio MS'"
                    lcCosto = "Promedio2"
                Case "'Ultimo MS'"
                    lcCosto = "Ultimo2"
                Case "'Anterior MS'"
                    lcCosto = "Anterior2"
            End Select

			Dim lcAlmacenTransito As String = goServicios.mObtenerCampoFormatoSQL(cusAdministrativo.goAlmacen.pcAlmacenTransito)
			
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("DECLARE @lnCero DECIMAL(28,10);")
			loComandoSeleccionar.AppendLine("SET @lnCero = 0;")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("DECLARE @lnDecimalesCostos INT;")
			loComandoSeleccionar.AppendLine("SET @lnDecimalesCostos = 4;")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("SET NOCOUNT ON;")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("-- *****************************************************************")
			loComandoSeleccionar.AppendLine("-- Tabla de artículos filtrados.")
			loComandoSeleccionar.AppendLine("-- *****************************************************************")
			loComandoSeleccionar.AppendLine("CREATE TABLE #tabArticulos(	Cod_Art CHAR(30), ")
			loComandoSeleccionar.AppendLine("							Cos_Pro1 DECIMAL (28, 10), Cos_Ult1 DECIMAL (28, 10), Cos_Ant1 DECIMAL (28, 10), Cos_Cli1 DECIMAL (28, 10),")
			loComandoSeleccionar.AppendLine("							Cos_Pro2 DECIMAL (28, 10), Cos_Ult2 DECIMAL (28, 10), Cos_Ant2 DECIMAL (28, 10), Cos_Cli2 DECIMAL (28, 10),")
			loComandoSeleccionar.AppendLine("							Tipo CHAR(15), Cod_Uni1 CHAR(10) )")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("-- Para acelerar el filtrado de los renglones ")
			loComandoSeleccionar.AppendLine("CREATE CLUSTERED INDEX Articulos_Cod_Art ON #tabArticulos(Cod_Art)")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("INSERT INTO #tabArticulos(	Cod_Art,")
			loComandoSeleccionar.AppendLine("							Cos_Pro1, Cos_Ult1, Cos_Ant1, Cos_Cli1,")
			loComandoSeleccionar.AppendLine("							Cos_Pro2, Cos_Ult2, Cos_Ant2, Cos_Cli2,")
			loComandoSeleccionar.AppendLine("							Tipo, Cod_Uni1)")
			loComandoSeleccionar.AppendLine("SELECT		Articulos.Cod_Art,")
			loComandoSeleccionar.AppendLine("			Articulos.Cos_Pro1,")
			loComandoSeleccionar.AppendLine("			Articulos.Cos_Ult1,")
			loComandoSeleccionar.AppendLine("			Articulos.Cos_Ant1,")
			loComandoSeleccionar.AppendLine("			Articulos.Cos_Cli1,")
			loComandoSeleccionar.AppendLine("			Articulos.Cos_Pro2,")
			loComandoSeleccionar.AppendLine("			Articulos.Cos_Ult2,")
			loComandoSeleccionar.AppendLine("			Articulos.Cos_Ant2,")
			loComandoSeleccionar.AppendLine("			Articulos.Cos_Cli2,")
			loComandoSeleccionar.AppendLine("			Articulos.Tipo,")
			loComandoSeleccionar.AppendLine("			Articulos.Cod_Uni1")
			loComandoSeleccionar.AppendLine("FROM		Articulos")
			loComandoSeleccionar.AppendLine("	WHERE	Tipo <> 'Servicio'")
			loComandoSeleccionar.AppendLine("		AND Cod_Art		BETWEEN " & lcArticuloDesde 	& " AND " & lcArticuloHasta)
			loComandoSeleccionar.AppendLine("		AND Nom_Art		BETWEEN " & lcNombreDesde		& " AND " & lcNombreHasta)
			loComandoSeleccionar.AppendLine("		AND Cod_Dep		BETWEEN " & lcDepartamentoDesde	& " AND " & lcDepartamentoHasta)
			loComandoSeleccionar.AppendLine("		AND Cod_Pro		BETWEEN " & lcProveedorDesde	& " AND " & lcProveedorHasta)
			loComandoSeleccionar.AppendLine("ORDER BY	Articulos.Cod_Art;")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("-- *****************************************************************")
			loComandoSeleccionar.AppendLine("-- Tabla de movimientos filtrados.	")
			loComandoSeleccionar.AppendLine("-- *****************************************************************")
			loComandoSeleccionar.AppendLine("CREATE TABLE #tabMovimientos(	Fecha DATETIME,					Registro DATETIME, ")
			loComandoSeleccionar.AppendLine("								Cod_Art CHAR(30),				Tipo CHAR(15),					Can_Art1 DECIMAL(28, 10),")
			loComandoSeleccionar.AppendLine("								Cos_Ult1 DECIMAL (28, 10), 		Cos_Pro1 DECIMAL (28, 10),		Cos_Ant1 DECIMAL (28, 10),")
			loComandoSeleccionar.AppendLine("								Cos_Ult2 DECIMAL (28, 10), 		Cos_Pro2 DECIMAL (28, 10),		Cos_Ant2 DECIMAL (28, 10),")
			loComandoSeleccionar.AppendLine("								Clase CHAR(30),					Por_Des_Ren DECIMAL (28, 10),	Por_Des_Doc DECIMAL (28, 10),")
			loComandoSeleccionar.AppendLine("								Mon_Des_Doc DECIMAL (28, 10),	Por_Rec_Doc DECIMAL (28, 10),	Mon_Rec_Doc DECIMAL (28, 10),")
			loComandoSeleccionar.AppendLine("								Mon_Bru_Doc DECIMAL (28, 10),	Mon_Otr1 DECIMAL (28, 10),		Mon_Otr2 DECIMAL (28, 10),")
			loComandoSeleccionar.AppendLine("								Mon_Otr3 DECIMAL (28, 10),		Posicion INT,					Revisado BIT);")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("WITH tmpMovimientos AS (")
			loComandoSeleccionar.AppendLine("		SELECT		")
			loComandoSeleccionar.AppendLine("					Compras.fec_ini						AS fecha,")
			loComandoSeleccionar.AppendLine("					Compras.registro					AS registro,")
			loComandoSeleccionar.AppendLine("					Renglones_Compras.cod_art			AS cod_art,")
			loComandoSeleccionar.AppendLine("					'Entrada'							AS tipo,")
			loComandoSeleccionar.AppendLine("					Renglones_Compras.can_art1			AS can_art1,")
			loComandoSeleccionar.AppendLine("					Renglones_Compras.precio1			AS cos_ult1,")
			loComandoSeleccionar.AppendLine("					Renglones_Compras.cos_pro1			AS cos_pro1,")
			loComandoSeleccionar.AppendLine("					Renglones_Compras.cos_ult1			AS cos_ant1,")
			loComandoSeleccionar.AppendLine("					Renglones_Compras.precio2			AS cos_ult2,")
			loComandoSeleccionar.AppendLine("					Renglones_Compras.cos_pro2	 		AS cos_pro2,")
			loComandoSeleccionar.AppendLine("					Renglones_Compras.cos_ult2			AS cos_ant2,")
			loComandoSeleccionar.AppendLine("					'COMPRAS'							AS Clase,")
			loComandoSeleccionar.AppendLine("					Renglones_Compras.por_des			AS Por_Des_Ren,")
			loComandoSeleccionar.AppendLine("					Compras.Por_Des1					AS Por_Des_Doc,")
			loComandoSeleccionar.AppendLine("					Compras.Mon_Des1					AS Mon_Des_Doc,")
			loComandoSeleccionar.AppendLine("					Compras.Por_Rec1					AS Por_Rec_Doc,")
			loComandoSeleccionar.AppendLine("					Compras.Mon_Rec1					AS Mon_Rec_Doc,")
			loComandoSeleccionar.AppendLine("					Compras.Mon_Bru						AS Mon_Bru_Doc,")
			loComandoSeleccionar.AppendLine("					Compras.Mon_Otr1					AS Mon_Otr1,")
			loComandoSeleccionar.AppendLine("					Compras.Mon_Otr2					AS Mon_Otr2,")
			loComandoSeleccionar.AppendLine("					Compras.Mon_Otr3					AS Mon_Otr3")
			loComandoSeleccionar.AppendLine("		FROM		Compras")
			loComandoSeleccionar.AppendLine("			JOIN	Renglones_Compras")
			loComandoSeleccionar.AppendLine("				ON	Renglones_Compras.documento = Compras.documento")
			loComandoSeleccionar.AppendLine("				AND	Compras.status IN ('Confirmado', 'Afectado', 'Procesado')")
			loComandoSeleccionar.AppendLine("				AND	Compras.fec_ini <= " & ldFecha)
			loComandoSeleccionar.AppendLine("				AND Renglones_Compras.Cod_Art	BETWEEN " & lcArticuloDesde	 & " AND " & lcArticuloHasta)	 
			loComandoSeleccionar.AppendLine("				AND Renglones_Compras.Cod_Alm	BETWEEN " & lcAlmacenDesde	 & " AND " & lcAlmacenHasta)
			loComandoSeleccionar.AppendLine("				AND Compras.Cod_Mon				BETWEEN " & lcMonedaDesde	 & " AND " & lcMonedaHasta)
			loComandoSeleccionar.AppendLine("				AND Compras.Cod_Suc				BETWEEN " & lcSucursalDesde	 & " AND " & lcSucursalHasta)
			loComandoSeleccionar.AppendLine("			")
			loComandoSeleccionar.AppendLine("	UNION ALL")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("		SELECT		")
			loComandoSeleccionar.AppendLine("					Recepciones.fec_ini	 				AS fecha,")
			loComandoSeleccionar.AppendLine("					Recepciones.registro				AS registro,")
			loComandoSeleccionar.AppendLine("					Renglones_Recepciones.cod_art		AS cod_art,")
			loComandoSeleccionar.AppendLine("					'Entrada'							AS tipo,")
			loComandoSeleccionar.AppendLine("					Renglones_Recepciones.can_art1		AS can_art1,")
			loComandoSeleccionar.AppendLine("					Renglones_Recepciones.precio1		AS cos_ult1,")
			loComandoSeleccionar.AppendLine("					Renglones_Recepciones.cos_pro1		AS cos_pro1,")
			loComandoSeleccionar.AppendLine("					Renglones_Recepciones.cos_ult1		AS cos_ant1,")
			loComandoSeleccionar.AppendLine("					Renglones_Recepciones.precio2		AS cos_ult2,")
			loComandoSeleccionar.AppendLine("					Renglones_Recepciones.cos_pro2	 	AS cos_pro2,")
			loComandoSeleccionar.AppendLine("					Renglones_Recepciones.cos_ult2		AS cos_ant2,")
			loComandoSeleccionar.AppendLine("					'RECEPCIONES'						AS Clase,")
			loComandoSeleccionar.AppendLine("					Renglones_Recepciones.por_des		AS Por_Des_Ren,")
			loComandoSeleccionar.AppendLine("					Recepciones.Por_Des1				AS Por_Des_Doc,")
			loComandoSeleccionar.AppendLine("					Recepciones.Mon_Des1				AS Mon_Des_Doc,")
			loComandoSeleccionar.AppendLine("					Recepciones.Por_Rec1				AS Por_Rec_Doc,")
			loComandoSeleccionar.AppendLine("					Recepciones.Mon_Rec1				AS Mon_Rec_Doc,")
			loComandoSeleccionar.AppendLine("					Recepciones.Mon_Bru					AS Mon_Bru_Doc,")
			loComandoSeleccionar.AppendLine("					Recepciones.Mon_Otr1				AS Mon_Otr1,")
			loComandoSeleccionar.AppendLine("					Recepciones.Mon_Otr2				AS Mon_Otr2,")
			loComandoSeleccionar.AppendLine("					Recepciones.Mon_Otr3				AS Mon_Otr3")
			loComandoSeleccionar.AppendLine("		FROM		Recepciones, Renglones_Recepciones")
			loComandoSeleccionar.AppendLine("		WHERE		Renglones_Recepciones.documento = Recepciones.documento")
			loComandoSeleccionar.AppendLine("				AND	Recepciones.status IN ('Confirmado', 'Afectado', 'Procesado')")
			loComandoSeleccionar.AppendLine("				AND	Recepciones.fec_ini <= " & ldFecha)	
			loComandoSeleccionar.AppendLine("				AND NOT EXISTS (SELECT		1  ")
			loComandoSeleccionar.AppendLine("								FROM		Renglones_Compras ")
			loComandoSeleccionar.AppendLine("									JOIN Compras ON Renglones_Compras.Documento = Compras.Documento	 ")
			loComandoSeleccionar.AppendLine("										AND Compras.status IN ('Confirmado', 'Afectado', 'Procesado')")
			loComandoSeleccionar.AppendLine("										AND Compras.fec_ini <= " & ldFecha)
			loComandoSeleccionar.AppendLine("								WHERE	Renglones_Compras.Doc_Ori = Renglones_Recepciones.documento  ")
			loComandoSeleccionar.AppendLine("									AND	Renglones_Compras.Ren_Ori = Renglones_Recepciones.Renglon ")
			loComandoSeleccionar.AppendLine("					)")
			loComandoSeleccionar.AppendLine("				")
			loComandoSeleccionar.AppendLine("				")
			'loComandoSeleccionar.AppendLine("				AND (Renglones_Recepciones.documento + '/' + CAST(Renglones_Recepciones.Renglon AS CHAR(10))) NOT IN")
			'loComandoSeleccionar.AppendLine("					(	SELECT (Renglones_Compras.Doc_Ori + '/' + CAST(Renglones_Compras.Ren_Ori AS CHAR(10))) AS origen")
			'loComandoSeleccionar.AppendLine("						FROM	Renglones_Compras")
			'loComandoSeleccionar.AppendLine("							JOIN Compras ON Renglones_Compras.Documento = Compras.Documento")   
			'loComandoSeleccionar.AppendLine("								AND Renglones_Compras.Tip_Ori = 'Recepciones'")
			'loComandoSeleccionar.AppendLine("								AND Compras.status IN ('Confirmado', 'Afectado', 'Procesado')")
			'loComandoSeleccionar.AppendLine("								AND Compras.fec_ini <= " & ldFecha)
			'loComandoSeleccionar.AppendLine("					)")
			loComandoSeleccionar.AppendLine("				AND Renglones_Recepciones.Cod_Art	BETWEEN " & lcArticuloDesde	 & " AND " & lcArticuloHasta) 
			loComandoSeleccionar.AppendLine("				AND Renglones_Recepciones.Cod_Alm	BETWEEN " & lcAlmacenDesde	 & " AND " & lcAlmacenHasta) 
			loComandoSeleccionar.AppendLine("				AND Recepciones.Cod_Mon				BETWEEN " & lcMonedaDesde	 & " AND " & lcMonedaHasta)
			loComandoSeleccionar.AppendLine("				AND Recepciones.Cod_Suc				BETWEEN " & lcSucursalDesde	 & " AND " & lcSucursalHasta)
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("	UNION ALL		")
			loComandoSeleccionar.AppendLine("					")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("		SELECT		")
			loComandoSeleccionar.AppendLine("					Facturas.fec_ini					AS fecha,	")
			loComandoSeleccionar.AppendLine("					Facturas.registro					AS registro,	")
			loComandoSeleccionar.AppendLine("					Renglones_Facturas.cod_art			AS cod_art,	")
			loComandoSeleccionar.AppendLine("					'Salida'							AS tipo,	")
			loComandoSeleccionar.AppendLine("					Renglones_Facturas.can_art1			AS can_art1,	")
			loComandoSeleccionar.AppendLine("					@lnCero								AS cos_ult1,	")
			loComandoSeleccionar.AppendLine("					@lnCero								AS cos_pro1,	")
			loComandoSeleccionar.AppendLine("					@lnCero								AS cos_ant1,	")
			loComandoSeleccionar.AppendLine("					@lnCero								AS cos_ult2,	")
			loComandoSeleccionar.AppendLine("					@lnCero	 							AS cos_pro2,	")
			loComandoSeleccionar.AppendLine("					@lnCero								AS cos_ant2,	")
			loComandoSeleccionar.AppendLine("					'VENTAS'							AS Clase,	")
			loComandoSeleccionar.AppendLine("					@lnCero								AS Por_Des_Ren,	")
			loComandoSeleccionar.AppendLine("					@lnCero								AS Por_Des_Doc,	")
			loComandoSeleccionar.AppendLine("					@lnCero								AS Mon_Des_Doc,	")
			loComandoSeleccionar.AppendLine("					@lnCero								AS Por_Rec_Doc,	")
			loComandoSeleccionar.AppendLine("					@lnCero								AS Mon_Rec_Doc,	")
			loComandoSeleccionar.AppendLine("					@lnCero	 							AS Mon_Bru_Doc,	")
			loComandoSeleccionar.AppendLine("					@lnCero								AS Mon_Otr1,	")
			loComandoSeleccionar.AppendLine("					@lnCero								AS Mon_Otr2,	")
			loComandoSeleccionar.AppendLine("					@lnCero	 							AS Mon_Otr3	")
			loComandoSeleccionar.AppendLine("		FROM		Facturas	")
			loComandoSeleccionar.AppendLine("			JOIN	Renglones_Facturas")
			loComandoSeleccionar.AppendLine("				ON	Renglones_Facturas.documento = Facturas.documento	")
			loComandoSeleccionar.AppendLine("				AND	Facturas.status IN ('Confirmado', 'Afectado', 'Procesado')	")
			loComandoSeleccionar.AppendLine("				AND	Facturas.fec_ini <= " & ldFecha)
			loComandoSeleccionar.AppendLine("				AND Renglones_Facturas.Cod_Art		BETWEEN " & lcArticuloDesde	 & " AND " & lcArticuloHasta)
			loComandoSeleccionar.AppendLine("				AND Renglones_Facturas.Cod_Alm		BETWEEN " & lcAlmacenDesde	 & " AND " & lcAlmacenHasta)
			loComandoSeleccionar.AppendLine("				AND Facturas.Cod_Mon				BETWEEN " & lcMonedaDesde	 & " AND " & lcMonedaHasta)
			loComandoSeleccionar.AppendLine("				AND Facturas.Cod_Suc				BETWEEN " & lcSucursalDesde	 & " AND " & lcSucursalHasta)
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("	UNION ALL		")
			loComandoSeleccionar.AppendLine("					")
			loComandoSeleccionar.AppendLine("		SELECT		")
			loComandoSeleccionar.AppendLine("					Entregas.fec_ini	 			AS fecha,	")
			loComandoSeleccionar.AppendLine("					Entregas.registro				AS registro,	")
			loComandoSeleccionar.AppendLine("					Renglones_Entregas.cod_art		AS cod_art,	")
			loComandoSeleccionar.AppendLine("					'Salida'						AS tipo,	")
			loComandoSeleccionar.AppendLine("					Renglones_Entregas.can_art1		AS can_art1,	")
			loComandoSeleccionar.AppendLine("					@lnCero							AS cos_ult1,	")
			loComandoSeleccionar.AppendLine("					@lnCero							AS cos_pro1,	")
			loComandoSeleccionar.AppendLine("					@lnCero							AS cos_ant1,	")
			loComandoSeleccionar.AppendLine("					@lnCero							AS cos_ult2,	")
			loComandoSeleccionar.AppendLine("					@lnCero	 						AS cos_pro2,	")
			loComandoSeleccionar.AppendLine("					@lnCero							AS cos_ant2,	")
			loComandoSeleccionar.AppendLine("					'VENTAS'						AS Clase,	")
			loComandoSeleccionar.AppendLine("					@lnCero							AS Por_Des_Ren,	")
			loComandoSeleccionar.AppendLine("					@lnCero							AS Por_Des_Doc,	")
			loComandoSeleccionar.AppendLine("					@lnCero							AS Mon_Des_Doc,	")
			loComandoSeleccionar.AppendLine("					@lnCero							AS Por_Rec_Doc,	")
			loComandoSeleccionar.AppendLine("					@lnCero							AS Mon_Rec_Doc,	")
			loComandoSeleccionar.AppendLine("					@lnCero	 						AS Mon_Bru_Doc,	")
			loComandoSeleccionar.AppendLine("					@lnCero							AS Mon_Otr1,	")
			loComandoSeleccionar.AppendLine("					@lnCero							AS Mon_Otr2,	")
			loComandoSeleccionar.AppendLine("					@lnCero	 						AS Mon_Otr3	")
			loComandoSeleccionar.AppendLine("		FROM		Entregas, Renglones_Entregas	")
			loComandoSeleccionar.AppendLine("		WHERE		Renglones_Entregas.documento = Entregas.documento	")
			loComandoSeleccionar.AppendLine("				AND	Entregas.status IN ('Confirmado', 'Afectado', 'Procesado')	")
			loComandoSeleccionar.AppendLine("				AND	Entregas.fec_ini <= " & ldFecha)  
			loComandoSeleccionar.AppendLine("				AND NOT EXISTS (SELECT		1  ")
			loComandoSeleccionar.AppendLine("								FROM		Renglones_Facturas ")
			loComandoSeleccionar.AppendLine("									JOIN Facturas ON Renglones_Facturas.Documento = Facturas.Documento	 ")
			loComandoSeleccionar.AppendLine("										AND Facturas.status IN ('Confirmado', 'Afectado', 'Procesado')")
			loComandoSeleccionar.AppendLine("										AND Facturas.fec_ini <= " & ldFecha)
			loComandoSeleccionar.AppendLine("								WHERE	Renglones_Facturas.Doc_Ori = Renglones_Entregas.documento  ")
			loComandoSeleccionar.AppendLine("									AND	Renglones_Facturas.Ren_Ori = Renglones_Entregas.Renglon ")
			loComandoSeleccionar.AppendLine("					)")
			loComandoSeleccionar.AppendLine("				AND Renglones_Entregas.Cod_Art		BETWEEN " & lcArticuloDesde	 & " AND " & lcArticuloHasta) 
			loComandoSeleccionar.AppendLine("				AND Renglones_Entregas.Cod_Alm		BETWEEN " & lcAlmacenDesde	 & " AND " & lcAlmacenHasta) 
			loComandoSeleccionar.AppendLine("				AND Entregas.Cod_Mon				BETWEEN " & lcMonedaDesde	 & " AND " & lcMonedaHasta)
			loComandoSeleccionar.AppendLine("				AND Entregas.Cod_Suc				BETWEEN " & lcSucursalDesde	 & " AND " & lcSucursalHasta)
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("	UNION ALL		")
			loComandoSeleccionar.AppendLine("					")
			loComandoSeleccionar.AppendLine("		SELECT		")
			loComandoSeleccionar.AppendLine("					Ajustes.fec_ini						AS fecha,")
			loComandoSeleccionar.AppendLine("					Ajustes.registro					AS registro,")
			loComandoSeleccionar.AppendLine("					Renglones_Ajustes.cod_art			AS cod_art,")
			loComandoSeleccionar.AppendLine("					Tipos_Ajustes.tipo					AS tipo,")
			loComandoSeleccionar.AppendLine("					Renglones_Ajustes.can_art1			AS can_art1,")
			loComandoSeleccionar.AppendLine("					Renglones_Ajustes.cos_ult1			AS cos_ult1,")
			loComandoSeleccionar.AppendLine("					Renglones_Ajustes.cos_pro1			AS cos_pro1,")
			loComandoSeleccionar.AppendLine("					Renglones_Ajustes.cos_ant1			AS cos_ant1,")
			loComandoSeleccionar.AppendLine("					Renglones_Ajustes.cos_ult2			AS cos_ult2,")
			loComandoSeleccionar.AppendLine("					Renglones_Ajustes.cos_pro2		 	AS cos_pro2,")
			loComandoSeleccionar.AppendLine("					Renglones_Ajustes.cos_ant2			AS cos_ant2,")
			loComandoSeleccionar.AppendLine("					'AJUSTES'							AS Clase,")
			loComandoSeleccionar.AppendLine("					@lnCero								AS Por_Des_Ren,")
			loComandoSeleccionar.AppendLine("					@lnCero								AS Por_Des_Doc,")
			loComandoSeleccionar.AppendLine("					@lnCero								AS Mon_Des_Doc,")
			loComandoSeleccionar.AppendLine("					@lnCero								AS Por_Rec_Doc,")
			loComandoSeleccionar.AppendLine("					@lnCero	 							AS Mon_Rec_Doc,")
			loComandoSeleccionar.AppendLine("					@lnCero								AS Mon_Bru_Doc,")
			loComandoSeleccionar.AppendLine("					@lnCero								AS Mon_Otr1,")
			loComandoSeleccionar.AppendLine("					@lnCero	 							AS Mon_Otr2,")
			loComandoSeleccionar.AppendLine("					@lnCero								AS Mon_Otr3")
			loComandoSeleccionar.AppendLine("		FROM		Ajustes, Renglones_Ajustes, Tipos_Ajustes")
			loComandoSeleccionar.AppendLine("		WHERE		Renglones_Ajustes.documento = Ajustes.documento")
			loComandoSeleccionar.AppendLine("				AND	Renglones_Ajustes.cod_tip = Tipos_Ajustes.cod_tip ")
			loComandoSeleccionar.AppendLine("				AND	Tipos_Ajustes.tipo != 'Salida'")
			loComandoSeleccionar.AppendLine("				AND	Ajustes.status = 'Confirmado'")
			loComandoSeleccionar.AppendLine("				AND	Ajustes.fec_ini <= " & ldFecha)
			loComandoSeleccionar.AppendLine("				AND Renglones_Ajustes.Cod_Art		BETWEEN " & lcArticuloDesde	 & " AND " & lcArticuloHasta)	 
			loComandoSeleccionar.AppendLine("				AND Renglones_Ajustes.Cod_Alm		BETWEEN " & lcAlmacenDesde	 & " AND " & lcAlmacenHasta) 
			loComandoSeleccionar.AppendLine("				AND Ajustes.Cod_Mon					BETWEEN " & lcMonedaDesde	 & " AND " & lcMonedaHasta)
			loComandoSeleccionar.AppendLine("				AND Ajustes.Cod_Suc					BETWEEN " & lcSucursalDesde	 & " AND " & lcSucursalHasta)
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("	UNION ALL")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("		SELECT		")
			loComandoSeleccionar.AppendLine("					Ajustes.fec_ini						AS fecha,")
			loComandoSeleccionar.AppendLine("					Ajustes.registro					AS registro,")
			loComandoSeleccionar.AppendLine("					Renglones_Ajustes.cod_art			AS cod_art,")
			loComandoSeleccionar.AppendLine("					Tipos_Ajustes.tipo					AS tipo,")
			loComandoSeleccionar.AppendLine("					Renglones_Ajustes.can_art1			AS can_art1,")
			loComandoSeleccionar.AppendLine("					@lnCero								AS cos_ult1,")
			loComandoSeleccionar.AppendLine("					@lnCero								AS cos_pro1,")
			loComandoSeleccionar.AppendLine("					@lnCero								AS cos_ant1,")
			loComandoSeleccionar.AppendLine("					@lnCero	 							AS cos_ult2,")
			loComandoSeleccionar.AppendLine("					@lnCero								AS cos_pro2,")
			loComandoSeleccionar.AppendLine("					@lnCero								AS cos_ant2,")
			loComandoSeleccionar.AppendLine("					'VENTAS'							AS Clase,")
			loComandoSeleccionar.AppendLine("					@lnCero								AS Por_Des_Ren,")
			loComandoSeleccionar.AppendLine("					@lnCero								AS Por_Des_Doc,")
			loComandoSeleccionar.AppendLine("					@lnCero								AS Mon_Des_Doc,")
			loComandoSeleccionar.AppendLine("					@lnCero								AS Por_Rec_Doc,")
			loComandoSeleccionar.AppendLine("					@lnCero	 							AS Mon_Rec_Doc,")
			loComandoSeleccionar.AppendLine("					@lnCero								AS Mon_Bru_Doc,")
			loComandoSeleccionar.AppendLine("					@lnCero								AS Mon_Otr1,")
			loComandoSeleccionar.AppendLine("					@lnCero	 							AS Mon_Otr2,")
			loComandoSeleccionar.AppendLine("					@lnCero								AS Mon_Otr3")
			loComandoSeleccionar.AppendLine("		FROM		Ajustes, Renglones_Ajustes, Tipos_Ajustes")
			loComandoSeleccionar.AppendLine("		WHERE		Renglones_Ajustes.documento = Ajustes.documento")
			loComandoSeleccionar.AppendLine("				AND	Renglones_Ajustes.cod_tip = Tipos_Ajustes.cod_tip ")
			loComandoSeleccionar.AppendLine("				AND	Tipos_Ajustes.tipo = 'Salida'")
			loComandoSeleccionar.AppendLine("				AND	Ajustes.status = 'Confirmado'")
			loComandoSeleccionar.AppendLine("				AND	Ajustes.fec_ini <= " & ldFecha)
			loComandoSeleccionar.AppendLine("				AND Renglones_Ajustes.Cod_Art		BETWEEN " & lcArticuloDesde	 & " AND " & lcArticuloHasta) 
			loComandoSeleccionar.AppendLine("				AND Renglones_Ajustes.Cod_Alm		BETWEEN " & lcAlmacenDesde	 & " AND " & lcAlmacenHasta) 
			loComandoSeleccionar.AppendLine("				AND Ajustes.Cod_Mon					BETWEEN " & lcMonedaDesde	 & " AND " & lcMonedaHasta)
			loComandoSeleccionar.AppendLine("				AND Ajustes.Cod_Suc					BETWEEN " & lcSucursalDesde	 & " AND " & lcSucursalHasta)
			loComandoSeleccionar.AppendLine("				")
			loComandoSeleccionar.AppendLine("	UNION ALL")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("		SELECT		Traslados.fec_ini					AS fecha,")
			loComandoSeleccionar.AppendLine("					Traslados.registro					AS registro,")
			loComandoSeleccionar.AppendLine("					Renglones_Traslados.cod_art			AS cod_art,")
			loComandoSeleccionar.AppendLine("					'Salida'							AS tipo,")
			loComandoSeleccionar.AppendLine("					Renglones_Traslados.can_art1		AS can_art1,")
			loComandoSeleccionar.AppendLine("					Renglones_Traslados.cos_ult1		AS cos_ult1,")
			loComandoSeleccionar.AppendLine("					Renglones_Traslados.cos_pro1		AS cos_pro1,")
			loComandoSeleccionar.AppendLine("					Renglones_Traslados.cos_ant1		AS cos_ant1,")
			loComandoSeleccionar.AppendLine("					Renglones_Traslados.cos_ult2		AS cos_ult2,")
			loComandoSeleccionar.AppendLine("					Renglones_Traslados.cos_pro2		AS cos_pro2,")
			loComandoSeleccionar.AppendLine("					Renglones_Traslados.cos_ant2		AS cos_ant2,")
			loComandoSeleccionar.AppendLine("					'TRASLADOS'							AS Clase,")
			loComandoSeleccionar.AppendLine("					@lnCero								AS Por_Des_Ren,")
			loComandoSeleccionar.AppendLine("					@lnCero								AS Por_Des_Doc,")
			loComandoSeleccionar.AppendLine("					@lnCero								AS Mon_Des_Doc,")
			loComandoSeleccionar.AppendLine("					@lnCero								AS Por_Rec_Doc,")
			loComandoSeleccionar.AppendLine("					@lnCero	 							AS Mon_Rec_Doc,")
			loComandoSeleccionar.AppendLine("					@lnCero								AS Mon_Bru_Doc,")
			loComandoSeleccionar.AppendLine("					@lnCero								AS Mon_Otr1,")
			loComandoSeleccionar.AppendLine("					@lnCero	 							AS Mon_Otr2,")
			loComandoSeleccionar.AppendLine("					@lnCero								AS Mon_Otr3")
			loComandoSeleccionar.AppendLine("		FROM		Traslados, Renglones_Traslados")
			loComandoSeleccionar.AppendLine("		WHERE		Renglones_Traslados.documento = Traslados.documento")
			loComandoSeleccionar.AppendLine("				AND	Traslados.status IN ('Confirmado', 'Procesado')")
			loComandoSeleccionar.AppendLine("				AND	Traslados.fec_ini <= " & ldFecha)
			loComandoSeleccionar.AppendLine("				AND Renglones_Traslados.Cod_Art		BETWEEN " & lcArticuloDesde	 & " AND " & lcArticuloHasta) 
			loComandoSeleccionar.AppendLine("				AND Traslados.Alm_Ori				BETWEEN " & lcAlmacenDesde	 & " AND " & lcAlmacenHasta) 
			loComandoSeleccionar.AppendLine("				AND Traslados.Cod_Mon				BETWEEN " & lcMonedaDesde	 & " AND " & lcMonedaHasta)
			loComandoSeleccionar.AppendLine("				AND Traslados.Cod_Suc				BETWEEN " & lcSucursalDesde	 & " AND " & lcSucursalHasta)
			loComandoSeleccionar.AppendLine("				")
			loComandoSeleccionar.AppendLine("	UNION ALL	")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("		SELECT		Traslados.fec_ini					AS fecha,")
			loComandoSeleccionar.AppendLine("					Traslados.registro					AS registro,")
			loComandoSeleccionar.AppendLine("					Renglones_Traslados.cod_art			AS cod_art,")
			loComandoSeleccionar.AppendLine("					'Entrada'							AS tipo,")
			loComandoSeleccionar.AppendLine("					Renglones_Traslados.can_art1		AS can_art1,")
			loComandoSeleccionar.AppendLine("					Renglones_Traslados.cos_ult1		AS cos_ult1,")
			loComandoSeleccionar.AppendLine("					Renglones_Traslados.cos_pro1		AS cos_pro1,")
			loComandoSeleccionar.AppendLine("					Renglones_Traslados.cos_ant1		AS cos_ant1,")
			loComandoSeleccionar.AppendLine("					Renglones_Traslados.cos_ult2		AS cos_ult2,")
			loComandoSeleccionar.AppendLine("					Renglones_Traslados.cos_pro2		AS cos_pro2,")
			loComandoSeleccionar.AppendLine("					Renglones_Traslados.cos_ant2		AS cos_ant2,")
			loComandoSeleccionar.AppendLine("					'TRASLADOS'							AS Clase,")
			loComandoSeleccionar.AppendLine("					@lnCero								AS Por_Des_Ren,")
			loComandoSeleccionar.AppendLine("					@lnCero								AS Por_Des_Doc,")
			loComandoSeleccionar.AppendLine("					@lnCero								AS Mon_Des_Doc,")
			loComandoSeleccionar.AppendLine("					@lnCero								AS Por_Rec_Doc,")
			loComandoSeleccionar.AppendLine("					@lnCero	 							AS Mon_Rec_Doc,")
			loComandoSeleccionar.AppendLine("					@lnCero								AS Mon_Bru_Doc,")
			loComandoSeleccionar.AppendLine("					@lnCero								AS Mon_Otr1,")
			loComandoSeleccionar.AppendLine("					@lnCero	 							AS Mon_Otr2,")
			loComandoSeleccionar.AppendLine("					@lnCero								AS Mon_Otr3")
			loComandoSeleccionar.AppendLine("		FROM		Traslados, Renglones_Traslados")
			loComandoSeleccionar.AppendLine("		WHERE		Renglones_Traslados.documento = Traslados.documento")
			loComandoSeleccionar.AppendLine("				AND	Traslados.status = 'Confirmado'")
			loComandoSeleccionar.AppendLine("				AND	Traslados.fec_ini <= " & ldFecha)
			loComandoSeleccionar.AppendLine("				AND Renglones_Traslados.Cod_Art		BETWEEN " & lcArticuloDesde	 & " AND " & lcArticuloHasta) 
			loComandoSeleccionar.AppendLine("				AND " & lcAlmacenTransito &  "				BETWEEN " & lcAlmacenDesde	 & " AND " & lcAlmacenHasta) 
			loComandoSeleccionar.AppendLine("				AND Traslados.Cod_Mon				BETWEEN " & lcMonedaDesde	 & " AND " & lcMonedaHasta)
			loComandoSeleccionar.AppendLine("				AND Traslados.Cod_Suc				BETWEEN " & lcSucursalDesde	 & " AND " & lcSucursalHasta)
			loComandoSeleccionar.AppendLine("				")
			loComandoSeleccionar.AppendLine("	UNION ALL	")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("		SELECT		Traslados.fec_ini					AS fecha,")
			loComandoSeleccionar.AppendLine("					Traslados.registro					AS registro,")
			loComandoSeleccionar.AppendLine("					Renglones_Traslados.cod_art			AS cod_art,")
			loComandoSeleccionar.AppendLine("					'Entrada'							AS tipo,")
			loComandoSeleccionar.AppendLine("					Renglones_Traslados.can_art1		AS can_art1,")
			loComandoSeleccionar.AppendLine("					Renglones_Traslados.cos_ult1		AS cos_ult1,")
			loComandoSeleccionar.AppendLine("					Renglones_Traslados.cos_pro1		AS cos_pro1,")
			loComandoSeleccionar.AppendLine("					Renglones_Traslados.cos_ant1		AS cos_ant1,")
			loComandoSeleccionar.AppendLine("					Renglones_Traslados.cos_ult2		AS cos_ult2,")
			loComandoSeleccionar.AppendLine("					Renglones_Traslados.cos_pro2		AS cos_pro2,")
			loComandoSeleccionar.AppendLine("					Renglones_Traslados.cos_ant2		AS cos_ant2,")
			loComandoSeleccionar.AppendLine("					'TRASLADOS'							AS Clase,")
			loComandoSeleccionar.AppendLine("					@lnCero								AS Por_Des_Ren,")
			loComandoSeleccionar.AppendLine("					@lnCero								AS Por_Des_Doc,")
			loComandoSeleccionar.AppendLine("					@lnCero								AS Mon_Des_Doc,")
			loComandoSeleccionar.AppendLine("					@lnCero								AS Por_Rec_Doc,")
			loComandoSeleccionar.AppendLine("					@lnCero	 							AS Mon_Rec_Doc,")
			loComandoSeleccionar.AppendLine("					@lnCero								AS Mon_Bru_Doc,")
			loComandoSeleccionar.AppendLine("					@lnCero								AS Mon_Otr1,")
			loComandoSeleccionar.AppendLine("					@lnCero	 							AS Mon_Otr2,")
			loComandoSeleccionar.AppendLine("					@lnCero								AS Mon_Otr3")
			loComandoSeleccionar.AppendLine("		FROM		Traslados, Renglones_Traslados")
			loComandoSeleccionar.AppendLine("		WHERE		Renglones_Traslados.documento = Traslados.documento")
			loComandoSeleccionar.AppendLine("				AND	Traslados.status = 'Procesado'")
			loComandoSeleccionar.AppendLine("				AND	Traslados.fec_ini <= " & ldFecha)
			loComandoSeleccionar.AppendLine("				AND Renglones_Traslados.Cod_Art		BETWEEN " & lcArticuloDesde	 & " AND " & lcArticuloHasta) 
			loComandoSeleccionar.AppendLine("				AND Traslados.Alm_Des				BETWEEN " & lcAlmacenDesde	 & " AND " & lcAlmacenHasta) 
			loComandoSeleccionar.AppendLine("				AND Traslados.Cod_Mon				BETWEEN " & lcMonedaDesde	 & " AND " & lcMonedaHasta)
			loComandoSeleccionar.AppendLine("				AND Traslados.Cod_Suc				BETWEEN " & lcSucursalDesde	 & " AND " & lcSucursalHasta)
			loComandoSeleccionar.AppendLine("				")
			loComandoSeleccionar.AppendLine("	UNION ALL	")
			loComandoSeleccionar.AppendLine("				")
			loComandoSeleccionar.AppendLine("		SELECT		")
			loComandoSeleccionar.AppendLine("					Devoluciones_Clientes.fec_ini		AS fecha,")
			loComandoSeleccionar.AppendLine("					Devoluciones_Clientes.registro		AS registro,")
			loComandoSeleccionar.AppendLine("					Renglones_dClientes.cod_art			AS cod_art,")
			loComandoSeleccionar.AppendLine("					'Entrada'							AS tipo,")
			loComandoSeleccionar.AppendLine("					Renglones_dClientes.can_art1		AS can_art1,")
			loComandoSeleccionar.AppendLine("					Renglones_dClientes.cos_ult1		AS cos_ult1,")
			loComandoSeleccionar.AppendLine("					Renglones_dClientes.cos_pro1		AS cos_pro1,")
			loComandoSeleccionar.AppendLine("					Renglones_dClientes.cos_ant1		AS cos_ant1,")
			loComandoSeleccionar.AppendLine("					Renglones_dClientes.cos_ult2		AS cos_ult2,")
			loComandoSeleccionar.AppendLine("					Renglones_dClientes.cos_pro2		AS cos_pro2,")
			loComandoSeleccionar.AppendLine("					Renglones_dClientes.cos_ant2		AS cos_ant2,")
			loComandoSeleccionar.AppendLine("					'DEVOLUCIONESCLIENTES'				AS Clase,")
			loComandoSeleccionar.AppendLine("					Renglones_dClientes.por_des			AS Por_Des_Ren,")
			loComandoSeleccionar.AppendLine("					Devoluciones_Clientes.Por_Des1		AS Por_Des_Doc,")
			loComandoSeleccionar.AppendLine("					Devoluciones_Clientes.Mon_Des1		AS Mon_Des_Doc,")
			loComandoSeleccionar.AppendLine("					Devoluciones_Clientes.Por_Rec1		AS Por_Rec_Doc,")
			loComandoSeleccionar.AppendLine("					Devoluciones_Clientes.Mon_Rec1		AS Mon_Rec_Doc,")
			loComandoSeleccionar.AppendLine("					Devoluciones_Clientes.Mon_Bru		AS Mon_Bru_Doc,")
			loComandoSeleccionar.AppendLine("					Devoluciones_Clientes.Mon_Otr1		AS Mon_Otr1,")
			loComandoSeleccionar.AppendLine("					Devoluciones_Clientes.Mon_Otr2		AS Mon_Otr2,")
			loComandoSeleccionar.AppendLine("					Devoluciones_Clientes.Mon_Otr3		AS Mon_Otr3")
			loComandoSeleccionar.AppendLine("		FROM		Devoluciones_Clientes, Renglones_dClientes")
			loComandoSeleccionar.AppendLine("		WHERE		Renglones_dClientes.documento = Devoluciones_Clientes.documento")
			loComandoSeleccionar.AppendLine("				AND	Devoluciones_Clientes.status IN ('Confirmado', 'Afectado', 'Procesado')")
			loComandoSeleccionar.AppendLine("				AND	Devoluciones_Clientes.fec_ini <= " & ldFecha)
			loComandoSeleccionar.AppendLine("				AND Renglones_dClientes.Cod_Art		BETWEEN " & lcArticuloDesde	 & " AND " & lcArticuloHasta)
			loComandoSeleccionar.AppendLine("				AND Renglones_dClientes.Cod_Alm		BETWEEN " & lcAlmacenDesde	 & " AND " & lcAlmacenHasta)
			loComandoSeleccionar.AppendLine("				AND Devoluciones_Clientes.Cod_Mon	BETWEEN " & lcMonedaDesde	 & " AND " & lcMonedaHasta)
			loComandoSeleccionar.AppendLine("				AND Devoluciones_Clientes.Cod_Suc	BETWEEN " & lcSucursalDesde	 & " AND " & lcSucursalHasta)
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("	UNION ALL")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("		SELECT		")
			loComandoSeleccionar.AppendLine("					Devoluciones_Proveedores.fec_ini		AS fecha,")
			loComandoSeleccionar.AppendLine("					Devoluciones_Proveedores.registro		AS registro,")
			loComandoSeleccionar.AppendLine("					Renglones_dProveedores.cod_art			AS cod_art,")
			loComandoSeleccionar.AppendLine("					'Salida'								AS tipo,")
			loComandoSeleccionar.AppendLine("					Renglones_dProveedores.can_art1			AS can_art1,")
			loComandoSeleccionar.AppendLine("					@lnCero									AS cos_ult1,")
			loComandoSeleccionar.AppendLine("					@lnCero									AS cos_pro1,")
			loComandoSeleccionar.AppendLine("					@lnCero									AS cos_ant1,")
			loComandoSeleccionar.AppendLine("					@lnCero	 								AS cos_ult2,")
			loComandoSeleccionar.AppendLine("					@lnCero									AS cos_pro2,")
			loComandoSeleccionar.AppendLine("					@lnCero									AS cos_ant2,")
			loComandoSeleccionar.AppendLine("					'VENTAS'								AS Clase,")
			loComandoSeleccionar.AppendLine("					@lnCero									AS Por_Des_Ren,")
			loComandoSeleccionar.AppendLine("					@lnCero									AS Por_Des_Doc,")
			loComandoSeleccionar.AppendLine("					@lnCero									AS Mon_Des_Doc,")
			loComandoSeleccionar.AppendLine("					@lnCero									AS Por_Rec_Doc,")
			loComandoSeleccionar.AppendLine("					@lnCero	 								AS Mon_Rec_Doc,")
			loComandoSeleccionar.AppendLine("					@lnCero									AS Mon_Bru_Doc,")
			loComandoSeleccionar.AppendLine("					@lnCero									AS Mon_Otr1,")
			loComandoSeleccionar.AppendLine("					@lnCero	 								AS Mon_Otr2,")
			loComandoSeleccionar.AppendLine("					@lnCero									AS Mon_Otr3")
			loComandoSeleccionar.AppendLine("		FROM		Devoluciones_Proveedores, Renglones_dProveedores")
			loComandoSeleccionar.AppendLine("		WHERE		Renglones_dProveedores.documento = Devoluciones_Proveedores.documento")
			loComandoSeleccionar.AppendLine("				AND	Devoluciones_Proveedores.status IN ('Confirmado', 'Afectado', 'Procesado')")
			loComandoSeleccionar.AppendLine("				AND	Devoluciones_Proveedores.fec_ini <= " & ldFecha)
			loComandoSeleccionar.AppendLine("				AND Renglones_dProveedores.Cod_Art		BETWEEN " & lcArticuloDesde	 & " AND " & lcArticuloHasta) 
			loComandoSeleccionar.AppendLine("				AND Renglones_dProveedores.Cod_Alm		BETWEEN " & lcAlmacenDesde	 & " AND " & lcAlmacenHasta) 
			loComandoSeleccionar.AppendLine("				AND Devoluciones_Proveedores.Cod_Mon	BETWEEN " & lcMonedaDesde	 & " AND " & lcMonedaHasta)
			loComandoSeleccionar.AppendLine("				AND Devoluciones_Proveedores.Cod_Suc	BETWEEN " & lcSucursalDesde	 & " AND " & lcSucursalHasta)
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine(")")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("INSERT INTO  #tabMovimientos(	Fecha, Registro, ")
			loComandoSeleccionar.AppendLine("								Cod_Art, Tipo, Can_Art1,")
			loComandoSeleccionar.AppendLine("								Cos_Ult1, Cos_Pro1, Cos_Ant1,")
			loComandoSeleccionar.AppendLine("								Cos_Ult2, Cos_Pro2, Cos_Ant2,")
			loComandoSeleccionar.AppendLine("								Clase, Por_Des_Ren, Por_Des_Doc, Mon_Des_Doc,")
			loComandoSeleccionar.AppendLine("								Por_Rec_Doc, Mon_Rec_Doc, Mon_Bru_Doc,")
			loComandoSeleccionar.AppendLine("								Mon_Otr1, Mon_Otr2, Mon_Otr3,")
			loComandoSeleccionar.AppendLine("								Posicion)")
			loComandoSeleccionar.AppendLine("	SELECT		'19000101 00:00:00.000' AS fecha,		'19000101 00:00:00.000' AS registro, ")
			loComandoSeleccionar.AppendLine("				Cod_Art		AS cod_art,		'Entrada'	AS tipo,		@lnCero		AS can_art1, ")
			loComandoSeleccionar.AppendLine("				cos_ult1	AS cos_ult1,	cos_pro1 	AS cos_pro1,	cos_ant1	AS cos_ant1,")
			loComandoSeleccionar.AppendLine("				cos_ult2	AS cos_ult2,	cos_pro2 	AS cos_pro2,	cos_ant2	AS cos_ant2,")
			loComandoSeleccionar.AppendLine("				'CREACION'	AS Clase,		@lnCero 	AS Por_Des_Ren,	@lnCero		AS Por_Des_Doc, @lnCero AS Mon_Des_Doc,")
			loComandoSeleccionar.AppendLine("				@lnCero 	AS Por_Rec_Doc,	@lnCero 	AS Mon_Rec_Doc,	@lnCero		AS Mon_Bru_Doc,")
			loComandoSeleccionar.AppendLine("				@lnCero 	AS Mon_Otr1,	@lnCero 	AS Mon_Otr2,	@lnCero		AS Mon_Otr3,")
			loComandoSeleccionar.AppendLine("				CAST(0 AS INT) AS Posicion")
			loComandoSeleccionar.AppendLine("	FROM		Articulos ")
			loComandoSeleccionar.AppendLine("	WHERE		Cod_Art COLLATE DATABASE_DEFAULT IN (SELECT Cod_Art COLLATE DATABASE_DEFAULT FROM #tabArticulos) ")
			loComandoSeleccionar.AppendLine("UNION ALL")
			loComandoSeleccionar.AppendLine("	SELECT		fecha,			registro, ")
			loComandoSeleccionar.AppendLine("				cod_art,		tipo,			SUM(can_art1) AS can_art1, ")
			loComandoSeleccionar.AppendLine("				cos_ult1, 		cos_pro1,		cos_ant1,")
			loComandoSeleccionar.AppendLine("				cos_ult2, 		cos_pro2,		cos_ant2,")
			loComandoSeleccionar.AppendLine("				Clase,			Por_Des_Ren,	Por_Des_Doc, Mon_Des_Doc, ")
			loComandoSeleccionar.AppendLine("				Por_Rec_Doc, Mon_Rec_Doc, 		Mon_Bru_Doc,")
			loComandoSeleccionar.AppendLine("				Mon_Otr1,		Mon_Otr2, 		Mon_Otr3,")
			loComandoSeleccionar.AppendLine("				CAST(0 AS INT) AS Posicion")
			loComandoSeleccionar.AppendLine("	FROM		tmpMovimientos")
			loComandoSeleccionar.AppendLine("	WHERE		Cod_Art COLLATE DATABASE_DEFAULT IN (SELECT Cod_Art COLLATE DATABASE_DEFAULT FROM #tabArticulos)")
			loComandoSeleccionar.AppendLine("	GROUP BY	fecha, registro, ")
			loComandoSeleccionar.AppendLine("				cod_art, tipo, ")
			loComandoSeleccionar.AppendLine("				cos_ult1, cos_pro1, cos_ant1,")
			loComandoSeleccionar.AppendLine("				cos_ult2, cos_pro2, cos_ant2,")
			loComandoSeleccionar.AppendLine("				Clase, Por_Des_Ren, Por_Des_Doc, Mon_Des_Doc,")
			loComandoSeleccionar.AppendLine("				Por_Rec_Doc, Mon_Rec_Doc, Mon_Bru_Doc,")
			loComandoSeleccionar.AppendLine("				Mon_Otr1, Mon_Otr2, Mon_Otr3")
			loComandoSeleccionar.AppendLine("	ORDER BY	cod_art, fecha, registro")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("-- Ajusta los costos: ajuste por Descuentos y Recargos en entradas ")
			loComandoSeleccionar.AppendLine("UPDATE	#tabMovimientos ")
			loComandoSeleccionar.AppendLine("SET	Cos_Ult1 = ROUND(Cos_Ult1*(100 - Por_Des_Ren)*(100 + Por_Rec_Doc - Por_Des_Doc)/10000, @lnDecimalesCostos),")
			loComandoSeleccionar.AppendLine("		Cos_Ult2 = ROUND(Cos_Ult2*(100 - Por_Des_Ren)*(100 + Por_Rec_Doc - Por_Des_Doc)/10000, @lnDecimalesCostos)")
			loComandoSeleccionar.AppendLine("WHERE	Clase IN ('COMPRAS', 'RECEPCIONES', 'DEVOLUCIONESCLIENTES')")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("-- Ajusta los costos: ajuste por Otros Montos en entradas ")
			loComandoSeleccionar.AppendLine("UPDATE	#tabMovimientos ")
			loComandoSeleccionar.AppendLine("SET	Cos_Ult1 = ROUND(Cos_Ult1 + Cos_Ult1*(Mon_Otr1+Mon_Otr2+Mon_Otr3)/(Mon_Bru_Doc + Mon_Rec_Doc-Mon_Des_Doc), @lnDecimalesCostos),")
			loComandoSeleccionar.AppendLine("		Cos_Ult2 = ROUND(Cos_Ult2 + Cos_Ult2*(Mon_Otr1+Mon_Otr2+Mon_Otr3)/(Mon_Bru_Doc + Mon_Rec_Doc-Mon_Des_Doc), @lnDecimalesCostos)")
			loComandoSeleccionar.AppendLine("WHERE	Clase IN ('COMPRAS', 'RECEPCIONES', 'DEVOLUCIONESCLIENTES')")
			loComandoSeleccionar.AppendLine("	AND (Mon_Bru_Doc + Mon_Rec_Doc-Mon_Des_Doc) <> 0")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("-- Enumera las filas de la tabla temporal de movimientos ")
			loComandoSeleccionar.AppendLine("UPDATE	#tabMovimientos ")
			loComandoSeleccionar.AppendLine("SET		Posicion = NumeroFila")
			loComandoSeleccionar.AppendLine("FROM	(	SELECT	ROW_NUMBER() OVER (ORDER BY Cod_Art, Fecha, Registro, CASE WHEN Tipo = 'Entrada' THEN 0 ELSE 1 END) AS NumeroFila,")
			loComandoSeleccionar.AppendLine("					Cod_Art, Fecha, Registro, Tipo")
			loComandoSeleccionar.AppendLine("			FROM #tabMovimientos")
			loComandoSeleccionar.AppendLine("		) AS Posiciones")
			loComandoSeleccionar.AppendLine("WHERE		#tabMovimientos.Cod_Art		= Posiciones.Cod_Art")
			loComandoSeleccionar.AppendLine("		AND #tabMovimientos.Fecha		= Posiciones.Fecha")
			loComandoSeleccionar.AppendLine("		AND #tabMovimientos.Registro	= Posiciones.Registro")
			loComandoSeleccionar.AppendLine("		AND #tabMovimientos.Tipo		= Posiciones.Tipo")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("-- Para acelerar las búsquedas dentro del WHILE ")
			loComandoSeleccionar.AppendLine("CREATE CLUSTERED INDEX tabMovimientos_Posicion_PX ON #tabMovimientos(Posicion)")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("-- ***************************************************************************")
			loComandoSeleccionar.AppendLine("--	Generación del tabulador de costos ***************************************")
			loComandoSeleccionar.AppendLine("-- ***************************************************************************")
			loComandoSeleccionar.AppendLine("CREATE TABLE #tabCostos(")
			loComandoSeleccionar.AppendLine("			Fecha			DATETIME,")
			loComandoSeleccionar.AppendLine("			Articulo		CHAR(30),")
			loComandoSeleccionar.AppendLine("			Tipo			CHAR(10),")
			loComandoSeleccionar.AppendLine("			Cantidad		DECIMAL(28,10),")
			loComandoSeleccionar.AppendLine("			Ultimo1			DECIMAL(28,10),")
			loComandoSeleccionar.AppendLine("			Promedio1		DECIMAL(28,10),")
			loComandoSeleccionar.AppendLine("			Anterior1		DECIMAL(28,10),")
			loComandoSeleccionar.AppendLine("			Ultimo2			DECIMAL(28,10),")
			loComandoSeleccionar.AppendLine("			Promedio2		DECIMAL(28,10),")
			loComandoSeleccionar.AppendLine("			Anterior2		DECIMAL(28,10),")
			loComandoSeleccionar.AppendLine("			Fec_Pro			DATETIME,")
			loComandoSeleccionar.AppendLine("			Fec_Ult			DATETIME,")
			loComandoSeleccionar.AppendLine("			Fec_Ant			DATETIME,")
			loComandoSeleccionar.AppendLine("			Clase			CHAR(30),")
			loComandoSeleccionar.AppendLine("			Contador		INT IDENTITY(1, 1) ")
			loComandoSeleccionar.AppendLine("	)")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("-- Para acelerar la lectura y actualización del tabulador")
			loComandoSeleccionar.AppendLine("CREATE NONCLUSTERED INDEX tabCostos_Articulo_PK ON #tabCostos(Articulo)")
			loComandoSeleccionar.AppendLine("CREATE CLUSTERED INDEX tabCostos_Fecha_PX ON #tabCostos(Articulo,Fecha)")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("DECLARE @Fecha	 			DATETIME")
			loComandoSeleccionar.AppendLine("DECLARE @Registro			DATETIME")
			loComandoSeleccionar.AppendLine("DECLARE @Articulo			CHAR(30)")
			loComandoSeleccionar.AppendLine("DECLARE @Tipo				CHAR(10)")
			loComandoSeleccionar.AppendLine("DECLARE @Cantidad			DECIMAL(28,10)")
			loComandoSeleccionar.AppendLine("DECLARE @Ultimo1			DECIMAL(28,10)")
			loComandoSeleccionar.AppendLine("DECLARE @Promedio1			DECIMAL(28,10)")
			loComandoSeleccionar.AppendLine("DECLARE @Anterior1			DECIMAL(28,10)")
			loComandoSeleccionar.AppendLine("DECLARE @Ultimo2			DECIMAL(28,10)")
			loComandoSeleccionar.AppendLine("DECLARE @Promedio2			DECIMAL(28,10)")
			loComandoSeleccionar.AppendLine("DECLARE @Anterior2			DECIMAL(28,10)")
			loComandoSeleccionar.AppendLine("DECLARE @Clase				CHAR(30)")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("DECLARE @ExistenciaActual		DECIMAL(28,10)")
			loComandoSeleccionar.AppendLine("DECLARE @Promedio1Actual		DECIMAL(28,10)")
			loComandoSeleccionar.AppendLine("DECLARE @Promedio2Actual		DECIMAL(28,10)")
			loComandoSeleccionar.AppendLine("DECLARE @Ultimo1Actual 		DECIMAL(28,10)")
			loComandoSeleccionar.AppendLine("DECLARE @Ultimo2Actual 		DECIMAL(28,10)")
			loComandoSeleccionar.AppendLine("DECLARE @Anterior1Actual		DECIMAL(28,10)")
			loComandoSeleccionar.AppendLine("DECLARE @Anterior2Actual		DECIMAL(28,10)")
			loComandoSeleccionar.AppendLine("DECLARE @Fec_ProActual			DATETIME")
			loComandoSeleccionar.AppendLine("DECLARE @Fec_UltActual			DATETIME")
			loComandoSeleccionar.AppendLine("DECLARE @Fec_AntActual			DATETIME")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("DECLARE @lnContador INT;")
			loComandoSeleccionar.AppendLine("DECLARE @lnMaximo INT;")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("SET @lnContador = 1;")
			loComandoSeleccionar.AppendLine("SET @lnMaximo = (SELECT COUNT(*) FROM #tabMovimientos);")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("WHILE (@lnContador<=@lnMaximo)")
			loComandoSeleccionar.AppendLine("BEGIN")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("		-- Registro activo:")
			loComandoSeleccionar.AppendLine("		SELECT	@Fecha		= Fecha, ")
			loComandoSeleccionar.AppendLine("				@Registro	= Registro, ")
			loComandoSeleccionar.AppendLine("				@Articulo	= Cod_Art, ")
			loComandoSeleccionar.AppendLine("				@Tipo		= Tipo, ")
			loComandoSeleccionar.AppendLine("				@Cantidad	= Can_Art1, ")
			loComandoSeleccionar.AppendLine("				@Ultimo1	= Cos_Ult1, ")
			loComandoSeleccionar.AppendLine("				@Promedio1	= Cos_Pro1, ")
			loComandoSeleccionar.AppendLine("				@Anterior1	= Cos_Ant1,")
			loComandoSeleccionar.AppendLine("				@Ultimo2	= Cos_Ult2, ")
			loComandoSeleccionar.AppendLine("				@Promedio2	= Cos_Pro2, ")
			loComandoSeleccionar.AppendLine("				@Anterior2	= Cos_Ant2, ")
			loComandoSeleccionar.AppendLine("				@Clase		= Clase")
			loComandoSeleccionar.AppendLine("		FROM (	SELECT	TOP 1 Fecha, registro, ")
			loComandoSeleccionar.AppendLine("						Cod_Art, Tipo, Can_Art1, ")
			loComandoSeleccionar.AppendLine("						Cos_Ult1, Cos_Pro1, Cos_Ant1,")
			loComandoSeleccionar.AppendLine("						Cos_Ult2, Cos_Pro2, Cos_Ant2, Clase")
			loComandoSeleccionar.AppendLine("				FROM	#tabMovimientos ")
			loComandoSeleccionar.AppendLine("				WHERE	Posicion = @lnContador) AS Movimientos;")
			loComandoSeleccionar.AppendLine("		")
			loComandoSeleccionar.AppendLine("		")
			loComandoSeleccionar.AppendLine("		-- Existencias:")
			loComandoSeleccionar.AppendLine("		SET @ExistenciaActual	= @lnCero;")
			loComandoSeleccionar.AppendLine("		SET @Promedio1Actual	= @lnCero;")
			loComandoSeleccionar.AppendLine("		SET @Promedio2Actual	= @lnCero;")
			loComandoSeleccionar.AppendLine("		SET @Ultimo1Actual		= @lnCero;")
			loComandoSeleccionar.AppendLine("		SET @Ultimo2Actual		= @lnCero;")
			loComandoSeleccionar.AppendLine("		SET @Anterior1Actual	= @lnCero;")
			loComandoSeleccionar.AppendLine("		SET @Anterior2Actual	= @lnCero;")
			loComandoSeleccionar.AppendLine("		")
			loComandoSeleccionar.AppendLine("		")
			loComandoSeleccionar.AppendLine("		")
			loComandoSeleccionar.AppendLine("		SELECT	TOP 1 ")
			loComandoSeleccionar.AppendLine("				@ExistenciaActual	= Cantidad,")
			loComandoSeleccionar.AppendLine("				@Promedio1Actual	= Promedio1,")
			loComandoSeleccionar.AppendLine("				@Promedio2Actual	= Promedio2,")
			loComandoSeleccionar.AppendLine("				@Ultimo1Actual		= Ultimo1,")
			loComandoSeleccionar.AppendLine("				@Ultimo2Actual		= Ultimo2,")
			loComandoSeleccionar.AppendLine("				@Anterior1Actual	= Anterior1,")
			loComandoSeleccionar.AppendLine("				@Anterior2Actual	= Anterior2,")
			loComandoSeleccionar.AppendLine("				@Fec_ProActual		= Fec_Pro,")
			loComandoSeleccionar.AppendLine("				@Fec_UltActual		= Fec_Ult,")
			loComandoSeleccionar.AppendLine("				@Fec_AntActual		= Fec_Ant")
			loComandoSeleccionar.AppendLine("		FROM	#tabCostos")
			loComandoSeleccionar.AppendLine("		WHERE	(Articulo = @Articulo)")
			loComandoSeleccionar.AppendLine("		ORDER BY Fecha DESC, ")
			loComandoSeleccionar.AppendLine("				(CASE WHEN Clase = 'TRASLADOS' ")	
			loComandoSeleccionar.AppendLine("					THEN (CASE WHEN Tipo = 'Entrada' THEN -Cantidad ELSE Cantidad END)")
			loComandoSeleccionar.AppendLine("					ELSE (CASE WHEN Tipo = 'Entrada' THEN Cantidad ELSE -Cantidad END)")
			loComandoSeleccionar.AppendLine("				END) DESC;")
			loComandoSeleccionar.AppendLine("		")
			loComandoSeleccionar.AppendLine("		")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("		IF (@Tipo = 'Entrada')")
			loComandoSeleccionar.AppendLine("			BEGIN	")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("					INSERT	")
			loComandoSeleccionar.AppendLine("					INTO	#tabCostos")
			loComandoSeleccionar.AppendLine("						(Fecha, Articulo, Tipo, Cantidad, Ultimo1, Promedio1, Anterior1, Ultimo2, Promedio2, Anterior2, Fec_Pro, Fec_Ult, Fec_Ant, Clase)")
			loComandoSeleccionar.AppendLine("					VALUES	(	@Fecha,")
			loComandoSeleccionar.AppendLine("								@Articulo,")
			loComandoSeleccionar.AppendLine("								@Tipo,")
			loComandoSeleccionar.AppendLine("								@ExistenciaActual + @Cantidad,")
			loComandoSeleccionar.AppendLine("								@Ultimo1,")
			loComandoSeleccionar.AppendLine("								CASE	WHEN (@ExistenciaActual < @lnCero OR @ExistenciaActual + @Cantidad <= @lnCero) THEN")
			loComandoSeleccionar.AppendLine("											@Ultimo1")
			loComandoSeleccionar.AppendLine("										ELSE ")
			loComandoSeleccionar.AppendLine("											ROUND(")
			loComandoSeleccionar.AppendLine("												(	  ROUND(@Promedio1Actual * @ExistenciaActual, @lnDecimalesCostos)")
			loComandoSeleccionar.AppendLine("													+ ROUND(@Ultimo1 * @Cantidad, @lnDecimalesCostos)")
			loComandoSeleccionar.AppendLine("												)/(@ExistenciaActual + @Cantidad)")
			loComandoSeleccionar.AppendLine("											, @lnDecimalesCostos)")
			loComandoSeleccionar.AppendLine("											")
			loComandoSeleccionar.AppendLine("										END,")
			loComandoSeleccionar.AppendLine("								@Anterior1,")
			loComandoSeleccionar.AppendLine("								@Ultimo2,")
			loComandoSeleccionar.AppendLine("								CASE	WHEN (@ExistenciaActual < @lnCero OR @ExistenciaActual + @Cantidad <= @lnCero) THEN ")
			loComandoSeleccionar.AppendLine("											@Ultimo2")
			loComandoSeleccionar.AppendLine("										ELSE ")
			loComandoSeleccionar.AppendLine("											ROUND(")
			loComandoSeleccionar.AppendLine("												(	  ROUND(@Promedio2Actual * @ExistenciaActual, @lnDecimalesCostos)")
			loComandoSeleccionar.AppendLine("													+ ROUND(@Ultimo2 * @Cantidad, @lnDecimalesCostos)")
			loComandoSeleccionar.AppendLine("												)/(@ExistenciaActual + @Cantidad)")
			loComandoSeleccionar.AppendLine("											, @lnDecimalesCostos)")
			loComandoSeleccionar.AppendLine("										END, ")
			loComandoSeleccionar.AppendLine("								@Anterior2,")
			loComandoSeleccionar.AppendLine("								@Fecha,")
			loComandoSeleccionar.AppendLine("								@Fecha,")
			loComandoSeleccionar.AppendLine("								@Fecha,")
			loComandoSeleccionar.AppendLine("								@Clase")
			loComandoSeleccionar.AppendLine("							)")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("			END")
			loComandoSeleccionar.AppendLine("					")
			loComandoSeleccionar.AppendLine("		ELSE IF (@Tipo = 'Salida')")
			loComandoSeleccionar.AppendLine("			BEGIN")
			loComandoSeleccionar.AppendLine("					")
			loComandoSeleccionar.AppendLine("					INSERT")
			loComandoSeleccionar.AppendLine("					INTO	#tabCostos")
			loComandoSeleccionar.AppendLine("						(Fecha, Articulo, Tipo, Cantidad, Ultimo1, Promedio1, Anterior1, Ultimo2, Promedio2, Anterior2, Fec_Pro, Fec_Ult, Fec_Ant, Clase)")
			loComandoSeleccionar.AppendLine("					VALUES	(	@Fecha,")
			loComandoSeleccionar.AppendLine("								@Articulo,")
			loComandoSeleccionar.AppendLine("								@Tipo,")
			loComandoSeleccionar.AppendLine("								@ExistenciaActual - @Cantidad,")
			loComandoSeleccionar.AppendLine("								@Ultimo1Actual,")
			loComandoSeleccionar.AppendLine("								@Promedio1Actual,")
			loComandoSeleccionar.AppendLine("								@Anterior1Actual,")
			loComandoSeleccionar.AppendLine("								@Ultimo2Actual,")
			loComandoSeleccionar.AppendLine("								@Promedio2Actual,")
			loComandoSeleccionar.AppendLine("								@Anterior2Actual,")
			loComandoSeleccionar.AppendLine("								@Fec_ProActual,")
			loComandoSeleccionar.AppendLine("								@Fec_UltActual,")
			loComandoSeleccionar.AppendLine("								@Fec_AntActual,")
			loComandoSeleccionar.AppendLine("								@Clase")
			loComandoSeleccionar.AppendLine("								")
			loComandoSeleccionar.AppendLine("							)")
			loComandoSeleccionar.AppendLine("			")
			loComandoSeleccionar.AppendLine("			END")
			loComandoSeleccionar.AppendLine("			")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("		ELSE IF (@Tipo = 'Cos_Ult1')")
			loComandoSeleccionar.AppendLine("			BEGIN")
			loComandoSeleccionar.AppendLine("					INSERT	")
			loComandoSeleccionar.AppendLine("					INTO	#tabCostos   ")
			loComandoSeleccionar.AppendLine("						(Fecha, Articulo, Tipo, Cantidad, Ultimo1, Promedio1, Anterior1, Ultimo2, Promedio2, Anterior2, Fec_Pro, Fec_Ult, Fec_Ant, Clase)")
			loComandoSeleccionar.AppendLine("					VALUES (	@Fecha, ")
			loComandoSeleccionar.AppendLine("								@Articulo,")
			loComandoSeleccionar.AppendLine("								@Tipo,")
			loComandoSeleccionar.AppendLine("								@ExistenciaActual,")
			loComandoSeleccionar.AppendLine("								@Ultimo1,")
			loComandoSeleccionar.AppendLine("								@Promedio1Actual,")
			loComandoSeleccionar.AppendLine("								@Anterior1Actual,")
			loComandoSeleccionar.AppendLine("								@Ultimo2Actual,")
			loComandoSeleccionar.AppendLine("								@Promedio2Actual,")
			loComandoSeleccionar.AppendLine("								@Anterior2Actual,")
			loComandoSeleccionar.AppendLine("								@Fec_ProActual,")
			loComandoSeleccionar.AppendLine("								@Fecha,")
			loComandoSeleccionar.AppendLine("								@Fec_AntActual,")
			loComandoSeleccionar.AppendLine("								@Clase")
			loComandoSeleccionar.AppendLine("						)")
			loComandoSeleccionar.AppendLine("	")
			loComandoSeleccionar.AppendLine("			END")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("		ELSE IF (@Tipo = 'Cos_Ult2')")
			loComandoSeleccionar.AppendLine("			BEGIN	")
			loComandoSeleccionar.AppendLine("					INSERT	")
			loComandoSeleccionar.AppendLine("					INTO	#tabCostos")
			loComandoSeleccionar.AppendLine("						(Fecha, Articulo, Tipo, Cantidad, Ultimo1, Promedio1, Anterior1, Ultimo2, Promedio2, Anterior2, Fec_Pro, Fec_Ult, Fec_Ant, Clase)")
			loComandoSeleccionar.AppendLine("					VALUES (	@Fecha, ")
			loComandoSeleccionar.AppendLine("								@Articulo,")
			loComandoSeleccionar.AppendLine("								@Tipo,")
			loComandoSeleccionar.AppendLine("								@ExistenciaActual,")
			loComandoSeleccionar.AppendLine("								@Ultimo1Actual,")
			loComandoSeleccionar.AppendLine("								@Promedio1Actual,")
			loComandoSeleccionar.AppendLine("								@Anterior1Actual,")
			loComandoSeleccionar.AppendLine("								@Ultimo2,")
			loComandoSeleccionar.AppendLine("								@Promedio2Actual,")
			loComandoSeleccionar.AppendLine("								@Anterior2Actual,")
			loComandoSeleccionar.AppendLine("								@Fec_ProActual,")
			loComandoSeleccionar.AppendLine("								@Fecha,")
			loComandoSeleccionar.AppendLine("								@Fec_AntActual,")
			loComandoSeleccionar.AppendLine("								@Clase")
			loComandoSeleccionar.AppendLine("						)")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("			END")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("		ELSE IF (@Tipo = 'Cos_Pro1')")
			loComandoSeleccionar.AppendLine("			BEGIN	")
			loComandoSeleccionar.AppendLine("					INSERT	")
			loComandoSeleccionar.AppendLine("					INTO	#tabCostos")
			loComandoSeleccionar.AppendLine("						(Fecha, Articulo, Tipo, Cantidad, Ultimo1, Promedio1, Anterior1, Ultimo2, Promedio2, Anterior2, Fec_Pro, Fec_Ult, Fec_Ant, Clase)")
			loComandoSeleccionar.AppendLine("					VALUES (	@Fecha,")
			loComandoSeleccionar.AppendLine("								@Articulo,")
			loComandoSeleccionar.AppendLine("								@Tipo,")
			loComandoSeleccionar.AppendLine("								@ExistenciaActual,")
			loComandoSeleccionar.AppendLine("								@Ultimo1Actual,")
			loComandoSeleccionar.AppendLine("								@Promedio1,")
			loComandoSeleccionar.AppendLine("								@Anterior1Actual,")
			loComandoSeleccionar.AppendLine("								@Ultimo2Actual,")
			loComandoSeleccionar.AppendLine("								@Promedio2Actual,")
			loComandoSeleccionar.AppendLine("								@Anterior2Actual,")
			loComandoSeleccionar.AppendLine("								@Fecha,")
			loComandoSeleccionar.AppendLine("								@Fec_UltActual,")
			loComandoSeleccionar.AppendLine("								@Fec_AntActual,")
			loComandoSeleccionar.AppendLine("								@Clase")
			loComandoSeleccionar.AppendLine("						)")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("			END")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("		ELSE IF (@Tipo = 'Cos_Pro2')")
			loComandoSeleccionar.AppendLine("			BEGIN	")
			loComandoSeleccionar.AppendLine("					INSERT	")
			loComandoSeleccionar.AppendLine("					INTO	#tabCostos")
			loComandoSeleccionar.AppendLine("						(Fecha, Articulo, Tipo, Cantidad, Ultimo1, Promedio1, Anterior1, Ultimo2, Promedio2, Anterior2, Fec_Pro, Fec_Ult, Fec_Ant, Clase)")
			loComandoSeleccionar.AppendLine("					VALUES (	@Fecha, ")
			loComandoSeleccionar.AppendLine("								@Articulo,")
			loComandoSeleccionar.AppendLine("								@Tipo,")
			loComandoSeleccionar.AppendLine("								@ExistenciaActual,")
			loComandoSeleccionar.AppendLine("								@Ultimo1Actual,")
			loComandoSeleccionar.AppendLine("								@Promedio1Actual,")
			loComandoSeleccionar.AppendLine("								@Anterior1Actual,")
			loComandoSeleccionar.AppendLine("								@Ultimo2Actual,")
			loComandoSeleccionar.AppendLine("								@Promedio2,")
			loComandoSeleccionar.AppendLine("								@Anterior2Actual,")
			loComandoSeleccionar.AppendLine("								@Fecha,")
			loComandoSeleccionar.AppendLine("								@Fec_UltActual,")
			loComandoSeleccionar.AppendLine("								@Fec_AntActual,")
			loComandoSeleccionar.AppendLine("								@Clase			")
			loComandoSeleccionar.AppendLine("						)						")
			loComandoSeleccionar.AppendLine("												")
			loComandoSeleccionar.AppendLine("			END									")
			loComandoSeleccionar.AppendLine("												")
			loComandoSeleccionar.AppendLine("		SET @lnContador = @lnContador + 1;		")
			loComandoSeleccionar.AppendLine("END											")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("SELECT T.Articulo					AS Cod_Art,")
			loComandoSeleccionar.AppendLine("		Articulos.Nom_Art			AS Nom_Art, ")
			loComandoSeleccionar.AppendLine("		T.Cantidad					AS Stock,")
			loComandoSeleccionar.AppendLine("		Articulos.Cod_Uni1			AS Cod_Uni,")
			loComandoSeleccionar.AppendLine("		T." & lcCosto & "			AS Costo")
			loComandoSeleccionar.AppendLine("FROM	(")
			loComandoSeleccionar.AppendLine("			SELECT	Tabulador.* ")
			loComandoSeleccionar.AppendLine("			FROM	#tabCostos AS Tabulador")
			loComandoSeleccionar.AppendLine("				JOIN (	SELECT	MAX(Fecha)		AS Fecha_Maxima,")
			loComandoSeleccionar.AppendLine("								MAX(Contador)	AS Contador_Maximo,")
			loComandoSeleccionar.AppendLine("								Articulo		AS Articulo")
			loComandoSeleccionar.AppendLine("						FROM	#tabCostos		AS F")
			loComandoSeleccionar.AppendLine("						GROUP BY Articulo")
			loComandoSeleccionar.AppendLine("					) AS Fechas")
			loComandoSeleccionar.AppendLine("				ON Tabulador.Fecha = Fechas.Fecha_Maxima")
			loComandoSeleccionar.AppendLine("				AND Tabulador.Articulo = Fechas.Articulo")
			loComandoSeleccionar.AppendLine("				AND Contador = Fechas.Contador_Maximo")
			loComandoSeleccionar.AppendLine("		) AS T ")
			loComandoSeleccionar.AppendLine("	JOIN Articulos On Articulos.Cod_Art COLLATE DATABASE_DEFAULT = T.Articulo COLLATE DATABASE_DEFAULT")
			loComandoSeleccionar.AppendLine("WHERE T.Cantidad <> 0")
			loComandoSeleccionar.AppendLine("ORDER BY Articulo")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("")
			'loComandoSeleccionar.AppendLine("DROP TABLE #tabArticulos")
			'loComandoSeleccionar.AppendLine("DROP TABLE #tabCostos")
			'loComandoSeleccionar.AppendLine("DROP TABLE #tabMovimientos")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("")
			loComandoSeleccionar.AppendLine("")


			'Me.mEscribirConsulta(loComandoSeleccionar.ToString())
          
            Dim loServicios As New cusDatos.goDatos

            Dim laDatosReporte As DataSet = loServicios.mObtenerTodosSinEsquema(loComandoSeleccionar.ToString(), "curReportes", 1200)
            
            loObjetoReporte = cusAplicacion.goReportes.mCargarReporte("rVInventario_Fecha", laDatosReporte)

            Me.mTraducirReporte(loObjetoReporte)

            Me.mFormatearCamposReporte(loObjetoReporte)

            Me.crvrVInventario_Fecha.ReportSource = loObjetoReporte

        Catch loExcepcion As Exception
               
               Me.WbcAdministradorMensajeModal.mMostrarMensajeModal("Error", _
                          "No se pudo Completar el Proceso: " & loExcepcion.Message, _
                           vis3Controles.wbcAdministradorMensajeModal.enumTipoMensaje.KN_Error, _
                           "auto", _
                           "auto")

        End Try

    End Sub

    Protected Sub Page_Unload(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Unload

        Try

            loObjetoReporte.Close()

        Catch loExcepcion As Exception

        End Try

    End Sub

End Class
'-------------------------------------------------------------------------------------------'
' Fin del codigo																			'
'-------------------------------------------------------------------------------------------'
' JJD: 01/08/09: Programacion inicial														'
'-------------------------------------------------------------------------------------------'
' JJD: 07/08/09: Continuacion de la Programacion											'
'-------------------------------------------------------------------------------------------'
' MAT: 18/05/11: Reprogramación, Ajuste del Select y de la vista de diseño					'
'-------------------------------------------------------------------------------------------'
' RJG: 19/11/11: Ajuste del SELECT: cálculo del costo similar al de Reconstruir existencias.'
'-------------------------------------------------------------------------------------------'
' RJG: 13/03/12: Se corrigió error de cálculo cuando dos movimientos del mismo artículo		'
'				 ocurren en la misma fecha/hora. Se optimizó la consulta quitando las		'
'				 variables de los parametros.												'
'-------------------------------------------------------------------------------------------'
' RJG: 23/03/12: Se agregó un filtro fijo para solo mostrar con existencia <> 0.			'
'-------------------------------------------------------------------------------------------'
' RJG: 14/05/12: Se agregaron los Traslados entre Almacenes para poder reflejar las			'
'				 existencias por almacén.													'
'-------------------------------------------------------------------------------------------'
' RJG: 16/05/12: Se corrigió error de cálculo al generar el tabulador (debido al orden de 	'
'				 aplicación de cada par de traslados.										'
'-------------------------------------------------------------------------------------------'
' RJG: 16/11/12: Se optimizó el tiempo de ejecución del reporte para manejar mayor volumen	'
'				 de datos.																	'
'-------------------------------------------------------------------------------------------'
